import { ambiguousEvent, flag, n, seedCreate, set } from "../18_20/helpers.js";
const rows = [
    { id: "EVT_23_BRIDGE_001", title: "Lo que significan tus 23", age: 23, family: "legacy", months: [7], seed: "SEED_ELITE_ROLE_BARGAIN" },
    { id: "EVT_23_MKT_001", title: "El salto que promete más de lo que firma", age: 23, family: "market", months: [7, 8], seed: "SEED_ELITE_ROLE_BARGAIN", gates: [{ path: "reputation.marketHeat", op: "gte", value: 34 }] },
    { id: "EVT_23_CON_001", title: "El contrato que pone techo", age: 23, family: "contract", months: [7, 8, 9], seed: "SEED_CONTRACT_CEILING" },
    { id: "EVT_23_AGT_001", title: "Ya no llaman solo a tu agente", age: 23, family: "agent", months: [8, 9, 10], seed: "SEED_DIRECT_RECRUIT" },
    { id: "EVT_23_BODY_001", title: "El calendario ya pesa distinto", age: 23, family: "medical", months: [8, 9, 10, 11], seed: "SEED_LOAD_MANAGEMENT" },
    { id: "EVT_23_MONEY_001", title: "Invertir ya no es comprar", age: 23, family: "money", months: [8, 9, 10, 11], seed: "SEED_FAMILY_BUSINESS" },
    { id: "EVT_23_HOME_001", title: "Tu nombre en una pared", age: 23, family: "family", months: [9, 10, 11, 12], seed: "SEED_HOME_SYMBOL" },
    { id: "EVT_23_EUR_001", title: "La lista europea", age: 23, family: "sport", months: [8, 9, 1, 2], seed: "SEED_EURO_REGISTRATION", gates: [{ path: "flags.CONTINENTAL_CONTEXT", op: "eq", value: true }], common: [flag("CONTINENTAL_REGISTERED", true)], weight: 24 },
    { id: "EVT_23_LOCK_001", title: "Cúbreme diez minutos", age: 23, family: "team", months: [9, 10, 11, 12], read: ["SEED_TEAMMATE_COVER"] },
    { id: "EVT_23_MATCH_001", title: "El partido que cambia el radar", age: 23, family: "sport", months: [9, 10, 11, 2, 3, 4], verified: true, body: "Llega un partido de alto escaparate. El técnico te ofrece un rol muy conservador para neutralizar la banda rival, mientras tu agente asegura que habrá ojeadores y gente de selección.", labels: ["Ejecutar el plan al milímetro", "Pedir licencia para atacar tras recuperación", "Jugar el rol pero asumir más riesgos si el marcador lo permite", "Decir al técnico que tu mejor impacto es ofensivo"] },
    { id: "EVT_23_NAT_001", title: "La primera llamada", age: 23, family: "selection", months: [9, 10, 11, 3, 4, 5], seed: "SEED_FIRST_ABSOLUTE_CALL", gates: [{ path: "flags.NATIONAL_GATE_OPEN", op: "eq", value: true }], verified: true, body: "Álvaro Sanz te convoca por primera vez con la selección absoluta o te incluye como reserva inmediata. En la primera charla deja claro que no promete minutos.", labels: ["Aceptar cualquier rol y observar", "Preguntar qué necesitas para jugar", "Mantener perfil bajo y acercarte a los veteranos", "Pedir a tu agente que reduzca prensa y marcas durante la concentración"], common: [flag("NATIONAL_CALLED", true), set("professional.nationalRole", "fringe"), n("professional.nationalStanding", 8)] },
    { id: "EVT_23_PRS_001", title: "Decisión técnica", age: 23, family: "press", months: [10, 11, 12, 1, 2], read: ["SEED_FIRST_LEAK"], labels: ["Autorizar una filtración", "Pedir una reunión interna", "Decir públicamente que competirás sin dar detalles", "Guardar silencio tres partidos"] },
    { id: "EVT_23_CAP_001", title: "El capitán quiere una frase", age: 23, family: "captaincy", months: [10, 11, 12, 1, 2], verified: true, body: "El capitán critica en privado la planificación del club y pide a tres jugadores que, al pasar por zona mixta, repitan una idea: «la plantilla necesita ayuda».", labels: ["Repetir la frase", "Hablar de mejorar sin pedir fichajes", "Negarte a coordinar mensajes", "Pedir que el capitán lo plantee primero en reunión formal"] },
    { id: "EVT_23_MED_001", title: "Club o selección", age: 23, family: "medical", months: [10, 11, 3, 4], seed: "SEED_CLUB_NATIONAL_CONFLICT", gates: [{ path: "flags.NATIONAL_GATE_OPEN", op: "eq", value: true }], verified: true, body: "Tienes una sobrecarga pequeña antes de una ventana internacional. El club recomienda quedarte y recuperar; la selección puede evaluarte allí sin comprometerte a jugar.", labels: ["Viajar y dejar que selección decida", "Quedarte con el club", "Pedir pruebas externas y decidir con el resultado", "Viajar dejando claro que no aceptarás medicación para jugar"] },
    { id: "EVT_23_JAN_001", title: "Enero: seis meses para convencerles", age: 23, family: "market", months: [1], seed: "SEED_ELITE_ROLE_BARGAIN", verified: true, weight: 24, body: "Si juegas poco, aparece una cesión de seis meses con opción de compra; si juegas mucho, un club mayor ofrece ficharte y dejarte cedido donde estás hasta verano.", labels: ["Moverte ya", "Quedarte hasta verano", "Aceptar solo con las condiciones de propiedad que prefieres", "Usar la propuesta para renegociar tu rol actual"] },
    { id: "EVT_24_MKT_001", title: "Tres ofertas, ninguna completa", age: 24, family: "market", months: [7, 8], seed: "SEED_ELITE_ROLE_BARGAIN", gates: [{ path: "reputation.marketHeat", op: "gte", value: 38 }], verified: true, choiceEffects: [[n("professional.clubPrestigeTier", 1, 1, 5), n("professional.roleSecurity", -8)], [n("professional.roleSecurity", 8)], [set("professional.route", "abroad"), flag("ABROAD_ROUTE", true), n("professional.foreignAdaptation", 20)], [n("professional.contractPower", 6)]], body: "Tras una temporada fuerte llegan tres perfiles de oferta: un club mayor con rol incierto, un club parecido donde serías pieza central y un destino extranjero con mejor salario y competición continental.", labels: ["Elegir el mayor techo deportivo", "Elegir el rol más claro", "Elegir el proyecto extranjero", "Pedir tiempo para provocar una mejora y arriesgar las tres"] },
    { id: "EVT_24_CON_001", title: "Tus derechos de imagen", age: 24, family: "contract", months: [7, 8, 9], seed: "SEED_IMAGE_RIGHTS", verified: true, body: "Una renovación o fichaje incluye un aumento salarial importante si cedes al club parte del control comercial de tu imagen durante el contrato.", labels: ["Ceder el porcentaje por salario", "Mantener control y cobrar menos", "Ceder solo en campañas del club", "Pedir una prima variable si imagen supera un umbral"] },
    { id: "EVT_24_AGT_001", title: "Exclusividad mundial", age: 24, family: "agent", months: [7, 8, 9, 10], seed: "SEED_DIRECT_RECRUIT", gates: [{ path: "reputation.marketHeat", op: "gte", value: 42 }], verified: true, common: [flag("SUPER_AGENT", true)], body: "Samuel Ordóñez ofrece incorporarte a su agencia internacional. Promete acceso a clubes mayores, pero exige exclusividad amplia y una comisión superior.", labels: ["Cambiar a Ordóñez", "Renovar con tu agente actual", "Pedir al actual que iguale servicios, no comisión", "Negociar con Ordóñez exclusividad corta o limitada"] },
    { id: "EVT_24_IMG_001", title: "La campaña que quiere una promesa", age: 24, family: "image", months: [7, 8, 9], seed: "SEED_SPONSOR_IMAGE", gates: [{ path: "professional.commercialPower", op: "gte", value: 28 }], verified: true, body: "Una marca te ofrece una campaña nacional basada en la frase «voy a quedarme para hacer historia», mientras tu contrato todavía permite salir.", labels: ["Aceptar el lema", "Pedir un mensaje sin promesa de futuro", "Rechazar la campaña", "Aceptar solo si se publica tras cerrar mercado"] },
    { id: "EVT_24_LIFE_001", title: "Quién trabaja para ti", age: 24, family: "life", months: [8, 9, 10], seed: "SEED_PERSONAL_STAFF", verified: true, body: "Entre viajes, prensa y contratos necesitas ayuda para agenda y asuntos diarios. Dani quiere encargarse de parte; tu agencia ofrece un profesional; tu familia prefiere a alguien conocido.", labels: ["Contratar a Dani", "Elegir profesional de la agencia", "Contratar a un independiente", "Repartir tareas entre alguien cercano y un profesional"] },
    { id: "EVT_24_ABR_001", title: "Volver no es retroceder", age: 24, family: "market", months: [7, 8, 1], read: ["SEED_FOREIGN_ADAPT"], gates: [{ path: "flags.ABROAD_ROUTE", op: "eq", value: true }], verified: true, body: "Si llevas años fuera, aparece una oferta española de nivel similar. En el extranjero ya tienes rol y vida montada; volver mejora cercanía familiar y visibilidad doméstica.", labels: ["Volver", "Renovar fuera", "Esperar otra temporada", "Usar la oferta española para mejorar el contrato exterior"] },
    { id: "EVT_24_FREE_001", title: "La prima por llegar libre", age: 24, family: "contract", months: [7, 8, 1], seed: "SEED_CONTRACT_CEILING", gates: [{ path: "contract.monthsRemaining", op: "lte", value: 14 }], verified: true, body: "Si llegas libre o cerca de libertad, el nuevo club ofrece una prima alta, pero pide salario algo menor y contrato largo. Tu agente cobra parte de la prima." },
    { id: "EVT_24_CCH_001", title: "Han fichado al de 70 millones", age: 24, family: "tactical", months: [7, 8, 9], seed: "SEED_STAR_COMPETITION", gates: [{ path: "professional.clubPrestigeTier", op: "gte", value: 4 }], verified: true, body: "Un fichaje estrella ocupa tu posición o una zona cercana. El entrenador insiste en que «los buenos juegan», pero el club necesita justificar una inversión enorme.", common: [flag("STAR_COMPETITION", true)] },
    { id: "EVT_24_MATCH_001", title: "El penalti no tiene dueño", age: 24, family: "sport", months: [9, 10, 11, 2, 3], seed: "SEED_PENALTY_HIERARCHY", labels: ["Entregarle el balón", "Decir que lo tiras tú", "Preguntar al capitán o técnico desde el campo", "Proponer decidirlo con una regla rápida entre ambos"] },
    { id: "EVT_24_LOCK_001", title: "El chat privado", age: 24, family: "team", months: [10, 11, 12, 1], seed: "SEED_PRIVATE_CHAT", verified: true, body: "Un grupo de jugadores comenta de forma dura decisiones del entrenador en un chat privado. Tú puedes intervenir, leer sin escribir o salir. Semanas después existe riesgo de captura filtrada.", labels: ["Criticar también", "Intentar bajar el tono", "No escribir nada", "Salir del grupo"] },
    { id: "EVT_24_EUR_001", title: "El lateral no llega", age: 24, family: "sport", months: [2, 3, 4, 5], read: ["SEED_EURO_REGISTRATION"], gates: [{ path: "flags.CONTINENTAL_REGISTERED", op: "eq", value: true }], verified: true, body: "Antes de una eliminatoria continental, el lateral titular es baja. El técnico quiere usar un sistema en el que tú recorras toda la banda.", labels: ["Aceptar", "Aceptar con límite de minutos si sube la carga", "Proponer otro sistema que te mantenga arriba", "Aceptar el partido pero no fijar esa posición"] },
    { id: "EVT_24_NAT_001", title: "La lista de 26", age: 24, family: "selection", months: [3, 4, 5, 6], seed: "SEED_MAJOR_TOURNAMENT", gates: [{ path: "flags.NATIONAL_TOURNAMENT_CYCLE", op: "eq", value: true }], verified: true, body: "Se acerca un gran torneo internacional. Álvaro Sanz tiene más candidatos que plazas. Te convoca a la concentración previa, pero no garantiza la lista final.", labels: ["Mantener tu preparación habitual", "Subir carga para llegar en pico de forma", "Pedir al club que gestione minutos previos", "Hablar con Sanz para entender qué rol compites realmente"] },
    { id: "EVT_24_MED_001", title: "La final y el isquio", age: 24, family: "medical", months: [4, 5], seed: "SEED_BIG_MATCH_BODY", gates: [{ path: "flags.FINAL_CONTEXT", op: "eq", value: true }], verified: true, body: "Tienes una lesión muscular de bajo grado o una señal compatible con riesgo justo antes de una final o eliminatoria y, potencialmente, un torneo internacional cercano.", labels: ["No jugar", "Intentar llegar con tratamiento conservador y test final", "Aceptar analgesia permitida si el médico la considera segura", "Jugar solo si pasas una prueba funcional definida"] },
    { id: "EVT_24_PRS_001", title: "El precio que nadie pidió", age: 24, family: "press", months: [9, 10, 11, 12, 1], seed: "SEED_PUBLIC_CONTRACT", gates: [{ path: "reputation.marketHeat", op: "gte", value: 48 }], verified: true, body: "Un medio publica que tu club no escuchará ofertas por debajo de una cifra enorme. Nadie te había informado de ese precio.", labels: ["Preguntar internamente y no hablar", "Negar públicamente que exista precio acordado", "Autorizar a tu agente a decir que escucharías proyectos", "Llamar a Clara para intentar conocer la fuente"] },
    { id: "EVT_24_JAN_001", title: "El cheque imposible", age: 24, family: "money", months: [1], seed: "SEED_WEALTHY_EXIT", gates: [{ path: "reputation.marketHeat", op: "gte", value: 46 }], verified: true, choiceEffects: [[flag("WEALTHY_EXIT_ACCEPTED", true), n("contract.salaryMonthly", 26000, 0, 150000), n("professional.moneyComfort", 18), n("professional.roleSecurity", -9), n("professional.contractPower", -6)], [n("reputation.marketHeat", 4), n("professional.contractPower", 3)], [n("contract.salaryMonthly", 12000, 0, 150000), n("professional.contractPower", 4)], [n("contract.salaryMonthly", 7000, 0, 150000), n("professional.institutionalTrust", -4)]], body: "Un club de una liga menos prestigiosa pero financieramente poderosa ofrece triplicar o cuadruplicar tu salario en enero.", labels: ["Aceptar", "Rechazar para competir al máximo nivel", "Pedir contrato más corto o cláusula de retorno", "Usar la oferta para renovar o mejorar en tu club"] },
    { id: "EVT_25_TEAM_001", title: "El joven que viene detrás", age: 25, family: "team", months: [7, 8, 9], seed: "SEED_YOUNG_MENTOR", verified: true, body: "Un canterano de 18-19 años empieza a entrenar contigo y ocupa tu misma zona. Te admira, pero el club lo presenta como futuro activo estratégico.", labels: ["Ayudarle abiertamente", "Tratarlo como a cualquier competidor", "Darle consejos fuera de campo, no tácticos de tu posición", "Pedir a tu agente que averigüe por qué lo promocionan"] },
    { id: "EVT_25_CAP_001", title: "El brazalete", age: 25, family: "captaincy", months: [7, 8, 9, 10], seed: "SEED_CAPTAINCY_STYLE", gates: [{ path: "flags.CAPTAINCY_WINDOW", op: "eq", value: true }], verified: true, labels: ["Aceptar", "Rechazar para centrarte en jugar", "Aceptar como capitán secundario", "Pedir que el vestuario vote"] },
    { id: "EVT_25_TACT_001", title: "De extremo a interior", age: 25, family: "tactical", months: [8, 9, 10, 11], read: ["SEED_TACTICAL_SACRIFICE"], verified: true, body: "Un entrenador propone una reconversión más estable hacia interior o mediapunta de trabajo mixto porque tus datos físicos y lectura han cambiado.", labels: ["Abrazar la reconversión", "Probarla solo en ciertos partidos", "Rechazar y proteger rol ofensivo", "Aceptar mientras el agente sondea clubes que te quieran arriba"] },
    { id: "EVT_25_MED_001", title: "La molestia que vuelve", age: 25, family: "medical", months: [9, 10, 11, 12, 1, 2], seed: "SEED_CHRONIC_BODY", gates: [{ path: "professional.bodyLoad", op: "gte", value: 34 }], verified: true, body: "La misma zona muscular o articular empieza a dar avisos repetidos. No es una lesión catastrófica, pero ya existe patrón.", labels: ["Rediseñar entrenamiento", "Mantener rutina hasta una lesión clara", "Cambiar solo fuera de temporada", "Consultar otro especialista antes de tocar el plan"] },
    { id: "EVT_25_CON_001", title: "La renovación que define el siguiente pico", age: 25, family: "contract", months: [9, 10, 11, 12, 1], seed: "SEED_CONTRACT_CEILING", labels: ["Renovar ahora", "Esperar al verano", "Firmar solo con cláusula de salida razonable", "Acordar seguir negociando sin firmar"] },
    { id: "EVT_25_NAT_001", title: "Ser internacional no es tener sitio", age: 25, family: "selection", months: [9, 10, 11, 3, 4, 5], read: ["SEED_FIRST_ABSOLUTE_CALL"], gates: [{ path: "flags.NATIONAL_CALLED", op: "eq", value: true }] },
    { id: "EVT_25_AGT_001", title: "Enséñame la oferta", age: 25, family: "agent", months: [10, 11, 12, 1], seed: "SEED_AGENT_PROOF" },
    { id: "EVT_25_MKT_001", title: "La llamada directa", age: 25, family: "market", months: [1, 5, 6], seed: "SEED_DIRECT_RECRUIT", gates: [{ path: "reputation.marketHeat", op: "gte", value: 44 }] },
    { id: "EVT_25_FAM_001", title: "El negocio ya no es pequeño", age: 25, family: "family", months: [2, 3, 4, 5], seed: "SEED_FAMILY_BUSINESS", verified: true, body: "La inversión o proyecto familiar de años anteriores ha crecido, necesita capital adicional o atraviesa una mala fase. La cantidad solicitada ya no es simbólica.", labels: ["Aportar capital", "Prestar con contrato y calendario", "No poner más dinero", "Financiar solo si entra un gestor externo"] },
    { id: "EVT_25_END_001", title: "A los 26, ¿qué estás protegiendo?", age: 25, family: "legacy", months: [5, 6], seed: "SEED_AGE26_PRIORITY", verified: true, choiceEffects: [[set("world.nextCyclePriority", "ceiling")], [set("world.nextCyclePriority", "role")], [set("world.nextCyclePriority", "body_stability")], [set("world.nextCyclePriority", "freedom")]], body: "Al cerrar la tercera temporada del bloque, tu agente o persona de confianza te pide ordenar prioridades antes del siguiente contrato.", labels: ["Proteger techo deportivo", "Proteger minutos e identidad", "Proteger cuerpo y estabilidad", "Proteger libertad"] }
];
const familyFx = {
    market: [[n("reputation.marketHeat", 7), n("professional.roleSecurity", -4)], [n("professional.roleSecurity", 6), n("reputation.marketHeat", -1)], [n("professional.contractPower", 5), n("professional.environmentStability", -2)], [n("professional.contractPower", 4), n("professional.institutionalTrust", -3)]],
    contract: [[n("professional.contractPower", 7), n("professional.institutionalTrust", -3)], [n("professional.contractPower", 2), n("professional.institutionalTrust", 4)], [n("professional.contractPower", 5), n("professional.roleSecurity", -2)], [n("professional.institutionalTrust", 5), n("professional.contractPower", -2)]],
    agent: [[n("professional.agentControl", -7), n("professional.contractPower", 5)], [n("professional.agentControl", 5), n("professional.environmentStability", 2)], [n("professional.agentControl", 8), n("reputation.marketHeat", -2)], [n("professional.agentControl", 1), n("professional.contractPower", 3)]],
    medical: [[n("professional.bodyLoad", 7), n("sport.roleScore", 3)], [n("professional.bodyLoad", -6), n("professional.roleSecurity", -2)], [n("professional.bodyLoad", -3), n("professional.institutionalTrust", 3)], [n("body.risk", -3), n("professional.bodyLoad", -2)]],
    money: [[n("professional.moneyComfort", 10), n("professional.environmentStability", -2)], [n("professional.moneyComfort", 5), n("professional.environmentStability", 4)], [n("professional.moneyComfort", 2), n("professional.contractPower", 3)], [n("professional.moneyComfort", 4), n("professional.agentControl", 2)]],
    family: [[n("professional.environmentStability", 6), n("professional.moneyComfort", -2)], [n("professional.environmentStability", 4)], [n("professional.environmentStability", -2), n("professional.contractPower", 2)], [n("professional.environmentStability", 5), n("professional.moneyComfort", -1)]],
    sport: [[n("professional.continentalCred", 7), n("professional.bodyLoad", 4)], [n("professional.continentalCred", 4), n("professional.bodyLoad", 1)], [n("sport.roleScore", 5), n("professional.bodyLoad", 3)], [n("professional.roleSecurity", 4), n("professional.continentalCred", 2)]],
    selection: [[n("professional.nationalStanding", 8), n("professional.bodyLoad", 3)], [n("professional.nationalStanding", 5), n("professional.environmentStability", 2)], [n("professional.nationalStanding", 4), n("professional.commercialPower", 2)], [n("professional.nationalStanding", 3), n("professional.agentControl", 2)]],
    press: [[n("reputation.mediaHeat", 8), n("professional.publicPolarization", 5)], [n("professional.institutionalTrust", 3), n("reputation.mediaHeat", 2)], [n("professional.contractPower", 3), n("professional.publicPolarization", 2)], [n("reputation.mediaHeat", 4), n("professional.commercialPower", 2)]],
    image: [[n("professional.commercialPower", 9), n("professional.publicPolarization", 4)], [n("professional.commercialPower", 5), n("professional.publicPolarization", -1)], [n("professional.commercialPower", -2), n("professional.environmentStability", 2)], [n("professional.commercialPower", 6), n("professional.contractPower", 2)]],
    life: [[n("professional.environmentStability", 4), n("professional.commercialPower", 2)], [n("professional.agentControl", -3), n("professional.environmentStability", 3)], [n("professional.agentControl", 5), n("professional.environmentStability", 2)], [n("professional.environmentStability", 5), n("professional.moneyComfort", -1)]],
    team: [[n("professional.lockerPower", 6), n("professional.environmentStability", -2)], [n("professional.lockerPower", 3), n("professional.environmentStability", 4)], [n("professional.roleSecurity", 4), n("professional.lockerPower", -1)], [n("professional.lockerPower", 4), n("professional.institutionalTrust", 2)]],
    captaincy: [[n("professional.lockerPower", 8), n("professional.publicPolarization", 2)], [n("professional.lockerPower", 2), n("professional.environmentStability", 4)], [n("professional.lockerPower", 5), n("professional.institutionalTrust", -2)], [n("professional.lockerPower", 6), n("professional.environmentStability", 1)]],
    tactical: [[n("sport.roleScore", 5), n("professional.bodyLoad", 2)], [n("professional.roleSecurity", 5), n("professional.continentalCred", 2)], [n("reputation.marketHeat", 5), n("professional.roleSecurity", -3)], [n("professional.contractPower", 3), n("sport.roleScore", 2)]],
    legacy: [[n("professional.contractPower", 3), n("reputation.prestige", 3)], [n("professional.roleSecurity", 4), n("professional.environmentStability", 2)], [n("professional.bodyLoad", -3), n("professional.environmentStability", 4)], [n("professional.contractPower", 5), n("professional.agentControl", 4)]]
};
function make(r) {
    const fx = familyFx[r.family] ?? familyFx.legacy;
    const labels = r.labels ?? ["Tomar la iniciativa", "Esperar y reunir información", "Proteger tu posición", "Buscar una solución intermedia"];
    const common = r.common ?? [];
    const choiceExtra = r.choiceEffects ?? [[], [], [], []];
    const cs = labels.map((label, i) => ({ id: String.fromCharCode(65 + i), label, intentTags: [["ceiling"], ["patience"], ["control"], ["balance"]][i], primaryMessage: ["La decisión abre una oportunidad sin eliminar sus costes.", "La espera mejora una parte de la información, pero consume tiempo.", "Proteges una dimensión de la carrera y aceptas perder margen en otra.", "Mantienes varias puertas abiertas, a cambio de una postura menos nítida."][i], secondaryMessage: ["El mismo movimiento produce una lectura menos favorable de la esperada.", "Mientras esperas, un tercero mueve primero.", "La protección funciona, pero cambia cómo te leen club, mercado o vestuario.", "El compromiso reduce el conflicto inmediato sin resolver toda la tensión."][i], immediateEffects: [...common, ...choiceExtra[i]], primaryEffects: fx[i], secondaryEffects: [...fx[i], n("professional.environmentStability", i === 1 ? 1 : -1)], primarySeedTransitions: r.seed ? [seedCreate(r.seed, 54, { choice: String.fromCharCode(65 + i) })] : undefined, secondarySeedTransitions: r.seed ? [seedCreate(r.seed, 46, { choice: String.fromCharCode(65 + i) })] : undefined }));
    return ambiguousEvent({ id: r.id, ageWindow: [r.age, r.age], phase: "23_26", family: r.family, title: r.title, body: r.body ?? "La etapa adulta de la carrera enfrenta objetivos compatibles en teoría, pero difíciles de conservar a la vez.", visible: ["Conoces las condiciones formales y tu situación deportiva actual."], uncertain: ["No conoces la agenda completa de terceros ni cómo evolucionará el contexto."], choices: cs, gates: r.gates, timeWindow: { months: r.months }, weight: r.weight ?? (r.id === "EVT_25_END_001" ? 96 : r.id === "EVT_23_BRIDGE_001" ? 28 : 12), cooldown: 99999, seedsRead: r.read, seedsWrite: r.seed ? [r.seed] : undefined, tags: [r.family, r.age === 25 ? "transition26" : "adult_consolidation"], canonStatus: r.verified ? "verified" : "technical_adaptation" });
}
export const PRINCIPAL_EVENTS_23_26 = rows.map(make);
