import type { EventDefinition } from "../../../core/types.js";
import { ambiguousEvent, flag, n, seedCreate, set } from "../18_20/helpers.js";

const choiceSeed=(seedId:string,choice:string)=>[seedCreate(seedId,60,{choice})];
const common=(age:31,months:number[])=>({
  ageWindow:[age,age] as [number,number],
  phase:"30_34" as const,
  timeWindow:{months},
  cooldown:99999,
  weight:10,
  tags:["maturity","t51_canonical_reimplementation","t51_trigger_approximation"],
  canonStatus:"technical_adaptation" as const
});

const surgery31=ambiguousEvent({...common(31,[2,3]),id:"EVT_31_MED_001",family:"medical",title:"La operación y agosto",body:"Una molestia que llevas meses manejando puede operarse ahora con un plazo que te haría perder casi toda la pretemporada, o seguir tratándose hasta que falle o desaparezca.",visible:["Conoces plazos, historial y riesgos cualitativos de cada plan."],uncertain:["No sabes si una pretemporada perdida reducirá tu rol más que el dolor ni si la cirugía resolverá por completo el problema."],gates:[{path:"flags.HAS_SEED_CHRONIC_BODY",op:"eq",value:true}],seedsRead:["SEED_SURGERY_TIMING"],seedsWrite:["SEED_SURGERY_31"],choices:[
  {id:"A",label:"Operarte ya",intentTags:["surgery_now","health"],immediateEffects:[flag("AGE31_SURGERY_NOW",true)],primaryMessage:"Aceptas perder preparación para intentar resolver el problema antes de otra temporada larga.",secondaryMessage:"La intervención sale razonablemente bien, pero recuperar tejido no devuelve ritmo competitivo de inmediato.",primaryEffects:[n("professional.recoveryDebt",-7),n("professional.recoveryMargin",5)],secondaryEffects:[n("professional.availability",-9),n("professional.roleSecurity",-2)],primarySeedTransitions:choiceSeed("SEED_SURGERY_31","A"),secondarySeedTransitions:choiceSeed("SEED_SURGERY_31","A")},
  {id:"B",label:"Posponer hasta invierno",intentTags:["delay_surgery","competition"],immediateEffects:[flag("AGE31_SURGERY_WINTER",true)],primaryMessage:"Proteges el inicio de temporada y aplazas la decisión hasta una ventana menos visible.",secondaryMessage:"Puedes firmar un gran otoño o llegar al invierno con más dolor y menos margen.",primaryEffects:[n("professional.availability",4),n("professional.statusInertia",3)],secondaryEffects:[n("professional.recoveryDebt",6)],primarySeedTransitions:choiceSeed("SEED_SURGERY_31","B"),secondarySeedTransitions:choiceSeed("SEED_SURGERY_31","B")},
  {id:"C",label:"Seguir conservador sin fecha",intentTags:["conservative_treatment","wait"],immediateEffects:[flag("AGE31_SURGERY_UNDATED",true)],primaryMessage:"Mantienes el tratamiento y evitas fijar una cirugía que todavía no consideras inevitable.",secondaryMessage:"La flexibilidad preserva opciones, pero convierte cada recaída en una nueva negociación con el calendario.",primaryEffects:[n("professional.matchSelectivity",4),n("professional.careerControl",2)],secondaryEffects:[n("professional.recoveryDebt",3)],primarySeedTransitions:choiceSeed("SEED_SURGERY_31","C"),secondarySeedTransitions:choiceSeed("SEED_SURGERY_31","C")},
  {id:"D",label:"Operarte solo con un plan de retorno por escrito",intentTags:["return_plan","surgery"],immediateEffects:[flag("AGE31_SURGERY_RETURN_PLAN",true)],primaryMessage:"Vinculas la cirugía a un acuerdo explícito sobre cómo volverás a competir, sin convertirlo en una garantía contractual.",secondaryMessage:"El plan reduce ambigüedad, pero ningún documento puede obligar al entrenador a ignorar tu forma cuando regreses.",primaryEffects:[n("professional.careerControl",5),n("professional.roleSecurity",3),n("professional.institutionalTrust",2)],secondaryEffects:[n("professional.availability",-7)],primarySeedTransitions:choiceSeed("SEED_SURGERY_31","D"),secondarySeedTransitions:choiceSeed("SEED_SURGERY_31","D")}
]});

const market31=ambiguousEvent({...common(31,[7,8,1]),id:"EVT_31_MKT_001",family:"market",title:"Dos años de estrella o uno de élite",body:"Tienes una propuesta de dos años para ser figura de un club competitivo y otra de un año en un candidato a todo con rol menos claro.",visible:["Conoces los paquetes deportivos y económicos completos de las dos propuestas."],uncertain:["No sabes cuál de los dos entrenadores sobrevivirá ni qué fichajes llegarán después de ti."],gates:[{path:"contract.monthsRemaining",op:"lte",value:18},{path:"reputation.marketHeat",op:"gte",value:55}],seedsRead:["SEED_AGE30_CONTRACT"],seedsWrite:["SEED_LAST_BIG_MOVE_31"],choices:[
  {id:"A",label:"Dos años como figura",intentTags:["star_role","security"],immediateEffects:[set("contract.monthsRemaining",24),flag("AGE31_TWO_YEAR_STAR",true)],primaryMessage:"Eliges más partidos previstos y una jerarquía clara durante dos temporadas.",secondaryMessage:"La seguridad contractual no impide que una lesión o un cambio táctico reduzcan esa jerarquía.",primaryEffects:[n("professional.roleSecurity",7),n("professional.moneyComfort",4)],secondaryEffects:[n("professional.careerControl",1)],primarySeedTransitions:choiceSeed("SEED_LAST_BIG_MOVE_31","A"),secondarySeedTransitions:choiceSeed("SEED_LAST_BIG_MOVE_31","A")},
  {id:"B",label:"Un año en el gigante",intentTags:["elite_move","trophies"],immediateEffects:[set("contract.monthsRemaining",12),flag("AGE31_ONE_YEAR_ELITE",true)],primaryMessage:"Aceptas un último salto a máxima exposición competitiva aun sin titularidad garantizada.",secondaryMessage:"La vitrina es mayor, pero una rotación larga puede hacer que el año pase más rápido que la oportunidad.",primaryEffects:[n("professional.veteranLeverage",5),n("professional.statusInertia",4)],secondaryEffects:[n("professional.roleSecurity",-5)],primarySeedTransitions:choiceSeed("SEED_LAST_BIG_MOVE_31","B"),secondarySeedTransitions:choiceSeed("SEED_LAST_BIG_MOVE_31","B")},
  {id:"C",label:"Pedir al gigante opción automática por minutos",intentTags:["elite_move","minutes_clause"],immediateEffects:[flag("AGE31_ELITE_MINUTES_OPTION",true)],primaryMessage:"Intentas convertir rendimiento y minutos en una segunda temporada automática.",secondaryMessage:"La cláusula protege si juegas; no evita que el propio club controle cuántos minutos alcanzas.",primaryEffects:[n("professional.contractPower",6),n("professional.careerControl",4)],secondaryEffects:[n("professional.roleSecurity",-2)],primarySeedTransitions:choiceSeed("SEED_LAST_BIG_MOVE_31","C"),secondarySeedTransitions:choiceSeed("SEED_LAST_BIG_MOVE_31","C")},
  {id:"D",label:"Esperar mercado y arriesgar ambas",intentTags:["wait","market_test"],immediateEffects:[flag("AGE31_MARKET_WAIT",true)],primaryMessage:"No aceptas que dos ofertas actuales definan todo tu mercado.",secondaryMessage:"Esperar puede mejorar las condiciones o dejarte sin ninguna de las dos estructuras que hoy sí existen.",primaryEffects:[n("professional.careerControl",4),n("professional.contractPower",2)],secondaryEffects:[n("professional.roleSecurity",-5),n("professional.veteranLeverage",-2)],primarySeedTransitions:choiceSeed("SEED_LAST_BIG_MOVE_31","D"),secondarySeedTransitions:choiceSeed("SEED_LAST_BIG_MOVE_31","D")}
]});

const home31=ambiguousEvent({...common(31,[7,8,1]),id:"EVT_31_HOME_001",family:"family",title:"Valdoria llama con 31",body:"UDV quiere que regreses mientras todavía eres competitivo. El proyecto deportivo es serio, pero el salario es mucho menor y tu llegada convertiría cada resultado en noticia local.",visible:["Conoces el rol central, la duración, el salario y el plan deportivo del club."],uncertain:["No sabes si el proyecto puede crecer al ritmo de tu ambición ni cuánto poder informal acabarías asumiendo."],gates:[{path:"professional.homePull",op:"gte",value:55}],seedsRead:["SEED_EARLY_HOME_RETURN"],seedsWrite:["SEED_HOME_RETURN_31"],choices:[
  {id:"A",label:"Volver ahora",intentTags:["home_return","competition"],immediateEffects:[flag("HOME_RETURN_30",true),flag("AGE31_HOME_RETURN",true),set("professional.route","home"),set("professional.ownerClub","UDV"),set("professional.registrationClub","UDV"),set("club","UDV")],primaryMessage:"Regresas antes de que el fútbol te obligue, con nivel suficiente para que el retorno sea deportivo y no ceremonial.",secondaryMessage:"Tu peso puede elevar al club o hacer que cada decisión quede atrapada alrededor de tu figura.",primaryEffects:[n("professional.homePull",12),n("professional.legacyCapital",7),n("professional.institutionalPower",5)],secondaryEffects:[n("professional.environmentStability",4)],primarySeedTransitions:choiceSeed("SEED_HOME_RETURN_31","A"),secondarySeedTransitions:choiceSeed("SEED_HOME_RETURN_31","A")},
  {id:"B",label:"Decir que todavía no es el momento",intentTags:["delay_home_return","competition"],immediateEffects:[flag("AGE31_HOME_NOT_YET",true)],primaryMessage:"Mantienes abierta la relación con Valdoria sin convertir nostalgia en una obligación inmediata.",secondaryMessage:"El club puede esperar, cambiar de proyecto o dejar de necesitar exactamente el jugador que eres hoy.",primaryEffects:[n("professional.careerControl",4),n("professional.veteranLeverage",2)],secondaryEffects:[n("professional.homePull",2)],primarySeedTransitions:choiceSeed("SEED_HOME_RETURN_31","B"),secondarySeedTransitions:choiceSeed("SEED_HOME_RETURN_31","B")},
  {id:"C",label:"Pedir contrato corto y objetivos",intentTags:["home_return","short_contract"],immediateEffects:[flag("AGE31_HOME_OBJECTIVES",true),set("contract.monthsRemaining",12)],primaryMessage:"Aceptas explorar el regreso, pero intentas impedir que el vínculo sentimental sustituya a objetivos deportivos medibles.",secondaryMessage:"Los objetivos ordenan expectativas; también pueden convertir cada tramo malo en un juicio sobre tu regreso.",primaryEffects:[n("professional.contractPower",4),n("professional.careerControl",4),n("professional.homePull",5)],secondaryEffects:[n("professional.roleSecurity",1)],primarySeedTransitions:choiceSeed("SEED_HOME_RETURN_31","C"),secondarySeedTransitions:choiceSeed("SEED_HOME_RETURN_31","C")},
  {id:"D",label:"Ayudar al club de otra forma sin fichar",intentTags:["home_support","legacy"],immediateEffects:[flag("AGE31_HOME_SUPPORT_NO_SIGN",true)],primaryMessage:"Separás el vínculo con Valdoria de tu siguiente contrato como futbolista.",secondaryMessage:"Ganas margen para ayudar sin ocupar el equipo, pero la afición puede interpretar la distancia como una promesa aplazada.",primaryEffects:[n("professional.legacyCapital",5),n("professional.institutionalPower",2)],secondaryEffects:[n("professional.homePull",3)],primarySeedTransitions:choiceSeed("SEED_HOME_RETURN_31","D"),secondarySeedTransitions:choiceSeed("SEED_HOME_RETURN_31","D")}
]});

const agent31=ambiguousEvent({...common(31,[8,9,1]),id:"EVT_31_AGT_001",family:"agent",title:"Es el último gran contrato",body:"Tu agencia insiste en maximizar comisión y salario porque «a los 33 nadie pagará esto». Un asesor independiente cree que la libertad contractual vale más que la cifra.",visible:["Conoces las ofertas, la comisión y los escenarios financieros que te presentan."],uncertain:["No sabes si la frase es análisis real, táctica comercial o miedo genuino de tu agente."],gates:[{path:"contract.monthsRemaining",op:"lte",value:18}],seedsRead:["SEED_AGENT_LAST_CONTRACT"],seedsWrite:["SEED_SELF_REPRESENTATION_PREP"],choices:[
  {id:"A",label:"Seguir estrategia de agencia",intentTags:["agency_strategy","money"],immediateEffects:[flag("AGE31_AGENT_STRATEGY",true)],primaryMessage:"Delegas la negociación para maximizar cifra y cerrar mientras el mercado paga tu historial reciente.",secondaryMessage:"La agencia puede tener razón y beneficiarse de que aceptes su definición de lo que significa «último».",primaryEffects:[n("professional.moneyComfort",6),n("professional.contractPower",4)],secondaryEffects:[n("professional.careerControl",-3)],primarySeedTransitions:choiceSeed("SEED_SELF_REPRESENTATION_PREP","A"),secondarySeedTransitions:choiceSeed("SEED_SELF_REPRESENTATION_PREP","A")},
  {id:"B",label:"Contratar asesor externo para comparar",intentTags:["independent_advice","compare"],immediateEffects:[flag("AGE31_EXTERNAL_ADVISOR",true)],primaryMessage:"Creas una segunda lectura de las ofertas antes de aceptar el marco de tu propia agencia.",secondaryMessage:"Más información mejora control, pero dos asesores también pueden producir estrategias incompatibles.",primaryEffects:[n("professional.careerControl",5),n("professional.contractPower",2)],secondaryEffects:[n("professional.institutionalTrust",-1)],primarySeedTransitions:choiceSeed("SEED_SELF_REPRESENTATION_PREP","B"),secondarySeedTransitions:choiceSeed("SEED_SELF_REPRESENTATION_PREP","B")},
  {id:"C",label:"Negociar tú las variables deportivas y dejar dinero a la agencia",intentTags:["split_negotiation","sport_control"],immediateEffects:[flag("AGE31_SPLIT_NEGOTIATION",true)],primaryMessage:"Separás salario y comisión de rol, minutos y proyecto para no delegar toda la decisión de carrera.",secondaryMessage:"La división aumenta tu control y también crea puntos de fricción sobre quién puede prometer qué.",primaryEffects:[n("professional.careerControl",7),n("professional.roleSecurity",3)],secondaryEffects:[n("professional.contractPower",1)],primarySeedTransitions:choiceSeed("SEED_SELF_REPRESENTATION_PREP","C"),secondarySeedTransitions:choiceSeed("SEED_SELF_REPRESENTATION_PREP","C")},
  {id:"D",label:"Cambiar de agente antes de firmar",intentTags:["change_agent","reset"],immediateEffects:[flag("AGE31_AGENT_CHANGED",true)],primaryMessage:"Cambias de representación antes de comprometer uno de los contratos más sensibles de tu carrera.",secondaryMessage:"El nuevo agente puede abrir relaciones distintas o llegar demasiado tarde a conversaciones que ya estaban maduras.",primaryEffects:[n("professional.careerControl",5),n("professional.veteranLeverage",2)],secondaryEffects:[n("professional.contractPower",-2)],primarySeedTransitions:choiceSeed("SEED_SELF_REPRESENTATION_PREP","D"),secondarySeedTransitions:choiceSeed("SEED_SELF_REPRESENTATION_PREP","D")}
]});

export const CANONICAL_REIMPLEMENTATIONS_30_34:EventDefinition[]=[surgery31,market31,home31,agent31];
