import type { EventDefinition } from "../../../core/types.js";
import { ambiguousEvent, flag, n, seedCreate } from "../18_20/helpers.js";

const seed=(seedId:string,choice:string)=>[seedCreate(seedId,60,{choice})];
const common=(months:number[],authorityGuarded=false)=>({
  ageWindow:[32,32] as [number,number],phase:"30_34" as const,timeWindow:{months},cooldown:99999,weight:10,
  tags:["maturity","t51_canonical_reimplementation","t51_trigger_approximation",...(authorityGuarded?["t51_shared_authority_guard"]:[])],canonStatus:"technical_adaptation" as const
});

const contract=ambiguousEvent({...common([7,8,9],true),id:"EVT_32_CON_001",family:"contract",title:"Contrato de un año renovable",body:"Tu club ofrece contrato anual con renovación automática por minutos. Cobrarías menos fijo, pero si sigues jugando conservarías continuidad sin quedar atado.",visible:["Conoces el umbral de minutos, el salario y el rol comunicado."],uncertain:["No sabes si el club administrará tus minutos pensando también en la cláusula."],gates:[{path:"contract.monthsRemaining",op:"lte",value:14}],seedsRead:["SEED_AGE30_CONTRACT"],seedsWrite:["SEED_ROLLING_CONTRACT"],choices:[
 {id:"A",label:"Aceptar",intentTags:["rolling_contract"],immediateEffects:[flag("ROLLING_CONTRACT",true)],primaryMessage:"Aceptas que la continuidad dependa de una condición objetiva de participación.",secondaryMessage:"La regla reduce ambigüedad y puede hacer sospechosa cada rotación cercana al umbral.",primaryEffects:[n("professional.contractPower",4),n("professional.roleSecurity",2)],secondaryEffects:[n("professional.institutionalTrust",-1)],primarySeedTransitions:seed("SEED_ROLLING_CONTRACT","A"),secondarySeedTransitions:seed("SEED_ROLLING_CONTRACT","A")},
 {id:"B",label:"Pedir dos años garantizados",intentTags:["guaranteed_contract"],immediateEffects:[flag("AGE32_TWO_YEARS_GUARANTEED",true)],primaryMessage:"Cambias el incentivo por seguridad contractual completa.",secondaryMessage:"La garantía protege ingresos y puede dejarte atado si el rol cae antes que el contrato.",primaryEffects:[n("professional.moneyComfort",5),n("professional.roleSecurity",4)],secondaryEffects:[n("professional.careerControl",-3)],primarySeedTransitions:seed("SEED_ROLLING_CONTRACT","B"),secondarySeedTransitions:seed("SEED_ROLLING_CONTRACT","B")},
 {id:"C",label:"Cambiar el gatillo de minutos por partidos convocado o disponible",intentTags:["availability_clause"],immediateEffects:[flag("AGE32_AVAILABILITY_CLAUSE",true)],primaryMessage:"Intentas que la renovación premie disponibilidad y no una cifra que el propio entrenador controla.",secondaryMessage:"La nueva métrica reduce un conflicto y crea otros alrededor de qué cuenta como realmente disponible.",primaryEffects:[n("professional.contractPower",6),n("professional.careerControl",4)],secondaryEffects:[n("professional.matchSelectivity",1)],primarySeedTransitions:seed("SEED_ROLLING_CONTRACT","C"),secondarySeedTransitions:seed("SEED_ROLLING_CONTRACT","C")},
 {id:"D",label:"Rechazar cualquier automático y negociar cada verano",intentTags:["annual_market","freedom"],immediateEffects:[flag("AGE32_NO_AUTOMATIC_RENEWAL",true)],primaryMessage:"Prefieres que cada temporada vuelva a poner precio y rol sobre la mesa.",secondaryMessage:"Conservas libertad y aceptas que una mala primavera pueda dejarte sin la renovación que hoy estaría casi asegurada.",primaryEffects:[n("professional.careerControl",6),n("professional.veteranLeverage",3)],secondaryEffects:[n("professional.roleSecurity",-4)],primarySeedTransitions:seed("SEED_ROLLING_CONTRACT","D"),secondarySeedTransitions:seed("SEED_ROLLING_CONTRACT","D")}
]});

const home=ambiguousEvent({...common([7,8,1],true),id:"EVT_32_HOME_001",family:"captaincy",title:"Valdoria te ofrece el brazalete",body:"UDV presenta un proyecto de dos años con capitanía probable y papel central. No promete ascenso ni títulos; promete que el equipo se construirá para aprovechar tu versión actual.",visible:["Conoces el plan táctico, el presupuesto y el rol previsto."],uncertain:["No sabes si el club podrá resistir la presión de convertir cada fichaje en «para ti»."],gates:[{path:"professional.homePull",op:"gte",value:55}],seedsRead:["SEED_HOME_RETURN_31"],seedsWrite:["SEED_HOME_CAPTAIN_OFFER"],choices:[
 {id:"A",label:"Volver",intentTags:["home_return","captaincy"],immediateEffects:[flag("HOME_RETURN_30",true),flag("AGE32_HOME_CAPTAIN_RETURN",true)],primaryMessage:"Aceptas que tu versión competitiva actual sea el centro de un regreso deportivo real.",secondaryMessage:"El proyecto puede liberarte o convertir cada problema institucional en una discusión sobre tu figura.",primaryEffects:[n("professional.homePull",12),n("professional.legacyCapital",6),n("professional.lockerPower",5)],secondaryEffects:[n("professional.successionPressure",2)],primarySeedTransitions:seed("SEED_HOME_CAPTAIN_OFFER","A"),secondarySeedTransitions:seed("SEED_HOME_CAPTAIN_OFFER","A")},
 {id:"B",label:"Pedir que no te prometan capitanía",intentTags:["home_return","no_privilege"],immediateEffects:[flag("AGE32_HOME_NO_CAPTAIN_PROMISE",true)],primaryMessage:"Intentas separar el regreso de un privilegio que el vestuario debería validar.",secondaryMessage:"Renunciar al símbolo puede mejorar legitimidad o parecer un gesto teatral si todos esperan que ejerzas el poder igualmente.",primaryEffects:[n("professional.legacyCapital",5),n("professional.institutionalTrust",4)],secondaryEffects:[n("professional.lockerPower",1)],primarySeedTransitions:seed("SEED_HOME_CAPTAIN_OFFER","B"),secondarySeedTransitions:seed("SEED_HOME_CAPTAIN_OFFER","B")},
 {id:"C",label:"Exigir que el proyecto no dependa de tu nombre comercialmente",intentTags:["institutional_boundary","home_return"],immediateEffects:[flag("AGE32_HOME_NO_COMMERCIAL_DEPENDENCE",true)],primaryMessage:"Pides que plantilla, patrocinio y narrativa puedan sobrevivir a una lesión o a tu salida.",secondaryMessage:"La condición protege al club y limita parte del dinero y atención que precisamente hace posible el proyecto.",primaryEffects:[n("professional.careerControl",5),n("professional.institutionalPower",4)],secondaryEffects:[n("professional.commercialPower",-2)],primarySeedTransitions:seed("SEED_HOME_CAPTAIN_OFFER","C"),secondarySeedTransitions:seed("SEED_HOME_CAPTAIN_OFFER","C")},
 {id:"D",label:"Rechazar y dejar puerta abierta para más adelante",intentTags:["delay_home_return","market"],immediateEffects:[flag("AGE32_HOME_DELAYED",true)],primaryMessage:"No conviertes la llamada emocional en una obligación contractual inmediata.",secondaryMessage:"La puerta queda abierta, pero el proyecto que hoy necesita tu versión competitiva puede no existir después.",primaryEffects:[n("professional.careerControl",4),n("professional.veteranLeverage",2)],secondaryEffects:[n("professional.homePull",3)],primarySeedTransitions:seed("SEED_HOME_CAPTAIN_OFFER","D"),secondarySeedTransitions:seed("SEED_HOME_CAPTAIN_OFFER","D")}
]});

const agent=ambiguousEvent({...common([8,9,1]),id:"EVT_32_AGT_001",family:"agent",title:"¿Necesitas agente?",body:"Tras años de comisiones y conflictos te planteas gestionar personalmente una renovación sencilla con apoyo de abogado, manteniendo agente solo para mercado internacional.",visible:["Conoces costes, contactos actuales y complejidad contractual."],uncertain:["No sabes qué oportunidades nunca llegarán a ti sin una red de intermediación activa."],seedsRead:["SEED_AGENT_LAST_CONTRACT"],seedsWrite:["SEED_SELF_REPRESENTATION"],choices:[
 {id:"A",label:"Representarte en contratos domésticos",intentTags:["self_representation","domestic"],immediateEffects:[flag("AGE32_SELF_REP_DOMESTIC",true)],primaryMessage:"Asumes la negociación sencilla y reservas intermediación para operaciones donde la red sí aporta valor.",secondaryMessage:"Ganas control y puedes perder llamadas que nunca sabrás que existieron.",primaryEffects:[n("professional.careerControl",7),n("professional.contractPower",4)],secondaryEffects:[n("professional.veteranLeverage",-1)],primarySeedTransitions:seed("SEED_SELF_REPRESENTATION","A"),secondarySeedTransitions:seed("SEED_SELF_REPRESENTATION","A")},
 {id:"B",label:"Mantener agencia completa",intentTags:["agency","network"],immediateEffects:[flag("AGE32_FULL_AGENCY",true)],primaryMessage:"Mantienes una estructura que conoce clubes, tiempos y personas mejor que tú.",secondaryMessage:"Conservas acceso y aceptas que el conflicto entre comisión y control no desaparece por experiencia.",primaryEffects:[n("professional.veteranLeverage",4),n("professional.contractPower",2)],secondaryEffects:[n("professional.careerControl",-2)],primarySeedTransitions:seed("SEED_SELF_REPRESENTATION","B"),secondarySeedTransitions:seed("SEED_SELF_REPRESENTATION","B")},
 {id:"C",label:"Cambiar a fee fijo sin porcentaje",intentTags:["fixed_fee","agency"],immediateEffects:[flag("AGE32_AGENT_FIXED_FEE",true)],primaryMessage:"Intentas eliminar el incentivo a maximizar cifra cuando quizá te importe más el rol.",secondaryMessage:"El fee alinea una parte de los intereses, no convierte a tu representante en neutral.",primaryEffects:[n("professional.careerControl",5),n("professional.moneyComfort",2)],secondaryEffects:[n("professional.contractPower",1)],primarySeedTransitions:seed("SEED_SELF_REPRESENTATION","C"),secondarySeedTransitions:seed("SEED_SELF_REPRESENTATION","C")},
 {id:"D",label:"Crear pequeño equipo propio de representación",intentTags:["representation_team","control"],immediateEffects:[flag("AGE32_OWN_REP_TEAM",true)],primaryMessage:"Construyes una estructura a tu alrededor en vez de sustituir una persona por otra.",secondaryMessage:"El equipo puede profesionalizar decisiones o crear una nueva capa de empleados dependientes de que sigas jugando.",primaryEffects:[n("professional.careerControl",6),n("professional.commercialPower",3)],secondaryEffects:[n("professional.moneyComfort",-2)],primarySeedTransitions:seed("SEED_SELF_REPRESENTATION","D"),secondarySeedTransitions:seed("SEED_SELF_REPRESENTATION","D")}
]});

const fan=ambiguousEvent({...common([10,11,12]),id:"EVT_32_FAN_001",family:"press",title:"Te cantan después de jugar mal",body:"Haces un partido claramente malo y, aun así, parte del estadio canta tu nombre por todo lo que representas. Otra parte critica que el pasado te proteja.",visible:["Ves la reacción del estadio y el análisis objetivo de tu partido."],uncertain:["No sabes si el apoyo es cariño, protesta contra el entrenador o deseo de negar un posible declive."],gates:[{path:"professional.legacyCapital",op:"gte",value:45},{path:"sport.form",op:"lte",value:48}],seedsWrite:["SEED_FAN_LEGACY_BUFFER"],choices:[
 {id:"A",label:"Agradecer y reconocer mal partido",intentTags:["accountability","fans"],immediateEffects:[flag("AGE32_FAN_ADMIT_BAD_GAME",true)],primaryMessage:"Aceptas el cariño sin usarlo para negar lo que ocurrió en el campo.",secondaryMessage:"La honestidad puede reforzar respeto y también regalar titulares sobre declive.",primaryEffects:[n("professional.legacyCapital",5),n("professional.publicMyth",2)],secondaryEffects:[n("reputation.mediaHeat",2)],primarySeedTransitions:seed("SEED_FAN_LEGACY_BUFFER","A"),secondarySeedTransitions:seed("SEED_FAN_LEGACY_BUFFER","A")},
 {id:"B",label:"Agradecer sin autocrítica",intentTags:["fans","neutral_message"],immediateEffects:[flag("AGE32_FAN_THANK_ONLY",true)],primaryMessage:"Reconoces al estadio sin convertir una noche mala en diagnóstico público.",secondaryMessage:"Evitas alimentar el relato y dejas abierta la acusación de que tu estatus te protege de evaluar el presente.",primaryEffects:[n("professional.publicMyth",3)],secondaryEffects:[n("professional.legacyCapital",1)],primarySeedTransitions:seed("SEED_FAN_LEGACY_BUFFER","B"),secondarySeedTransitions:seed("SEED_FAN_LEGACY_BUFFER","B")},
 {id:"C",label:"No comentar",intentTags:["silence","fans"],immediateEffects:[flag("AGE32_FAN_NO_COMMENT",true)],primaryMessage:"No conviertes la grada en una discusión pública sobre tu nivel.",secondaryMessage:"El silencio reduce tus palabras y aumenta el espacio para interpretarlas por ti.",primaryEffects:[n("professional.careerControl",2)],secondaryEffects:[n("reputation.mediaHeat",1)],primarySeedTransitions:seed("SEED_FAN_LEGACY_BUFFER","C"),secondarySeedTransitions:seed("SEED_FAN_LEGACY_BUFFER","C")},
 {id:"D",label:"Defender que la evaluación debe ser igual para todos",intentTags:["equal_standard","accountability"],immediateEffects:[flag("AGE32_FAN_EQUAL_STANDARD",true)],primaryMessage:"Rechazas que el historial rebaje el estándar deportivo que exiges al resto.",secondaryMessage:"La posición protege credibilidad y puede sonar como una crítica indirecta a quienes usan tu legado para defenderte.",primaryEffects:[n("professional.legacyCapital",4),n("professional.lockerPower",2)],secondaryEffects:[n("professional.publicMyth",-1)],primarySeedTransitions:seed("SEED_FAN_LEGACY_BUFFER","D"),secondarySeedTransitions:seed("SEED_FAN_LEGACY_BUFFER","D")}
]});

const national=ambiguousEvent({...common([3,4,5]),id:"EVT_32_NAT_001",family:"selection",title:"La lista final",body:"A semanas de un gran torneo estás entre 30 preseleccionados para 26 plazas. Antes eras automático; ahora el seleccionador necesita dos roles que también cubres tú.",visible:["Conoces competidores, forma reciente y criterios generales de selección."],uncertain:["No sabes si tu liderazgo compensa menor ritmo ni cuánto pesa una molestia reciente."],gates:[{path:"facts.nationalSelection.preselected30",op:"eq",value:true}],seedsRead:["SEED_NATIONAL_PHASEDOWN"],seedsWrite:["SEED_FINAL_NT_SQUAD"],choices:[
 {id:"A",label:"Aceptar cualquier rol",intentTags:["national_team","any_role"],immediateEffects:[flag("AGE32_NT_ANY_ROLE",true)],primaryMessage:"Priorizas estar en el torneo por encima de la jerarquía que tuviste antes.",secondaryMessage:"La flexibilidad puede conservar tu plaza o confirmar que la selección ya te ve principalmente como veterano de rotación.",primaryEffects:[n("professional.roleAdaptability",4),n("professional.nationalStanding",2)],secondaryEffects:[n("professional.statusInertia",-1)],primarySeedTransitions:seed("SEED_FINAL_NT_SQUAD","A"),secondarySeedTransitions:seed("SEED_FINAL_NT_SQUAD","A")},
 {id:"B",label:"Decir que solo tiene sentido ir si puedes ayudar en campo",intentTags:["national_team","sport_role"],immediateEffects:[flag("AGE32_NT_FIELD_ROLE_ONLY",true)],primaryMessage:"Pides que la convocatoria se justifique por utilidad deportiva y no solo por liderazgo simbólico.",secondaryMessage:"La claridad protege tu criterio y facilita al seleccionador elegir a otro si no puede prometerte ese papel.",primaryEffects:[n("professional.careerControl",4),n("professional.motivationReserve",2)],secondaryEffects:[n("professional.nationalStanding",-2)],primarySeedTransitions:seed("SEED_FINAL_NT_SQUAD","B"),secondarySeedTransitions:seed("SEED_FINAL_NT_SQUAD","B")},
 {id:"C",label:"Pedir claridad sin exigir plaza",intentTags:["national_team","clarity"],immediateEffects:[flag("AGE32_NT_CLARITY",true)],primaryMessage:"Quieres conocer cómo te compara el seleccionador sin convertir la conversación en un ultimátum.",secondaryMessage:"Ganas información, no control sobre la lista definitiva.",primaryEffects:[n("professional.careerControl",3),n("professional.institutionalTrust",2)],secondaryEffects:[n("professional.nationalStanding",1)],primarySeedTransitions:seed("SEED_FINAL_NT_SQUAD","C"),secondarySeedTransitions:seed("SEED_FINAL_NT_SQUAD","C")},
 {id:"D",label:"Retirarte internacionalmente antes de la lista",intentTags:["national_retirement","control_exit"],immediateEffects:[flag("NATIONAL_RETIRED",true),flag("AGE32_NT_RETIRE_BEFORE_LIST",true)],primaryMessage:"Eliges tú el final internacional antes de exponerte a quedar fuera.",secondaryMessage:"Controlas la despedida y renuncias voluntariamente a una última oportunidad que todavía podía existir.",primaryEffects:[n("professional.recoveryDebt",-5),n("professional.motivationReserve",3),n("professional.legacyCapital",3)],secondaryEffects:[n("professional.nationalStanding",-8)],primarySeedTransitions:seed("SEED_FINAL_NT_SQUAD","D"),secondarySeedTransitions:seed("SEED_FINAL_NT_SQUAD","D")}
]});

export const CANONICAL_REIMPLEMENTATIONS_32A:EventDefinition[]=[contract,home,agent,fan,national];
