import type { EventDefinition } from "../../../core/types.js";
import { ambiguousEvent, flag, n, seedCreate } from "../18_20/helpers.js";

const seed=(seedId:string,choice:string)=>[seedCreate(seedId,60,{choice})];
const common=(months:number[])=>({
  ageWindow:[31,31] as [number,number],
  phase:"30_34" as const,
  timeWindow:{months},
  cooldown:99999,
  weight:10,
  tags:["maturity","t51_canonical_reimplementation","t51_trigger_approximation"],
  canonStatus:"technical_adaptation" as const
});

const legacy=ambiguousEvent({...common([9,10,11]),id:"EVT_31_LEGACY_001",family:"legacy",title:"Tu nombre en una academia",body:"Una marca y tu entorno proponen abrir una academia con tu nombre. UDV ofrece colaborar si se hace en Valdoria, pero quiere influencia sobre captación y metodología.",visible:["Conoces el modelo económico, los socios propuestos y cómo se usaría tu imagen."],uncertain:["No sabes si el proyecto será legado real o una distracción que dependerá de terceros."],gates:[{path:"professional.legacyCapital",op:"gte",value:35},{path:"professional.moneyComfort",op:"gte",value:25}],seedsWrite:["SEED_LEGACY_ACADEMY"],choices:[
  {id:"A",label:"Crear academia independiente",intentTags:["legacy","independent"],immediateEffects:[flag("AGE31_ACADEMY_INDEPENDENT",true)],primaryMessage:"Construyes el proyecto fuera de la estructura de cualquier club.",secondaryMessage:"Ganas autonomía, pero también concentras riesgo, tiempo y reputación en socios que todavía no han demostrado nada.",primaryEffects:[n("professional.legacyCapital",6),n("professional.careerControl",3)],secondaryEffects:[n("professional.moneyComfort",-3)],primarySeedTransitions:seed("SEED_LEGACY_ACADEMY","A"),secondarySeedTransitions:seed("SEED_LEGACY_ACADEMY","A")},
  {id:"B",label:"Hacerla con UDV",intentTags:["legacy","home_institution"],immediateEffects:[flag("AGE31_ACADEMY_UDV",true)],primaryMessage:"Vinculas el proyecto a Valdoria y a una institución que ya tiene estructura local.",secondaryMessage:"La colaboración reduce fricción operativa y crea un posible conflicto sobre quién controla metodología, captación y tu nombre.",primaryEffects:[n("professional.legacyCapital",7),n("professional.homePull",4),n("professional.institutionalPower",3)],secondaryEffects:[n("professional.careerControl",-2)],primarySeedTransitions:seed("SEED_LEGACY_ACADEMY","B"),secondarySeedTransitions:seed("SEED_LEGACY_ACADEMY","B")},
  {id:"C",label:"Posponer a retirada",intentTags:["legacy","delay"],immediateEffects:[flag("AGE31_ACADEMY_DELAYED",true)],primaryMessage:"Decides que un proyecto de legado no debe competir todavía con tu carrera activa.",secondaryMessage:"Proteges foco y puedes llegar a la retirada con más claridad, aunque la oportunidad y los socios actuales pueden desaparecer.",primaryEffects:[n("professional.careerControl",4),n("professional.motivationReserve",2)],secondaryEffects:[n("professional.legacyCapital",1)],primarySeedTransitions:seed("SEED_LEGACY_ACADEMY","C"),secondarySeedTransitions:seed("SEED_LEGACY_ACADEMY","C")},
  {id:"D",label:"Financiar becas sin poner tu nombre",intentTags:["legacy","scholarships"],immediateEffects:[flag("AGE31_ACADEMY_SCHOLARSHIPS",true)],primaryMessage:"Apoyas formación sin convertirla en una extensión de tu marca personal.",secondaryMessage:"El impacto puede ser más limpio y menos visible; renuncias a parte del capital reputacional que buscaban los socios.",primaryEffects:[n("professional.legacyCapital",5),n("professional.publicMyth",1)],secondaryEffects:[n("professional.moneyComfort",-2)],primarySeedTransitions:seed("SEED_LEGACY_ACADEMY","D"),secondarySeedTransitions:seed("SEED_LEGACY_ACADEMY","D")}
]});

const comeback=ambiguousEvent({...common([9,10,11,2,3]),id:"EVT_31_RETURN_001",family:"medical",title:"Volver sin ritmo",body:"Tras lesión o cirugía recibes el alta médica, pero tus datos de entrenamiento están lejos de tus mejores semanas. El entrenador necesita decidir si convocarte ya.",visible:["Ves el alta, la carga reciente y tus sensaciones de entrenamiento."],uncertain:["Alta médica no equivale a rendimiento ni elimina el riesgo de recaída."],gates:[{path:"flags.RECOVERING_INJURY",op:"eq",value:true}],seedsRead:["SEED_SURGERY_31"],seedsWrite:["SEED_COMEBACK_PACING"],choices:[
  {id:"A",label:"Pedir entrar ya aunque sea pocos minutos",intentTags:["comeback","early_minutes"],immediateEffects:[flag("AGE31_COMEBACK_NOW",true)],primaryMessage:"Buscas recuperar ritmo dentro de partidos reales aunque la carga sea mínima.",secondaryMessage:"Los primeros minutos pueden devolverte timing o convertir una vuelta controlada en una recaída prematura.",primaryEffects:[n("professional.availability",4),n("professional.statusInertia",2)],secondaryEffects:[n("professional.recoveryDebt",6)],primarySeedTransitions:seed("SEED_COMEBACK_PACING","A"),secondarySeedTransitions:seed("SEED_COMEBACK_PACING","A")},
  {id:"B",label:"Jugar primero con filial o amistoso si existe",intentTags:["comeback","controlled_minutes"],immediateEffects:[flag("AGE31_COMEBACK_CONTROLLED",true)],primaryMessage:"Buscas exposición competitiva con menor coste de jerarquía y resultado.",secondaryMessage:"El escalón intermedio puede mejorar sensaciones sin replicar del todo la velocidad del primer equipo.",primaryEffects:[n("professional.recoveryMargin",4),n("professional.availability",2)],secondaryEffects:[n("professional.statusInertia",-1)],primarySeedTransitions:seed("SEED_COMEBACK_PACING","B"),secondarySeedTransitions:seed("SEED_COMEBACK_PACING","B")},
  {id:"C",label:"Esperar dos semanas completas",intentTags:["comeback","wait"],immediateEffects:[flag("AGE31_COMEBACK_TWO_WEEKS",true)],primaryMessage:"Priorizas dos semanas de carga completa antes de exponerte a un partido.",secondaryMessage:"El cuerpo gana margen mientras otro jugador dispone de dos semanas para convertir tu ausencia en una jerarquía nueva.",primaryEffects:[n("professional.recoveryDebt",-5),n("professional.recoveryMargin",5)],secondaryEffects:[n("professional.roleSecurity",-3)],primarySeedTransitions:seed("SEED_COMEBACK_PACING","C"),secondarySeedTransitions:seed("SEED_COMEBACK_PACING","C")},
  {id:"D",label:"Dejar al staff decidir sin presión",intentTags:["comeback","staff_trust"],immediateEffects:[flag("AGE31_COMEBACK_STAFF_DECIDES",true)],primaryMessage:"Renuncias a empujar la fecha y aceptas que disponibilidad y convocatoria sean decisiones distintas.",secondaryMessage:"El gesto mejora confianza, pero también cede control sobre un momento que puede redefinir tu rol.",primaryEffects:[n("professional.institutionalTrust",4),n("professional.recoveryMargin",2)],secondaryEffects:[n("professional.careerControl",-2)],primarySeedTransitions:seed("SEED_COMEBACK_PACING","D"),secondarySeedTransitions:seed("SEED_COMEBACK_PACING","D")}
]});

const tactical=ambiguousEvent({...common([10,11,12]),id:"EVT_31_TACT_001",family:"tactical",title:"Ya no eres extremo",body:"Un nuevo análisis concluye que tu mejor versión actual podría ser como segundo punta o interior creador, con menos metros defensivos y más balón entre líneas.",visible:["Ves vídeos, métricas y comparación de acciones entre tu posición histórica y el rol propuesto."],uncertain:["No sabes si el nuevo rol mantendrá producción o solo oculta una caída física."],seedsWrite:["SEED_ROLE_REINVENTION_32"],choices:[
  {id:"A",label:"Adoptarlo como posición principal",intentTags:["reinvention","primary_role"],immediateEffects:[flag("ROLE_REINVENTED_30",true),flag("AGE31_NEW_PRIMARY_ROLE",true)],primaryMessage:"Aceptas que tu mejor versión adulta puede requerir una identidad táctica distinta.",secondaryMessage:"El cambio puede abrir un segundo pico o reducir números y mercado antes de demostrar que funciona.",primaryEffects:[n("professional.roleAdaptability",8),n("professional.tacticalReading",5)],secondaryEffects:[n("professional.statusInertia",-2)],primarySeedTransitions:seed("SEED_ROLE_REINVENTION_32","A"),secondarySeedTransitions:seed("SEED_ROLE_REINVENTION_32","A")},
  {id:"B",label:"Mantener posición histórica",intentTags:["historic_role","resist_reinvention"],immediateEffects:[flag("AGE31_KEEP_HISTORIC_ROLE",true)],primaryMessage:"Defiendes que una lectura de datos no debe borrar años de automatismos y producción.",secondaryMessage:"Mantener el rol conserva referencia y puede exponer más claramente cualquier pérdida de explosividad.",primaryEffects:[n("professional.statusInertia",4),n("professional.motivationReserve",2)],secondaryEffects:[n("professional.recoveryDebt",2)],primarySeedTransitions:seed("SEED_ROLE_REINVENTION_32","B"),secondarySeedTransitions:seed("SEED_ROLE_REINVENTION_32","B")},
  {id:"C",label:"Alternar según rival",intentTags:["hybrid_role","adapt"],immediateEffects:[flag("ROLE_REINVENTED_30",true),flag("AGE31_HYBRID_ROLE",true)],primaryMessage:"Conviertes la ambigüedad en una herramienta táctica y no en una elección definitiva.",secondaryMessage:"La versatilidad aumenta utilidad, aunque puede impedir que consolides automatismos o una jerarquía clara en ninguna posición.",primaryEffects:[n("professional.roleAdaptability",7),n("professional.tacticalReading",6)],secondaryEffects:[n("professional.roleSecurity",1)],primarySeedTransitions:seed("SEED_ROLE_REINVENTION_32","C"),secondarySeedTransitions:seed("SEED_ROLE_REINVENTION_32","C")},
  {id:"D",label:"Probarlo seis partidos antes de redefinir tu perfil",intentTags:["role_trial","six_matches"],immediateEffects:[flag("AGE31_ROLE_SIX_MATCH_TRIAL",true)],primaryMessage:"Exiges una muestra competitiva antes de convertir una hipótesis táctica en tu nueva identidad.",secondaryMessage:"Seis partidos generan evidencia, pero el calendario y los rivales pueden hacer que la muestra engañe.",primaryEffects:[n("professional.careerControl",4),n("professional.roleAdaptability",3)],secondaryEffects:[n("professional.statusInertia",1)],primarySeedTransitions:seed("SEED_ROLE_REINVENTION_32","D"),secondarySeedTransitions:seed("SEED_ROLE_REINVENTION_32","D")}
]});

const coach=ambiguousEvent({...common([7,8,9]),id:"EVT_31_CCH_001",family:"captaincy",title:"El nuevo entrenador no te debe nada",body:"Cambio de entrenador. El nuevo técnico te respeta, pero te dice que no le importan tus 300 partidos ni tu salario: seleccionará según su modelo.",visible:["Conoces sus ideas tácticas y has tenido una conversación frontal sobre el nuevo punto de partida."],uncertain:["No sabes si la neutralidad es real o si quiere marcar autoridad frente al vestuario."],seedsWrite:["SEED_NEW_COACH_RESET"],choices:[
  {id:"A",label:"Aceptar empezar de cero",intentTags:["coach_reset","compete"],immediateEffects:[flag("AGE31_COACH_RESET_ACCEPTED",true)],primaryMessage:"Aceptas competir bajo el criterio nuevo sin reclamar deuda por tu historial.",secondaryMessage:"La postura facilita la relación, pero también permite que el entrenador reduzca tu rol sin coste político contigo.",primaryEffects:[n("professional.institutionalTrust",4),n("professional.motivationReserve",3)],secondaryEffects:[n("professional.statusInertia",-2)],primarySeedTransitions:seed("SEED_NEW_COACH_RESET","A"),secondarySeedTransitions:seed("SEED_NEW_COACH_RESET","A")},
  {id:"B",label:"Recordarle qué sabes del vestuario",intentTags:["locker_knowledge","veteran_power"],immediateEffects:[flag("AGE31_COACH_LOCKER_REMINDER",true)],primaryMessage:"Pones sobre la mesa información informal que un técnico recién llegado todavía no tiene.",secondaryMessage:"Puede verlo como ayuda valiosa o como una demostración de poder que necesita limitar.",primaryEffects:[n("professional.lockerPower",5),n("professional.legacyCapital",2)],secondaryEffects:[n("professional.institutionalTrust",-2)],primarySeedTransitions:seed("SEED_NEW_COACH_RESET","B"),secondarySeedTransitions:seed("SEED_NEW_COACH_RESET","B")},
  {id:"C",label:"Pedir claridad sobre tu encaje",intentTags:["role_clarity","coach_talk"],immediateEffects:[flag("AGE31_COACH_ROLE_CLARITY",true)],primaryMessage:"Pides saber qué comportamientos y posiciones te acercan realmente a jugar.",secondaryMessage:"La claridad permite adaptarte, aunque escuchar un rol menor puede convertir incertidumbre en una realidad incómoda.",primaryEffects:[n("professional.careerControl",4),n("professional.roleAdaptability",3)],secondaryEffects:[n("professional.roleSecurity",-1)],primarySeedTransitions:seed("SEED_NEW_COACH_RESET","C"),secondarySeedTransitions:seed("SEED_NEW_COACH_RESET","C")},
  {id:"D",label:"No buscar reunión adicional y competir",intentTags:["compete","no_meeting"],immediateEffects:[flag("AGE31_COACH_NO_EXTRA_MEETING",true)],primaryMessage:"Decides que tu respuesta será el entrenamiento y no otra conversación sobre estatus.",secondaryMessage:"La competencia evita negociar privilegios, pero reduce tu capacidad de corregir una interpretación táctica equivocada.",primaryEffects:[n("professional.motivationReserve",4),n("professional.statusInertia",1)],secondaryEffects:[n("professional.careerControl",-1)],primarySeedTransitions:seed("SEED_NEW_COACH_RESET","D"),secondarySeedTransitions:seed("SEED_NEW_COACH_RESET","D")}
]});

const national=ambiguousEvent({...common([9,10,3,4]),id:"EVT_31_NAT_001",family:"selection",title:"Club contra selección, otra vez",body:"El club pide que no viajes a una concentración menor por carga; la selección dice que tu presencia como veterano ayuda incluso si juegas poco.",visible:["Conoces las recomendaciones de ambos cuerpos técnicos y médicos."],uncertain:["No sabes si ausentarte tendrá coste político real ni si viajar empeorará tu disponibilidad posterior."],gates:[{path:"professional.nationalStanding",op:"gte",value:20},{path:"professional.recoveryDebt",op:"gte",value:25}],seedsWrite:["SEED_CLUB_NT_LOAD_TENSION"],choices:[
  {id:"A",label:"Ir siempre",intentTags:["national_team","always_go"],immediateEffects:[flag("AGE31_NT_ALWAYS_GO",true)],primaryMessage:"Priorizas disponibilidad total con la selección mientras sigas convocado.",secondaryMessage:"La presencia sostiene vínculo y liderazgo mientras la carga de viaje se acumula sobre el calendario del club.",primaryEffects:[n("professional.nationalStanding",4),n("professional.legacyCapital",2)],secondaryEffects:[n("professional.recoveryDebt",5)],primarySeedTransitions:seed("SEED_CLUB_NT_LOAD_TENSION","A"),secondarySeedTransitions:seed("SEED_CLUB_NT_LOAD_TENSION","A")},
  {id:"B",label:"Quedarte con el club",intentTags:["club_first","rest"],immediateEffects:[flag("AGE31_NT_STAY_CLUB",true)],primaryMessage:"Aceptas que una concentración menor no compense el coste físico de viajar.",secondaryMessage:"El club gana disponibilidad; la selección puede entenderlo o usar la ventana para consolidar a otro jugador.",primaryEffects:[n("professional.recoveryDebt",-5),n("professional.institutionalTrust",3)],secondaryEffects:[n("professional.nationalStanding",-4)],primarySeedTransitions:seed("SEED_CLUB_NT_LOAD_TENSION","B"),secondarySeedTransitions:seed("SEED_CLUB_NT_LOAD_TENSION","B")},
  {id:"C",label:"Viajar pero pedir minutos limitados",intentTags:["national_team","limited_minutes"],immediateEffects:[flag("AGE31_NT_LIMITED_MINUTES",true)],primaryMessage:"Intentas conservar presencia internacional sin pagar toda la carga competitiva.",secondaryMessage:"La solución puede satisfacer a ambos o parecer a ambos una concesión insuficiente.",primaryEffects:[n("professional.matchSelectivity",5),n("professional.nationalStanding",2)],secondaryEffects:[n("professional.recoveryDebt",1)],primarySeedTransitions:seed("SEED_CLUB_NT_LOAD_TENSION","C"),secondarySeedTransitions:seed("SEED_CLUB_NT_LOAD_TENSION","C")},
  {id:"D",label:"Pedir que ambos staffs acuerden un plan por escrito",intentTags:["joint_plan","coordination"],immediateEffects:[flag("AGE31_NT_JOINT_PLAN",true)],primaryMessage:"Obligas a club y selección a compartir una política concreta de carga y minutos.",secondaryMessage:"La coordinación reduce ambigüedad, aunque un acuerdo conjunto puede dejar a ambas partes parcialmente insatisfechas.",primaryEffects:[n("professional.careerControl",5),n("professional.matchSelectivity",3)],secondaryEffects:[n("professional.institutionalTrust",1)],primarySeedTransitions:seed("SEED_CLUB_NT_LOAD_TENSION","D"),secondarySeedTransitions:seed("SEED_CLUB_NT_LOAD_TENSION","D")}
]});

const final=ambiguousEvent({...common([4,5]),id:"EVT_31_FINAL_001",family:"sport",title:"La final de 70 minutos",body:"Antes de una final, el entrenador te dice que el plan ideal es que juegues 60-70 minutos a máxima intensidad y salga otro jugador antes de que caiga tu presión.",visible:["Conoces un plan físico-táctico detallado para tu papel en la final."],uncertain:["No sabes el marcador futuro ni cómo te sentirás al minuto 65."],gates:[{path:"flags.FINAL_CONTEXT",op:"eq",value:true},{path:"sport.roleScore",op:"gte",value:35}],seedsWrite:["SEED_MANAGED_FINAL_ROLE"],choices:[
  {id:"A",label:"Aceptar el plan",intentTags:["final","managed_minutes"],immediateEffects:[flag("AGE31_FINAL_PLAN_ACCEPTED",true)],primaryMessage:"Aceptas maximizar intensidad dentro de una ventana prevista de 60-70 minutos.",secondaryMessage:"El plan puede ser perfecto y quedar obsoleto en cuanto cambie el marcador o el partido necesite prórroga.",primaryEffects:[n("professional.matchSelectivity",5),n("professional.institutionalTrust",3)],secondaryEffects:[n("professional.statusInertia",1)],primarySeedTransitions:seed("SEED_MANAGED_FINAL_ROLE","A"),secondarySeedTransitions:seed("SEED_MANAGED_FINAL_ROLE","A")},
  {id:"B",label:"Pedir que el cambio dependa del partido, no del reloj",intentTags:["final","game_state"],immediateEffects:[flag("AGE31_FINAL_GAME_STATE_CHANGE",true)],primaryMessage:"Aceptas gestión física, pero rechazas que el minuto decida antes que el contexto competitivo.",secondaryMessage:"La flexibilidad puede mantenerte cuando el equipo te necesita o alargar carga precisamente cuando más fatiga acumulas.",primaryEffects:[n("professional.careerControl",4),n("professional.veteranLeverage",2)],secondaryEffects:[n("professional.recoveryDebt",3)],primarySeedTransitions:seed("SEED_MANAGED_FINAL_ROLE","B"),secondarySeedTransitions:seed("SEED_MANAGED_FINAL_ROLE","B")},
  {id:"C",label:"Solicitar empezar en el banquillo para terminar",intentTags:["final","finisher"],immediateEffects:[flag("AGE31_FINAL_FINISHER",true)],primaryMessage:"Cambias prestigio de titularidad por la posibilidad de estar en el campo cuando se decida el título.",secondaryMessage:"Puedes entrar con el partido abierto o ver cómo la final se resuelve antes de que tu rol llegue a existir.",primaryEffects:[n("professional.roleAdaptability",5),n("professional.recoveryDebt",-2)],secondaryEffects:[n("professional.statusInertia",-2)],primarySeedTransitions:seed("SEED_MANAGED_FINAL_ROLE","C"),secondarySeedTransitions:seed("SEED_MANAGED_FINAL_ROLE","C")},
  {id:"D",label:"No discutir y pedir solo aviso antes del cambio",intentTags:["final","coach_trust"],immediateEffects:[flag("AGE31_FINAL_NOTICE_ONLY",true)],primaryMessage:"Dejas la decisión táctica al entrenador y solo pides no enterarte del relevo por la pizarra.",secondaryMessage:"La confianza simplifica el partido, pero cede casi todo el control sobre cómo termina tu noche.",primaryEffects:[n("professional.institutionalTrust",4),n("professional.motivationReserve",2)],secondaryEffects:[n("professional.careerControl",-2)],primarySeedTransitions:seed("SEED_MANAGED_FINAL_ROLE","D"),secondarySeedTransitions:seed("SEED_MANAGED_FINAL_ROLE","D")}
]});

export const CANONICAL_REIMPLEMENTATIONS_31B:EventDefinition[]=[legacy,comeback,tactical,coach,national,final];
