import type { EventDefinition, SeedTransition } from "../../../core/types.js";
import { ambiguousEvent, flag, n, seedCreate } from "../18_20/helpers.js";

const seed=(seedId:string,choice:string)=>[seedCreate(seedId,60,{choice})];
const seedMany=(ids:string[],choice:string):SeedTransition[]=>ids.map(id=>seedCreate(id,60,{choice}));
const common=(months:number[],authorityGuarded=false)=>({ageWindow:[33,33] as [number,number],phase:"30_34" as const,timeWindow:{months},cooldown:99999,weight:10,tags:["maturity","t51_canonical_reimplementation","t51_trigger_approximation",...(authorityGuarded?["t51_shared_authority_guard"]:[])],canonStatus:"technical_adaptation" as const});

const body=ambiguousEvent({...common([8,9,10,11]),id:"EVT_33_BODY_001",family:"medical",title:"Dos partidos en 72 horas",body:"El staff te comunica que sus datos ya no recomiendan dos titularidades de alta intensidad con menos de 72 horas entre ellas. No es una prohibición médica.",visible:["Ves tus datos longitudinales de recuperación y carga."],uncertain:["No sabes si esta limitación es permanente, contextual o demasiado conservadora."],gates:[{path:"professional.recoveryMargin",op:"lte",value:55}],seedsRead:["SEED_MATCH_SELECTIVITY"],seedsWrite:["SEED_72H_LIMIT"],choices:[
 {id:"A",label:"Aceptar como regla general",intentTags:["recovery_rule","selectivity"],immediateEffects:[flag("AGE33_72H_RULE",true)],primaryMessage:"Conviertes la recomendación en una regla de disponibilidad antes de que exista una lesión que te obligue.",secondaryMessage:"La restricción puede alargar tu disponibilidad y reducir ritmo o presencia en semanas grandes.",primaryEffects:[n("professional.matchSelectivity",8),n("professional.recoveryDebt",-5)],secondaryEffects:[n("professional.statusInertia",-2)],primarySeedTransitions:seed("SEED_72H_LIMIT","A"),secondarySeedTransitions:seed("SEED_72H_LIMIT","A")},
 {id:"B",label:"Decidir caso a caso",intentTags:["case_by_case","recovery"],immediateEffects:[flag("AGE33_72H_CASE_BY_CASE",true)],primaryMessage:"No conviertes una tendencia estadística en una prohibición automática.",secondaryMessage:"La flexibilidad conserva contexto y vuelve a abrir la misma negociación cada semana congestionada.",primaryEffects:[n("professional.matchSelectivity",4),n("professional.careerControl",3)],secondaryEffects:[n("professional.recoveryDebt",-1)],primarySeedTransitions:seed("SEED_72H_LIMIT","B"),secondarySeedTransitions:seed("SEED_72H_LIMIT","B")},
 {id:"C",label:"Ignorar mientras te sientas bien",intentTags:["ignore_limit","availability"],immediateEffects:[flag("AGE33_72H_IGNORE",true)],primaryMessage:"Mantienes la identidad de estar disponible si las sensaciones no dicen lo contrario.",secondaryMessage:"Las sensaciones pueden acertar durante semanas y llegar tarde cuando la deuda de recuperación ya existe.",primaryEffects:[n("professional.availability",4),n("professional.motivationReserve",2)],secondaryEffects:[n("professional.recoveryDebt",7)],primarySeedTransitions:seed("SEED_72H_LIMIT","C"),secondarySeedTransitions:seed("SEED_72H_LIMIT","C")},
 {id:"D",label:"Cambiar rol para intentar sostener ambos partidos",intentTags:["role_change","recovery"],immediateEffects:[flag("AGE33_72H_ROLE_CHANGE",true)],primaryMessage:"Intentas reducir demanda física sin renunciar a estar en los dos partidos.",secondaryMessage:"La adaptación puede prolongar tu presencia y terminar redefiniendo tu posición en la fase final de carrera.",primaryEffects:[n("professional.roleAdaptability",7),n("professional.tacticalReading",5),n("professional.matchSelectivity",2)],secondaryEffects:[n("professional.statusInertia",-1)],primarySeedTransitions:seed("SEED_72H_LIMIT","D"),secondarySeedTransitions:seed("SEED_72H_LIMIT","D")}
]});

const captain=ambiguousEvent({...common([9,10,11]),id:"EVT_33_CAP_001",family:"captaincy",title:"Entregar el brazalete",body:"El club propone anunciar que otro compañero será capitán principal la próxima temporada, aunque tú sigas. Te ofrecen un papel de capitán institucional y mentor.",visible:["Conoces el plan de transición y el compañero candidato."],uncertain:["No sabes si el nuevo rol tendrá poder real o será ceremonial."],gates:[{path:"facts.playerClubLeadership.currentRole",op:"eq",value:"captain"}],seedsRead:["SEED_CAPTAIN_HANDOVER"],seedsWrite:["SEED_VETERAN_LEADERSHIP_FINAL"],choices:[
 {id:"A",label:"Apoyar transición pública",intentTags:["captaincy_handover","public_support"],immediateEffects:[flag("AGE33_CAPTAIN_PUBLIC_HANDOVER",true)],primaryMessage:"Conviertes la sucesión en una decisión visible que no necesita un conflicto para existir.",secondaryMessage:"Una transición limpia puede aumentar legado mientras reduce tu voz diaria más rápido de lo esperado.",primaryEffects:[n("professional.legacyCapital",7),n("professional.successionPressure",-5)],secondaryEffects:[n("professional.lockerPower",-2)],primarySeedTransitions:seed("SEED_VETERAN_LEADERSHIP_FINAL","A"),secondarySeedTransitions:seed("SEED_VETERAN_LEADERSHIP_FINAL","A")},
 {id:"B",label:"Pedir compartir capitanía",intentTags:["shared_captaincy","transition"],immediateEffects:[flag("AGE33_SHARED_CAPTAINCY",true)],primaryMessage:"Intentas que la transición sea gradual y que el candidato gane autoridad sin borrar la tuya de golpe.",secondaryMessage:"Compartir puede enseñar sucesión o prolongar una ambigüedad de poder dentro del vestuario.",primaryEffects:[n("professional.lockerPower",4),n("professional.legacyCapital",3)],secondaryEffects:[n("professional.successionPressure",2)],primarySeedTransitions:seed("SEED_VETERAN_LEADERSHIP_FINAL","B"),secondarySeedTransitions:seed("SEED_VETERAN_LEADERSHIP_FINAL","B")},
 {id:"C",label:"Rechazar cargo ceremonial y ser uno más",intentTags:["no_ceremonial_role","team"],immediateEffects:[flag("AGE33_NO_CEREMONIAL_CAPTAIN",true)],primaryMessage:"Aceptas perder el título antes que conservar una autoridad que no sea real.",secondaryMessage:"La decisión puede liberar al vestuario y hacerte perder canales informales que todavía importaban.",primaryEffects:[n("professional.careerControl",4),n("professional.institutionalTrust",3)],secondaryEffects:[n("professional.lockerPower",-4)],primarySeedTransitions:seed("SEED_VETERAN_LEADERSHIP_FINAL","C"),secondarySeedTransitions:seed("SEED_VETERAN_LEADERSHIP_FINAL","C")},
 {id:"D",label:"Posponer anuncio hasta saber si renuevas",intentTags:["delay_handover","contract"],immediateEffects:[flag("AGE33_CAPTAIN_WAIT_RENEWAL",true)],primaryMessage:"Evitas anunciar una jerarquía para una temporada en la que quizá ni siquiera estés.",secondaryMessage:"La lógica contractual es clara y puede parecer resistencia a una sucesión que el club quería cerrar ya.",primaryEffects:[n("professional.careerControl",3),n("professional.contractPower",2)],secondaryEffects:[n("professional.successionPressure",3)],primarySeedTransitions:seed("SEED_VETERAN_LEADERSHIP_FINAL","D"),secondarySeedTransitions:seed("SEED_VETERAN_LEADERSHIP_FINAL","D")}
]});

const market=ambiguousEvent({...common([7,8,1],true),id:"EVT_33_MKT_001",family:"market",title:"Cuatro futuros",body:"Llegan cuatro tipos de propuesta: seguir en tu club con salario reducido; un candidato a títulos como especialista; una liga rica; o UDV con liderazgo total.",visible:["Conoces paquetes económicos, duración y roles comunicados de cada ruta."],uncertain:["No sabes cuál será realmente tu último contrato ni si tu cuerpo permitirá completarlo."],gates:[{path:"reputation.marketHeat",op:"gte",value:30}],seedsWrite:["SEED_FINAL_FOUR_WAYS","SEED_AGE34_PRIORITY"],choices:[
 {id:"A",label:"Continuidad",intentTags:["continuity","stability"],immediateEffects:[flag("AGE33_FUTURE_CONTINUITY",true)],primaryMessage:"Aceptas menos salario a cambio de entorno conocido y una negociación mínima de adaptación.",secondaryMessage:"La continuidad reduce ruido y puede convertirte lentamente en una pieza secundaria sin un momento claro de ruptura.",primaryEffects:[n("professional.environmentStability",6),n("professional.institutionalTrust",3)],secondaryEffects:[n("professional.veteranLeverage",-2)],primarySeedTransitions:seedMany(["SEED_FINAL_FOUR_WAYS","SEED_AGE34_PRIORITY"],"A"),secondarySeedTransitions:seedMany(["SEED_FINAL_FOUR_WAYS","SEED_AGE34_PRIORITY"],"A")},
 {id:"B",label:"Última carrera por títulos",intentTags:["trophies","specialist"],immediateEffects:[flag("SPECIALIST_ROLE",true),flag("AGE33_FUTURE_TITLES",true)],primaryMessage:"Cambias centralidad por una última exposición a partidos y trofeos de máximo nivel.",secondaryMessage:"Puedes vivir noches decisivas o pasar la temporada esperando una oportunidad que nunca llega.",primaryEffects:[n("professional.statusInertia",4),n("professional.roleAdaptability",4)],secondaryEffects:[n("sport.roleScore",-5)],primarySeedTransitions:seedMany(["SEED_FINAL_FOUR_WAYS","SEED_AGE34_PRIORITY"],"B"),secondarySeedTransitions:seedMany(["SEED_FINAL_FOUR_WAYS","SEED_AGE34_PRIORITY"],"B")},
 {id:"C",label:"Maximizar seguridad económica",intentTags:["money","security"],immediateEffects:[flag("RICH_LEAGUE_ROUTE",true),flag("AGE33_FUTURE_MONEY",true)],primaryMessage:"Aceptas que ambición también puede significar asegurar económicamente la vida posterior al fútbol.",secondaryMessage:"El contrato compra seguridad y puede reducir exposición competitiva, selección y narrativa deportiva final.",primaryEffects:[n("professional.moneyComfort",10),n("professional.careerControl",3)],secondaryEffects:[n("professional.statusInertia",-3)],primarySeedTransitions:seedMany(["SEED_FINAL_FOUR_WAYS","SEED_AGE34_PRIORITY"],"C"),secondarySeedTransitions:seedMany(["SEED_FINAL_FOUR_WAYS","SEED_AGE34_PRIORITY"],"C")},
 {id:"D",label:"Volver a Valdoria",intentTags:["home_return","legacy"],immediateEffects:[flag("HOME_RETURN_30",true),flag("AGE33_FUTURE_HOME",true)],primaryMessage:"Eliges que el último tramo competitivo tenga un vínculo directo con el lugar que representa tu origen.",secondaryMessage:"La historia es potente y puede multiplicar la presión de que cada resultado parezca una evaluación de tu legado.",primaryEffects:[n("professional.homePull",14),n("professional.legacyCapital",6)],secondaryEffects:[n("professional.environmentStability",2)],primarySeedTransitions:seedMany(["SEED_FINAL_FOUR_WAYS","SEED_AGE34_PRIORITY"],"D"),secondarySeedTransitions:seedMany(["SEED_FINAL_FOUR_WAYS","SEED_AGE34_PRIORITY"],"D")},
 {id:"E",label:"Esperar y considerar incluso parar",intentTags:["wait","retirement_option"],immediateEffects:[flag("AGE33_FUTURE_WAIT",true)],primaryMessage:"No firmas por miedo a perder opciones y aceptas que parar también pueda entrar en la decisión.",secondaryMessage:"Esperar conserva libertad y añade una posibilidad real: que el mercado se reduzca antes de que decidas.",primaryEffects:[n("professional.careerControl",5),n("professional.retirementDistance",3)],secondaryEffects:[n("professional.veteranLeverage",-5)],primarySeedTransitions:seedMany(["SEED_FINAL_FOUR_WAYS","SEED_AGE34_PRIORITY"],"E"),secondarySeedTransitions:seedMany(["SEED_FINAL_FOUR_WAYS","SEED_AGE34_PRIORITY"],"E")}
]});

const press=ambiguousEvent({...common([9,10,11,12]),id:"EVT_33_PRS_001",family:"press",title:"¿Estás pensando en retirarte?",body:"En una entrevista aparentemente rutinaria te preguntan directamente por retirada. No has tomado decisión. Cualquier respuesta será titular.",visible:["Conoces la pregunta, el medio y el contexto de la entrevista."],uncertain:["No sabes si reconocer dudas bajará mercado o liberará presión; negar puede perseguirte si cambias de idea pronto."],gates:[{path:"reputation.mediaHeat",op:"gte",value:25}],seedsWrite:["SEED_RETIREMENT_PUBLIC_TONE","SEED_HOME_PULL_PUBLIC"],choices:[
 {id:"A",label:"«No pienso en ello»",intentTags:["retirement_tone","deny"],immediateEffects:[flag("AGE33_PRESS_NO_RETIREMENT_THOUGHT",true)],primaryMessage:"Cierras la pregunta sin convertir una duda futura en noticia presente.",secondaryMessage:"La frase protege foco y puede convertirse en contradicción si cambias de idea pronto.",primaryEffects:[n("professional.motivationReserve",3),n("professional.veteranLeverage",2)],secondaryEffects:[n("reputation.mediaHeat",2)],primarySeedTransitions:seed("SEED_RETIREMENT_PUBLIC_TONE","A"),secondarySeedTransitions:seed("SEED_RETIREMENT_PUBLIC_TONE","A")},
 {id:"B",label:"«Lo evalúo cada verano»",intentTags:["retirement_tone","open"],immediateEffects:[flag("AGE33_PRESS_ANNUAL_REVIEW",true)],primaryMessage:"Reconoces incertidumbre sin fijar una fecha que todavía no existe.",secondaryMessage:"La sinceridad puede aliviar presión y hacer que cada mercado empiece preguntando si sigues.",primaryEffects:[n("professional.careerControl",4),n("professional.retirementDistance",1)],secondaryEffects:[n("professional.veteranLeverage",-1)],primarySeedTransitions:seed("SEED_RETIREMENT_PUBLIC_TONE","B"),secondarySeedTransitions:seed("SEED_RETIREMENT_PUBLIC_TONE","B")},
 {id:"C",label:"«Quiero terminar en Valdoria»",intentTags:["retirement_tone","home"],immediateEffects:[flag("AGE33_PRESS_HOME_END",true)],primaryMessage:"Conviertes una preferencia emocional en una declaración pública sobre el final de tu carrera.",secondaryMessage:"La frase puede acercar el regreso y convertirse en promesa involuntaria para afición, club y mercado.",primaryEffects:[n("professional.homePull",8),n("professional.legacyCapital",3)],secondaryEffects:[n("professional.careerControl",-2)],primarySeedTransitions:seedMany(["SEED_RETIREMENT_PUBLIC_TONE","SEED_HOME_PULL_PUBLIC"],"C"),secondarySeedTransitions:seedMany(["SEED_RETIREMENT_PUBLIC_TONE","SEED_HOME_PULL_PUBLIC"],"C")},
 {id:"D",label:"Negarte a responder",intentTags:["retirement_tone","no_comment"],immediateEffects:[flag("AGE33_PRESS_NO_COMMENT",true)],primaryMessage:"Rechazas convertir una decisión privada no tomada en material de negociación pública.",secondaryMessage:"No das una promesa y tampoco impides que el silencio se convierta en titular.",primaryEffects:[n("professional.careerControl",3)],secondaryEffects:[n("reputation.mediaHeat",3)],primarySeedTransitions:seed("SEED_RETIREMENT_PUBLIC_TONE","D"),secondarySeedTransitions:seed("SEED_RETIREMENT_PUBLIC_TONE","D")}
]});

export const CANONICAL_REIMPLEMENTATIONS_33A:EventDefinition[]=[body,captain,market,press];
