import type { SeedDefinition } from "../core/types.js";
import { SEED_CATALOG_34_PLUS_BRIDGE_COMPATIBILITY, SEED_CATALOG_34_PLUS_CANONICAL } from "./seed-34plus.js";

export const SEED_CATALOG_18_20: SeedDefinition[] = [
  { id: "SEED_RIVAS_TRUST", originEvents: ["EVT_18_PRE_001", "EVT_18_PRE_002"], npcRefs: ["NPC_ACA_01"], ageWindow: [18, null], description: "Confianza temprana en Rivas como mentor y fuente de contexto." },
  { id: "SEED_MENA_EARLY_READ", originEvents: ["EVT_18_PRE_003", "EVT_18_MATCH_001"], npcRefs: ["NPC_CCH_02"], ageWindow: [18, 30], description: "Primera lectura de Mena sobre la inteligencia táctica y competitiva del protagonista." },
  { id: "SEED_BRUNO_FAVOR", originEvents: ["EVT_18_TEAM_001"], npcRefs: ["NPC_PLR_12"], ageWindow: [18, 32], description: "Favor, negativa o uso oportunista de una noche con ojeadores." },
  { id: "SEED_VELA_STANCE", originEvents: ["EVT_18_CAP_001"], npcRefs: ["NPC_PLR_10"], ageWindow: [18, null], description: "Posición adoptada cuando el capitán choca con la dirección." },
  { id: "SEED_CLARA_CHANNEL", originEvents: ["EVT_18_PRS_001", "EVT_18_PRS_002"], npcRefs: ["NPC_PRS_01"], ageWindow: [18, null], description: "Canal de información mutuo; acceso y riesgo de filtraciones." },
  { id: "SEED_FIRST_AGENT", originEvents: ["EVT_18_AGT_001"], npcRefs: ["NPC_AGT_01", "NPC_AGT_02"], ageWindow: [18, 35], description: "Quién entró primero en la carrera y cómo se negoció." },
  { id: "SEED_FIRST_LEAK", originEvents: ["EVT_18_MKT_001", "EVT_18_JAN_001", "EVT_18_CAP_001"], npcRefs: ["NPC_PRS_01", "NPC_DIR_02"], ageWindow: [18, 30], description: "Primera vez que el jugador usa o tolera una filtración como palanca." },
  { id: "SEED_PHYSIO_CONFIDENCE", originEvents: ["EVT_18_MED_001"], npcRefs: ["NPC_MED_01"], ageWindow: [18, 35], description: "Confidencialidad y sinceridad sobre molestias." },
  { id: "SEED_DANI_NORMALITY", originEvents: ["EVT_18_SOC_001", "EVT_19_SUM_001"], npcRefs: ["NPC_SOC_01"], ageWindow: [18, 30], description: "Cómo cambia la amistad cuando aparecen fama y disciplina profesional." },
  { id: "SEED_COACH_PUBLIC", originEvents: ["EVT_18_END_001", "EVT_18_END_002"], npcRefs: ["NPC_CCH_01"], ageWindow: [18, 32], description: "Apoyo, distancia o silencio cuando el técnico está cuestionado." },
  { id: "SEED_EXIT_STYLE_UDV", originEvents: ["CEVT_18_PLAYOFF_01", "EVT_18_SUM_001", "EVT_19_MKT_001"], npcRefs: ["NPC_DIR_02"], ageWindow: [18, null], description: "No importa solo irse o quedarse, sino cómo se negoció y comunicó; incluye la postura retención-vs-mercado nacida en un playoff real." },
  { id: "SEED_ADRIAN_MIRROR", originEvents: ["EVT_19_RIV_001", "EVT_19_MEDIA_001"], npcRefs: ["NPC_PLR_15"], ageWindow: [19, 31], description: "Competencia, alianza o humillación mutua entre dos canteranos." },
  { id: "SEED_NANO_SHADOW", originEvents: ["EVT_18_PRE_001", "EVT_19_TEAM_001"], npcRefs: ["NPC_PLR_14"], ageWindow: [18, 35], description: "El amigo puede sentirse protegido, eclipsado o utilizado." },
  { id: "SEED_AGENT_OMISSION", originEvents: ["EVT_19_AGENT_001"], npcRefs: ["NPC_AGT_01", "NPC_AGT_02"], ageWindow: [19, 35], description: "Respuesta al descubrir que una información no llegó a tiempo." },
  { id: "SEED_BODY_PRECEDENT", originEvents: ["EVT_18_PRE_002", "EVT_18_MED_001", "EVT_19_BODY_001"], npcRefs: ["NPC_MED_01"], ageWindow: [18, 35], description: "Patrón de ocultar, comunicar o sobreproteger molestias; modifica riesgos futuros." },
  { id: "SEED_FIRST_BIG_MONEY", originEvents: ["EVT_20_LIFE_001", "EVT_21_MONEY_001"], npcRefs: ["NPC_FAM_01", "NPC_FAM_02"], ageWindow: [20, null], description: "Primer salto salarial y patrón de gasto, ahorro o apoyo familiar." },
  { id: "SEED_AGENT_POWER", originEvents: ["EVT_20_AGT_001", "EVT_21_AGT_002"], npcRefs: ["NPC_AGT_01", "NPC_AGT_02"], ageWindow: [20, 35], description: "Cuánto control cedió el jugador sobre llamadas, filtraciones y negociación." },
  { id: "SEED_FOREIGN_ADAPT", originEvents: ["EVT_20_ABR_001", "EVT_21_ABR_001"], npcRefs: [], ageWindow: [20, 32], description: "Idioma, red social, adaptación y forma de pedir ayuda fuera." },
  { id: "SEED_MEDICAL_DISCLOSURE", originEvents: ["EVT_20_MED_001", "EVT_22_MED_001"], npcRefs: ["NPC_MED_01"], ageWindow: [20, 35], description: "Patrón de transparencia médica en fichajes y disponibilidad." },
  { id: "SEED_TEAMMATE_COVER", originEvents: ["EVT_20_LOCK_002"], npcRefs: [], ageWindow: [20, 34], description: "Mentir, callar o desmarcarse para proteger a un compañero." },
  { id: "SEED_FIRST_CAPTAIN_ROOM", originEvents: ["EVT_21_CAP_001"], npcRefs: ["NPC_PLR_11"], ageWindow: [21, 36], description: "Primera entrada real en una decisión de jerarquía adulta." },
  { id: "SEED_PUBLIC_CONTRACT", originEvents: ["EVT_21_PRS_001"], npcRefs: ["NPC_PRS_01"], ageWindow: [21, 32], description: "Uso público o negación de cifras y condiciones contractuales." },
  { id: "SEED_FAMILY_MONEY", originEvents: ["EVT_21_MONEY_001"], npcRefs: ["NPC_FAM_01", "NPC_FAM_02"], ageWindow: [21, null], description: "Dinero y dependencia económica cambian el equilibrio familiar." },
  { id: "SEED_SELECTION_SNUB", originEvents: ["EVT_21_NAT_001"], npcRefs: [], ageWindow: [21, 30], description: "Reacción a una convocatoria o ausencia importante." },
  { id: "SEED_SPONSOR_IMAGE", originEvents: ["EVT_21_IMG_001"], npcRefs: [], ageWindow: [21, 35], description: "Primera cesión consciente de imagen y contradicciones futuras." },
  { id: "SEED_TACTICAL_SACRIFICE", originEvents: ["EVT_21_CCH_002", "EVT_22_TACT_001"], npcRefs: ["NPC_CCH_02"], ageWindow: [21, 34], description: "Aceptar un rol útil que reduce números o rechazarlo para proteger perfil." },
  { id: "SEED_DEADLINE_DAY", originEvents: ["EVT_22_DDL_001"], npcRefs: ["NPC_AGT_01", "NPC_AGT_02"], ageWindow: [22, 35], description: "Conducta del jugador cuando solo quedan horas de mercado." },
  { id: "SEED_LOCKER_VOTE", originEvents: ["EVT_22_LOCK_001"], npcRefs: ["NPC_PLR_11"], ageWindow: [22, 36], description: "Posición en una disputa interna sobre primas, disciplina o capitanía." },
  { id: "SEED_HOME_DISTANCE", originEvents: ["EVT_21_IMG_001", "EVT_22_HOME_001"], npcRefs: ["NPC_SOC_01"], ageWindow: [21, null], description: "Grado de vínculo real con el lugar de origen tras años fuera." },
  { id: "SEED_FIRST_FREE_AGENCY", originEvents: ["EVT_22_CON_001", "EVT_22_CON_002"], npcRefs: ["NPC_AGT_01", "NPC_AGT_02"], ageWindow: [22, 35], description: "Precedente de agotar contrato, renovar tarde o aceptar venta controlada." },
  { id: "SEED_CONTRACT_HARDLINE", originEvents: ["EVT_18_SUM_001", "EVT_19_MKT_001"], npcRefs: ["NPC_DIR_02"], ageWindow: [18, 30], description: "Precedente de negociación dura sobre duración, cláusula y control contractual." }
];

export const SEED_CATALOG_23_26: SeedDefinition[] = [
  { id:"SEED_ELITE_ROLE_BARGAIN", originEvents:["EVT_23_BRIDGE_001","EVT_23_MKT_001"], npcRefs:[], ageWindow:[23,30], description:"Techo deportivo frente a rol real en operaciones de alto nivel." },
  { id:"SEED_CONTRACT_CEILING", originEvents:["EVT_23_CON_001","EVT_25_CON_001"], npcRefs:["NPC_AGT_01","NPC_AGT_02"], ageWindow:[23,32], description:"Cuánto techo salarial y libertad se sacrifica por seguridad contractual." },
  { id:"SEED_DIRECT_RECRUIT", originEvents:["EVT_23_AGT_001","EVT_25_MKT_001"], npcRefs:["NPC_AGT_01","NPC_AGT_02"], ageWindow:[23,32], description:"Interés directo de estructuras deportivas y agencias de mayor alcance." },
  { id:"SEED_LOAD_MANAGEMENT", originEvents:["EVT_23_BODY_001"], npcRefs:["NPC_MED_01"], ageWindow:[23,null], description:"Patrón adulto de gestión de carga y disponibilidad." },
  { id:"SEED_FAMILY_BUSINESS", originEvents:["EVT_23_MONEY_001","EVT_25_FAM_001"], npcRefs:["NPC_FAM_01","NPC_FAM_02"], ageWindow:[23,null], description:"Capital, límites y responsabilidades dentro de un proyecto familiar." },
  { id:"SEED_HOME_SYMBOL", originEvents:["EVT_23_HOME_001"], npcRefs:[], ageWindow:[23,null], description:"El jugador se convierte, o evita convertirse, en símbolo de su club/origen." },
  { id:"SEED_EURO_REGISTRATION", originEvents:["EVT_23_EUR_001"], npcRefs:[], ageWindow:[23,32], description:"Registro, rol y credibilidad acumulada en competición continental." },
  { id:"SEED_FIRST_ABSOLUTE_CALL", originEvents:["EVT_23_NAT_001"], npcRefs:[], ageWindow:[23,null], description:"Primera llamada de la selección absoluta sin presuponer minutos ni continuidad." },
  { id:"SEED_CLUB_NATIONAL_CONFLICT", originEvents:["EVT_23_MED_001"], npcRefs:["NPC_MED_01"], ageWindow:[23,32], description:"Conflicto de incentivos entre disponibilidad para club y selección." },
  { id:"SEED_IMAGE_RIGHTS", originEvents:["EVT_24_CON_001"], npcRefs:[], ageWindow:[24,null], description:"Control y cesión de derechos de imagen en contratos de alto valor." },
  { id:"SEED_PERSONAL_STAFF", originEvents:["EVT_24_LIFE_001"], npcRefs:["NPC_SOC_01"], ageWindow:[24,null], description:"Quién gestiona agenda, logística y vida profesional del jugador." },
  { id:"SEED_STAR_COMPETITION", originEvents:["EVT_24_CCH_001"], npcRefs:[], ageWindow:[24,32], description:"Competencia directa con una inversión estrella en la misma zona." },
  { id:"SEED_PENALTY_HIERARCHY", originEvents:["EVT_24_MATCH_001"], npcRefs:[], ageWindow:[24,34], description:"Jerarquía de penaltis y conducta bajo conflicto competitivo." },
  { id:"SEED_PRIVATE_CHAT", originEvents:["EVT_24_LOCK_001"], npcRefs:[], ageWindow:[24,34], description:"Participación, silencio o salida de un chat privado susceptible de filtración." },
  { id:"SEED_MAJOR_TOURNAMENT", originEvents:["EVT_24_NAT_001"], npcRefs:[], ageWindow:[24,null], description:"Preparación y posición respecto a un gran torneo de selección." },
  { id:"SEED_BIG_MATCH_BODY", originEvents:["EVT_24_MED_001"], npcRefs:["NPC_MED_01"], ageWindow:[24,null], description:"Precedente físico antes de una final o partido de máximo valor." },
  { id:"SEED_WEALTHY_EXIT", originEvents:["EVT_24_JAN_001"], npcRefs:["NPC_AGT_01","NPC_AGT_02"], ageWindow:[24,null], description:"Oferta de riqueza extraordinaria a cambio de exposición competitiva." },
  { id:"SEED_YOUNG_MENTOR", originEvents:["EVT_25_TEAM_001"], npcRefs:[], ageWindow:[25,null], description:"Relación con un joven que también puede convertirse en competidor real." },
  { id:"SEED_CAPTAINCY_STYLE", originEvents:["EVT_25_CAP_001"], npcRefs:[], ageWindow:[25,null], description:"Forma de ejercer, compartir o rechazar liderazgo formal." },
  { id:"SEED_CHRONIC_BODY", originEvents:["EVT_25_MED_001"], npcRefs:["NPC_MED_01"], ageWindow:[25,null], description:"Patrón físico recurrente que exige gestión sin implicar declive automático." },
  { id:"SEED_AGENT_PROOF", originEvents:["EVT_25_AGT_001"], npcRefs:["NPC_AGT_01","NPC_AGT_02"], ageWindow:[25,34], description:"Evidencia real sobre promesas, omisiones o capacidad de representación." },
  { id:"SEED_AGE26_PRIORITY", originEvents:["EVT_25_END_001"], npcRefs:[], ageWindow:[25,null], description:"Prioridad declarada al cerrar los 26: techo, rol, cuerpo/estabilidad o libertad." }
];


export const SEED_CATALOG_26_30: SeedDefinition[] = [
  { id:"SEED_PEAK_IDENTITY", originEvents:["EVT_26_IDN_001"], npcRefs:[], ageWindow:[26,34], description:"Cómo reacciona a ser tratado como activo maduro y reemplazable." },
  { id:"SEED_SHADOW_ESCAPE", originEvents:["EVT_26_MKT_001"], npcRefs:[], ageWindow:[26,34], description:"Si prefiere protagonismo a permanecer en una máquina ganadora." },
  { id:"SEED_PROJECT_FACE", originEvents:["EVT_26_CLB_001"], npcRefs:[], ageWindow:[26,36], description:"Aceptación de ser centro deportivo y comercial de un proyecto." },
  { id:"SEED_PEAK_CONTRACT", originEvents:["EVT_26_CON_001"], npcRefs:["NPC_AGT_01","NPC_AGT_02"], ageWindow:[26,36], description:"Contrato estructural firmado en el pico." },
  { id:"SEED_GLOBAL_IMAGE", originEvents:["EVT_26_IMG_001"], npcRefs:["NPC_PRS_01"], ageWindow:[26,null], description:"Expansión de imagen a escala máxima." },
  { id:"SEED_SELF_OPTIMIZATION", originEvents:["EVT_26_BODY_001"], npcRefs:["NPC_MED_01"], ageWindow:[26,null], description:"Profesionalización y control del rendimiento." },
  { id:"SEED_YOUNG_SUCCESSOR", originEvents:["EVT_26_TEAM_001"], npcRefs:[], ageWindow:[26,null], description:"Primera convivencia con un sucesor real." },
  { id:"SEED_INTERNATIONAL_LOAD", originEvents:["EVT_26_NAT_001"], npcRefs:[], ageWindow:[26,36], description:"Cómo reparte disponibilidad entre club, selección y descanso." },
  { id:"SEED_HOME_INSTITUTION", originEvents:["EVT_26_HOME_001"], npcRefs:["NPC_DIR_02"], ageWindow:[26,null], description:"Vínculo institucional con UDV y Valdoria." },
  { id:"SEED_BIG_GAME_BENCH", originEvents:["EVT_27_FINAL_001"], npcRefs:[], ageWindow:[27,36], description:"Reacción a suplencia en cita máxima." },
  { id:"SEED_RECORD_CHASE", originEvents:["EVT_27_REC_001"], npcRefs:[], ageWindow:[27,null], description:"Peso dado a récords y su persecución." },
  { id:"SEED_LOCKER_ENDORSEMENT", originEvents:["EVT_27_LOCK_001"], npcRefs:[], ageWindow:[27,36], description:"Uso del poder en conflictos colectivos." },
  { id:"SEED_PEAK_LOAD", originEvents:["EVT_27_BODY_001"], npcRefs:["NPC_MED_01"], ageWindow:[27,null], description:"Patrón de descanso en máxima densidad." },
  { id:"SEED_DOCUMENTARY_ACCESS", originEvents:["EVT_27_PRS_001"], npcRefs:["NPC_PRS_01"], ageWindow:[27,null], description:"Acceso concedido a vida y vestuario." },
  { id:"SEED_AGENT_CONFLICT_PEAK", originEvents:["EVT_27_AGT_001"], npcRefs:["NPC_AGT_01","NPC_AGT_02"], ageWindow:[27,36], description:"Conflictos de incentivo con la agencia en máximo mercado." },
  { id:"SEED_PUBLIC_RIVALRY", originEvents:["EVT_27_RIV_001"], npcRefs:["NPC_PLR_15"], ageWindow:[27,null], description:"Grado de rivalidad pública con el espejo generacional." },
  { id:"SEED_MENTOR_ADVICE", originEvents:["EVT_27_MENT_001"], npcRefs:[], ageWindow:[27,null], description:"Consejo dado a un joven sobre su carrera." },
  { id:"SEED_NATIONAL_ROLE", originEvents:["EVT_27_NAT_001"], npcRefs:[], ageWindow:[27,36], description:"Cómo acepta o disputa jerarquía internacional madura." },
  { id:"SEED_FINAL_BENCH", originEvents:["EVT_28_FINAL_001"], npcRefs:[], ageWindow:[28,36], description:"Ganar o perder una final sin controlar el rol." },
  { id:"SEED_MEGA_TRANSFER", originEvents:["EVT_28_MKT_001"], npcRefs:[], ageWindow:[28,36], description:"Primer movimiento o propuesta transformadora." },
  { id:"SEED_PUBLIC_EXIT_PRESSURE", originEvents:["EVT_28_PRS_001"], npcRefs:["NPC_PRS_01"], ageWindow:[28,36], description:"Uso público de presión para salir." },
  { id:"SEED_WEALTH_STRUCTURE", originEvents:["EVT_28_MONEY_001"], npcRefs:["NPC_FAM_01","NPC_FAM_02"], ageWindow:[28,null], description:"Profesionalización del patrimonio." },
  { id:"SEED_HOME_OWNERSHIP", originEvents:["EVT_28_HOME_001"], npcRefs:["NPC_DIR_02"], ageWindow:[28,null], description:"Entrada económica o institucional en el origen." },
  { id:"SEED_PERSONAL_BRAND_INDEPENDENCE", originEvents:["EVT_28_IMG_001"], npcRefs:[], ageWindow:[28,null], description:"Separación de marca personal y club." },
  { id:"SEED_SECOND_STAR", originEvents:["EVT_28_TEAM_001"], npcRefs:[], ageWindow:[28,36], description:"Convivencia con otra superestrella equivalente." },
  { id:"SEED_POSITIONAL_REINVENTION", originEvents:["EVT_28_TACT_001"], npcRefs:[], ageWindow:[28,null], description:"Aceptación inicial de adaptación táctica del pico." },
  { id:"SEED_GLOBAL_AWARD_BEHAVIOR", originEvents:["EVT_28_GALA_001"], npcRefs:["NPC_PRS_01"], ageWindow:[28,null], description:"Cómo gestiona candidatura, derrota o victoria pública." },
  { id:"SEED_MANAGER_POWER", originEvents:["EVT_29_CCH_001"], npcRefs:[], ageWindow:[29,36], description:"Uso de influencia sobre el futuro del entrenador." },
  { id:"SEED_FAN_FRACTURE", originEvents:["EVT_29_FAN_001"], npcRefs:[], ageWindow:[29,null], description:"Primera fractura seria con la afición propia." },
  { id:"SEED_SURGERY_TIMING", originEvents:["EVT_29_MED_001"], npcRefs:["NPC_MED_01"], ageWindow:[29,null], description:"Elección de calendario ante dolencia persistente." },
  { id:"SEED_NATIONAL_CAPTAINCY", originEvents:["EVT_29_NAT_001"], npcRefs:[], ageWindow:[29,null], description:"Aceptación y estilo de capitanía internacional." },
  { id:"SEED_ELITE_SACRIFICE", originEvents:["EVT_29_EUR_001"], npcRefs:[], ageWindow:[29,36], description:"Sacrificio estadístico en cita de máximo nivel." },
  { id:"SEED_RECORD_PUBLIC_TONE", originEvents:["EVT_29_REC_001"], npcRefs:["NPC_PRS_01"], ageWindow:[29,null], description:"Cómo comunica un récord en contexto colectivo." },
  { id:"SEED_WEALTHY_PEAK_EXIT", originEvents:["EVT_29_MKT_001"], npcRefs:["NPC_AGT_01","NPC_AGT_02"], ageWindow:[29,null], description:"Salida de la máxima exposición a cambio de riqueza y control." },
  { id:"SEED_EARLY_HOME_RETURN", originEvents:["EVT_29_HOME_001"], npcRefs:["NPC_DIR_02"], ageWindow:[29,null], description:"Regreso competitivo al origen antes del declive." },
  { id:"SEED_FIRST_PEAK_DIP", originEvents:["EVT_29_FORM_001"], npcRefs:[], ageWindow:[29,null], description:"Primer descenso relevante de forma o rol durante el pico." },
  { id:"SEED_AGE30_PRIORITY", originEvents:["EVT_29_FIN_001"], npcRefs:[], ageWindow:[29,null], description:"Prioridad declarada al entrar en la etapa 30-34." }
];

export const SEED_CATALOG_30_34: SeedDefinition[] = [
  { id:"SEED_VETERAN_LABEL", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[30,null], description:"Memoria canónica de madurez 30-34: veteran label." },
  { id:"SEED_AGE30_CONTRACT", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[30,null], description:"Memoria canónica de madurez 30-34: age30 contract." },
  { id:"SEED_MATCH_SELECTIVITY", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[30,null], description:"Memoria canónica de madurez 30-34: match selectivity." },
  { id:"SEED_LAST_BIG_MOVE_WINDOW", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[30,null], description:"Memoria canónica de madurez 30-34: last big move window." },
  { id:"SEED_AGENT_LAST_CONTRACT", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[30,null], description:"Memoria canónica de madurez 30-34: agent last contract." },
  { id:"SEED_NATIONAL_PHASEDOWN", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[30,null], description:"Memoria canónica de madurez 30-34: national phasedown." },
  { id:"SEED_DORSAL_SUCCESSION", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[30,null], description:"Memoria canónica de madurez 30-34: dorsal succession." },
  { id:"SEED_FAMILY_ANCHOR", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[30,null], description:"Memoria canónica de madurez 30-34: family anchor." },
  { id:"SEED_RELOCATION_LIMIT", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[30,null], description:"Memoria canónica de madurez 30-34: relocation limit." },
  { id:"SEED_MEDICAL_AUTHORITY", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[30,null], description:"Memoria canónica de madurez 30-34: medical authority." },
  { id:"SEED_BIG_GAME_ROTATION_30", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[30,null], description:"Memoria canónica de madurez 30-34: big game rotation 30." },
  { id:"SEED_FALSE_RESURGENCE", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[30,null], description:"Memoria canónica de madurez 30-34: false resurgence." },
  { id:"SEED_ROLE_COMMUNICATION", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[30,null], description:"Memoria canónica de madurez 30-34: role communication." },
  { id:"SEED_CAPTAIN_HANDOVER", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[30,null], description:"Memoria canónica de madurez 30-34: captain handover." },
  { id:"SEED_MILESTONE_CHASE_500", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[30,null], description:"Memoria canónica de madurez 30-34: milestone chase 500." },
  { id:"SEED_PAIN_WITHOUT_SCAN", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[30,null], description:"Memoria canónica de madurez 30-34: pain without scan." },
  { id:"SEED_OLD_NETWORK_FAVOR", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[30,null], description:"Memoria canónica de madurez 30-34: old network favor." },
  { id:"SEED_FALSE_ULTIMATUM", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[30,null], description:"Memoria canónica de madurez 30-34: false ultimatum." },
  { id:"SEED_NATIONAL_ABSENCE", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[30,null], description:"Memoria canónica de madurez 30-34: national absence." },
  { id:"SEED_SPECIALIST_BIGCLUB", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[30,null], description:"Memoria canónica de madurez 30-34: specialist bigclub." },
  { id:"SEED_SURGERY_31", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[31,null], description:"Memoria canónica de madurez 30-34: surgery 31." },
  { id:"SEED_LAST_BIG_MOVE_31", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[31,null], description:"Memoria canónica de madurez 30-34: last big move 31." },
  { id:"SEED_HOME_RETURN_31", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[31,null], description:"Memoria canónica de madurez 30-34: home return 31." },
  { id:"SEED_SELF_REPRESENTATION_PREP", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[31,null], description:"Memoria canónica de madurez 30-34: self representation prep." },
  { id:"SEED_FORMAL_MENTOR", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[31,null], description:"Memoria canónica de madurez 30-34: formal mentor." },
  { id:"SEED_LEGACY_ACADEMY", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[31,null], description:"Memoria canónica de madurez 30-34: legacy academy." },
  { id:"SEED_COMEBACK_PACING", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[31,null], description:"Memoria canónica de madurez 30-34: comeback pacing." },
  { id:"SEED_ROLE_REINVENTION_32", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[31,null], description:"Memoria canónica de madurez 30-34: role reinvention 32." },
  { id:"SEED_NEW_COACH_RESET", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[31,null], description:"Memoria canónica de madurez 30-34: new coach reset." },
  { id:"SEED_SQUAD_YOUTH_WAVE", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[31,null], description:"Memoria canónica de madurez 30-34: squad youth wave." },
  { id:"SEED_CLUB_NT_LOAD_TENSION", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[31,null], description:"Memoria canónica de madurez 30-34: club nt load tension." },
  { id:"SEED_MANAGED_FINAL_ROLE", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[31,null], description:"Memoria canónica de madurez 30-34: managed final role." },
  { id:"SEED_BUSINESS_REPUTATION_SHOCK", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[31,null], description:"Memoria canónica de madurez 30-34: business reputation shock." },
  { id:"SEED_ROLLING_CONTRACT", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[32,null], description:"Memoria canónica de madurez 30-34: rolling contract." },
  { id:"SEED_LATE_RICH_OFFER", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[32,null], description:"Memoria canónica de madurez 30-34: late rich offer." },
  { id:"SEED_LATE_CONTENDER_BENCH", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[32,null], description:"Memoria canónica de madurez 30-34: late contender bench." },
  { id:"SEED_HOME_CAPTAIN_OFFER", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[32,null], description:"Memoria canónica de madurez 30-34: home captain offer." },
  { id:"SEED_SELF_REPRESENTATION", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[32,null], description:"Memoria canónica de madurez 30-34: self representation." },
  { id:"SEED_LOW_STATS_HIGH_IMPACT", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[32,null], description:"Memoria canónica de madurez 30-34: low stats high impact." },
  { id:"SEED_REPLACEMENT_BREAKOUT", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[32,null], description:"Memoria canónica de madurez 30-34: replacement breakout." },
  { id:"SEED_FAN_LEGACY_BUFFER", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[32,null], description:"Memoria canónica de madurez 30-34: fan legacy buffer." },
  { id:"SEED_TRAVEL_LOAD", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[32,null], description:"Memoria canónica de madurez 30-34: travel load." },
  { id:"SEED_FINAL_NT_SQUAD", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[32,null], description:"Memoria canónica de madurez 30-34: final nt squad." },
  { id:"SEED_BOSMAN_33", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[32,null], description:"Memoria canónica de madurez 30-34: bosman 33." },
  { id:"SEED_72H_LIMIT", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[33,null], description:"Memoria canónica de madurez 30-34: 72h limit." },
  { id:"SEED_RECORD_VS_BODY", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[33,null], description:"Memoria canónica de madurez 30-34: record vs body." },
  { id:"SEED_VETERAN_LEADERSHIP_FINAL", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[33,null], description:"Memoria canónica de madurez 30-34: veteran leadership final." },
  { id:"SEED_FINAL_FOUR_WAYS", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[33,null], description:"Memoria canónica de madurez 30-34: final four ways." },
  { id:"SEED_AGE34_PRIORITY", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[33,null], description:"Memoria canónica de madurez 30-34: age34 priority." },
  { id:"SEED_RETIREMENT_PUBLIC_TONE", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[33,null], description:"Memoria canónica de madurez 30-34: retirement public tone." },
  { id:"SEED_HOME_PULL_PUBLIC", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[33,null], description:"Memoria canónica de madurez 30-34: home pull public." },
  { id:"SEED_RETIREMENT_DISTANCE_PROFILE", originEvents:["PASADA_6_30_34"], npcRefs:[], ageWindow:[33,null], description:"Memoria canónica de madurez 30-34: retirement distance profile." }
];



export const SEED_CATALOG_34_PLUS: SeedDefinition[] = [
  ...SEED_CATALOG_34_PLUS_BRIDGE_COMPATIBILITY,
  ...SEED_CATALOG_34_PLUS_CANONICAL
];

export const SEED_CATALOG: SeedDefinition[] = [...SEED_CATALOG_18_20, ...SEED_CATALOG_23_26, ...SEED_CATALOG_26_30, ...SEED_CATALOG_30_34, ...SEED_CATALOG_34_PLUS];

export const SEED_IDS = new Set(SEED_CATALOG.map(s => s.id));
