import type { EventDefinition, GameState } from "../../../core/types.js";
import { ambiguousEvent, n, seedCreate } from "../18_20/helpers.js";

export type StagedMarketBatch1Id =
 | "EVT_34_BRIDGE_001" | "EVT_34_PAY_001" | "EVT_34_HOME_001" | "EVT_34_AGT_001"
 | "EVT_34_CON_001" | "EVT_34_MAR_001" | "EVT_35_MKT_001" | "EVT_35_CON_001";

export function isStagedMarketBatch1Eligible(state:GameState,id:StagedMarketBatch1Id,authoritativeFactsSatisfied:boolean):boolean{
 if(!authoritativeFactsSatisfied || state.retirement.status!=="playing") return false;
 return state.age>=Number(id.split("_")[1]);
}

const E:EventDefinition[]=[
 ambiguousEvent({
  id:"EVT_34_BRIDGE_001",ageWindow:[34,null],phase:"34_plus",family:"contract",title:"La reunión sin horizonte",
  body:"Tu club propone un año y revisar en marzo. La conversación solo existe cuando una negociación o renovación real está acreditada; la escena no inventa la oferta.",
  visible:["Rol previsto","salario","calendario de conversaciones"],uncertain:["El club puede estar siendo prudente","puede estar preparando sucesión o esperando ver tu cuerpo"],
  gates:[{path:"retirement.status",op:"eq",value:"playing"}],weight:12,
  choices:[
   {id:"A",label:"Firmar un año sin más",intentTags:["contract","stability"],primaryMessage:"Aceptas que la última etapa se negocie año a año.",secondaryMessage:"Ganas continuidad, pero cedes parte del control sobre el siguiente marzo.",primaryEffects:[n("professional.environmentStability",4),n("professional.contractPower",-2)],secondaryEffects:[n("professional.environmentStability",2),n("professional.careerControl",-2)],primarySeedTransitions:[seedCreate("SEED_AGE34_REALITY",64,{stance:"one_year"})],secondarySeedTransitions:[seedCreate("SEED_AGE34_REALITY",69,{stance:"one_year",review_risk:true})]},
   {id:"B",label:"Exigir definición de rol",intentTags:["contract","role"],primaryMessage:"No cambias el contrato por tu cuenta; pides que la negociación incluya una expectativa deportiva verificable.",secondaryMessage:"Ganas claridad, aunque la negociación se vuelve más difícil.",primaryEffects:[n("professional.careerControl",4),n("professional.contractPower",2)],secondaryEffects:[n("professional.environmentStability",-2)],primarySeedTransitions:[seedCreate("SEED_AGE34_REALITY",66,{stance:"role_clarity"})],secondarySeedTransitions:[seedCreate("SEED_AGE34_REALITY",71,{stance:"role_clarity",friction:true})]},
   {id:"C",label:"Esperar hasta agosto",intentTags:["contract","delay"],primaryMessage:"Mantienes abierta la negociación y aceptas el riesgo de perder la oferta actual.",secondaryMessage:"El tiempo puede darte información o dejarte con menos palanca.",primaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",-2)],secondaryEffects:[n("professional.contractPower",-3)],primarySeedTransitions:[seedCreate("SEED_AGE34_REALITY",62,{stance:"wait_august"})],secondarySeedTransitions:[seedCreate("SEED_AGE34_REALITY",68,{stance:"wait_august",leverage_risk:true})]},
   {id:"D",label:"Pedir salida si no hay compromiso",intentTags:["contract","exit_request"],primaryMessage:"Planteas una salida como condición de negociación; la escena no cambia club ni registro.",secondaryMessage:"Recuperas control, pero deterioras el margen institucional.",primaryEffects:[n("professional.careerControl",5),n("professional.institutionalTrust",-3)],secondaryEffects:[n("professional.environmentStability",-4)],primarySeedTransitions:[seedCreate("SEED_AGE34_REALITY",68,{stance:"exit_if_no_commitment"})],secondarySeedTransitions:[seedCreate("SEED_AGE34_REALITY",74,{stance:"exit_if_no_commitment",relationship_cost:true})]}
  ],seedsWrite:["SEED_AGE34_REALITY"],tags:["canonical_34plus","staged_not_registered","awaiting_external_fact","market_authority_consumer"],canonStatus:"verified"
 }),
 ambiguousEvent({
  id:"EVT_34_PAY_001",ageWindow:[34,null],phase:"34_plus",family:"contract",title:"La cifra que ya no te pagan",
  body:"Una renovación real reduce mucho tu salario aunque el club siga considerándote importante. La comparación usa términos históricos reales; no se deduce de marketHeat.",
  visible:["Oferta formal","salario histórico","comparables parciales"],uncertain:["No sabes si otro club pagará más","la rebaja puede ser política interna"],
  gates:[{path:"retirement.status",op:"eq",value:"playing"}],weight:11,
  choices:[
   {id:"A",label:"Aceptar",intentTags:["contract","accept"],primaryMessage:"Aceptas la nueva escala económica sin convertirla en juicio sobre tu rendimiento.",secondaryMessage:"Aseguras continuidad, pero normalizas una pérdida de poder contractual.",primaryEffects:[n("professional.environmentStability",4),n("professional.contractPower",-3)],secondaryEffects:[n("professional.careerControl",-2)],primarySeedTransitions:[seedCreate("SEED_VETERAN_PAYCUT",66,{stance:"accept"})],secondarySeedTransitions:[seedCreate("SEED_VETERAN_PAYCUT",72,{stance:"accept",status_cost:true})]},
   {id:"B",label:"Pedir primas por minutos/títulos",intentTags:["contract","counter"],primaryMessage:"Contrapropones una estructura variable solo si la authority contractual puede representarla.",secondaryMessage:"Defiendes valor deportivo, pero abres otra ronda de negociación.",primaryEffects:[n("professional.contractPower",4),n("professional.careerControl",3)],secondaryEffects:[n("professional.environmentStability",-2)],primarySeedTransitions:[seedCreate("SEED_VETERAN_PAYCUT",65,{stance:"bonus_counter"})],secondarySeedTransitions:[seedCreate("SEED_VETERAN_PAYCUT",70,{stance:"bonus_counter",friction:true})]},
   {id:"C",label:"Rechazar por estatus",intentTags:["contract","reject"],primaryMessage:"Rechazas la oferta formal sin inventar otra alternativa.",secondaryMessage:"Proteges tu valoración, pero puedes quedarte con menos mercado real.",primaryEffects:[n("professional.contractPower",3),n("professional.environmentStability",-3)],secondaryEffects:[n("professional.careerControl",-2)],primarySeedTransitions:[seedCreate("SEED_VETERAN_PAYCUT",68,{stance:"reject_status"})],secondarySeedTransitions:[seedCreate("SEED_VETERAN_PAYCUT",74,{stance:"reject_status",market_risk:true})]},
   {id:"D",label:"Filtrar que escuchas mercado",intentTags:["contract","public"],primaryMessage:"Haces pública tu disponibilidad a escuchar sin crear una oferta que no existe.",secondaryMessage:"La presión aumenta, pero también la lectura de que el vínculo puede terminar.",primaryEffects:[n("reputation.mediaHeat",4),n("professional.careerControl",2)],secondaryEffects:[n("professional.institutionalTrust",-3)],primarySeedTransitions:[seedCreate("SEED_VETERAN_PAYCUT",67,{stance:"signal_market"})],secondarySeedTransitions:[seedCreate("SEED_VETERAN_PAYCUT",72,{stance:"signal_market",public_cost:true})]}
  ],seedsWrite:["SEED_VETERAN_PAYCUT"],tags:["canonical_34plus","staged_not_registered","awaiting_external_fact","market_authority_consumer"],canonStatus:"verified"
 }),
 ambiguousEvent({
  id:"EVT_34_HOME_001",ageWindow:[34,null],phase:"34_plus",family:"market",title:"Valdoria no puede igualarlo",
  body:"UDV tiene una oferta formal real, inferior a propuestas exteriores igualmente reales, a cambio de un proyecto central. Ninguna opción cambia de club sin la authority de mercado.",
  visible:["Salario","duración","propuestas concurrentes","contexto deportivo"],uncertain:["No sabes cuánto pesa volver hasta vivirlo","no sabes si UDV será competitivo"],
  gates:[{path:"retirement.status",op:"eq",value:"playing"}],weight:10,
  choices:[
   {id:"A",label:"Volver",intentTags:["home","market"],primaryMessage:"Eliges la oferta real de regreso si sigue siendo elegible.",secondaryMessage:"El cierre emocional gana peso, pero la diferencia económica sigue existiendo.",primaryEffects:[n("professional.homePull",5),n("professional.environmentStability",4)],secondaryEffects:[n("professional.contractPower",-3)],primarySeedTransitions:[seedCreate("SEED_FINAL_HOME_WINDOW",72,{stance:"return"})],secondarySeedTransitions:[seedCreate("SEED_FINAL_HOME_WINDOW",77,{stance:"return",financial_cost:true})]},
   {id:"B",label:"Usar la oferta para mejorar otras",intentTags:["market","leverage"],primaryMessage:"Usas solo ofertas concurrentes reales como palanca.",secondaryMessage:"Aumentas presión negociadora y arriesgas desgastar la vía de regreso.",primaryEffects:[n("professional.contractPower",5),n("professional.careerControl",3)],secondaryEffects:[n("professional.institutionalTrust",-3)],primarySeedTransitions:[seedCreate("SEED_FINAL_HOME_WINDOW",65,{stance:"leverage"})],secondarySeedTransitions:[seedCreate("SEED_FINAL_HOME_WINDOW",71,{stance:"leverage",home_cost:true})]},
   {id:"C",label:"Pedir a UDV más poder deportivo",intentTags:["home","role"],primaryMessage:"Pides contexto deportivo explícito sin fingir que sea una cláusula contractual existente.",secondaryMessage:"La petición aclara el proyecto, pero puede exceder lo que el club está dispuesto a prometer.",primaryEffects:[n("professional.careerControl",4),n("professional.institutionalPower",3)],secondaryEffects:[n("professional.environmentStability",-2)],primarySeedTransitions:[seedCreate("SEED_FINAL_HOME_WINDOW",67,{stance:"ask_sporting_power"})],secondarySeedTransitions:[seedCreate("SEED_FINAL_HOME_WINDOW",72,{stance:"ask_sporting_power",promise_gap:true})]},
   {id:"D",label:"Posponer un año",intentTags:["home","delay"],primaryMessage:"No cierras la puerta, pero tampoco fabricas una oferta futura.",secondaryMessage:"Conservas nivel actual y aceptas que la ventana emocional puede no repetirse.",primaryEffects:[n("professional.careerControl",3),n("professional.homePull",2)],secondaryEffects:[n("professional.motivationReserve",-2)],primarySeedTransitions:[seedCreate("SEED_FINAL_HOME_WINDOW",63,{stance:"postpone"})],secondarySeedTransitions:[seedCreate("SEED_FINAL_HOME_WINDOW",69,{stance:"postpone",window_risk:true})]}
  ],seedsWrite:["SEED_FINAL_HOME_WINDOW"],tags:["canonical_34plus","staged_not_registered","awaiting_external_fact","market_authority_consumer"],canonStatus:"verified"
 }),
 ambiguousEvent({
  id:"EVT_34_AGT_001",ageWindow:[34,null],phase:"34_plus",family:"agent",title:"El agente dice que esperes",
  body:"Tu agente certificado dice que en dos semanas puede llegar algo mejor. Hoy existe una oferta formal con caducidad; la futura no se considera real hasta que market authority la produzca.",
  visible:["Oferta formal existente","fecha de caducidad","historial real con tu agente"],uncertain:["No sabes si la oferta futura existe","puede ser una apuesta del agente"],
  gates:[{path:"retirement.status",op:"eq",value:"playing"}],weight:10,
  choices:[
   {id:"A",label:"Esperar",intentTags:["agent","delay"],primaryMessage:"Confías en la lectura del agente y dejas correr parte del reloj.",secondaryMessage:"La espera puede mejorar el mercado o hacer caducar la única oferta real.",primaryEffects:[n("professional.careerControl",1),n("professional.environmentStability",-2)],secondaryEffects:[n("professional.contractPower",-3)],primarySeedTransitions:[seedCreate("SEED_LAST_AGENT_GAMBLE",68,{stance:"wait"})],secondarySeedTransitions:[seedCreate("SEED_LAST_AGENT_GAMBLE",75,{stance:"wait",expiry_risk:true})]},
   {id:"B",label:"Firmar la segura",intentTags:["agent","certainty"],primaryMessage:"Aceptas la oferta elegible actual mediante market authority.",secondaryMessage:"Compras certeza y renuncias a comprobar si el agente tenía razón.",primaryEffects:[n("professional.environmentStability",5),n("professional.careerControl",-1)],secondaryEffects:[n("professional.contractPower",-1)],primarySeedTransitions:[seedCreate("SEED_LAST_AGENT_GAMBLE",62,{stance:"take_safe"})],secondarySeedTransitions:[seedCreate("SEED_LAST_AGENT_GAMBLE",66,{stance:"take_safe",missed_upside:true})]},
   {id:"C",label:"Hablar directamente con el club futuro",intentTags:["agent","direct"],primaryMessage:"Buscas información directa; el contacto no se transforma automáticamente en oferta.",secondaryMessage:"Ganas autonomía y tensas la relación de intermediación.",primaryEffects:[n("professional.careerControl",5),n("professional.environmentStability",-2)],secondaryEffects:[n("professional.environmentStability",-4)],primarySeedTransitions:[seedCreate("SEED_LAST_AGENT_GAMBLE",66,{stance:"direct_contact"})],secondarySeedTransitions:[seedCreate("SEED_LAST_AGENT_GAMBLE",71,{stance:"direct_contact",agent_friction:true})]},
   {id:"D",label:"Pedir prueba concreta al agente",intentTags:["agent","evidence"],primaryMessage:"Pides evidencia antes de arriesgar una oferta real.",secondaryMessage:"La exigencia mejora disciplina de información, pero pone a prueba la confianza acumulada.",primaryEffects:[n("professional.careerControl",4),n("professional.institutionalTrust",1)],secondaryEffects:[n("professional.environmentStability",-1)],primarySeedTransitions:[seedCreate("SEED_LAST_AGENT_GAMBLE",64,{stance:"ask_proof"})],secondarySeedTransitions:[seedCreate("SEED_LAST_AGENT_GAMBLE",69,{stance:"ask_proof",trust_test:true})]}
  ],seedsWrite:["SEED_LAST_AGENT_GAMBLE"],tags:["canonical_34plus","staged_not_registered","awaiting_external_fact","active_agent_authority_consumer"],canonStatus:"verified"
 }),
 ambiguousEvent({
  id:"EVT_34_CON_001",ageWindow:[34,null],phase:"34_plus",family:"contract",title:"La cláusula de salida digna",
  body:"Un club ofrece dos años con una salida condicionada si tu rol cae. La escena solo puede activarse si esa cláusula es representable por la authority contractual.",
  visible:["Duración","salario","cláusula representada"],uncertain:["No sabes si la cláusula te protege o protege sobre todo al club"],
  gates:[{path:"retirement.status",op:"eq",value:"playing"}],weight:9,
  choices:[
   {id:"A",label:"Aceptarla",intentTags:["contract","accept"],primaryMessage:"Aceptas la estructura contractual real.",secondaryMessage:"Ganas horizonte y dejas una puerta de salida cuyo uso futuro no controlas por completo.",primaryEffects:[n("professional.environmentStability",4),n("professional.contractPower",-1)],secondaryEffects:[n("professional.careerControl",-2)],primarySeedTransitions:[seedCreate("SEED_DIGNIFIED_EXIT_CLAUSE",68,{stance:"accept"})],secondarySeedTransitions:[seedCreate("SEED_DIGNIFIED_EXIT_CLAUSE",73,{stance:"accept",club_option_risk:true})]},
   {id:"B",label:"Pedir que sea bilateral",intentTags:["contract","counter"],primaryMessage:"Contrapropones una salida bilateral únicamente si puede persistirse en términos reales.",secondaryMessage:"Equilibras el riesgo, pero haces menos atractiva la oferta para el club.",primaryEffects:[n("professional.contractPower",5),n("professional.careerControl",3)],secondaryEffects:[n("professional.environmentStability",-2)],primarySeedTransitions:[seedCreate("SEED_DIGNIFIED_EXIT_CLAUSE",70,{stance:"bilateral"})],secondarySeedTransitions:[seedCreate("SEED_DIGNIFIED_EXIT_CLAUSE",75,{stance:"bilateral",negotiation_cost:true})]},
   {id:"C",label:"Cambiar a un año sin cláusula",intentTags:["contract","counter"],primaryMessage:"Prefieres menos duración a una condición que no quieres arrastrar.",secondaryMessage:"Conservas flexibilidad y vuelves a exponer tu futuro al mercado antes.",primaryEffects:[n("professional.careerControl",5),n("professional.environmentStability",-1)],secondaryEffects:[n("professional.contractPower",-1)],primarySeedTransitions:[seedCreate("SEED_DIGNIFIED_EXIT_CLAUSE",65,{stance:"one_year"})],secondarySeedTransitions:[seedCreate("SEED_DIGNIFIED_EXIT_CLAUSE",70,{stance:"one_year",future_market_risk:true})]},
   {id:"D",label:"Rechazar y buscar seguridad total",intentTags:["contract","reject"],primaryMessage:"Rechazas la oferta existente sin fabricar otra.",secondaryMessage:"Mantienes tu línea roja y asumes que la seguridad total quizá no aparezca.",primaryEffects:[n("professional.careerControl",4),n("professional.environmentStability",-3)],secondaryEffects:[n("professional.contractPower",-2)],primarySeedTransitions:[seedCreate("SEED_DIGNIFIED_EXIT_CLAUSE",67,{stance:"reject"})],secondarySeedTransitions:[seedCreate("SEED_DIGNIFIED_EXIT_CLAUSE",74,{stance:"reject",market_risk:true})]}
  ],seedsWrite:["SEED_DIGNIFIED_EXIT_CLAUSE"],tags:["canonical_34plus","staged_not_registered","awaiting_external_fact","contract_authority_consumer"],canonStatus:"verified"
 }),
 ambiguousEvent({
  id:"EVT_34_MAR_001",ageWindow:[34,null],phase:"34_plus",family:"contract",title:"Marzo: el club no llama",
  body:"Había una promesa factual de revisar tu contrato en marzo y pasan dos semanas sin reunión. El silencio solo existe si la promesa previa está persistida.",
  visible:["Fecha real","promesa previa","ausencia de reunión"],uncertain:["Pueden esperar presupuesto o entrenador","también pueden estar preparando sustituto"],
  gates:[{path:"retirement.status",op:"eq",value:"playing"}],timeWindow:{months:[3,4]},weight:9,
  choices:[
   {id:"A",label:"Pedir reunión",intentTags:["contract","clarity"],primaryMessage:"Pides que se cumpla la revisión sin escribir su resultado.",secondaryMessage:"Fuerzas claridad y haces visible que el silencio ya tiene coste.",primaryEffects:[n("professional.careerControl",4),n("professional.environmentStability",-1)],secondaryEffects:[n("professional.institutionalTrust",-2)],primarySeedTransitions:[seedCreate("SEED_MARCH_SILENCE",66,{stance:"ask_meeting"})],secondarySeedTransitions:[seedCreate("SEED_MARCH_SILENCE",71,{stance:"ask_meeting",friction:true})]},
   {id:"B",label:"Empezar a negociar fuera sin avisar",intentTags:["contract","market"],primaryMessage:"Abres interés externo sin asumir que exista una oferta.",secondaryMessage:"Recuperas palanca y deterioras la confianza si el club lo descubre.",primaryEffects:[n("professional.careerControl",5),n("professional.contractPower",2)],secondaryEffects:[n("professional.institutionalTrust",-4)],primarySeedTransitions:[seedCreate("SEED_MARCH_SILENCE",69,{stance:"outside_talks"})],secondarySeedTransitions:[seedCreate("SEED_MARCH_SILENCE",75,{stance:"outside_talks",trust_cost:true})]},
   {id:"C",label:"Esperar hasta abril",intentTags:["contract","delay"],primaryMessage:"Concedes tiempo al club sin convertir silencio en rechazo.",secondaryMessage:"La paciencia evita una escalada, pero reduce tiempo de reacción.",primaryEffects:[n("professional.environmentStability",2),n("professional.careerControl",-1)],secondaryEffects:[n("professional.contractPower",-3)],primarySeedTransitions:[seedCreate("SEED_MARCH_SILENCE",61,{stance:"wait_april"})],secondarySeedTransitions:[seedCreate("SEED_MARCH_SILENCE",67,{stance:"wait_april",time_cost:true})]},
   {id:"D",label:"Filtrar que no hay conversaciones",intentTags:["contract","press"],primaryMessage:"Haces público el hecho de que no existe reunión, sin afirmar que no exista futuro.",secondaryMessage:"La presión acelera el tema y reduce espacio para una solución silenciosa.",primaryEffects:[n("reputation.mediaHeat",4),n("professional.careerControl",2)],secondaryEffects:[n("professional.institutionalTrust",-3)],primarySeedTransitions:[seedCreate("SEED_MARCH_SILENCE",67,{stance:"public_silence"})],secondarySeedTransitions:[seedCreate("SEED_MARCH_SILENCE",72,{stance:"public_silence",public_cost:true})]}
  ],seedsWrite:["SEED_MARCH_SILENCE"],tags:["canonical_34plus","staged_not_registered","awaiting_external_fact","contract_authority_consumer"],canonStatus:"verified"
 }),
 ambiguousEvent({
  id:"EVT_35_MKT_001",ageWindow:[35,null],phase:"34_plus",family:"market",title:"Tres ofertas, tres versiones de ti",
  body:"Tres ofertas reales y concurrentes te proponen identidades deportivas distintas: especialista arriba, titular en un club medio o símbolo-líder en UDV.",
  visible:["Tres ofertas formales","tiers reales","contexto de rol visible"],uncertain:["No sabes qué versión de ti seguirá existiendo en febrero"],
  gates:[{path:"retirement.status",op:"eq",value:"playing"}],weight:12,
  choices:[
   {id:"A",label:"Especialista arriba",intentTags:["market","trophies"],primaryMessage:"Eliges la oferta de mayor techo aunque el rol sea más estrecho.",secondaryMessage:"Te acercas a competir arriba y aceptas depender más de ventanas concretas.",primaryEffects:[n("professional.matchSelectivity",5),n("professional.roleSecurity",-3)],secondaryEffects:[n("professional.motivationReserve",-1)],primarySeedTransitions:[seedCreate("SEED_THREE_VERSIONS_35",70,{version:"specialist_top"})],secondarySeedTransitions:[seedCreate("SEED_THREE_VERSIONS_35",75,{version:"specialist_top",role_risk:true})]},
   {id:"B",label:"Titular más abajo",intentTags:["market","minutes"],primaryMessage:"Eliges el contexto con más continuidad deportiva.",secondaryMessage:"Proteges minutos y cedes parte de escaparate y techo competitivo.",primaryEffects:[n("professional.roleSecurity",5),n("professional.environmentStability",2)],secondaryEffects:[n("professional.publicMyth",-1)],primarySeedTransitions:[seedCreate("SEED_THREE_VERSIONS_35",68,{version:"starter_mid"})],secondarySeedTransitions:[seedCreate("SEED_THREE_VERSIONS_35",72,{version:"starter_mid",ceiling_cost:true})]},
   {id:"C",label:"UDV",intentTags:["market","home"],primaryMessage:"Eliges la oferta real de regreso por su significado y centralidad.",secondaryMessage:"El rol simbólico pesa, pero no garantiza resultados ni minutos.",primaryEffects:[n("professional.homePull",5),n("professional.environmentStability",4)],secondaryEffects:[n("professional.contractPower",-2)],primarySeedTransitions:[seedCreate("SEED_THREE_VERSIONS_35",72,{version:"home_symbol"})],secondarySeedTransitions:[seedCreate("SEED_THREE_VERSIONS_35",77,{version:"home_symbol",expectation_weight:true})]},
   {id:"D",label:"Esperar una cuarta opción",intentTags:["market","delay"],primaryMessage:"No eliges ninguna de las tres y mantienes el mercado abierto.",secondaryMessage:"Conservas libertad y aceptas que la cuarta opción puede no existir.",primaryEffects:[n("professional.careerControl",5),n("professional.environmentStability",-2)],secondaryEffects:[n("professional.contractPower",-3)],primarySeedTransitions:[seedCreate("SEED_THREE_VERSIONS_35",64,{version:"wait_fourth"})],secondarySeedTransitions:[seedCreate("SEED_THREE_VERSIONS_35",71,{version:"wait_fourth",no_offer_risk:true})]}
  ],seedsWrite:["SEED_THREE_VERSIONS_35"],tags:["canonical_34plus","staged_not_registered","awaiting_external_fact","multi_offer_authority_consumer"],canonStatus:"verified"
 }),
 ambiguousEvent({
  id:"EVT_35_CON_001",ageWindow:[35,null],phase:"34_plus",family:"contract",title:"Contrato por objetivos físicos",
  body:"Una oferta veterana real combina fijo bajo y primas por convocatorias, minutos y disponibilidad. La escena solo se activa si esos términos son representables por authority contractual.",
  visible:["Fórmula contractual real","métricas representadas","contexto corporal factual"],uncertain:["No sabes si los incentivos alinean al club contigo o crean incentivos para no activarlos"],
  gates:[{path:"retirement.status",op:"eq",value:"playing"}],weight:9,
  choices:[
   {id:"A",label:"Aceptar",intentTags:["contract","accept"],primaryMessage:"Aceptas la estructura real y asumes más variabilidad económica.",secondaryMessage:"Ganas oportunidad, pero parte de tu remuneración depende de decisiones que no controlas.",primaryEffects:[n("professional.environmentStability",2),n("professional.contractPower",-2)],secondaryEffects:[n("professional.careerControl",-2)],primarySeedTransitions:[seedCreate("SEED_AVAILABILITY_CONTRACT",68,{stance:"accept"})],secondarySeedTransitions:[seedCreate("SEED_AVAILABILITY_CONTRACT",74,{stance:"accept",incentive_risk:true})]},
   {id:"B",label:"Convertir parte en primas colectivas",intentTags:["contract","counter"],primaryMessage:"Contrapropones incentivos colectivos solo si la authority puede persistirlos.",secondaryMessage:"Reduces dependencia de tus minutos y compartes riesgo con el rendimiento del equipo.",primaryEffects:[n("professional.contractPower",4),n("professional.environmentStability",2)],secondaryEffects:[n("professional.careerControl",1)],primarySeedTransitions:[seedCreate("SEED_AVAILABILITY_CONTRACT",66,{stance:"team_bonus_counter"})],secondarySeedTransitions:[seedCreate("SEED_AVAILABILITY_CONTRACT",70,{stance:"team_bonus_counter",team_dependency:true})]},
   {id:"C",label:"Pedir mínimo garantizado mayor",intentTags:["contract","counter"],primaryMessage:"Pides más fijo para reducir incertidumbre sin inventar una nueva oferta.",secondaryMessage:"Defiendes seguridad y elevas la probabilidad de que el club cierre la negociación.",primaryEffects:[n("professional.contractPower",5),n("professional.careerControl",2)],secondaryEffects:[n("professional.environmentStability",-2)],primarySeedTransitions:[seedCreate("SEED_AVAILABILITY_CONTRACT",67,{stance:"higher_floor"})],secondarySeedTransitions:[seedCreate("SEED_AVAILABILITY_CONTRACT",72,{stance:"higher_floor",deal_risk:true})]},
   {id:"D",label:"Rechazar por desconfianza",intentTags:["contract","reject"],primaryMessage:"Rechazas la oferta real sin convertir el contexto corporal en diagnóstico.",secondaryMessage:"Proteges tu línea roja y vuelves al mercado con menos certeza.",primaryEffects:[n("professional.careerControl",4),n("professional.environmentStability",-3)],secondaryEffects:[n("professional.contractPower",-2)],primarySeedTransitions:[seedCreate("SEED_AVAILABILITY_CONTRACT",69,{stance:"reject_distrust"})],secondarySeedTransitions:[seedCreate("SEED_AVAILABILITY_CONTRACT",74,{stance:"reject_distrust",market_risk:true})]}
  ],seedsWrite:["SEED_AVAILABILITY_CONTRACT"],tags:["canonical_34plus","staged_not_registered","awaiting_external_fact","contract_authority_consumer"],canonStatus:"verified"
 })
];

export const STAGED_MARKET_BATCH_1=E;
