import type { EventDefinition, SeedTransition } from "../../../core/types.js";
import { ambiguousEvent, n, seedCreate } from "../18_20/helpers.js";

const intensify = (seedId: string, intensity: number): SeedTransition => ({ seedId, action: "intensify", intensity });

export const A5_SHARED_EXTERNAL_PRINCIPAL_REQUIREMENTS = Object.freeze({
  EVT_20_MED_001: { owner:"medical/world", facts:["new medical service received-record knowledge","known diagnosed vs symptom history"], forbidden:["body.risk as diagnosis","assuming old club shared records"] },
  EVT_20_AGT_001: { owner:"A1/A3", facts:["active agent","representation permissions","delegation/service terms"], forbidden:["agentControl as identity","contact flag as contract"] },
  EVT_20_MATCH_003: { owner:"A4", facts:["official match score","coach order","player on pitch at minute 65"], forbidden:["role/form as live-match fact","narrative RNG score"] },
  EVT_20_BRUNO_001: { owner:"A1/A2/world", facts:["current Bruno market contact","contact provenance","active-agent channel"], forbidden:["SEED_BRUNO_FAVOR creating current opportunity"] },
  EVT_21_MONEY_001: { owner:"world/family", facts:["real family debt/request","amount/provenance"], forbidden:["cash threshold as family debt"] },
  EVT_21_AGT_001: { owner:"A1/A3", facts:["active representation","commission terms","service scope","revisability"], forbidden:["agentControl as commission","relationship as contract"] },
  EVT_21_NAT_001: { owner:"A4/#174", facts:["official national-team list","protagonist omitted from that list"], forbidden:["nationalStanding as call-up","heat as list"] },
  EVT_21_MED_001: { owner:"medical+A4", facts:["compatible diagnosed injury","treatment option","high-value official match context"], forbidden:["body.risk as diagnosis","invented match importance"] },
  EVT_21_CCH_002: { owner:"A1/shared-coach", facts:["actual current-club coach transition","new current coach/role relation when certified"], forbidden:["COACH_FIRED history as current change","fixed Montalbán/Mena after club change"] },
  EVT_22_LOCK_001: { owner:"A1/world", facts:["specific teammate sale case","salary conflict","participants","knowledge provenance"], forbidden:["lockerPower as sale fact","invented teammate"] },
  EVT_22_HOME_001: { owner:"A4", facts:["official fixture against UDV/former home club","participation context"], forbidden:["calendar month as fixture","exit seed as match fact"] },
  EVT_22_MED_001: { owner:"medical/world", facts:["real transfer medical examination","requested test","finding relevance context"], forbidden:["risk as MRI","invented buyer medical concern"] },
  EVT_22_TACT_001: { owner:"A4+A1/coach", facts:["official high-value match","concrete tactical role/order","current coach authority"], forbidden:["roleScore as order","invented tactical moment"] }
});

const EVT_20_MED_001=ambiguousEvent({
 id:"EVT_20_MED_001",ageWindow:[20,20],phase:"20_23",family:"medical",title:"El historial que viaja contigo",
 body:"Un nuevo servicio médico te pregunta por episodios previos. Tú distingues diagnósticos de molestias; lo que el nuevo club realmente ha recibido debe venir de la autoridad médica, no de una suposición.",
 visible:["Conoces qué episodios fueron diagnosticados y cuáles fueron solo molestias."],uncertain:["No sabes qué información recibió el nuevo servicio ni cuánto pesará una omisión menor."],weight:10,
 choices:[
  {id:"FULL_DETAIL",label:"Contarlo todo con detalle",intentTags:["medical","transparent"],primaryMessage:"La transparencia facilita contexto clínico aunque puede abrir pruebas adicionales.",secondaryMessage:"Más información mejora confianza y también puede retrasar una operación mientras se contrasta.",primaryEffects:[n("control.career",2)],secondaryEffects:[n("professional.environmentStability",-1)],primarySeedTransitions:[seedCreate("SEED_MEDICAL_DISCLOSURE",62,{stance:"full_detail"})],secondarySeedTransitions:[seedCreate("SEED_MEDICAL_DISCLOSURE",66,{stance:"full_detail",extra_tests:true})]},
  {id:"DIAGNOSED_ONLY",label:"Responder solo a lo que figure como diagnóstico",intentTags:["medical","privacy"],primaryMessage:"Usas una frontera verificable entre diagnóstico y sensación.",secondaryMessage:"La frontera protege privacidad pero puede parecer demasiado literal si el otro servicio conoce más contexto.",primaryEffects:[n("control.career",4)],secondaryEffects:[n("professional.environmentStability",-2)],primarySeedTransitions:[seedCreate("SEED_MEDICAL_DISCLOSURE",54,{stance:"diagnosed_only"})],secondarySeedTransitions:[seedCreate("SEED_MEDICAL_DISCLOSURE",58,{stance:"diagnosed_only",credibility_risk:true})]},
  {id:"MINIMIZE",label:"Minimizar un episodio que consideras irrelevante",intentTags:["medical","conceal"],primaryMessage:"La omisión puede no cambiar nada si el episodio realmente carecía de relevancia clínica.",secondaryMessage:"Si aparece un informe compatible, el problema pasa de salud a credibilidad.",primaryEffects:[n("control.career",1)],secondaryEffects:[n("professional.environmentStability",-4)],primarySeedTransitions:[seedCreate("SEED_MEDICAL_DISCLOSURE",68,{stance:"minimize"})],secondarySeedTransitions:[seedCreate("SEED_MEDICAL_DISCLOSURE",74,{stance:"minimize",credibility_cost:true})]},
  {id:"ASK_RECORDS",label:"Preguntar primero qué información médica han recibido",intentTags:["medical","information"],primaryMessage:"Pides saber el terreno factual antes de responder.",secondaryMessage:"La prudencia te da contexto aunque puede percibirse como una respuesta defensiva.",primaryEffects:[n("control.career",5)],secondaryEffects:[n("professional.environmentStability",-1)],primarySeedTransitions:[seedCreate("SEED_MEDICAL_DISCLOSURE",50,{stance:"ask_received_records"})],secondarySeedTransitions:[seedCreate("SEED_MEDICAL_DISCLOSURE",54,{stance:"ask_received_records",defensive_read:true})]}
 ],seedsRead:["SEED_BODY_PRECEDENT","SEED_PHYSIO_CONFIDENCE"],seedsWrite:["SEED_MEDICAL_DISCLOSURE"],tags:["medical","privacy","a5_ready_external_blocker"],canonStatus:"verified"
});

const EVT_20_AGT_001=ambiguousEvent({
 id:"EVT_20_AGT_001",ageWindow:[20,20],phase:"20_23",family:"agent",title:"El teléfono del agente",
 body:"Con representación activa, el problema ya no es quién te llamó primero sino qué puede responder tu agente sin pedirte permiso. Identidad, comisión y permisos deben provenir del contrato de representación real.",
 visible:["Si existe agente activo, sabes quién es.","Los permisos y servicios concretos no se deducen de agentControl."],uncertain:["No sabes qué oportunidades filtrará ni qué contactos considera poco serios."],
 gates:[{path:"facts.activeAgentNpcId",op:"exists"}],weight:11,
 choices:[
  {id:"BROAD_CONTROL",label:"Darle control amplio",intentTags:["agent","delegate"],primaryMessage:"Centralizas la respuesta profesional cuando el contrato lo permite.",secondaryMessage:"La eficiencia aumenta y también el riesgo de que una oportunidad se descarte sin ti.",primaryEffects:[n("professional.agentControl",7),n("control.career",-3)],secondaryEffects:[n("professional.agentControl",8),n("control.career",-6)],primarySeedTransitions:[seedCreate("SEED_AGENT_POWER",65,{choice:"A"})],secondarySeedTransitions:[seedCreate("SEED_AGENT_POWER",72,{choice:"A",omission_risk:true})]},
  {id:"REPORT_ALL",label:"Exigir que te informe de todo contacto serio antes de responder",intentTags:["agent","information"],primaryMessage:"Conservas autorización sobre contactos relevantes.",secondaryMessage:"El filtro protege autonomía y puede ralentizar una operación rápida.",primaryEffects:[n("control.career",6),n("professional.agentControl",2)],secondaryEffects:[n("control.career",4)],primarySeedTransitions:[seedCreate("SEED_AGENT_POWER",58,{choice:"B"})],secondarySeedTransitions:[seedCreate("SEED_AGENT_POWER",62,{choice:"B",timing_cost:true})]},
  {id:"SPLIT_FUNCTIONS",label:"Mantener prensa e imagen en tus manos y mercado en las suyas",intentTags:["agent","split_scope"],primaryMessage:"Separar funciones crea un contrapeso claro cuando el contrato lo admite.",secondaryMessage:"La especialización mejora control y aumenta el número de canales que deben coordinarse.",primaryEffects:[n("control.career",5),n("professional.agentControl",1)],secondaryEffects:[n("professional.environmentStability",-2)],primarySeedTransitions:[seedCreate("SEED_AGENT_POWER",55,{choice:"C"})],secondarySeedTransitions:[seedCreate("SEED_AGENT_POWER",60,{choice:"C",coordination_cost:true})]},
  {id:"NO_CENTRALIZE",label:"Negarte a centralizar",intentTags:["agent","autonomy"],primaryMessage:"Mantienes más decisiones directas contigo.",secondaryMessage:"La autonomía evita dependencia y puede fragmentar respuestas cuando el volumen de contactos crece.",primaryEffects:[n("control.career",7),n("professional.agentControl",-5)],secondaryEffects:[n("control.career",4),n("professional.environmentStability",-2)],primarySeedTransitions:[seedCreate("SEED_AGENT_POWER",52,{choice:"D"})],secondarySeedTransitions:[seedCreate("SEED_AGENT_POWER",58,{choice:"D",fragmentation:true})]}
 ],seedsRead:["SEED_AGENT_OMISSION","SEED_FIRST_AGENT"],seedsWrite:["SEED_AGENT_POWER"],tags:["agent","representation","a5_ready_external_blocker"],canonStatus:"verified"
});

const EVT_20_MATCH_003=ambiguousEvent({
 id:"EVT_20_MATCH_003",ageWindow:[20,20],phase:"20_23",family:"sport",title:"El minuto 65",
 body:"En un partido oficial, el entrenador cambia tu tarea en el minuto 65. Marcador, orden y tu presencia en campo deben existir como hechos A4 antes de que esta escena pueda activarse.",
 visible:["Conoces el marcador y la orden concreta cuando el match store los acredita.","Tus estadísticas recientes son contexto, no sustituto del momento."],uncertain:["No sabes qué valoran los scouts ni cuánto margen táctico tolerará el entrenador."],weight:13,
 choices:[
  {id:"STRICT",label:"Cumplir de forma estricta",intentTags:["tactical","discipline"],primaryMessage:"Priorizas la orden incluso si reduce tus acciones visibles.",secondaryMessage:"La disciplina puede ganar confianza y dejar menos highlights.",primaryEffects:[n("professional.roleSecurity",4)],secondaryEffects:[n("reputation.marketHeat",-1)]},
  {id:"HYBRID",label:"Cumplir sin renunciar a atacar cuando el contexto lo permita",intentTags:["tactical","adapt"],primaryMessage:"Buscas una lectura híbrida entre obediencia y oportunidad.",secondaryMessage:"La interpretación puede resolver el partido o parecer una licencia que nadie concedió.",primaryEffects:[n("professional.roleSecurity",2),n("control.career",2)],secondaryEffects:[n("professional.environmentStability",-2)]},
  {id:"OWN_GAME",label:"Mantener tu juego y asumir el riesgo",intentTags:["identity","risk"],primaryMessage:"Proteges tu perfil ofensivo aunque te apartes de la orden.",secondaryMessage:"Una jugada decisiva puede justificarte o una sustitución inmediata dejar el conflicto abierto.",primaryEffects:[n("reputation.marketHeat",3)],secondaryEffects:[n("professional.roleSecurity",-6),n("reputation.mediaHeat",2)]}
 ],seedsRead:["SEED_MENA_EARLY_READ"],tags:["sport","live_match","tactical","a5_ready_external_blocker"],canonStatus:"verified"
});

const EVT_20_BRUNO_001=ambiguousEvent({
 id:"EVT_20_BRUNO_001",ageWindow:[20,20],phase:"20_23",family:"market",title:"La llamada de Bruno",
 body:"Bruno puede ofrecer presentar tu nombre, pero un favor pasado no crea por sí solo una oportunidad actual. El contacto de mercado y su procedencia deben existir primero.",
 visible:["Tu memoria causal conserva cómo trataste a Bruno antes.","Si tienes agente activo, sabes quién debe recibir cualquier canal profesional."],uncertain:["No sabes si el puesto es prioridad ni cuánto pesa realmente Bruno."],
 gates:[{path:"facts.brunoFavorStance",op:"exists"}],weight:9,
 choices:[
  {id:"AUTHORIZE_NOTIFY",label:"Autorizarle y avisar a tu agente",intentTags:["bruno","agent","transparent"],eligibility:[{path:"facts.activeAgentNpcId",op:"exists"}],primaryMessage:"Mantienes el favor personal y el canal profesional alineados.",secondaryMessage:"La coordinación reduce conflicto pero puede ralentizar un contacto informal.",primaryEffects:[n("rel.NPC_PLR_12.trust",4),n("control.career",3)],secondaryEffects:[n("rel.NPC_PLR_12.trust",2)],primarySeedTransitions:[intensify("SEED_BRUNO_FAVOR",4),intensify("SEED_AGENT_POWER",3)],secondarySeedTransitions:[intensify("SEED_BRUNO_FAVOR",3),intensify("SEED_AGENT_POWER",4)]},
  {id:"AUTHORIZE_PRIVATE",label:"Autorizarle sin avisar al agente todavía",intentTags:["bruno","private","risk"],primaryMessage:"El contacto puede avanzar rápido si era real.",secondaryMessage:"Si llega a tu representación por otra vía, el problema pasa a ser también de confianza.",primaryEffects:[n("rel.NPC_PLR_12.trust",5),n("control.career",2)],secondaryEffects:[n("professional.agentControl",-3)],primarySeedTransitions:[intensify("SEED_BRUNO_FAVOR",5)],secondarySeedTransitions:[intensify("SEED_BRUNO_FAVOR",6),intensify("SEED_AGENT_POWER",5)]},
  {id:"ASK_PROOF",label:"Pedir más información antes de usar el favor",intentTags:["bruno","information"],primaryMessage:"Proteges a ambos de presentar tu nombre en una oportunidad poco concreta.",secondaryMessage:"La prudencia mejora la calidad del contacto y puede perder timing.",primaryEffects:[n("control.career",5),n("rel.NPC_PLR_12.respect",2)],secondaryEffects:[n("reputation.marketHeat",-1)],primarySeedTransitions:[intensify("SEED_BRUNO_FAVOR",2)],secondarySeedTransitions:[intensify("SEED_BRUNO_FAVOR",3)]},
  {id:"DECLINE_HELP",label:"Decirle que no, pero ofrecer ayudarle en otra cosa",intentTags:["bruno","boundary"],primaryMessage:"No conviertes el favor en canal de mercado y preservas la relación personal.",secondaryMessage:"Bruno puede entender el límite o sentir que su gesto anterior ya no tiene valor.",primaryEffects:[n("rel.NPC_PLR_12.trust",3)],secondaryEffects:[n("rel.NPC_PLR_12.affinity",-2)],primarySeedTransitions:[intensify("SEED_BRUNO_FAVOR",2)],secondarySeedTransitions:[intensify("SEED_BRUNO_FAVOR",3)]}
 ],seedsRead:["SEED_BRUNO_FAVOR","SEED_AGENT_POWER"],seedsWrite:["SEED_BRUNO_FAVOR","SEED_AGENT_POWER"],npcRefs:["NPC_PLR_12"],tags:["bruno","market_contact","a5_ready_external_blocker"],canonStatus:"verified"
});

const EVT_21_MONEY_001=ambiguousEvent({
 id:"EVT_21_MONEY_001",ageWindow:[21,21],phase:"20_23",family:"money",title:"El primer contrato que cambia a tu familia",
 body:"Una petición familiar importante llega cuando tus ingresos ya pueden resolverla. La deuda o necesidad debe ser un hecho familiar real; tener dinero no la inventa.",
 visible:["Conoces el importe solicitado y tus ingresos cuando el world/family owner lo materializa."],uncertain:["No sabes si la ayuda será puntual ni qué expectativa creará."],weight:10,
 choices:[
  {id:"PAY_ALL",label:"Pagar la deuda completa",intentTags:["family","money"],primaryMessage:"El problema inmediato desaparece y cambia el equilibrio de ayuda familiar.",secondaryMessage:"Resolverlo todo puede aliviar y también crear la expectativa de que siempre podrás hacerlo.",primaryEffects:[n("professional.moneyComfort",-6),n("rel.NPC_FAM_01.trust",5)],secondaryEffects:[n("professional.moneyComfort",-8),n("rel.NPC_FAM_02.leverage",4)],primarySeedTransitions:[seedCreate("SEED_FAMILY_MONEY",64,{stance:"pay_all"})],secondarySeedTransitions:[seedCreate("SEED_FAMILY_MONEY",70,{stance:"pay_all",dependency_risk:true})]},
  {id:"PART_LIMIT",label:"Ayudar con una parte y fijar límite",intentTags:["family","boundary"],primaryMessage:"Ayudas sin convertir tus ingresos en una obligación abierta.",secondaryMessage:"El límite protege sostenibilidad y puede sentirse frío en un momento de necesidad.",primaryEffects:[n("professional.moneyComfort",-3),n("control.career",3)],secondaryEffects:[n("rel.NPC_FAM_01.affinity",-2)],primarySeedTransitions:[seedCreate("SEED_FAMILY_MONEY",58,{stance:"partial_limit"})],secondarySeedTransitions:[seedCreate("SEED_FAMILY_MONEY",62,{stance:"partial_limit",friction:true})]},
  {id:"NO_MONEY",label:"No intervenir económicamente",intentTags:["family","autonomy"],primaryMessage:"Mantienes separadas carrera y responsabilidad económica familiar.",secondaryMessage:"La frontera preserva autonomía y puede dejar crecer un problema real.",primaryEffects:[n("control.career",4)],secondaryEffects:[n("rel.NPC_FAM_01.trust",-4)],primarySeedTransitions:[seedCreate("SEED_FAMILY_MONEY",50,{stance:"decline"})],secondarySeedTransitions:[seedCreate("SEED_FAMILY_MONEY",56,{stance:"decline",problem_persists:true})]},
  {id:"ASK_DOCUMENTS",label:"Pedir documentos y entender primero el problema",intentTags:["family","information"],primaryMessage:"Decides desde datos en vez de desde culpa o abundancia.",secondaryMessage:"La prudencia aclara el problema y puede sentirse humillante para quien pidió ayuda.",primaryEffects:[n("control.career",5)],secondaryEffects:[n("rel.NPC_FAM_02.affinity",-2)],primarySeedTransitions:[seedCreate("SEED_FAMILY_MONEY",54,{stance:"ask_documents"})],secondarySeedTransitions:[seedCreate("SEED_FAMILY_MONEY",58,{stance:"ask_documents",felt_distrusted:true})]}
 ],seedsWrite:["SEED_FAMILY_MONEY"],npcRefs:["NPC_FAM_01","NPC_FAM_02"],tags:["family","money","a5_ready_external_blocker"],canonStatus:"verified"
});

const EVT_21_AGT_001=ambiguousEvent({
 id:"EVT_21_AGT_001",ageWindow:[21,21],phase:"20_23",family:"agent",title:"La agencia quiere otro porcentaje",
 body:"Tu agencia propone cambiar comisión y servicios. La comisión actual, la propuesta y su revisabilidad deben existir en autoridad de representación; no se deducen de agentControl.",
 visible:["Conoces tu representante activo cuando está certificado."],uncertain:["No sabes cuánto acceso real compra una comisión mayor ni si otra agencia sería mejor."],
 gates:[{path:"facts.activeAgentNpcId",op:"exists"}],weight:10,
 choices:[
  {id:"ACCEPT_TARGETS",label:"Aceptar subida a cambio de objetivos concretos",intentTags:["agent","counter"],primaryMessage:"Vinculas más coste a compromisos verificables antes de aceptar términos.",secondaryMessage:"Los objetivos pueden alinear incentivos o convertirse en otra fuente de discusión.",primaryEffects:[n("professional.agentControl",3),n("control.career",2)],secondaryEffects:[n("professional.agentControl",4),n("professional.environmentStability",-1)],primarySeedTransitions:[intensify("SEED_AGENT_POWER",4)],secondarySeedTransitions:[intensify("SEED_AGENT_POWER",5)]},
  {id:"KEEP_TERMS",label:"Negarte y mantener contrato",intentTags:["agent","reject"],primaryMessage:"No cambias la relación económica sin evidencia adicional.",secondaryMessage:"Mantener términos protege coste y puede reducir prioridad interna de la agencia.",primaryEffects:[n("control.career",4)],secondaryEffects:[n("professional.agentControl",-2)],primarySeedTransitions:[intensify("SEED_AGENT_POWER",2)],secondarySeedTransitions:[intensify("SEED_AGENT_POWER",3)]},
  {id:"SOUND_OTHER",label:"Abrir conversaciones discretas con otra agencia",intentTags:["agent","market"],primaryMessage:"Buscas una comparación real antes de cambiar representación.",secondaryMessage:"El sondeo aporta referencia o se filtra y deteriora la relación actual.",primaryEffects:[n("control.career",5)],secondaryEffects:[n("professional.environmentStability",-3)],primarySeedTransitions:[intensify("SEED_AGENT_POWER",5)],secondarySeedTransitions:[intensify("SEED_AGENT_POWER",7)]},
  {id:"SPLIT_IMAGE",label:"Separar representación deportiva e imagen",intentTags:["agent","scope"],primaryMessage:"Divides servicios para reducir concentración cuando los contratos lo permiten.",secondaryMessage:"La especialización mejora contrapesos y complica coordinación.",primaryEffects:[n("control.career",5),n("professional.agentControl",-1)],secondaryEffects:[n("professional.environmentStability",-2)],primarySeedTransitions:[intensify("SEED_AGENT_POWER",4)],secondarySeedTransitions:[intensify("SEED_AGENT_POWER",5)]}
 ],seedsRead:["SEED_FIRST_AGENT","SEED_AGENT_POWER"],seedsWrite:["SEED_AGENT_POWER"],tags:["agent","commission","a5_ready_external_blocker"],canonStatus:"verified"
});

const EVT_21_NAT_001=ambiguousEvent({
 id:"EVT_21_NAT_001",ageWindow:[21,21],phase:"20_23",family:"selection",title:"La ausencia",
 body:"La lista oficial sale sin tu nombre. Solo una lista concreta puede demostrar la ausencia; standing, heat y caps son contexto agregado.",
 visible:["La lista es oficial cuando #174 la materializa."],uncertain:["No sabes si estuviste cerca, si pesa tu club o si nunca te consideraron."],weight:10,
 choices:[
  {id:"DO_MORE",label:"Decir que debes hacer más",intentTags:["selection","humble"],primaryMessage:"Conviertes la ausencia en una exigencia propia sin atribuir motivos al seleccionador.",secondaryMessage:"La respuesta es prudente y puede pasar desapercibida.",primaryEffects:[n("professional.nationalHeat",2),n("professional.environmentStability",2)],secondaryEffects:[n("professional.nationalHeat",1)],primarySeedTransitions:[seedCreate("SEED_SELECTION_SNUB",50,{stance:"do_more"})],secondarySeedTransitions:[seedCreate("SEED_SELECTION_SNUB",54,{stance:"do_more",quiet:true})]},
  {id:"MERIT_FIELD",label:"Decir que los méritos deberían medirse en el campo",intentTags:["selection","public"],primaryMessage:"Defiendes tu rendimiento sin afirmar conocer la causa de la lista.",secondaryMessage:"La frase proyecta hambre o se lee como crítica al criterio de selección.",primaryEffects:[n("professional.nationalHeat",4),n("reputation.mediaHeat",2)],secondaryEffects:[n("reputation.mediaHeat",5),n("professional.publicPolarization",3)],primarySeedTransitions:[seedCreate("SEED_SELECTION_SNUB",64,{stance:"merit_field"})],secondarySeedTransitions:[seedCreate("SEED_SELECTION_SNUB",70,{stance:"merit_field",critical_read:true})]},
  {id:"NO_SELECTION_TALK",label:"No hablar de selección",intentTags:["selection","silence"],primaryMessage:"Evitas construir una explicación sin datos.",secondaryMessage:"El silencio protege del error y deja a otros llenar el vacío.",primaryEffects:[n("professional.environmentStability",3)],secondaryEffects:[n("reputation.mediaHeat",2)],primarySeedTransitions:[seedCreate("SEED_SELECTION_SNUB",46,{stance:"silence"})],secondarySeedTransitions:[seedCreate("SEED_SELECTION_SNUB",50,{stance:"silence",others_speculate:true})]},
  {id:"PRIVATE_CHECK",label:"Llamar a tu agente para averiguar por vías privadas antes de responder",intentTags:["selection","agent","information"],eligibility:[{path:"facts.activeAgentNpcId",op:"exists"}],primaryMessage:"Buscas contexto sin presentarlo como verdad pública.",secondaryMessage:"La investigación puede aportar una pista o fabricar una certeza a partir de rumores.",primaryEffects:[n("control.career",4)],secondaryEffects:[n("professional.agentControl",2)],primarySeedTransitions:[seedCreate("SEED_SELECTION_SNUB",56,{stance:"private_check"})],secondarySeedTransitions:[seedCreate("SEED_SELECTION_SNUB",62,{stance:"private_check",uncertain_source:true})]}
 ],seedsWrite:["SEED_SELECTION_SNUB"],tags:["selection","official_list","a5_ready_external_blocker"],canonStatus:"verified"
});

const EVT_21_MED_001=ambiguousEvent({
 id:"EVT_21_MED_001",ageWindow:[21,21],phase:"20_23",family:"medical",title:"La inyección",
 body:"Un tratamiento permitiría intentar un partido de alto valor con una lesión compatible. Diagnóstico, dolor, recomendación y partido deben existir antes; el narrador no los sortea.",
 visible:["Conoces diagnóstico, dolor y recomendación solo desde autoridad médica.","El partido de alto valor debe ser un hecho A4."],uncertain:["No sabes cómo responderá tu cuerpo ni cuándo volverá una oportunidad igual."],weight:10,
 choices:[
  {id:"PLAY_TREATMENT",label:"Jugar con el tratamiento",intentTags:["medical","risk"],primaryMessage:"Aceptas el riesgo conocido dentro de la recomendación real.",secondaryMessage:"El tratamiento permite competir o prolonga la recuperación; el resultado médico no se inventa aquí.",primaryEffects:[n("control.career",1)],secondaryEffects:[n("professional.recoveryDebt",3)],primarySeedTransitions:[intensify("SEED_MEDICAL_DISCLOSURE",4),intensify("SEED_BODY_PRECEDENT",4)],secondarySeedTransitions:[intensify("SEED_MEDICAL_DISCLOSURE",6),intensify("SEED_BODY_PRECEDENT",6)]},
  {id:"UNAVAILABLE",label:"Declararte no disponible",intentTags:["medical","caution"],primaryMessage:"Proteges recuperación aunque pierdas una ventana deportiva.",secondaryMessage:"La ausencia evita exposición física y puede costar una oportunidad excepcional.",primaryEffects:[n("professional.recoveryDebt",-3),n("control.career",3)],secondaryEffects:[n("professional.roleSecurity",-2)]},
  {id:"SECOND_OPINION",label:"Pedir una segunda opinión rápida",intentTags:["medical","information"],primaryMessage:"Buscas más evidencia antes de asumir riesgo.",secondaryMessage:"La segunda opinión puede aclarar o consumir el tiempo disponible para decidir.",primaryEffects:[n("control.career",5)],secondaryEffects:[n("professional.environmentStability",-1)]},
  {id:"TRAIN_TEST",label:"Aceptar solo si entrenas sin empeorar en la víspera",intentTags:["medical","conditional"],primaryMessage:"Condicionas la disponibilidad a un dato funcional próximo al partido.",secondaryMessage:"La prueba puede reducir incertidumbre sin garantizar cómo responderás en competición.",primaryEffects:[n("control.career",4)],secondaryEffects:[n("professional.recoveryDebt",1)]}
 ],seedsRead:["SEED_MEDICAL_DISCLOSURE","SEED_BODY_PRECEDENT"],seedsWrite:["SEED_MEDICAL_DISCLOSURE","SEED_BODY_PRECEDENT"],tags:["medical","match_context","a5_ready_external_blocker"],canonStatus:"verified"
});

const EVT_21_CCH_002=ambiguousEvent({
 id:"EVT_21_CCH_002",ageWindow:[21,21],phase:"20_23",family:"tactical",title:"Otro entrenador, otra versión de ti",
 body:"Un cambio real de técnico trae un rol táctico distinto. La transición y el entrenador actual deben venir de autoridad de coach; no de un COACH_FIRED histórico.",
 visible:["La nueva posición y tareas son visibles cuando existe un cambio actual acreditado."],uncertain:["No sabes si el cambio durará ni cómo lo leerán scouts y mercado."],weight:10,
 choices:[
  {id:"EMBRACE",label:"Abrazar el rol",intentTags:["tactical","adapt"],primaryMessage:"Te comprometes con el perfil nuevo y das margen para que funcione.",secondaryMessage:"La adaptación puede elevar tu utilidad y reducir producción visible.",primaryEffects:[n("professional.roleAdaptability",5),n("professional.roleSecurity",3)],secondaryEffects:[n("reputation.marketHeat",-1)],primarySeedTransitions:[seedCreate("SEED_TACTICAL_SACRIFICE",58,{stance:"embrace"})],secondarySeedTransitions:[seedCreate("SEED_TACTICAL_SACRIFICE",64,{stance:"embrace",production_cost:true})]},
  {id:"FREEDOM",label:"Aceptarlo y pedir libertad en ciertos partidos",intentTags:["tactical","negotiate"],primaryMessage:"Aceptas la idea con un margen concreto para conservar fortalezas.",secondaryMessage:"La negociación puede mejorar el plan o parecer resistencia anticipada.",primaryEffects:[n("professional.roleAdaptability",4),n("control.career",3)],secondaryEffects:[n("professional.roleSecurity",-2)],primarySeedTransitions:[seedCreate("SEED_TACTICAL_SACRIFICE",60,{stance:"conditional_freedom"})],secondarySeedTransitions:[seedCreate("SEED_TACTICAL_SACRIFICE",65,{stance:"conditional_freedom",coach_friction:true})]},
  {id:"RESIST",label:"Resistirte y competir por tu perfil anterior",intentTags:["identity","resist"],primaryMessage:"Proteges el perfil que te trajo hasta aquí.",secondaryMessage:"Mantener identidad puede sostener mercado o dejarte fuera del nuevo plan.",primaryEffects:[n("control.career",4)],secondaryEffects:[n("professional.roleSecurity",-5)],primarySeedTransitions:[seedCreate("SEED_TACTICAL_SACRIFICE",68,{stance:"resist"})],secondarySeedTransitions:[seedCreate("SEED_TACTICAL_SACRIFICE",72,{stance:"resist",role_cost:true})]},
  {id:"SOUND_MARKET",label:"Pedir a tu agente que sondee mercado antes de decidir",intentTags:["agent","market"],eligibility:[{path:"facts.activeAgentNpcId",op:"exists"}],primaryMessage:"Contrastas alternativas sin convertir el sondeo en oferta.",secondaryMessage:"El movimiento aporta contexto y puede alterar confianza antes de que pruebes el nuevo rol.",primaryEffects:[n("control.career",5)],secondaryEffects:[n("professional.environmentStability",-3)],primarySeedTransitions:[seedCreate("SEED_TACTICAL_SACRIFICE",62,{stance:"sound_market"})],secondarySeedTransitions:[seedCreate("SEED_TACTICAL_SACRIFICE",68,{stance:"sound_market",trust_cost:true})]}
 ],seedsWrite:["SEED_TACTICAL_SACRIFICE"],tags:["coach_change","tactical","a5_ready_external_blocker"],canonStatus:"verified"
});

const EVT_22_LOCK_001=ambiguousEvent({
 id:"EVT_22_LOCK_001",ageWindow:[22,22],phase:"20_23",family:"team",title:"El compañero al que quieren vender",
 body:"Un compañero concreto está en una disputa salarial y parte del vestuario te pide posición. La venta, el conflicto y quién conoce qué deben ser hechos del mundo/NPC, no una lectura de lockerPower.",
 visible:["Conoces la petición y la parte de cifras colectivas realmente compartida."],uncertain:["No conoces todas sus condiciones ni la urgencia financiera real del club."],weight:10,
 choices:[
  {id:"SUPPORT",label:"Apoyar la medida",intentTags:["locker","solidarity"],primaryMessage:"Te alineas con una posición colectiva concreta.",secondaryMessage:"La solidaridad puede reforzar al grupo y tensionar tu relación institucional.",primaryEffects:[n("professional.lockerPower",5)],secondaryEffects:[n("professional.institutionalTrust",-4)],primarySeedTransitions:[seedCreate("SEED_LOCKER_VOTE",62,{stance:"support"})],secondarySeedTransitions:[seedCreate("SEED_LOCKER_VOTE",68,{stance:"support",club_cost:true})]},
  {id:"OPPOSE",label:"Oponerte y separar primas colectivas de su caso",intentTags:["locker","boundary"],primaryMessage:"Defiendes que el caso individual no decida automáticamente la política colectiva.",secondaryMessage:"La distinción puede ser razonable y leerse como ruptura de código.",primaryEffects:[n("control.career",4)],secondaryEffects:[n("professional.lockerPower",-4)],primarySeedTransitions:[seedCreate("SEED_LOCKER_VOTE",58,{stance:"oppose"})],secondarySeedTransitions:[seedCreate("SEED_LOCKER_VOTE",64,{stance:"oppose",locker_cost:true})]},
  {id:"MEETING",label:"Proponer una reunión con dirección sin amenaza",intentTags:["locker","institution"],primaryMessage:"Intentas llevar el conflicto a un canal donde ambas partes puedan aportar datos.",secondaryMessage:"La reunión puede desbloquear contexto o solo ganar tiempo para la dirección.",primaryEffects:[n("professional.lockerPower",3),n("professional.institutionalTrust",2)],secondaryEffects:[n("control.career",1)],primarySeedTransitions:[seedCreate("SEED_LOCKER_VOTE",56,{stance:"meeting"})],secondarySeedTransitions:[seedCreate("SEED_LOCKER_VOTE",60,{stance:"meeting",delay:true})]},
  {id:"MAJORITY",label:"No tomar posición y aceptar lo que decida la mayoría",intentTags:["locker","wait"],primaryMessage:"Evitas personalizar un conflicto con información incompleta.",secondaryMessage:"La neutralidad reduce exposición y también tu influencia en una decisión colectiva.",primaryEffects:[n("professional.environmentStability",2)],secondaryEffects:[n("professional.lockerPower",-2)],primarySeedTransitions:[seedCreate("SEED_LOCKER_VOTE",48,{stance:"majority"})],secondarySeedTransitions:[seedCreate("SEED_LOCKER_VOTE",52,{stance:"majority",low_influence:true})]}
 ],seedsWrite:["SEED_LOCKER_VOTE"],tags:["locker","sale_conflict","a5_ready_external_blocker"],canonStatus:"verified"
});

const EVT_22_HOME_001=ambiguousEvent({
 id:"EVT_22_HOME_001",ageWindow:[22,22],phase:"20_23",family:"sport",title:"El partido contra casa",
 body:"Tu club actual se cruza oficialmente con UDV o tu club de origen. El fixture y tu participación deben existir en A4; la memoria de cómo saliste solo cambia el significado de tus gestos.",
 visible:["Conoces tu salida previa y el ambiente cuando existe fixture real."],uncertain:["No sabes qué gesto leerán como respeto, cálculo o deslealtad."],
 gates:[{path:"club",op:"neq",value:"UDV"},{path:"facts.exitStyleYear19",op:"exists"}],weight:10,
 choices:[
  {id:"GREET",label:"Saludar a la grada antes del partido",intentTags:["home","respect"],primaryMessage:"Haces un gesto explícito antes de que el resultado condicione la lectura.",secondaryMessage:"El saludo puede reconciliar o parecer ensayado.",primaryEffects:[n("professional.environmentStability",3)],secondaryEffects:[n("reputation.mediaHeat",2)],primarySeedTransitions:[seedCreate("SEED_HOME_DISTANCE",54,{stance:"greet"})],secondarySeedTransitions:[seedCreate("SEED_HOME_DISTANCE",58,{stance:"greet",calculated_read:true})]},
  {id:"ROUTINE",label:"Mantener rutina y no teatralizar",intentTags:["home","professional"],primaryMessage:"Tratas el partido como competición sin negar tu historia.",secondaryMessage:"La normalidad evita gesto artificial y puede parecer distancia.",primaryEffects:[n("control.career",3)],secondaryEffects:[n("professional.publicPolarization",2)],primarySeedTransitions:[seedCreate("SEED_HOME_DISTANCE",50,{stance:"routine"})],secondarySeedTransitions:[seedCreate("SEED_HOME_DISTANCE",54,{stance:"routine",distance_read:true})]},
  {id:"NO_CELEBRATE",label:"Si marcas, no celebrar",intentTags:["home","symbolic"],primaryMessage:"Reservas un gesto de respeto si el hecho deportivo llega a ocurrir.",secondaryMessage:"El gesto puede agradar al origen y molestar a tu afición actual.",primaryEffects:[n("professional.environmentStability",2)],secondaryEffects:[n("professional.publicPolarization",3)],primarySeedTransitions:[seedCreate("SEED_HOME_DISTANCE",58,{stance:"no_celebrate"})],secondarySeedTransitions:[seedCreate("SEED_HOME_DISTANCE",62,{stance:"no_celebrate",current_fans_cost:true})]},
  {id:"DECIDE_LIVE",label:"Decidir la celebración solo en el momento según el ambiente",intentTags:["home","adaptive"],primaryMessage:"No prometes un gesto condicionado a un gol que quizá no ocurra.",secondaryMessage:"La flexibilidad evita teatralidad y deja la lectura a un instante de presión.",primaryEffects:[n("control.career",4)],secondaryEffects:[n("reputation.mediaHeat",1)],primarySeedTransitions:[seedCreate("SEED_HOME_DISTANCE",52,{stance:"decide_live"})],secondarySeedTransitions:[seedCreate("SEED_HOME_DISTANCE",56,{stance:"decide_live",ambiguous_read:true})]}
 ],seedsRead:["SEED_EXIT_STYLE_UDV"],seedsWrite:["SEED_HOME_DISTANCE"],tags:["home","former_club_fixture","a5_ready_external_blocker"],canonStatus:"verified"
});

const EVT_22_MED_001=ambiguousEvent({
 id:"EVT_22_MED_001",ageWindow:[22,22],phase:"20_23",family:"medical",title:"La resonancia antes de firmar",
 body:"Una operación avanzada depende de un reconocimiento. La prueba pedida y su resultado clínico deben venir del sistema médico; la escena no convierte risk en resonancia.",
 visible:["Conoces qué prueba se pide cuando existe un reconocimiento real."],uncertain:["No sabes si un hallazgo será relevante ni si el comprador mantendrá la operación."],weight:10,
 choices:[
  {id:"ALL_TESTS",label:"Hacer todas las pruebas",intentTags:["medical","transparent"],primaryMessage:"Aceptas completar el proceso médico con toda la evidencia solicitada.",secondaryMessage:"Más información puede salvarte de un mal contrato o consumir tiempo de mercado.",primaryEffects:[n("control.career",2)],secondaryEffects:[n("professional.environmentStability",-2)],primarySeedTransitions:[seedCreate("SEED_MEDICAL_DISCLOSURE",62,{stance:"all_tests"})],secondarySeedTransitions:[seedCreate("SEED_MEDICAL_DISCLOSURE",66,{stance:"all_tests",timing_cost:true})]},
  {id:"SECOND_OPINION",label:"Aportar segunda opinión propia en paralelo",intentTags:["medical","second_opinion"],primaryMessage:"Añades contexto médico sin sustituir el reconocimiento del comprador.",secondaryMessage:"La doble lectura puede aclarar o abrir una discrepancia difícil de cerrar a tiempo.",primaryEffects:[n("control.career",5)],secondaryEffects:[n("professional.environmentStability",-2)],primarySeedTransitions:[seedCreate("SEED_MEDICAL_DISCLOSURE",60,{stance:"second_opinion"})],secondarySeedTransitions:[seedCreate("SEED_MEDICAL_DISCLOSURE",65,{stance:"second_opinion",disagreement:true})]},
  {id:"CONDITIONAL_SIGN",label:"Presionar para firmar condicionado a revisión posterior",intentTags:["medical","market","risk"],primaryMessage:"Intentas separar firma y certeza médica cuando las partes lo aceptan formalmente.",secondaryMessage:"La presión puede acelerar o hacer que el comprador abandone.",primaryEffects:[n("professional.contractPower",3),n("control.career",3)],secondaryEffects:[n("reputation.marketHeat",-2)],primarySeedTransitions:[seedCreate("SEED_MEDICAL_DISCLOSURE",68,{stance:"conditional_sign"})],secondarySeedTransitions:[seedCreate("SEED_MEDICAL_DISCLOSURE",72,{stance:"conditional_sign",deal_risk:true})]},
  {id:"WITHDRAW",label:"Retirarte si sientes que dudan demasiado de ti",intentTags:["medical","boundary"],primaryMessage:"Conviertes la confianza médica en una condición para seguir negociando.",secondaryMessage:"La decisión protege dignidad y puede ser una mala lectura de prudencia clínica legítima.",primaryEffects:[n("control.career",6)],secondaryEffects:[n("reputation.marketHeat",-3)],primarySeedTransitions:[seedCreate("SEED_MEDICAL_DISCLOSURE",58,{stance:"withdraw"})],secondarySeedTransitions:[seedCreate("SEED_MEDICAL_DISCLOSURE",64,{stance:"withdraw",possible_misread:true})]}
 ],seedsRead:["SEED_MEDICAL_DISCLOSURE"],seedsWrite:["SEED_MEDICAL_DISCLOSURE"],tags:["medical","transfer_exam","a5_ready_external_blocker"],canonStatus:"verified"
});

const EVT_22_TACT_001=ambiguousEvent({
 id:"EVT_22_TACT_001",ageWindow:[22,22],phase:"20_23",family:"tactical",title:"Noventa minutos que no te favorecen",
 body:"En un partido grande, el plan te asigna un trabajo útil que probablemente reduzca tus estadísticas. El rol y el partido deben ser hechos A4/coach, no una deducción de roleScore.",
 visible:["Conoces la tarea y su coste probable cuando la orden es real."],uncertain:["No sabes si mercado y selección valorarán esa labor ni si el plan funcionará."],weight:10,
 choices:[
  {id:"ACCEPT",label:"Aceptar sin discutir",intentTags:["tactical","team"],primaryMessage:"Priorizas la tarea del equipo sin reservar condiciones.",secondaryMessage:"Puedes volverte imprescindible y quedar etiquetado en un rol menos brillante.",primaryEffects:[n("professional.roleSecurity",4),n("professional.roleAdaptability",3)],secondaryEffects:[n("reputation.marketHeat",-2)],primarySeedTransitions:[seedCreate("SEED_TACTICAL_SACRIFICE",58,{stance:"accept"})],secondarySeedTransitions:[seedCreate("SEED_TACTICAL_SACRIFICE",64,{stance:"accept",market_cost:true})]},
  {id:"ATTACK_FREEDOM",label:"Aceptar y pedir una libertad ofensiva concreta",intentTags:["tactical","negotiate"],primaryMessage:"Intentas proteger una salida ofensiva dentro del plan colectivo.",secondaryMessage:"La petición puede mejorar la tarea o parecer negociación en vísperas del partido.",primaryEffects:[n("professional.roleAdaptability",4),n("control.career",3)],secondaryEffects:[n("professional.roleSecurity",-2)],primarySeedTransitions:[seedCreate("SEED_TACTICAL_SACRIFICE",60,{stance:"attack_freedom"})],secondarySeedTransitions:[seedCreate("SEED_TACTICAL_SACRIFICE",65,{stance:"attack_freedom",coach_cost:true})]},
  {id:"MORE_ON_BALL",label:"Decir que puedes ayudar más con balón",intentTags:["tactical","identity"],primaryMessage:"Discutes el encaje deportivo sin negar la necesidad del equipo.",secondaryMessage:"La observación puede mejorar el plan o parecer resistencia a una tarea incómoda.",primaryEffects:[n("control.career",4)],secondaryEffects:[n("professional.environmentStability",-2)],primarySeedTransitions:[seedCreate("SEED_TACTICAL_SACRIFICE",62,{stance:"more_ball"})],secondarySeedTransitions:[seedCreate("SEED_TACTICAL_SACRIFICE",67,{stance:"more_ball",resistance_read:true})]},
  {id:"SCOUT_CONTEXT",label:"Aceptar pero pedir al agente que prepare contexto para scouts",intentTags:["tactical","agent","market"],eligibility:[{path:"facts.activeAgentNpcId",op:"exists"}],primaryMessage:"Aceptas el rol y separas el relato de mercado de la decisión táctica.",secondaryMessage:"Contextualizar puede ser profesional o parecer obsesión por proteger estadísticas.",primaryEffects:[n("professional.agentControl",2),n("control.career",2)],secondaryEffects:[n("reputation.mediaHeat",2)],primarySeedTransitions:[seedCreate("SEED_TACTICAL_SACRIFICE",64,{stance:"scout_context"})],secondarySeedTransitions:[seedCreate("SEED_TACTICAL_SACRIFICE",69,{stance:"scout_context",image_read:true})]}
 ],seedsWrite:["SEED_TACTICAL_SACRIFICE"],tags:["tactical","big_match","a5_ready_external_blocker"],canonStatus:"verified"
});

export const A5_SHARED_EXTERNAL_OWNER_READY_PRINCIPALS: EventDefinition[]=[
 EVT_20_MED_001,EVT_20_AGT_001,EVT_20_MATCH_003,EVT_20_BRUNO_001,EVT_21_MONEY_001,EVT_21_AGT_001,EVT_21_NAT_001,EVT_21_MED_001,EVT_21_CCH_002,EVT_22_LOCK_001,EVT_22_HOME_001,EVT_22_MED_001,EVT_22_TACT_001
];
