/* Generated by scripts/generate-t51-offer-bridge-evidence.mjs. Do not hand-edit. */
import type { OfferDisposition } from "../simulation/offers.js";

export interface FrozenOfferBridgeEventEvidence {
  eventFingerprint: string;
  choiceActions: Readonly<Record<string, OfferDisposition>>;
}

export const FROZEN_OFFER_BRIDGE_SOURCES: Readonly<Record<string, Readonly<Record<string, FrozenOfferBridgeEventEvidence>>>> = {"1a8a5e2006fe7160f4fbc02060568d3abec99df038fe3a1a7799c8a0e802eac7":{},"2e07efd2ea99c4e9ec4c2b20ae89664204f76db2c55a72d567208799c01bccff":{},"303527efcc42c17e502257c3d7c613facafa10c8ed113810b64a1d7ebc6d0bb1":{},"5d3fd71a8df42ed5b93fdde63ed386e9d776693addd62a30293dbecad7aa56d2":{},"691401e78db356a03bf7bf13c7d2a2931d66431cc3108f22a8664f37d3afbdb8":{},"6a9c66ab3afaec76299662afb2a662e19203f8c6c430a87cc458b8608965a651":{},"6e552f606ace400d7b535747fbf7ba6078c60fd92889d4a360eb4db0bfb1013a":{},"84871fae2bec92d74d1e607e0a48943e2e530a062d315a829cfe75eda9fe0886":{},"88751a2107c035826162968991e3a1808b2f4573afa3a3a20a3efa376fa8af1f":{},"ce2f30ea24934787fb116627c727e4adf6c7bd05f8b8e79f415a20643e3fd58f":{},"de9ef2f501c015705a28d54afd140259356f15566d424511e6dbf67769c9bd19":{},"fee2ff875bac7979d3907f5ee1004ef736efa9a257237c6dee629dd8687fe136":{}};
