/* Generated by scripts/generate-t51-post-legacy-registry.mjs. Do not hand-edit. */
import type { LegacyEventEvidence } from "./pre-t51-legacy-registry.js";

export interface PostT51ContentEvidenceSource {
  contentIdentity: string;
  engineBuild: string;
  sessionVersions: readonly number[];
  events: Readonly<Record<string, LegacyEventEvidence>>;
}

export const POST_T51_CONTENT_SOURCES: Readonly<Record<string, PostT51ContentEvidenceSource>> = {};
