import { instantiateNpcStates, instantiateRelationships } from "../catalog/npcs.js";
import { makeRngStream } from "../core/rng.js";
import type { GameState } from "../core/types.js";

export function createInitialState(saveSeed = 20260910): GameState {
  return {
    schemaVersion: 8,
    ageMilestones: [],
    market: {version:1,sequence:0,pending:null,history:[]},
    date: "2026-07-01",
    age: 18,
    season: "2026-27",
    phase: "18_20",
    club: "UDV",
    tier: 3,
    role: "academy_callup",
    careerStateTags: [],
    contract: { monthsRemaining: 12, salaryMonthly: 900, releaseClause: null },
    professional: {
      ownerClub: "UDV", registrationClub: "UDV", leagueTier: 3, clubPrestigeTier: 1, clubPrestigeScore: 18,
      contractPower: 18, roleSecurity: 24, agentControl: 100, environmentStability: 72, moneyComfort: 8,
      lockerPower: 12, foreignAdaptation: 0, nationalHeat: 2, nationalStanding: 0, nationalCaps: 0, nationalRole: "none",
      continentalCred: 0, bodyLoad: 12, commercialPower: 2, publicPolarization: 0, institutionalTrust: 58, injuryMinutesImpact: 0,
      peakStatus: 8, institutionalPower: 8, trophyCapital: 0, publicMyth: 3, careerControl: 10, nationalPower: 0, recoveryMargin: 82, successionPressure: 0, roleAdaptability: 35, veteranLeverage: 8, statusInertia: 5, recoveryDebt: 4, matchSelectivity: 10, explosiveness: 82, matchEndurance: 78, recoveryBetweenMatches: 84, technique: 62, tacticalReading: 48, composure: 52, availability: 90, gameSpeedPerception: 70, retirementDistance: 0, motivationReserve: 88, legacyCapital: 2, homePull: 25, relocationTolerance: 80, initializedAt30: false, initializedAt26: false,
      leagueTierAt23: 3, clubPrestigeTierAt23: 1, roleScoreAt23: 18, route: "home", initializedAt20: false, initializedAt23: false
    },
    finances: { cash: 1200 },
    body: { risk: 18, fatigue: 12, fitness: 78, acuteInjury: false },
    selection: { level: "none" },
    reputation: { prestige: 8, mediaHeat: 3, marketHeat: 5 },
    control: { career: 8, agentDependency: 0 },
    sport: { roleScore: 18, minutesShare: 0, form: 50, positionIdentity: "winger", appearances: 0 },
    world: { udvCashGap: 1100000, clubPressure: 42, coachSecurity: 48, marketWindowOpen: false, ownerClub: "UDV", nextCyclePriority: null, udvSeasonResolved: false },
    personality: { reserve: 50, impulsivity: 50, ambition: 55, professionalism: 55 },
    relationships: instantiateRelationships(),
    npcs: instantiateNpcStates(),
    flags: {
      PRESEASON_FIRST_TEAM_CALL: true,
      PRESEASON_STARTED: false,
      NANO_CALLED_UP: false,
      WIN_AGENT: false,
      FIRST_TEAM_ATTENTION: false,
      OFFICIAL_DEBUT: false,
      FORMATION_532: true,
      VELA_BOARD_TENSION: true,
      BODY_WINDOW: false,
      BRUNO_SCOUTS: false,
      SET_PIECE_WINDOW: false,
      CLARA_CONTACTED: false,
      WIN_DEBUT: false,
      AGENT_ACTIVE: false,
      EARLY_BREAKOUT: false,
      JAN_NO_DEBUT: false,
      BRUNO_EXIT: false,
      VELA_SEPARATED: false,
      COACH_FIRED: false,
      UDV_RELEGATED: false,
      UDV_PLAYOFF: false,
      BIG_CLUB_INTEREST: false,
      AGENT_SECOND_DISCREPANCY: false,
      RECOVERING_INJURY: false,
      LONG_INJURY: false,
      FOREIGN_DEV_INTEREST: false,
      NIGHT_PHOTO: false,
      LOAN_ACTIVE: false,
      LOAN_RETURN: false,
      CONFLICT_EXIT: false,
      BIG_CLUB: false,
      ABROAD_ROUTE: false,
      ABROAD_STRONG: false,
      LOWER_REBUILD: false,
      PROFESSIONAL_ADAPTED: false,
      CONTRACT_DISPUTE: false,
      CLUB_RELATION_DAMAGED: false,
      MEDIA_PROFILE: false,
      NATIONAL_RADAR: false,
      FOREIGN_STABLE: false,
      ROLE_PROMISE_BROKEN: false,
      TEAMMATE_COVER_CONTEXT: false,
      DEADLINE_CONTEXT: false,
      CAPTAIN_ROOM_CONTEXT: false,
      ADULT_23_ADAPTED: false,
      NATIONAL_GATE_OPEN: false,
      NATIONAL_CALLED: false,
      NATIONAL_REGULAR: false,
      NATIONAL_TOURNAMENT_CYCLE: false,
      CONTINENTAL_CONTEXT: false,
      CONTINENTAL_REGISTERED: false,
      HIGH_PROFILE_MATCH: false,
      STAR_COMPETITION: false,
      SUPER_AGENT: false,
      CLUB_OWNER_CHANGE: false,
      PUBLIC_PROMISE: false,
      FINAL_CONTEXT: false,
      CAPTAINCY_WINDOW: false,
      FAMILY_BUSINESS_ACTIVE: false,
      PERSONAL_STAFF_ACTIVE: false,
      WEALTHY_EXIT_ACCEPTED: false,
      MATURE_30_ADAPTED: false, NATIONAL_RETIRED: false, EARLY_RETIRED_30_34: false, RICH_LEAGUE_ROUTE: false, TRANSATLANTIC_PROJECT: false, SPECIALIST_ROLE: false, ROLE_REINVENTED_30: false, CAPTAIN_MENTOR: false, HOME_RETURN_30: false, ROLLING_CONTRACT: false
    },
    seeds: [],
    history: [],
    microfeeds: [],
    eventCooldowns: {},
    familyLastSeen: {},
    narrativePressure: { origin: 20, friendship: 15, body: 10, market: 8 },
    runtime: { day: 0, seasonDay: 0, daysSinceNarrative: 999, eventsThisSeason: 0 },
    retirement: { status:"playing", decidedDate:null, announcedDate:null, closedDate:null, decisionAge:null, reason:null, reversals:0, noMarketWindows:0, daysInStatus:0, closureType:null },
    epilogue: { generated:false, families:[], milestones:[], summaryKey:null },
    rngState: {
      narrative: makeRngStream(saveSeed, 0xA11CE),
      football: makeRngStream(saveSeed, 0xF007BA11),
      microfeed: makeRngStream(saveSeed, 0xFEED2026),
      qa: makeRngStream(saveSeed, 0x0A51A51)
    }
  };
}
