import type { EventDefinition, SeedTransition } from "../../../core/types.js";
import { ambiguousEvent, n, seedCreate } from "../18_20/helpers.js";

const transformSeed=(seedId:string,payload:Record<string,string|number|boolean|null>):SeedTransition=>({seedId,action:"transform",payload});

const TEAM26=ambiguousEvent({
 id:"EVT_26_TEAM_001",ageWindow:[26,26],phase:"26_30",family:"team",title:"El joven carísimo",
 body:"El club ficha o promociona a un atacante joven con enorme inversión y discurso de futuro. En la presentación dice que ha crecido viéndote jugar.",
 visible:["Conoces su posición, el coste estimado, sus declaraciones y el plan inicial que el club te comunica."],
 uncertain:["No sabes si viene a aprender, competir ya o facilitar una futura venta tuya."],
 choices:[
  {id:"A",label:"Integrarlo activamente",intentTags:["successor","mentor"],primaryMessage:"Le ayudas a entrar en el grupo sabiendo que su progreso también puede aumentar tu competencia.",secondaryMessage:"La integración mejora el vestuario, pero acelera la adaptación de un rival real por minutos.",primaryEffects:[n("professional.institutionalPower",3),n("professional.successionPressure",2)],secondaryEffects:[n("professional.environmentStability",3),n("professional.successionPressure",4)],primarySeedTransitions:[seedCreate("SEED_YOUNG_SUCCESSOR",68,{stance:"integrate"})],secondarySeedTransitions:[seedCreate("SEED_YOUNG_SUCCESSOR",72,{stance:"integrate"})]},
  {id:"B",label:"Ser cordial sin convertirte en mentor",intentTags:["successor","boundaries"],primaryMessage:"Le tratas como a cualquier compañero sin asumir una responsabilidad especial sobre su desarrollo.",secondaryMessage:"El límite reduce dependencia personal, aunque el club no obtiene de ti el puente generacional que esperaba.",primaryEffects:[n("professional.environmentStability",2),n("professional.careerControl",2)],secondaryEffects:[n("professional.environmentStability",1),n("professional.successionPressure",2)],primarySeedTransitions:[seedCreate("SEED_YOUNG_SUCCESSOR",58,{stance:"cordial_boundary"})],secondarySeedTransitions:[seedCreate("SEED_YOUNG_SUCCESSOR",62,{stance:"cordial_boundary"})]},
  {id:"C",label:"Marcar jerarquía en entrenamientos",intentTags:["successor","hierarchy"],primaryMessage:"Compites de forma explícita para dejar claro que el sitio se gana en el campo.",secondaryMessage:"La intensidad puede proteger jerarquía o aislarte si el vestuario interpreta que el joven se ha convertido en una amenaza personal.",primaryEffects:[n("professional.successionPressure",-2),n("professional.publicPolarization",1)],secondaryEffects:[n("professional.successionPressure",3),n("professional.environmentStability",-2)],primarySeedTransitions:[seedCreate("SEED_YOUNG_SUCCESSOR",64,{stance:"mark_hierarchy"})],secondarySeedTransitions:[seedCreate("SEED_YOUNG_SUCCESSOR",70,{stance:"mark_hierarchy"})]},
  {id:"D",label:"Pedir al técnico claridad sobre reparto de minutos",intentTags:["successor","role_clarity"],primaryMessage:"Pides información sobre el plan de minutos sin exigir que el joven desaparezca de la rotación.",secondaryMessage:"Ganas claridad parcial, aunque ningún reparto previo puede blindar una jerarquía durante toda la temporada.",primaryEffects:[n("professional.careerControl",4),n("professional.roleSecurity",1)],secondaryEffects:[n("professional.careerControl",3),n("professional.roleSecurity",-1)],primarySeedTransitions:[seedCreate("SEED_YOUNG_SUCCESSOR",66,{stance:"ask_minutes"})],secondarySeedTransitions:[seedCreate("SEED_YOUNG_SUCCESSOR",62,{stance:"ask_minutes"})]}
 ],
 gates:[{path:"facts.youngSuccessorArrival",op:"eq",value:true}],weight:18,cooldown:99999,
 seedsRead:["SEED_YOUNG_MENTOR"],seedsWrite:["SEED_YOUNG_SUCCESSOR"],
 tags:["team","succession","a6_ready_external_blocker","needs_current_roster_successor_fact","t5_25"],canonStatus:"verified"
});

const NAT26=ambiguousEvent({
 id:"EVT_26_NAT_001",ageWindow:[26,26],phase:"26_30",family:"selection",title:"Club y selección quieren tu agosto",
 body:"Tras un verano internacional exigente, tu club pide vacaciones completas y regreso progresivo. La selección programa una concentración comercial y deportiva opcional para líderes del grupo.",
 visible:["Conoces el calendario, la recomendación médica y el carácter opcional de la concentración."],
 uncertain:["No sabes cuánto pesa asistir en futuras jerarquías ni cuánto margen físico perderías por acortar descanso."],
 choices:[
  {id:"A",label:"Priorizar vacaciones",intentTags:["national","recovery"],primaryMessage:"Priorizas recuperación y aceptas que otro jugador ocupe espacio durante la concentración.",secondaryMessage:"Ganas margen físico sin garantía de conservar exactamente la misma jerarquía internacional.",primaryEffects:[n("professional.recoveryMargin",6),n("professional.nationalPower",-1)],secondaryEffects:[n("professional.recoveryMargin",4),n("professional.nationalPower",-2)],primarySeedTransitions:[seedCreate("SEED_INTERNATIONAL_LOAD",68,{policy:"vacation_first"})],secondarySeedTransitions:[seedCreate("SEED_INTERNATIONAL_LOAD",72,{policy:"vacation_first"})]},
  {id:"B",label:"Ir a la concentración",intentTags:["national","presence"],primaryMessage:"Mantienes presencia con la selección a costa de reducir parte del descanso.",secondaryMessage:"La asistencia refuerza continuidad, pero la carga de verano llega antes al inicio de club.",primaryEffects:[n("professional.nationalPower",4),n("professional.recoveryMargin",-4)],secondaryEffects:[n("professional.nationalPower",3),n("professional.bodyLoad",4)],primarySeedTransitions:[seedCreate("SEED_INTERNATIONAL_LOAD",72,{policy:"attend_full"})],secondarySeedTransitions:[seedCreate("SEED_INTERNATIONAL_LOAD",76,{policy:"attend_full"})]},
  {id:"C",label:"Ir solo a actos sin entrenar",intentTags:["national","managed_presence"],primaryMessage:"Mantienes presencia institucional sin asumir la carga completa de entrenamiento.",secondaryMessage:"El compromiso intermedio protege parte del descanso, aunque no satisface del todo a ninguna de las dos agendas.",primaryEffects:[n("professional.nationalPower",2),n("professional.recoveryMargin",2)],secondaryEffects:[n("professional.nationalPower",1),n("professional.environmentStability",1)],primarySeedTransitions:[seedCreate("SEED_INTERNATIONAL_LOAD",70,{policy:"events_only"})],secondarySeedTransitions:[seedCreate("SEED_INTERNATIONAL_LOAD",68,{policy:"events_only"})]},
  {id:"D",label:"Pedir al seleccionador que te libere públicamente para evitar especulación",intentTags:["national","public_clarity"],primaryMessage:"Pides que la ausencia se explique como descanso acordado y no como ruptura con la selección.",secondaryMessage:"La aclaración puede proteger el relato o amplificar una decisión que habría pasado casi inadvertida.",primaryEffects:[n("professional.careerControl",3),n("reputation.mediaHeat",1),n("professional.recoveryMargin",4)],secondaryEffects:[n("professional.publicPolarization",2),n("professional.recoveryMargin",3)],primarySeedTransitions:[seedCreate("SEED_INTERNATIONAL_LOAD",70,{policy:"public_release"})],secondarySeedTransitions:[seedCreate("SEED_INTERNATIONAL_LOAD",74,{policy:"public_release"})]}
 ],
 gates:[{path:"facts.nationalLeadershipCampOffer",op:"eq",value:true}],weight:18,cooldown:99999,
 seedsRead:["SEED_CLUB_NATIONAL_CONFLICT"],seedsWrite:["SEED_INTERNATIONAL_LOAD"],
 tags:["selection","recovery","a6_ready_external_blocker","needs_national_optional_camp_fact","t5_25"],canonStatus:"verified"
});

const RICH28=ambiguousEvent({
 id:"EVT_28_RICH_001",ageWindow:[28,28],phase:"26_30",family:"money",title:"La oferta financieramente absurda",
 body:"Un destino con menor prestigio competitivo ofrece una cantidad que multiplica cualquier contrato anterior y condiciones familiares excepcionales.",
 visible:["Conoces dinero, duración, ciudad, competiciones y cláusulas del paquete."],
 uncertain:["No sabes cuánto afectará a selección, marca o posibilidad de volver al máximo nivel."],
 choices:[
  {id:"A",label:"Aceptar",intentTags:["wealth","accept"],primaryMessage:"Aceptas convertir una ventana de mercado en seguridad económica extraordinaria.",secondaryMessage:"El salto financiero es real; su coste deportivo dependerá del contexto posterior y no queda predeterminado.",primaryEffects:[n("professional.moneyComfort",12),n("professional.careerControl",-2)],secondaryEffects:[n("professional.moneyComfort",10),n("reputation.marketHeat",-3)],primarySeedTransitions:[transformSeed("SEED_WEALTHY_EXIT",{peak28:"accept"})],secondarySeedTransitions:[transformSeed("SEED_WEALTHY_EXIT",{peak28:"accept"})]},
  {id:"B",label:"Rechazar por nivel deportivo",intentTags:["wealth","sport_priority"],primaryMessage:"Rechazas una mejora económica excepcional para conservar el entorno competitivo actual.",secondaryMessage:"Proteges nivel deportivo sin garantía de volver a recibir una cifra equivalente.",primaryEffects:[n("professional.careerControl",4),n("professional.trophyCapital",1)],secondaryEffects:[n("professional.careerControl",3),n("professional.moneyComfort",-1)],primarySeedTransitions:[transformSeed("SEED_WEALTHY_EXIT",{peak28:"reject_sport"})],secondarySeedTransitions:[transformSeed("SEED_WEALTHY_EXIT",{peak28:"reject_sport"})]},
  {id:"C",label:"Pedir contrato corto",intentTags:["wealth","short_contract"],primaryMessage:"Intentas capturar parte del valor económico sin cerrar una vuelta futura al máximo nivel.",secondaryMessage:"La duración corta conserva salida, pero el destino puede retirar o rebajar el paquete.",primaryEffects:[n("professional.careerControl",5),n("professional.contractPower",2)],secondaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",-1)],primarySeedTransitions:[transformSeed("SEED_WEALTHY_EXIT",{peak28:"short_contract"})],secondarySeedTransitions:[transformSeed("SEED_WEALTHY_EXIT",{peak28:"short_contract"})]},
  {id:"D",label:"Usar la oferta para subir salario en Europa o entorno principal",intentTags:["wealth","leverage"],primaryMessage:"Usas la oferta como referencia de mercado sin afirmar que tu club actual deba igualarla.",secondaryMessage:"La palanca puede mejorar términos o tensar una negociación que no tiene por qué alcanzar esa cifra.",primaryEffects:[n("professional.contractPower",5),n("professional.careerControl",2)],secondaryEffects:[n("professional.contractPower",3),n("professional.institutionalTrust",-2)],primarySeedTransitions:[transformSeed("SEED_WEALTHY_EXIT",{peak28:"leverage"})],secondarySeedTransitions:[transformSeed("SEED_WEALTHY_EXIT",{peak28:"leverage"})]}
 ],
 gates:[{path:"facts.wealthyPeakExitOffer",op:"eq",value:true}],weight:18,cooldown:99999,
 seedsRead:["SEED_WEALTHY_EXIT"],seedsWrite:["SEED_WEALTHY_EXIT"],
 tags:["money","market","a6_ready_external_blocker","needs_rich_offer_terms","needs_seed_wealthy_peak_exit_origin","t5_25"],canonStatus:"verified"
});

const HOME28=ambiguousEvent({
 id:"EVT_28_HOME_001",ageWindow:[28,28],phase:"26_30",family:"family",title:"Volver con 28 no es retirarte",
 body:"UDV o un club de origen equivalente ha crecido y puede ofrecerte un proyecto competitivo real. La prensa vende el posible regreso como «volver antes de tiempo».",
 visible:["Conoces proyecto, salario asumible y rol propuesto."],
 uncertain:["No sabes si el club está preparado para convivir con tu estatus ni si el regreso congelará mercado internacional."],
 choices:[
  {id:"A",label:"Volver",intentTags:["home","return"],primaryMessage:"Tratas el regreso como una decisión competitiva y no como un epílogo.",secondaryMessage:"El vínculo con el origen aumenta también la presión de convertirte en solución institucional.",primaryEffects:[n("professional.homePull",6),n("professional.legacyCapital",4)],secondaryEffects:[n("professional.homePull",5),n("professional.publicPolarization",2)],primarySeedTransitions:[transformSeed("SEED_HOME_SYMBOL",{return28:"accept"})],secondarySeedTransitions:[transformSeed("SEED_HOME_SYMBOL",{return28:"accept"})]},
  {id:"B",label:"Mantener vínculo pero seguir fuera",intentTags:["home","stay_away"],primaryMessage:"Conservas la relación con el origen sin cerrar tu etapa competitiva actual.",secondaryMessage:"El vínculo sigue vivo, pero una ventana real de regreso puede no repetirse.",primaryEffects:[n("professional.homePull",2),n("professional.careerControl",3)],secondaryEffects:[n("professional.homePull",1),n("professional.environmentStability",1)],primarySeedTransitions:[transformSeed("SEED_HOME_SYMBOL",{return28:"stay_away"})],secondarySeedTransitions:[transformSeed("SEED_HOME_SYMBOL",{return28:"stay_away"})]},
  {id:"C",label:"Pedir un plan deportivo de dos años antes",intentTags:["home","project_proof"],primaryMessage:"Pides que el regreso se sostenga en un plan deportivo y no solo en tu nombre.",secondaryMessage:"La exigencia mejora información, pero obliga al club a prometer menos y concretar más.",primaryEffects:[n("professional.careerControl",5),n("professional.homePull",2)],secondaryEffects:[n("professional.careerControl",4),n("professional.institutionalTrust",-1)],primarySeedTransitions:[transformSeed("SEED_HOME_SYMBOL",{return28:"ask_two_year_plan"})],secondarySeedTransitions:[transformSeed("SEED_HOME_SYMBOL",{return28:"ask_two_year_plan"})]},
  {id:"D",label:"Acordar que se vuelva a hablar a los 30",intentTags:["home","defer"],primaryMessage:"Pospones la conversación sin tratar el regreso como una obligación futura.",secondaryMessage:"Conservas libertad hoy, pero el club, tu cuerpo y el mercado pueden ser distintos a los treinta.",primaryEffects:[n("professional.careerControl",4),n("professional.homePull",1)],secondaryEffects:[n("professional.careerControl",3),n("professional.homePull",-1)],primarySeedTransitions:[transformSeed("SEED_HOME_SYMBOL",{return28:"revisit_30"})],secondarySeedTransitions:[transformSeed("SEED_HOME_SYMBOL",{return28:"revisit_30"})]}
 ],
 gates:[{path:"facts.competitiveHomeReturnOffer",op:"eq",value:true}],weight:18,cooldown:99999,
 seedsRead:["SEED_HOME_SYMBOL","SEED_HOME_INSTITUTION"],seedsWrite:["SEED_HOME_SYMBOL"],
 tags:["home","return","a6_ready_external_blocker","needs_home_return_offer_authority","needs_seed_early_home_return_origin","t5_25"],canonStatus:"verified"
});

const CON29=ambiguousEvent({
 id:"EVT_29_CON_001",ageWindow:[29,29],phase:"26_30",family:"contract",title:"El último contrato máximo",
 body:"Tu entorno cree que quizá sea la última negociación en la que puedes exigir condiciones de pico. Hay tres paquetes: salario máximo y rol incierto; menos dinero y proyecto central; contrato corto con libertad.",
 visible:["Conoces los tres paquetes completos y sus condiciones formales."],
 uncertain:["No sabes cómo cambiará tu cuerpo ni si aparecerá un comprador equivalente a los 31."],
 choices:[
  {id:"A",label:"Maximizar dinero",intentTags:["contract","money"],primaryMessage:"Priorizas el mayor valor económico disponible ahora.",secondaryMessage:"La seguridad financiera aumenta mientras aceptas más incertidumbre sobre el rol.",primaryEffects:[n("professional.moneyComfort",6),n("professional.roleSecurity",-2)],secondaryEffects:[n("professional.moneyComfort",5),n("professional.careerControl",-2)],primarySeedTransitions:[transformSeed("SEED_CONTRACT_CEILING",{age29:"money"})],secondarySeedTransitions:[transformSeed("SEED_CONTRACT_CEILING",{age29:"money"})]},
  {id:"B",label:"Maximizar rol",intentTags:["contract","role"],primaryMessage:"Priorizas ser pieza central aunque el paquete económico sea menor.",secondaryMessage:"El proyecto promete centralidad, pero ninguna jerarquía deportiva queda garantizada para toda la duración.",primaryEffects:[n("professional.roleSecurity",5),n("professional.moneyComfort",-1)],secondaryEffects:[n("professional.roleSecurity",3),n("professional.careerControl",1)],primarySeedTransitions:[transformSeed("SEED_CONTRACT_CEILING",{age29:"role"})],secondarySeedTransitions:[transformSeed("SEED_CONTRACT_CEILING",{age29:"role"})]},
  {id:"C",label:"Maximizar libertad",intentTags:["contract","freedom"],primaryMessage:"Priorizas duración corta y capacidad de volver a decidir con treinta o treinta y uno.",secondaryMessage:"La libertad aumenta junto al riesgo de que el siguiente mercado llegue con menos poder.",primaryEffects:[n("professional.careerControl",6),n("professional.environmentStability",-1)],secondaryEffects:[n("professional.careerControl",4),n("professional.contractPower",-1)],primarySeedTransitions:[transformSeed("SEED_CONTRACT_CEILING",{age29:"freedom"})],secondarySeedTransitions:[transformSeed("SEED_CONTRACT_CEILING",{age29:"freedom"})]},
  {id:"D",label:"Reabrir negociación intentando un híbrido y arriesgar perder alguno",intentTags:["contract","hybrid"],primaryMessage:"Intentas combinar dinero, rol y libertad sin fingir que los tres paquetes pueden conservarse intactos.",secondaryMessage:"La renegociación puede mejorar el equilibrio o hacer que una de las alternativas deje de estar disponible.",primaryEffects:[n("professional.contractPower",5),n("professional.careerControl",3)],secondaryEffects:[n("professional.contractPower",2),n("professional.environmentStability",-2)],primarySeedTransitions:[transformSeed("SEED_CONTRACT_CEILING",{age29:"hybrid_attempt"})],secondarySeedTransitions:[transformSeed("SEED_CONTRACT_CEILING",{age29:"hybrid_attempt"})]}
 ],
 gates:[{path:"facts.age29PeakContractPackages",op:"eq",value:true}],weight:18,cooldown:99999,
 seedsRead:["SEED_AGE30_PRIORITY","SEED_CONTRACT_CEILING"],seedsWrite:["SEED_CONTRACT_CEILING"],
 tags:["contract","market","a6_ready_external_blocker","needs_age29_multi_package_authority","needs_seed_last_peak_contract_catalog","t5_25"],canonStatus:"verified"
});

export const T525_STAGED_PRINCIPAL_EVENTS:EventDefinition[]=[TEAM26,NAT26,RICH28,HOME28,CON29];
