import type { EventDefinition, SeedTransition } from "../../../core/types.js";
import { ambiguousEvent, n, seedCreate } from "../18_20/helpers.js";
const transformSeed=(seedId:string,payload:Record<string,string|number|boolean|null>):SeedTransition=>({seedId,action:"transform",payload});

const MKT26=ambiguousEvent({
 id:"EVT_26_MKT_001",ageWindow:[26,26],phase:"26_30",family:"market",title:"Campeón aquí, protagonista allí",
 body:"Un proyecto ligeramente inferior en prestigio te ofrece ser eje del ataque; quedarte mantiene acceso inmediato a todos los títulos pero no garantiza centralidad.",
 visible:["Conoces rol propuesto, salario, plantilla y ambición pública del destino."],
 uncertain:["No sabes si el proyecto tendrá paciencia si tarda en ganar ni si tu club actual reducirá competencia."],
 choices:[
  {id:"A",label:"Ir donde serás el centro",intentTags:["market","central_role"],primaryMessage:"Priorizas protagonismo y poder deportivo en el nuevo proyecto.",secondaryMessage:"El rol central aumenta responsabilidad sin garantizar que el proyecto alcance su techo.",primaryEffects:[n("professional.careerControl",5),n("professional.roleSecurity",4)],secondaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",-2)],primarySeedTransitions:[seedCreate("SEED_SHADOW_ESCAPE",70,{stance:"central_project"})],secondarySeedTransitions:[seedCreate("SEED_SHADOW_ESCAPE",74,{stance:"central_project"})]},
  {id:"B",label:"Quedarte donde competirás por todos los títulos",intentTags:["market","trophy_context"],primaryMessage:"Priorizas seguir en el contexto de mayor probabilidad inmediata de títulos.",secondaryMessage:"La continuidad protege el nivel competitivo, pero no elimina la competencia por jerarquía.",primaryEffects:[n("professional.trophyCapital",2),n("professional.environmentStability",3)],secondaryEffects:[n("professional.roleSecurity",-1),n("professional.environmentStability",2)],primarySeedTransitions:[seedCreate("SEED_SHADOW_ESCAPE",58,{stance:"stay_trophy_context"})],secondarySeedTransitions:[seedCreate("SEED_SHADOW_ESCAPE",62,{stance:"stay_trophy_context"})]},
  {id:"C",label:"Pedir una salida solo si el destino ficha dos refuerzos concretos",intentTags:["market","conditional_project"],primaryMessage:"Condicionas el salto a señales verificables de ambición del destino.",secondaryMessage:"La condición mejora información, pero los refuerzos pueden no llegar y la ventana puede cerrarse.",primaryEffects:[n("professional.careerControl",4),n("professional.contractPower",2)],secondaryEffects:[n("professional.careerControl",2),n("reputation.marketHeat",-1)],primarySeedTransitions:[seedCreate("SEED_SHADOW_ESCAPE",68,{stance:"conditional_reinforcements"})],secondarySeedTransitions:[seedCreate("SEED_SHADOW_ESCAPE",72,{stance:"conditional_reinforcements"})]},
  {id:"D",label:"Esperar al final de pretemporada",intentTags:["market","wait"],primaryMessage:"Compras información sobre jerarquías reales antes de comprometerte.",secondaryMessage:"La espera aclara parte del contexto y reduce el tiempo disponible para cerrar alternativas.",primaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",1)],secondaryEffects:[n("reputation.marketHeat",-2),n("professional.careerControl",2)],primarySeedTransitions:[seedCreate("SEED_SHADOW_ESCAPE",60,{stance:"wait_preseason"})],secondarySeedTransitions:[seedCreate("SEED_SHADOW_ESCAPE",64,{stance:"wait_preseason"})]}
 ],
 gates:[{path:"facts.centralProjectOffer",op:"eq",value:true}],weight:18,cooldown:99999,
 seedsRead:["SEED_ELITE_ROLE_BARGAIN"],seedsWrite:["SEED_SHADOW_ESCAPE"],
 tags:["market","role","a6_ready_external_blocker","needs_rich_role_offer_authority","needs_project_face_origin_alignment","t5_26"],canonStatus:"verified"
});

const CON26=ambiguousEvent({
 id:"EVT_26_CON_001",ageWindow:[26,26],phase:"26_30",family:"contract",title:"El contrato que te convierte en estructura",
 body:"Tu club ofrece el mayor contrato de tu carrera. A cambio quiere cinco años, control parcial de imagen y una cláusula que prácticamente elimina una salida sencilla.",
 visible:["Conoces salario, prima, duración, derechos de imagen y cláusula."],
 uncertain:["No sabes cómo cambiarán entrenador, cuerpo y mercado durante cinco años."],
 choices:[
  {id:"A",label:"Firmar y convertirte en pieza estructural",intentTags:["contract","structure"],primaryMessage:"Aceptas seguridad máxima y una relación institucional de largo plazo.",secondaryMessage:"El contrato te da peso interno y también hace mucho más costosa una salida si cambia el ciclo.",primaryEffects:[n("professional.institutionalPower",5),n("professional.environmentStability",5),n("professional.careerControl",-3)],secondaryEffects:[n("professional.institutionalPower",4),n("professional.careerControl",-4)],primarySeedTransitions:[seedCreate("SEED_PEAK_CONTRACT",76,{stance:"five_year_structure"})],secondarySeedTransitions:[seedCreate("SEED_PEAK_CONTRACT",80,{stance:"five_year_structure"})]},
  {id:"B",label:"Pedir tres años y menos dinero",intentTags:["contract","shorter"],primaryMessage:"Cambias parte del salario por un horizonte contractual más corto.",secondaryMessage:"Ganas una salida temporal más cercana y renuncias a parte de la seguridad del paquete inicial.",primaryEffects:[n("professional.careerControl",5),n("professional.moneyComfort",-1)],secondaryEffects:[n("professional.careerControl",4),n("professional.contractPower",-1)],primarySeedTransitions:[seedCreate("SEED_PEAK_CONTRACT",68,{stance:"three_year_lower_money"})],secondarySeedTransitions:[seedCreate("SEED_PEAK_CONTRACT",72,{stance:"three_year_lower_money"})]},
  {id:"C",label:"Mantener cinco años pero exigir salida por objetivos o minutos",intentTags:["contract","exit_protection"],primaryMessage:"Aceptas la duración si existe una salida verificable ligada a objetivos o participación.",secondaryMessage:"La protección reduce el encierro contractual, aunque su valor dependerá de cómo se definan y cumplan los criterios.",primaryEffects:[n("professional.careerControl",5),n("professional.contractPower",4)],secondaryEffects:[n("professional.careerControl",3),n("professional.institutionalTrust",-1)],primarySeedTransitions:[seedCreate("SEED_PEAK_CONTRACT",74,{stance:"five_year_exit_protection"})],secondarySeedTransitions:[seedCreate("SEED_PEAK_CONTRACT",78,{stance:"five_year_exit_protection"})]},
  {id:"D",label:"Rechazar y entrar en temporada con contrato más corto",intentTags:["contract","reject"],primaryMessage:"Mantienes libertad futura y aceptas que cuerpo y mercado asumirán parte del riesgo.",secondaryMessage:"La decisión conserva opcionalidad, pero una lesión o bajada de mercado puede debilitar la siguiente negociación.",primaryEffects:[n("professional.careerControl",6),n("professional.environmentStability",-2)],secondaryEffects:[n("professional.contractPower",-2),n("professional.careerControl",4)],primarySeedTransitions:[seedCreate("SEED_PEAK_CONTRACT",64,{stance:"reject_long_structure"})],secondarySeedTransitions:[seedCreate("SEED_PEAK_CONTRACT",68,{stance:"reject_long_structure"})]}
 ],
 gates:[{path:"facts.peakStructureContractOffer",op:"eq",value:true}],weight:18,cooldown:99999,
 seedsRead:["SEED_CONTRACT_CEILING","SEED_IMAGE_RIGHTS"],seedsWrite:["SEED_PEAK_CONTRACT"],
 tags:["contract","image_rights","a6_ready_external_blocker","needs_rich_contract_terms","t5_26"],canonStatus:"verified"
});

const IMG26=ambiguousEvent({
 id:"EVT_26_IMG_001",ageWindow:[26,26],phase:"26_30",family:"image",title:"La cara del proyecto",
 body:"El club y una marca quieren presentarte como imagen principal de la temporada. El acuerdo incluye entrevistas, eventos y una campaña que asume que seguirás varios años.",
 visible:["Conoces calendario comercial, pago y mensajes de campaña."],
 uncertain:["No sabes si una crisis deportiva hará que el club deje de protegerte ni si aparecerá una oferta irresistible."],
 choices:[
  {id:"A",label:"Aceptar el paquete completo",intentTags:["image","project_face"],primaryMessage:"Aceptas ser centro deportivo y comercial del proyecto durante la campaña.",secondaryMessage:"La exposición eleva poder y también concentra responsabilidad si el proyecto se tuerce.",primaryEffects:[n("professional.publicMyth",6),n("professional.commercialPower",6),n("professional.publicPolarization",2)],secondaryEffects:[n("professional.publicMyth",5),n("professional.publicPolarization",4)],primarySeedTransitions:[seedCreate("SEED_GLOBAL_IMAGE",74,{stance:"full_package"})],secondarySeedTransitions:[seedCreate("SEED_GLOBAL_IMAGE",78,{stance:"full_package"})]},
  {id:"B",label:"Aceptar solo marca, no campaña de club",intentTags:["image","brand_only"],primaryMessage:"Separar marca y club reduce cuánto depende tu imagen de un ciclo institucional.",secondaryMessage:"Mantienes valor comercial, aunque renuncias a parte del poder que el club ofrecía alrededor de tu figura.",primaryEffects:[n("professional.commercialPower",5),n("professional.careerControl",3)],secondaryEffects:[n("professional.commercialPower",4),n("professional.institutionalPower",-1)],primarySeedTransitions:[seedCreate("SEED_GLOBAL_IMAGE",68,{stance:"brand_only"})],secondarySeedTransitions:[seedCreate("SEED_GLOBAL_IMAGE",72,{stance:"brand_only"})]},
  {id:"C",label:"Reducir compromisos para proteger descanso",intentTags:["image","load_protection"],primaryMessage:"Aceptas exposición limitada y reservas más ventanas para descanso y recuperación.",secondaryMessage:"Proteges carga a costa de una campaña menos intensa y de menor centralidad comercial.",primaryEffects:[n("professional.recoveryMargin",4),n("professional.commercialPower",2)],secondaryEffects:[n("professional.recoveryMargin",3),n("professional.commercialPower",1)],primarySeedTransitions:[seedCreate("SEED_GLOBAL_IMAGE",64,{stance:"reduced_commitments"})],secondarySeedTransitions:[seedCreate("SEED_GLOBAL_IMAGE",68,{stance:"reduced_commitments"})]},
  {id:"D",label:"Rechazar y mantener perfil bajo",intentTags:["image","decline"],primaryMessage:"Renuncias a convertir la temporada en una campaña alrededor de tu figura.",secondaryMessage:"Proteges foco y libertad narrativa, pero el club puede desplazar inversión de imagen hacia otra estrella.",primaryEffects:[n("professional.careerControl",4),n("professional.commercialPower",-2)],secondaryEffects:[n("professional.careerControl",3),n("professional.publicMyth",-1)],primarySeedTransitions:[seedCreate("SEED_GLOBAL_IMAGE",56,{stance:"decline"})],secondarySeedTransitions:[seedCreate("SEED_GLOBAL_IMAGE",60,{stance:"decline"})]}
 ],
 gates:[{path:"facts.projectFaceCommercialPackage",op:"eq",value:true}],weight:18,cooldown:99999,
 seedsRead:["SEED_SPONSOR_IMAGE","SEED_PROJECT_FACE"],seedsWrite:["SEED_GLOBAL_IMAGE"],
 tags:["image","project_face","a6_ready_external_blocker","needs_joint_club_brand_package","t5_26"],canonStatus:"verified"
});

const BODY26=ambiguousEvent({
 id:"EVT_26_BODY_001",ageWindow:[26,26],phase:"26_30",family:"medical",title:"Tu cuerpo como proyecto",
 body:"Tu entorno propone contratar nutricionista, preparador y fisio propios que viajen contigo. El club acepta colaborar, pero quiere que toda decisión médica pase por su staff.",
 visible:["Conoces coste, perfiles profesionales y reglas del club."],
 uncertain:["No sabes si duplicar equipos mejorará decisiones o creará dos autoridades en conflicto."],
 choices:[
  {id:"A",label:"Crear equipo privado completo",intentTags:["body","private_staff"],primaryMessage:"Construyes una estructura propia de rendimiento alrededor de tu carrera.",secondaryMessage:"La personalización aumenta y también la necesidad de coordinar dos equipos con autoridad médica distinta.",primaryEffects:[n("professional.recoveryMargin",5),n("professional.careerControl",4),n("professional.moneyComfort",-3)],secondaryEffects:[n("professional.recoveryMargin",3),n("professional.institutionalTrust",-2)],primarySeedTransitions:[seedCreate("SEED_SELF_OPTIMIZATION",74,{structure:"full_private_team"})],secondarySeedTransitions:[seedCreate("SEED_SELF_OPTIMIZATION",78,{structure:"full_private_team"})]},
  {id:"B",label:"Usar solo especialistas externos puntualmente",intentTags:["body","specialists"],primaryMessage:"Añades segundas opiniones concretas sin crear una estructura paralela permanente.",secondaryMessage:"La solución reduce solapamiento, aunque ofrece menos continuidad al seguimiento individual.",primaryEffects:[n("professional.recoveryMargin",3),n("professional.careerControl",2)],secondaryEffects:[n("professional.recoveryMargin",2),n("professional.environmentStability",1)],primarySeedTransitions:[seedCreate("SEED_SELF_OPTIMIZATION",64,{structure:"occasional_specialists"})],secondarySeedTransitions:[seedCreate("SEED_SELF_OPTIMIZATION",68,{structure:"occasional_specialists"})]},
  {id:"C",label:"Confiar exclusivamente en el club",intentTags:["body","club_staff"],primaryMessage:"Mantienes una única cadena de decisión médica y de rendimiento.",secondaryMessage:"La coordinación es simple, aunque renuncias a parte de la personalización y control que tu entorno proponía.",primaryEffects:[n("professional.institutionalTrust",4),n("professional.environmentStability",2)],secondaryEffects:[n("professional.institutionalTrust",3),n("professional.careerControl",-1)],primarySeedTransitions:[seedCreate("SEED_SELF_OPTIMIZATION",54,{structure:"club_only"})],secondarySeedTransitions:[seedCreate("SEED_SELF_OPTIMIZATION",58,{structure:"club_only"})]},
  {id:"D",label:"Contratar equipo propio pero compartir todos los datos",intentTags:["body","shared_data"],primaryMessage:"Creas apoyo propio y obligas a que club y especialistas trabajen con la misma información.",secondaryMessage:"La transparencia reduce algunos choques, aunque no elimina desacuerdos profesionales.",primaryEffects:[n("professional.recoveryMargin",4),n("professional.institutionalTrust",3),n("professional.careerControl",3)],secondaryEffects:[n("professional.recoveryMargin",3),n("professional.environmentStability",1)],primarySeedTransitions:[seedCreate("SEED_SELF_OPTIMIZATION",72,{structure:"private_shared_data"})],secondarySeedTransitions:[seedCreate("SEED_SELF_OPTIMIZATION",76,{structure:"private_shared_data"})]}
 ],
 gates:[{path:"facts.privatePerformanceStaffProposal",op:"eq",value:true}],weight:18,cooldown:99999,
 seedsRead:["SEED_CHRONIC_BODY","SEED_LOAD_MANAGEMENT","SEED_PERSONAL_STAFF"],seedsWrite:["SEED_SELF_OPTIMIZATION"],
 tags:["medical","staff","a6_ready_external_blocker","needs_private_staff_proposal_fact","t5_26"],canonStatus:"verified"
});

const AGT26=ambiguousEvent({
 id:"EVT_26_AGT_001",ageWindow:[26,26],phase:"26_30",family:"agent",title:"La oferta que tu agente no quiere",
 body:"Un club presenta una propuesta deportiva atractiva pero con comisión de intermediación baja y poco negocio para tu agencia. Tu agente la describe como «paso lateral».",
 visible:["Conoces la oferta, el rol, el salario y los comentarios de tu agente."],
 uncertain:["No sabes cuánto pesa la comisión en su opinión ni si existen ofertas mejores aún no formales."],
 choices:[
  {id:"A",label:"Seguir recomendación del agente",intentTags:["agent","trust"],primaryMessage:"Aceptas que su lectura deportiva pesa más que el conflicto potencial de incentivos.",secondaryMessage:"La recomendación puede ser correcta aunque exista un incentivo económico distinto.",primaryEffects:[n("professional.agentControl",-2),n("professional.environmentStability",2)],secondaryEffects:[n("professional.agentControl",-3),n("professional.careerControl",-1)],primarySeedTransitions:[transformSeed("SEED_AGENT_PROOF",{peak26:"follow_agent"})],secondarySeedTransitions:[transformSeed("SEED_AGENT_PROOF",{peak26:"follow_agent"})]},
  {id:"B",label:"Pedir valoración a asesor independiente",intentTags:["agent","second_opinion"],primaryMessage:"Buscas una lectura adicional sin declarar que tu agente está mintiendo.",secondaryMessage:"La segunda opinión añade información y también una voz que puede carecer del contexto completo.",primaryEffects:[n("professional.careerControl",4),n("professional.agentControl",2)],secondaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",-1)],primarySeedTransitions:[transformSeed("SEED_AGENT_PROOF",{peak26:"independent_review"})],secondarySeedTransitions:[transformSeed("SEED_AGENT_PROOF",{peak26:"independent_review"})]},
  {id:"C",label:"Hablar directamente con el club",intentTags:["agent","direct_contact"],primaryMessage:"Contrastas el proyecto directamente sin convertir el contacto en una aceptación de la oferta.",secondaryMessage:"Ganas información y tensionas el monopolio informativo de tu agencia.",primaryEffects:[n("professional.careerControl",5),n("professional.agentControl",3)],secondaryEffects:[n("professional.careerControl",4),n("professional.environmentStability",-1)],primarySeedTransitions:[transformSeed("SEED_DIRECT_RECRUIT",{peak26:"direct_club_check"})],secondarySeedTransitions:[transformSeed("SEED_DIRECT_RECRUIT",{peak26:"direct_club_check"})]},
  {id:"D",label:"Exigir a tu agencia que detalle conflictos económicos",intentTags:["agent","conflict_disclosure"],primaryMessage:"Pides separar el análisis deportivo de comisiones e incentivos de representación.",secondaryMessage:"La transparencia puede mejorar gobernanza o enfriar una relación que funcionaba por confianza implícita.",primaryEffects:[n("professional.careerControl",5),n("professional.agentControl",4)],secondaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",-2)],primarySeedTransitions:[transformSeed("SEED_AGENT_PROOF",{peak26:"conflict_disclosure"})],secondarySeedTransitions:[transformSeed("SEED_AGENT_PROOF",{peak26:"conflict_disclosure"})]}
 ],
 gates:[{path:"facts.agentConflictOffer",op:"eq",value:true}],weight:18,cooldown:99999,
 seedsRead:["SEED_AGENT_PROOF","SEED_DIRECT_RECRUIT"],seedsWrite:["SEED_AGENT_PROOF","SEED_DIRECT_RECRUIT"],
 tags:["agent","conflict","a6_ready_external_blocker","needs_offer_commission_and_role_terms","needs_seed_agent_conflict_peak_origin","t5_26"],canonStatus:"verified"
});

export const T526_STAGED_PRINCIPAL_EVENTS:EventDefinition[]=[MKT26,CON26,IMG26,BODY26,AGT26];
