import type { EventDefinition, SeedTransition } from "../../../core/types.js";
import { ambiguousEvent, n } from "../18_20/helpers.js";
const transformSeed=(seedId:string,payload:Record<string,string|number|boolean|null>):SeedTransition=>({seedId,action:"transform",payload});

const MKT27=ambiguousEvent({
 id:"EVT_27_MKT_001",ageWindow:[27,27],phase:"26_30",family:"market",title:"Quieren construir alrededor de ti",
 body:"Otro club te ofrece ser la cara deportiva de un proyecto nuevo: voz sobre perfiles de fichajes, dorsal, marketing y salario. No es necesariamente el club con más títulos probables.",
 visible:["Conoces propuesta, entrenador, presupuesto y rol."],uncertain:["No sabes si el propietario mantendrá gasto ni si la voz prometida tendrá poder real."],
 choices:[
  {id:"A",label:"Aceptar el proyecto",intentTags:["project","accept"],primaryMessage:"Aceptas ser el centro nominal del nuevo proyecto.",secondaryMessage:"La centralidad aumenta influencia y también exposición al éxito o fracaso del proyecto.",primaryEffects:[n("professional.institutionalPower",5),n("professional.careerControl",3)],secondaryEffects:[n("professional.institutionalPower",3),n("professional.environmentStability",-2)],primarySeedTransitions:[transformSeed("SEED_PROJECT_FACE",{age27:"accept_project"})],secondarySeedTransitions:[transformSeed("SEED_PROJECT_FACE",{age27:"accept_project"})]},
  {id:"B",label:"Quedarte en estructura más estable",intentTags:["project","stay"],primaryMessage:"Priorizas la estabilidad competitiva del entorno conocido.",secondaryMessage:"Conservas estructura y renuncias a parte del poder nominal de la alternativa.",primaryEffects:[n("professional.environmentStability",4),n("professional.institutionalPower",1)],secondaryEffects:[n("professional.environmentStability",3),n("professional.careerControl",-1)],primarySeedTransitions:[transformSeed("SEED_PROJECT_FACE",{age27:"stay_stable"})],secondarySeedTransitions:[transformSeed("SEED_PROJECT_FACE",{age27:"stay_stable"})]},
  {id:"C",label:"Exigir dos condiciones deportivas por escrito como objetivos del club",intentTags:["project","conditions"],primaryMessage:"Intentas convertir promesas de proyecto en objetivos verificables.",secondaryMessage:"Las condiciones mejoran trazabilidad, pero siguen siendo objetivos de club y no garantías de resultado.",primaryEffects:[n("professional.careerControl",5),n("professional.contractPower",3)],secondaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",-1)],primarySeedTransitions:[transformSeed("SEED_PROJECT_FACE",{age27:"written_objectives"})],secondarySeedTransitions:[transformSeed("SEED_PROJECT_FACE",{age27:"written_objectives"})]},
  {id:"D",label:"Usar la oferta para renovar",intentTags:["project","leverage"],primaryMessage:"Usas la alternativa como palanca sin tratarla como un traslado ya decidido.",secondaryMessage:"La palanca puede mejorar condiciones o endurecer la posición de tu club actual.",primaryEffects:[n("professional.contractPower",5),n("professional.careerControl",2)],secondaryEffects:[n("professional.contractPower",3),n("professional.institutionalTrust",-2)],primarySeedTransitions:[transformSeed("SEED_PROJECT_FACE",{age27:"renewal_leverage"})],secondarySeedTransitions:[transformSeed("SEED_PROJECT_FACE",{age27:"renewal_leverage"})]}
 ],gates:[{path:"facts.projectBuildOffer",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_PROJECT_FACE"],seedsWrite:["SEED_PROJECT_FACE"],
 tags:["market","project","a6_ready_external_blocker","needs_project_budget_role_offer","needs_seed_mega_transfer_origin","t5_27"],canonStatus:"verified"
});

const AWARD27=ambiguousEvent({
 id:"EVT_27_AWARD_001",ageWindow:[27,27],phase:"26_30",family:"press",title:"La gala",
 body:"Estás nominado a un gran premio individual junto a un compañero o rival. Días antes te piden entrevista y el periodista insiste en comparar méritos.",
 visible:["Conoces nominados, logros públicos y preguntas."],uncertain:["No sabes la votación ni cómo el vestuario interpreta una campaña individual."],
 choices:[
  {id:"A",label:"Defender abiertamente tu candidatura",intentTags:["award","ambition"],primaryMessage:"Defiendes tus méritos sin afirmar que la votación ya te pertenece.",secondaryMessage:"La ambición queda clara y también aumenta la comparación pública.",primaryEffects:[n("professional.publicMyth",3),n("professional.publicPolarization",2)],secondaryEffects:[n("reputation.mediaHeat",3),n("professional.publicPolarization",3)],primarySeedTransitions:[transformSeed("SEED_RECORD_CHASE",{award27:"defend"})],secondarySeedTransitions:[transformSeed("SEED_RECORD_CHASE",{award27:"defend"})]},
  {id:"B",label:"Priorizar mérito del equipo",intentTags:["award","team"],primaryMessage:"Centras la entrevista en el rendimiento colectivo sin fingir que el premio no te importa.",secondaryMessage:"Reduces fricción interna, aunque cedes parte del espacio narrativo individual.",primaryEffects:[n("professional.environmentStability",3),n("professional.publicMyth",1)],secondaryEffects:[n("professional.environmentStability",2),n("reputation.mediaHeat",-1)],primarySeedTransitions:[transformSeed("SEED_RECORD_CHASE",{award27:"team_first"})],secondarySeedTransitions:[transformSeed("SEED_RECORD_CHASE",{award27:"team_first"})]},
  {id:"C",label:"Elogiar al compañero y señalar tus números",intentTags:["award","balanced"],primaryMessage:"Reconoces al otro candidato y explicas por qué tus números también sostienen una candidatura seria.",secondaryMessage:"El equilibrio evita una falsa modestia y mantiene viva la comparación.",primaryEffects:[n("professional.publicMyth",2),n("professional.careerControl",2)],secondaryEffects:[n("reputation.mediaHeat",2),n("professional.publicPolarization",1)],primarySeedTransitions:[transformSeed("SEED_RECORD_CHASE",{award27:"balanced_case"})],secondarySeedTransitions:[transformSeed("SEED_RECORD_CHASE",{award27:"balanced_case"})]},
  {id:"D",label:"Rechazar entrevista",intentTags:["award","decline_media"],primaryMessage:"Evitas participar en la campaña previa y dejas que la votación siga sin tu intervención.",secondaryMessage:"La ausencia reduce tus palabras disponibles, no la comparación que otros medios seguirán haciendo.",primaryEffects:[n("professional.careerControl",3),n("reputation.mediaHeat",-1)],secondaryEffects:[n("professional.careerControl",2),n("professional.publicMyth",-1)],primarySeedTransitions:[transformSeed("SEED_RECORD_CHASE",{award27:"decline_interview"})],secondarySeedTransitions:[transformSeed("SEED_RECORD_CHASE",{award27:"decline_interview"})]}
 ],gates:[{path:"facts.globalAwardNomination",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_RECORD_CHASE"],seedsWrite:["SEED_RECORD_CHASE"],
 tags:["award","press","a6_ready_external_blocker","needs_award_nomination_fact","needs_seed_global_award_origin","t5_27"],canonStatus:"verified"
});

const MED27=ambiguousEvent({
 id:"EVT_27_MED_001",ageWindow:[27,27],phase:"26_30",family:"medical",title:"La cirugía puede esperar",
 body:"Una dolencia persistente tiene dos caminos: cirugía con varios meses de baja o tratamiento conservador que permite seguir pero no elimina el problema.",
 visible:["Conoces informes, plazos y probabilidades cualitativas."],uncertain:["No sabes si el tratamiento conservador aguantará ni si la cirugía devolverá nivel completo."],
 choices:[
  {id:"A",label:"Operarte ya",intentTags:["medical","surgery_now"],primaryMessage:"Aceptas la baja prevista para tratar el problema de forma definitiva ahora.",secondaryMessage:"La cirugía elimina parte de la incertidumbre diagnóstica y abre otra sobre recuperación y nivel posterior.",primaryEffects:[n("professional.recoveryMargin",5),n("professional.roleSecurity",-3)],secondaryEffects:[n("professional.recoveryMargin",3),n("professional.environmentStability",-2)],primarySeedTransitions:[transformSeed("SEED_CHRONIC_BODY",{surgery27:"now"})],secondarySeedTransitions:[transformSeed("SEED_CHRONIC_BODY",{surgery27:"now"})]},
  {id:"B",label:"Aguantar hasta final de temporada",intentTags:["medical","delay"],primaryMessage:"Aplazas la cirugía para mantener disponibilidad competitiva mientras el cuadro siga siendo compatible.",secondaryMessage:"Conservas la temporada y mantienes abierto el riesgo de que la dolencia limite más de lo previsto.",primaryEffects:[n("professional.roleSecurity",2),n("professional.recoveryMargin",-2)],secondaryEffects:[n("professional.bodyLoad",3),n("professional.recoveryMargin",-3)],primarySeedTransitions:[transformSeed("SEED_CHRONIC_BODY",{surgery27:"end_season"})],secondarySeedTransitions:[transformSeed("SEED_CHRONIC_BODY",{surgery27:"end_season"})]},
  {id:"C",label:"Tratar conservador y reevaluar cada mes",intentTags:["medical","conservative"],primaryMessage:"Mantienes un tratamiento conservador con puntos de reevaluación definidos.",secondaryMessage:"La estrategia conserva flexibilidad, pero cada mes puede cambiar el equilibrio entre competir y operar.",primaryEffects:[n("professional.careerControl",3),n("professional.recoveryMargin",1)],secondaryEffects:[n("professional.careerControl",2),n("professional.bodyLoad",1)],primarySeedTransitions:[transformSeed("SEED_CHRONIC_BODY",{surgery27:"monthly_review"})],secondarySeedTransitions:[transformSeed("SEED_CHRONIC_BODY",{surgery27:"monthly_review"})]},
  {id:"D",label:"Buscar especialista externo antes de decidir",intentTags:["medical","second_opinion"],primaryMessage:"Añades una segunda opinión antes de escoger calendario de tratamiento.",secondaryMessage:"Ganas información adicional sin garantía de que los especialistas coincidan.",primaryEffects:[n("professional.careerControl",4),n("professional.recoveryMargin",1)],secondaryEffects:[n("professional.environmentStability",-1),n("professional.careerControl",3)],primarySeedTransitions:[transformSeed("SEED_CHRONIC_BODY",{surgery27:"external_specialist"})],secondarySeedTransitions:[transformSeed("SEED_CHRONIC_BODY",{surgery27:"external_specialist"})]}
 ],gates:[{path:"facts.surgeryCompatibleDiagnosis",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_CHRONIC_BODY","SEED_BIG_MATCH_BODY"],seedsWrite:["SEED_CHRONIC_BODY"],
 tags:["medical","surgery","a6_ready_external_blocker","needs_surgical_diagnosis_fact","needs_seed_surgery_timing_origin","t5_27"],canonStatus:"verified"
});

const STAR27=ambiguousEvent({
 id:"EVT_27_STAR_001",ageWindow:[27,27],phase:"26_30",family:"team",title:"Dos estrellas, un foco",
 body:"Tu club ficha o ya tiene otra superestrella con contrato e imagen similares. Marketing propone campañas conjuntas, pero dentro del campo ambos queréis responsabilidades centrales.",
 visible:["Conoces roles declarados y propuesta comercial."],uncertain:["No sabes si el técnico equilibrará jerarquías ni cómo reaccionará la afición a la comparación."],
 choices:[
  {id:"A",label:"Abrazar la dupla públicamente",intentTags:["star","duo"],primaryMessage:"Presentas la convivencia como una fortaleza del proyecto.",secondaryMessage:"La narrativa compartida puede multiplicar exposición y también convertir cada desacuerdo en noticia.",primaryEffects:[n("professional.publicMyth",3),n("professional.environmentStability",2)],secondaryEffects:[n("professional.publicPolarization",2),n("reputation.mediaHeat",2)],primarySeedTransitions:[transformSeed("SEED_PENALTY_HIERARCHY",{secondStar27:"public_duo"})],secondarySeedTransitions:[transformSeed("SEED_PENALTY_HIERARCHY",{secondStar27:"public_duo"})]},
  {id:"B",label:"Separar marca y competir solo en campo",intentTags:["star","separate_brand"],primaryMessage:"Evitas fabricar una dupla comercial y dejas la competencia principal dentro del fútbol.",secondaryMessage:"La frontera reduce exposición conjunta, aunque no elimina comparaciones de jerarquía.",primaryEffects:[n("professional.careerControl",4),n("professional.environmentStability",1)],secondaryEffects:[n("professional.careerControl",3),n("professional.publicMyth",-1)],primarySeedTransitions:[transformSeed("SEED_PENALTY_HIERARCHY",{secondStar27:"separate_brand"})],secondarySeedTransitions:[transformSeed("SEED_PENALTY_HIERARCHY",{secondStar27:"separate_brand"})]},
  {id:"C",label:"Pedir reparto claro de penaltis y balón parado",intentTags:["star","set_piece_rules"],primaryMessage:"Pides reglas deportivas explícitas donde la ambigüedad puede generar conflictos repetidos.",secondaryMessage:"La regla reduce una fuente concreta de fricción, no la competencia global por protagonismo.",primaryEffects:[n("professional.careerControl",4),n("professional.environmentStability",2)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.environmentStability",1)],primarySeedTransitions:[transformSeed("SEED_PENALTY_HIERARCHY",{secondStar27:"set_piece_rules"})],secondarySeedTransitions:[transformSeed("SEED_PENALTY_HIERARCHY",{secondStar27:"set_piece_rules"})]},
  {id:"D",label:"No discutir jerarquía y dejar que rendimiento decida",intentTags:["star","performance"],primaryMessage:"Rechazas pactar una jerarquía previa y aceptas competir por responsabilidades.",secondaryMessage:"La decisión preserva meritocracia aparente y deja más conflictos para ser resueltos caso a caso.",primaryEffects:[n("professional.careerControl",2),n("professional.environmentStability",1)],secondaryEffects:[n("professional.successionPressure",2),n("professional.publicPolarization",1)],primarySeedTransitions:[transformSeed("SEED_PENALTY_HIERARCHY",{secondStar27:"performance_decides"})],secondarySeedTransitions:[transformSeed("SEED_PENALTY_HIERARCHY",{secondStar27:"performance_decides"})]}
 ],gates:[{path:"facts.currentClubSecondStar",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_PROJECT_FACE","SEED_STAR_COMPETITION","SEED_PENALTY_HIERARCHY"],seedsWrite:["SEED_PENALTY_HIERARCHY"],
 tags:["team","star","a6_ready_external_blocker","needs_second_star_current_club_fact","needs_seed_second_star_origin","t5_27"],canonStatus:"verified"
});

const TEAM27=ambiguousEvent({
 id:"EVT_27_TEAM_001",ageWindow:[27,27],phase:"26_30",family:"team",title:"Tu protegido juega por ti",
 body:"Una lesión o sanción te deja fuera y el joven al que ayudaste ocupa tu puesto. Juega muy bien y el técnico considera mantenerlo.",
 visible:["Conoces el rendimiento del joven y las declaraciones del técnico."],uncertain:["No sabes si tu puesto cambia por mérito, ciclo o simple momento."],
 choices:[
  {id:"A",label:"Felicitarlo y ayudarle",intentTags:["successor","mentor"],primaryMessage:"Mantienes la relación de ayuda incluso cuando la competencia ya afecta a tu sitio.",secondaryMessage:"El vínculo puede fortalecerse mientras su mejor rendimiento aumenta la presión sobre tu jerarquía.",primaryEffects:[n("professional.environmentStability",3),n("professional.successionPressure",2)],secondaryEffects:[n("professional.environmentStability",2),n("professional.successionPressure",4)],primarySeedTransitions:[transformSeed("SEED_YOUNG_SUCCESSOR",{peak27:"mentor"})],secondarySeedTransitions:[transformSeed("SEED_YOUNG_SUCCESSOR",{peak27:"mentor"})]},
  {id:"B",label:"Ser correcto pero centrarte en recuperar puesto",intentTags:["successor","competition"],primaryMessage:"Mantienes respeto personal y separas la recuperación de la relación con el joven.",secondaryMessage:"La frontera protege foco, aunque la competencia puede enfriar una relación que antes era de mentoría.",primaryEffects:[n("professional.careerControl",3),n("professional.successionPressure",-1)],secondaryEffects:[n("professional.environmentStability",-1),n("professional.careerControl",2)],primarySeedTransitions:[transformSeed("SEED_YOUNG_SUCCESSOR",{peak27:"compete"})],secondarySeedTransitions:[transformSeed("SEED_YOUNG_SUCCESSOR",{peak27:"compete"})]},
  {id:"C",label:"Pedir jugar juntos en otro sistema",intentTags:["successor","coexist"],primaryMessage:"Buscas una solución táctica que convierta competencia directa en coexistencia.",secondaryMessage:"La propuesta puede abrir un sistema útil o desplazar el problema a otra zona del equipo.",primaryEffects:[n("professional.roleAdaptability",4),n("professional.careerControl",3)],secondaryEffects:[n("professional.roleAdaptability",3),n("professional.environmentStability",1)],primarySeedTransitions:[transformSeed("SEED_YOUNG_SUCCESSOR",{peak27:"coexist_system"})],secondarySeedTransitions:[transformSeed("SEED_YOUNG_SUCCESSOR",{peak27:"coexist_system"})]},
  {id:"D",label:"Presionar para volver en cuanto estés disponible",intentTags:["successor","return_pressure"],primaryMessage:"Dejas claro que tu objetivo es recuperar el sitio en cuanto el estado físico o disciplinario lo permita.",secondaryMessage:"La presión puede acelerar tu regreso o hacer que el técnico perciba la competencia como un problema de jerarquía.",primaryEffects:[n("professional.roleSecurity",2),n("professional.careerControl",2)],secondaryEffects:[n("professional.environmentStability",-2),n("professional.successionPressure",2)],primarySeedTransitions:[transformSeed("SEED_YOUNG_SUCCESSOR",{peak27:"push_return"})],secondarySeedTransitions:[transformSeed("SEED_YOUNG_SUCCESSOR",{peak27:"push_return"})]}
 ],gates:[{path:"facts.successorPerformedDuringAbsence",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_YOUNG_SUCCESSOR","SEED_YOUNG_MENTOR"],seedsWrite:["SEED_YOUNG_SUCCESSOR"],
 tags:["team","succession","a6_ready_external_blocker","needs_successor_performance_fact","needs_seed_successor_peak_catalog","t5_27"],canonStatus:"verified"
});

export const T527_STAGED_PRINCIPAL_EVENTS:EventDefinition[]=[MKT27,AWARD27,MED27,STAR27,TEAM27];
