import type { EventDefinition, SeedTransition } from "../../../core/types.js";
import { ambiguousEvent, n } from "../18_20/helpers.js";
const tr=(seedId:string,payload:Record<string,string|number|boolean|null>):SeedTransition=>({seedId,action:"transform",payload});

const PRS27=ambiguousEvent({
 id:"EVT_27_PRS_001",ageWindow:[27,27],phase:"26_30",family:"press",title:"Te silban en casa",
 body:"Tras una lesión, mala racha, rumor de salida o campaña sobredimensionada, parte de tu propia afición te silba. Tu rendimiento previo sigue siendo importante.",
 visible:["Conoces la reacción del estadio y el tratamiento de la prensa."],uncertain:["No sabes si es una minoría ruidosa, una ruptura real o una protesta contra el club usando tu figura."],
 choices:[
  {id:"A",label:"Aplaudir al público al salir",intentTags:["fans","acknowledge"],primaryMessage:"Reconoces al estadio sin fingir que los silbidos no existen.",secondaryMessage:"El gesto puede rebajar tensión o ser leído como desafío según el contexto.",primaryEffects:[n("professional.publicMyth",2),n("professional.publicPolarization",1)],secondaryEffects:[n("professional.publicPolarization",3),n("reputation.mediaHeat",2)],primarySeedTransitions:[tr("SEED_GLOBAL_IMAGE",{fan27:"applaud"})],secondarySeedTransitions:[tr("SEED_GLOBAL_IMAGE",{fan27:"applaud"})]},
  {id:"B",label:"No reaccionar",intentTags:["fans","no_reaction"],primaryMessage:"Evitas convertir una reacción parcial del estadio en una disputa pública.",secondaryMessage:"El silencio reduce material inmediato, pero no impide que otros interpreten tu gesto.",primaryEffects:[n("professional.careerControl",2),n("reputation.mediaHeat",-1)],secondaryEffects:[n("professional.careerControl",1),n("professional.publicPolarization",1)],primarySeedTransitions:[tr("SEED_GLOBAL_IMAGE",{fan27:"no_reaction"})],secondarySeedTransitions:[tr("SEED_GLOBAL_IMAGE",{fan27:"no_reaction"})]},
  {id:"C",label:"Responder en entrevista",intentTags:["fans","media_reply"],primaryMessage:"Explicas tu lectura públicamente y aceptas que la respuesta amplíe el tema.",secondaryMessage:"La explicación puede aclarar tu posición o polarizar una reacción todavía minoritaria.",primaryEffects:[n("professional.careerControl",3),n("reputation.mediaHeat",3)],secondaryEffects:[n("professional.publicPolarization",4),n("reputation.mediaHeat",4)],primarySeedTransitions:[tr("SEED_GLOBAL_IMAGE",{fan27:"interview_reply"})],secondarySeedTransitions:[tr("SEED_GLOBAL_IMAGE",{fan27:"interview_reply"})]},
  {id:"D",label:"Pedir al club que te proteja públicamente",intentTags:["fans","club_support"],primaryMessage:"Pides respaldo institucional sin ordenar cuál debe ser el mensaje.",secondaryMessage:"El club puede defenderte de forma útil o convertir una protesta limitada en asunto oficial.",primaryEffects:[n("professional.institutionalTrust",3),n("professional.careerControl",2)],secondaryEffects:[n("reputation.mediaHeat",3),n("professional.publicPolarization",2)],primarySeedTransitions:[tr("SEED_GLOBAL_IMAGE",{fan27:"ask_club_support"})],secondarySeedTransitions:[tr("SEED_GLOBAL_IMAGE",{fan27:"ask_club_support"})]}
 ],gates:[{path:"facts.homeCrowdNegativeReaction",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_GLOBAL_IMAGE"],seedsWrite:["SEED_GLOBAL_IMAGE"],
 tags:["press","fans","a6_ready_external_blocker","needs_stadium_reaction_fact","needs_seed_fan_fracture_origin","t5_28"],canonStatus:"verified"
});

const TACT27=ambiguousEvent({
 id:"EVT_27_TACT_001",ageWindow:[27,27],phase:"26_30",family:"tactical",title:"Cambiar para seguir arriba",
 body:"El entrenador propone que juegues más cerca del área o más por dentro. Tus números de carrera exterior y velocidad ya no son los mismos, pero tu lectura y finalización han mejorado.",
 visible:["Conoces vídeos, métricas y plan del técnico."],uncertain:["No sabes si la nueva posición elevará impacto o reducirá valor y peso internacional."],
 choices:[
  {id:"A",label:"Aceptar la reconversión",intentTags:["tactical","accept"],primaryMessage:"Aceptas entrenar y competir con el nuevo rol como parte real de tu evolución.",secondaryMessage:"La adaptación puede extender el pico y reducir producción visible durante el ajuste.",primaryEffects:[n("professional.roleAdaptability",6),n("professional.tacticalReading",4)],secondaryEffects:[n("professional.roleAdaptability",4),n("professional.environmentStability",-1)],primarySeedTransitions:[tr("SEED_TACTICAL_SACRIFICE",{reinvention27:"accept"})],secondarySeedTransitions:[tr("SEED_TACTICAL_SACRIFICE",{reinvention27:"accept"})]},
  {id:"B",label:"Mantener posición principal",intentTags:["tactical","keep_role"],primaryMessage:"Proteges la identidad deportiva que todavía consideras competitiva.",secondaryMessage:"Mantienes especialización y reduces encajes si el sistema cambia alrededor de ti.",primaryEffects:[n("professional.careerControl",3),n("professional.roleAdaptability",-1)],secondaryEffects:[n("professional.roleSecurity",-1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_TACTICAL_SACRIFICE",{reinvention27:"keep_position"})],secondarySeedTransitions:[tr("SEED_TACTICAL_SACRIFICE",{reinvention27:"keep_position"})]},
  {id:"C",label:"Probarla solo en partidos concretos",intentTags:["tactical","situational"],primaryMessage:"Conviertes la reconversión en una herramienta de partido antes de hacerla identidad permanente.",secondaryMessage:"La prueba reduce riesgo de cambio total y también ralentiza el aprendizaje.",primaryEffects:[n("professional.roleAdaptability",3),n("professional.careerControl",2)],secondaryEffects:[n("professional.roleAdaptability",2),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_TACTICAL_SACRIFICE",{reinvention27:"situational"})],secondarySeedTransitions:[tr("SEED_TACTICAL_SACRIFICE",{reinvention27:"situational"})]},
  {id:"D",label:"Entrenarla pero pedir no cambiar etiqueta pública todavía",intentTags:["tactical","private_trial"],primaryMessage:"Entrenas el rol sin convertir inmediatamente el cambio en relato público de declive o reinvención.",secondaryMessage:"Ganas tiempo para probarlo, aunque la ambigüedad puede reaparecer si empiezas a jugar ahí con frecuencia.",primaryEffects:[n("professional.roleAdaptability",4),n("professional.careerControl",3)],secondaryEffects:[n("professional.roleAdaptability",3),n("reputation.mediaHeat",1)],primarySeedTransitions:[tr("SEED_TACTICAL_SACRIFICE",{reinvention27:"train_private"})],secondarySeedTransitions:[tr("SEED_TACTICAL_SACRIFICE",{reinvention27:"train_private"})]}
 ],gates:[{path:"facts.tacticalReconversionProposal",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_TACTICAL_SACRIFICE"],seedsWrite:["SEED_TACTICAL_SACRIFICE"],
 tags:["tactical","reinvention","a6_ready_external_blocker","needs_tactical_proposal_fact","needs_seed_positional_reinvention_origin","t5_28"],canonStatus:"verified"
});

const EUR27=ambiguousEvent({
 id:"EVT_27_EUR_001",ageWindow:[27,27],phase:"26_30",family:"sport",title:"La semifinal que exige desaparecer",
 body:"En una semifinal, el técnico diseña un papel de presión y ayudas que reduce casi a cero tus opciones de lucir. Tu agente teme que justo ahora se vote un premio individual.",
 visible:["Conoces plan, rival y calendario de premios."],uncertain:["No sabes si el sacrificio será recordado ni si un mal resultado lo hará parecer inútil."],
 choices:[
  {id:"A",label:"Aceptar plenamente",intentTags:["europe","sacrifice"],primaryMessage:"Aceptas el plan colectivo aunque reduzca tu producción visible.",secondaryMessage:"El sacrificio puede aumentar confianza interna sin garantizar resultado ni reconocimiento externo.",primaryEffects:[n("professional.institutionalTrust",4),n("professional.trophyCapital",1)],secondaryEffects:[n("professional.institutionalTrust",3),n("professional.publicMyth",-1)],primarySeedTransitions:[tr("SEED_TACTICAL_SACRIFICE",{elite27:"full_accept"})],secondarySeedTransitions:[tr("SEED_TACTICAL_SACRIFICE",{elite27:"full_accept"})]},
  {id:"B",label:"Pedir libertad en transiciones",intentTags:["europe","transition_freedom"],primaryMessage:"Aceptas la estructura defensiva y negocias una excepción ofensiva concreta.",secondaryMessage:"La concesión puede equilibrar impacto y plan o dejar zonas sin cubrir cuando el partido se rompa.",primaryEffects:[n("professional.careerControl",3),n("professional.institutionalTrust",2)],secondaryEffects:[n("professional.environmentStability",-1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_TACTICAL_SACRIFICE",{elite27:"transition_freedom"})],secondarySeedTransitions:[tr("SEED_TACTICAL_SACRIFICE",{elite27:"transition_freedom"})]},
  {id:"C",label:"Mostrar dudas por tu rol",intentTags:["europe","question_role"],primaryMessage:"Expresas dudas antes del partido sin negar que el técnico tome la decisión final.",secondaryMessage:"La conversación puede aclarar el plan o abrir una tensión justo antes de la cita.",primaryEffects:[n("professional.careerControl",2),n("professional.institutionalTrust",-1)],secondaryEffects:[n("professional.environmentStability",-2),n("professional.publicPolarization",1)],primarySeedTransitions:[tr("SEED_TACTICAL_SACRIFICE",{elite27:"question_role"})],secondarySeedTransitions:[tr("SEED_TACTICAL_SACRIFICE",{elite27:"question_role"})]},
  {id:"D",label:"Cumplir sin permitir que tu agente critique después",intentTags:["europe","message_control"],primaryMessage:"Aceptas el papel y separas la estrategia de cualquier campaña posterior de tu entorno.",secondaryMessage:"Proteges coherencia pública, aunque el resultado puede reabrir igualmente el debate de jerarquía.",primaryEffects:[n("professional.careerControl",4),n("professional.institutionalTrust",3)],secondaryEffects:[n("professional.careerControl",3),n("reputation.mediaHeat",-1)],primarySeedTransitions:[tr("SEED_TACTICAL_SACRIFICE",{elite27:"no_agent_critique"})],secondarySeedTransitions:[tr("SEED_TACTICAL_SACRIFICE",{elite27:"no_agent_critique"})]}
 ],gates:[{path:"facts.continentalSemifinalSacrificePlan",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_TACTICAL_SACRIFICE"],seedsWrite:["SEED_TACTICAL_SACRIFICE"],
 tags:["sport","europe","a6_ready_external_blocker","needs_competition_stage_and_plan","needs_seed_elite_sacrifice_origin","t5_28"],canonStatus:"verified"
});

const MATCH27=ambiguousEvent({
 id:"EVT_27_MATCH_001",ageWindow:[27,27],phase:"26_30",family:"sport",title:"El récord no se celebra",
 body:"Bates un récord en un partido que el equipo pierde o empata de forma dolorosa. Marketing quiere publicar inmediatamente una pieza preparada.",
 visible:["Conoces el hito, el resultado y el material de campaña."],uncertain:["No sabes si retrasar la celebración reduce alcance ni cómo lo interpretará la afición."],
 choices:[
  {id:"A",label:"Publicar igual",intentTags:["record","publish"],primaryMessage:"Publicas el logro sin negar el mal resultado colectivo.",secondaryMessage:"El hito recibe máxima exposición y también puede parecer desconectado del momento del equipo.",primaryEffects:[n("professional.publicMyth",3),n("reputation.mediaHeat",2)],secondaryEffects:[n("professional.publicPolarization",3),n("reputation.mediaHeat",3)],primarySeedTransitions:[tr("SEED_RECORD_CHASE",{public27:"publish_now"})],secondarySeedTransitions:[tr("SEED_RECORD_CHASE",{public27:"publish_now"})]},
  {id:"B",label:"Retrasar 24-48 horas",intentTags:["record","delay"],primaryMessage:"Separar el hito del golpe inmediato del resultado conserva ambos hechos.",secondaryMessage:"El retraso reduce fricción y puede reducir alcance de una campaña preparada para el momento exacto.",primaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",2)],secondaryEffects:[n("professional.publicMyth",1),n("reputation.mediaHeat",-1)],primarySeedTransitions:[tr("SEED_RECORD_CHASE",{public27:"delay"})],secondarySeedTransitions:[tr("SEED_RECORD_CHASE",{public27:"delay"})]},
  {id:"C",label:"Publicar solo un mensaje breve centrado en el equipo",intentTags:["record","team_message"],primaryMessage:"Reconoces el récord dentro de un mensaje que prioriza el contexto colectivo.",secondaryMessage:"La solución reduce protagonismo individual sin borrar que el logro ocurrió.",primaryEffects:[n("professional.environmentStability",2),n("professional.publicMyth",2)],secondaryEffects:[n("professional.environmentStability",1),n("professional.publicPolarization",1)],primarySeedTransitions:[tr("SEED_RECORD_CHASE",{public27:"team_brief"})],secondarySeedTransitions:[tr("SEED_RECORD_CHASE",{public27:"team_brief"})]},
  {id:"D",label:"Cancelar la campaña",intentTags:["record","cancel"],primaryMessage:"Renuncias a la pieza preparada por considerar que el contexto colectivo pesa más ahora.",secondaryMessage:"Proteges el momento del equipo y pierdes un activo de comunicación que quizá no pueda recuperarse igual.",primaryEffects:[n("professional.careerControl",3),n("professional.publicMyth",-1)],secondaryEffects:[n("professional.environmentStability",1),n("professional.commercialPower",-1)],primarySeedTransitions:[tr("SEED_RECORD_CHASE",{public27:"cancel"})],secondarySeedTransitions:[tr("SEED_RECORD_CHASE",{public27:"cancel"})]}
 ],gates:[{path:"facts.recordInNegativeResult",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_RECORD_CHASE"],seedsWrite:["SEED_RECORD_CHASE"],
 tags:["sport","record","a6_ready_external_blocker","needs_result_and_record_fact","needs_seed_record_public_tone_origin","t5_28"],canonStatus:"verified"
});

const AGT27=ambiguousEvent({
 id:"EVT_27_AGT_002",ageWindow:[27,27],phase:"26_30",family:"agent",title:"Tu agente negocia dos futuros",
 body:"Descubres que tu agencia mantiene conversaciones avanzadas tanto para renovar como para salir, usando cada vía para mejorar la otra. Tú habías pedido discreción, no doble negociación.",
 visible:["Conoces las dos conversaciones al descubrirlas."],uncertain:["No sabes si la táctica mejora realmente tus condiciones o si ya ha erosionado confianza."],
 choices:[
  {id:"A",label:"Permitir que siga",intentTags:["agent","parallel"],primaryMessage:"Aceptas la negociación paralela como táctica mientras mantengas visibilidad sobre ambas vías.",secondaryMessage:"La estrategia puede mejorar tus términos o hacer caer una opción si una parte detecta la palanca.",primaryEffects:[n("professional.contractPower",4),n("professional.agentControl",-2)],secondaryEffects:[n("professional.contractPower",2),n("professional.environmentStability",-2)],primarySeedTransitions:[tr("SEED_AGENT_CONFLICT_PEAK",{parallel27:"allow"})],secondarySeedTransitions:[tr("SEED_AGENT_CONFLICT_PEAK",{parallel27:"allow"})]},
  {id:"B",label:"Ordenar elegir una vía",intentTags:["agent","single_track"],primaryMessage:"Priorizas claridad y ordenas a la agencia que deje de usar una negociación contra la otra.",secondaryMessage:"Recuperas control de proceso y renuncias a parte de la palanca creada por la alternativa.",primaryEffects:[n("professional.careerControl",5),n("professional.agentControl",3)],secondaryEffects:[n("professional.contractPower",-1),n("professional.careerControl",4)],primarySeedTransitions:[tr("SEED_AGENT_CONFLICT_PEAK",{parallel27:"choose_one"})],secondarySeedTransitions:[tr("SEED_AGENT_CONFLICT_PEAK",{parallel27:"choose_one"})]},
  {id:"C",label:"Tomar control directo de una negociación",intentTags:["agent","direct_control"],primaryMessage:"Mantienes una vía con la agencia y tomas control personal de la otra.",secondaryMessage:"Aumentas información directa y también el riesgo de mensajes inconsistentes entre partes.",primaryEffects:[n("professional.careerControl",6),n("professional.agentControl",4)],secondaryEffects:[n("professional.environmentStability",-2),n("professional.careerControl",4)],primarySeedTransitions:[tr("SEED_AGENT_CONFLICT_PEAK",{parallel27:"direct_one"})],secondarySeedTransitions:[tr("SEED_AGENT_CONFLICT_PEAK",{parallel27:"direct_one"})]},
  {id:"D",label:"Cambiar de agente en mitad del proceso",intentTags:["agent","switch"],primaryMessage:"Rompes la representación por considerar incompatible la táctica con tus instrucciones.",secondaryMessage:"El cambio recupera una frontera de control y puede bloquear o retrasar las dos operaciones en marcha.",primaryEffects:[n("professional.careerControl",5),n("professional.environmentStability",-4)],secondaryEffects:[n("professional.contractPower",-2),n("professional.environmentStability",-5)],primarySeedTransitions:[tr("SEED_AGENT_CONFLICT_PEAK",{parallel27:"switch_requested"})],secondarySeedTransitions:[tr("SEED_AGENT_CONFLICT_PEAK",{parallel27:"switch_requested"})]}
 ],gates:[{path:"facts.parallelAdvancedNegotiations",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_AGENT_CONFLICT_PEAK"],seedsWrite:["SEED_AGENT_CONFLICT_PEAK"],
 tags:["agent","negotiation","a6_ready_external_blocker","needs_parallel_negotiation_authority","needs_active_agent_switch_action","needs_seed_parallel_negotiation_origin","t5_28"],canonStatus:"verified"
});

export const T528_STAGED_PRINCIPAL_EVENTS:EventDefinition[]=[PRS27,TACT27,EUR27,MATCH27,AGT27];
