import type { EventDefinition, SeedTransition } from "../../../core/types.js";
import { ambiguousEvent, n } from "../18_20/helpers.js";
const tr=(seedId:string,payload:Record<string,string|number|boolean|null>):SeedTransition=>({seedId,action:"transform",payload});

const MKT28=ambiguousEvent({
 id:"EVT_28_MKT_001",ageWindow:[28,28],phase:"26_30",family:"market",title:"Salir en la cima",
 body:"Tras una temporada excepcional, aparece la posibilidad de irte cuando tu valor y relación con la afición están arriba. Quedarte ofrece continuidad; salir quizá sea la última vez que eliges desde máxima fuerza.",
 visible:["Conoces las ofertas, tu contrato actual y la situación del club."],uncertain:["No sabes si el pico continuará ni si el nuevo proyecto encajará."],
 choices:[
  {id:"A",label:"Salir ahora",intentTags:["market","exit_peak"],primaryMessage:"Decides usar la ventana de máximo poder de mercado.",secondaryMessage:"Salir puede ser un salto maestro o cortar una era que todavía no había terminado.",primaryEffects:[n("professional.careerControl",6),n("reputation.marketHeat",2)],secondaryEffects:[n("professional.environmentStability",-2),n("professional.careerControl",4)],primarySeedTransitions:[tr("SEED_PEAK_CONTRACT",{exit28:"now"})],secondarySeedTransitions:[tr("SEED_PEAK_CONTRACT",{exit28:"now"})]},
  {id:"B",label:"Quedarte al menos un año",intentTags:["market","stay"],primaryMessage:"Priorizas continuidad y aceptas que el mercado futuro puede ser distinto.",secondaryMessage:"Quedarte puede consolidar legado o cerrar una ventana excepcional.",primaryEffects:[n("professional.environmentStability",4),n("professional.legacyCapital",2)],secondaryEffects:[n("reputation.marketHeat",-2),n("professional.careerControl",1)],primarySeedTransitions:[tr("SEED_PEAK_CONTRACT",{exit28:"stay_year"})],secondarySeedTransitions:[tr("SEED_PEAK_CONTRACT",{exit28:"stay_year"})]},
  {id:"C",label:"Renovar solo con salida pactada",intentTags:["market","renew_exit"],primaryMessage:"Intentas combinar continuidad y una salida verificable futura.",secondaryMessage:"La protección contractual puede preservar libertad sin garantizar que exista comprador.",primaryEffects:[n("professional.contractPower",4),n("professional.careerControl",4)],secondaryEffects:[n("professional.contractPower",2),n("professional.institutionalTrust",-1)],primarySeedTransitions:[tr("SEED_PEAK_CONTRACT",{exit28:"renew_with_exit"})],secondarySeedTransitions:[tr("SEED_PEAK_CONTRACT",{exit28:"renew_with_exit"})]},
  {id:"D",label:"Decidir según entrenador o fichajes antes de cerrar mercado",intentTags:["market","wait_context"],primaryMessage:"Compras información sobre el ciclo deportivo antes de decidir.",secondaryMessage:"La espera mejora contexto y reduce tiempo de maniobra.",primaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",1)],secondaryEffects:[n("reputation.marketHeat",-1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_PEAK_CONTRACT",{exit28:"wait_context"})],secondarySeedTransitions:[tr("SEED_PEAK_CONTRACT",{exit28:"wait_context"})]}
 ],gates:[{path:"facts.peakExitWindowOffers",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_PEAK_CONTRACT"],seedsWrite:["SEED_PEAK_CONTRACT"],
 tags:["market","peak","a6_ready_external_blocker","needs_peak_exit_offer_set","needs_seed_exit_at_peak_catalog","t5_29"],canonStatus:"verified"
});

const FORM28=ambiguousEvent({
 id:"EVT_28_FORM_001",ageWindow:[28,28],phase:"26_30",family:"sport",title:"Tres meses normales",
 body:"Por primera vez en años pasas varias semanas sin números extraordinarios. No estás mal; simplemente pareces humano. Prensa y entorno hablan de declive.",
 visible:["Ves tus métricas y resultados."],uncertain:["No sabes si es varianza, fatiga, táctica o inicio de descenso."],
 choices:[
  {id:"A",label:"No cambiar nada",intentTags:["form","hold"],primaryMessage:"Tratas la racha como información insuficiente para alterar todo tu proceso.",secondaryMessage:"La estabilidad evita sobrerreacción y puede prolongar un problema real si la causa no era azar.",primaryEffects:[n("professional.environmentStability",3),n("professional.careerControl",2)],secondaryEffects:[n("professional.environmentStability",2),n("professional.publicPolarization",1)],primarySeedTransitions:[tr("SEED_SELF_OPTIMIZATION",{dip28:"hold"})],secondarySeedTransitions:[tr("SEED_SELF_OPTIMIZATION",{dip28:"hold"})]},
  {id:"B",label:"Añadir trabajo individual",intentTags:["form","extra_work"],primaryMessage:"Añades trabajo específico sin asumir que la racha tenga una causa única.",secondaryMessage:"El trabajo puede ayudar o añadir carga a un periodo que ya podía ser fatiga.",primaryEffects:[n("professional.roleAdaptability",2),n("professional.bodyLoad",2)],secondaryEffects:[n("professional.bodyLoad",4),n("professional.recoveryMargin",-2)],primarySeedTransitions:[tr("SEED_SELF_OPTIMIZATION",{dip28:"extra_work"})],secondarySeedTransitions:[tr("SEED_SELF_OPTIMIZATION",{dip28:"extra_work"})]},
  {id:"C",label:"Pedir descanso corto",intentTags:["form","rest"],primaryMessage:"Pruebas una descarga breve antes de reinterpretar tu nivel.",secondaryMessage:"El descanso protege margen físico y puede interrumpir ritmo sin resolver la causa.",primaryEffects:[n("professional.recoveryMargin",4),n("professional.bodyLoad",-3)],secondaryEffects:[n("professional.roleSecurity",-1),n("professional.recoveryMargin",3)],primarySeedTransitions:[tr("SEED_SELF_OPTIMIZATION",{dip28:"short_rest"})],secondarySeedTransitions:[tr("SEED_SELF_OPTIMIZATION",{dip28:"short_rest"})]},
  {id:"D",label:"Cambiar rol táctico temporalmente",intentTags:["form","temporary_role"],primaryMessage:"Usas un cambio táctico acotado para probar si el contexto explica parte de la racha.",secondaryMessage:"El experimento puede recuperar impacto o generar más ruido sobre tu identidad.",primaryEffects:[n("professional.roleAdaptability",4),n("professional.tacticalReading",2)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.roleAdaptability",2)],primarySeedTransitions:[tr("SEED_SELF_OPTIMIZATION",{dip28:"temporary_role"})],secondarySeedTransitions:[tr("SEED_SELF_OPTIMIZATION",{dip28:"temporary_role"})]}
 ],gates:[{path:"facts.sustainedAverageFormAfterPeak",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_SELF_OPTIMIZATION"],seedsWrite:["SEED_SELF_OPTIMIZATION"],
 tags:["sport","form","a6_ready_external_blocker","needs_form_window_fact","needs_seed_first_peak_dip_origin_alignment","t5_29"],canonStatus:"verified"
});

const STAR28=ambiguousEvent({
 id:"EVT_28_STAR_001",ageWindow:[28,28],phase:"26_30",family:"team",title:"El chico ya no es promesa",
 body:"El joven que competía contigo ya produce a tu nivel o por encima durante meses. El club considera que ambos son titulares, pero la estructura táctica no siempre los admite juntos.",
 visible:["Conoces rendimiento, minutos y declaraciones del técnico."],uncertain:["No sabes si el club quiere vender a uno ni cuál tiene más mercado."],
 choices:[
  {id:"A",label:"Adaptarte para jugar juntos",intentTags:["succession","adapt"],primaryMessage:"Intentas convertir competencia directa en convivencia táctica.",secondaryMessage:"La adaptación puede ampliar carrera y cambiar números.",primaryEffects:[n("professional.roleAdaptability",5),n("professional.successionPressure",-2)],secondaryEffects:[n("professional.roleAdaptability",3),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_YOUNG_SUCCESSOR",{decision28:"adapt_together"})],secondarySeedTransitions:[tr("SEED_YOUNG_SUCCESSOR",{decision28:"adapt_together"})]},
  {id:"B",label:"Competir por el puesto original",intentTags:["succession","compete"],primaryMessage:"Mantienes la competencia en el rol donde construiste tu pico.",secondaryMessage:"La rivalidad puede elevar rendimiento o endurecer el vestuario.",primaryEffects:[n("professional.careerControl",3),n("professional.successionPressure",2)],secondaryEffects:[n("professional.environmentStability",-2),n("professional.successionPressure",4)],primarySeedTransitions:[tr("SEED_YOUNG_SUCCESSOR",{decision28:"compete_original"})],secondarySeedTransitions:[tr("SEED_YOUNG_SUCCESSOR",{decision28:"compete_original"})]},
  {id:"C",label:"Explorar salida",intentTags:["succession","market"],primaryMessage:"Tratas la nueva jerarquía como razón válida para comprobar mercado, no como derrota automática.",secondaryMessage:"Explorar alternativas recupera opcionalidad y puede erosionar confianza si se filtra.",primaryEffects:[n("professional.careerControl",5),n("reputation.marketHeat",3)],secondaryEffects:[n("professional.institutionalTrust",-2),n("reputation.mediaHeat",2)],primarySeedTransitions:[tr("SEED_YOUNG_SUCCESSOR",{decision28:"explore_exit"})],secondarySeedTransitions:[tr("SEED_YOUNG_SUCCESSOR",{decision28:"explore_exit"})]},
  {id:"D",label:"Pedir al club que defina quién es prioridad",intentTags:["succession","clarity"],primaryMessage:"Pides una definición institucional de jerarquía antes de decidir tu siguiente paso.",secondaryMessage:"La claridad puede ayudarte o forzar una respuesta que no querías oír.",primaryEffects:[n("professional.careerControl",4),n("professional.institutionalPower",2)],secondaryEffects:[n("professional.roleSecurity",-2),n("professional.environmentStability",-1)],primarySeedTransitions:[tr("SEED_YOUNG_SUCCESSOR",{decision28:"ask_priority"})],secondarySeedTransitions:[tr("SEED_YOUNG_SUCCESSOR",{decision28:"ask_priority"})]}
 ],gates:[{path:"facts.successorSustainedPeerPerformance",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_YOUNG_SUCCESSOR","SEED_POSITIONAL_REINVENTION"],seedsWrite:["SEED_YOUNG_SUCCESSOR"],
 tags:["team","succession","a6_ready_external_blocker","needs_successor_sustained_performance_fact","needs_seed_succession_decision_catalog","t5_29"],canonStatus:"verified"
});

const MED28=ambiguousEvent({
 id:"EVT_28_MED_001",ageWindow:[28,28],phase:"26_30",family:"medical",title:"No puedes jugar sesenta partidos",
 body:"Los médicos y preparadores coinciden: mantener el mismo volumen de club y selección eleva demasiado el riesgo. No recomiendan retirarte de nada; recomiendan elegir dónde descargar.",
 visible:["Conoces carga acumulada y opciones de rotación."],uncertain:["No sabes qué partido, torneo o racha será decisiva."],
 choices:[
  {id:"A",label:"Reducir amistosos o partidos menores de selección",intentTags:["load","national_reduce"],primaryMessage:"Descargas en selección sin convertirlo en retirada internacional.",secondaryMessage:"Proteges cuerpo y abres espacio competitivo a otros internacionales.",primaryEffects:[n("professional.recoveryMargin",5),n("professional.nationalPower",-1)],secondaryEffects:[n("professional.recoveryMargin",4),n("professional.nationalPower",-2)],primarySeedTransitions:[tr("SEED_INTERNATIONAL_LOAD",{load28:"national_reduce"})],secondarySeedTransitions:[tr("SEED_INTERNATIONAL_LOAD",{load28:"national_reduce"})]},
  {id:"B",label:"Pedir más rotación al club",intentTags:["load","club_rotate"],primaryMessage:"Trasladas parte de la descarga al calendario de club.",secondaryMessage:"Ganas recuperación y cedes minutos que otros pueden aprovechar.",primaryEffects:[n("professional.recoveryMargin",5),n("professional.roleSecurity",-1)],secondaryEffects:[n("professional.recoveryMargin",4),n("professional.successionPressure",2)],primarySeedTransitions:[tr("SEED_INTERNATIONAL_LOAD",{load28:"club_rotate"})],secondarySeedTransitions:[tr("SEED_INTERNATIONAL_LOAD",{load28:"club_rotate"})]},
  {id:"C",label:"Mantener todo y aceptar riesgo",intentTags:["load","keep_all"],primaryMessage:"Mantienes disponibilidad completa mientras el cuerpo lo permita.",secondaryMessage:"Conservas presencia competitiva y elevas exposición a fatiga o lesión.",primaryEffects:[n("professional.bodyLoad",4),n("professional.roleSecurity",2)],secondaryEffects:[n("professional.bodyLoad",6),n("professional.recoveryMargin",-4)],primarySeedTransitions:[tr("SEED_INTERNATIONAL_LOAD",{load28:"keep_all"})],secondarySeedTransitions:[tr("SEED_INTERNATIONAL_LOAD",{load28:"keep_all"})]},
  {id:"D",label:"Negociar un plan conjunto club-selección",intentTags:["load","joint_plan"],primaryMessage:"Intentas repartir descansos con información compartida entre ambos staffs.",secondaryMessage:"El plan reduce choques previstos y puede romperse si cambian lesiones o partidos clave.",primaryEffects:[n("professional.careerControl",4),n("professional.recoveryMargin",3)],secondaryEffects:[n("professional.environmentStability",1),n("professional.recoveryMargin",2)],primarySeedTransitions:[tr("SEED_INTERNATIONAL_LOAD",{load28:"joint_plan"})],secondarySeedTransitions:[tr("SEED_INTERNATIONAL_LOAD",{load28:"joint_plan"})]}
 ],gates:[{path:"facts.clubNationalLoadConflict",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_INTERNATIONAL_LOAD"],seedsWrite:["SEED_INTERNATIONAL_LOAD"],
 tags:["medical","calendar","a6_ready_external_blocker","needs_congestion_and_national_load_fact","needs_seed_load_choice_29_catalog","t5_29"],canonStatus:"verified"
});

const CLUB28=ambiguousEvent({
 id:"EVT_28_CLUB_001",ageWindow:[28,28],phase:"26_30",family:"captaincy",title:"El presidente quiere tu apoyo",
 body:"El entrenador está cuestionado y el presidente te pide una frase pública de respaldo para estabilizar el club. En privado no estás seguro de que el ciclo deba continuar.",
 visible:["Conoces la petición y la situación pública."],uncertain:["No sabes si el presidente ya busca sustituto ni si el entrenador sabe de la llamada."],
 choices:[
  {id:"A",label:"Respaldarlo con claridad",intentTags:["club","manager_support"],primaryMessage:"Usas capital público para respaldar de forma explícita al entrenador.",secondaryMessage:"El apoyo puede estabilizar o quedar archivado si el club cambia de técnico días después.",primaryEffects:[n("professional.institutionalPower",3),n("professional.institutionalTrust",3)],secondaryEffects:[n("professional.publicPolarization",2),n("reputation.mediaHeat",2)],primarySeedTransitions:[tr("SEED_MANAGER_POWER",{public28:"clear_backing"})],secondarySeedTransitions:[tr("SEED_MANAGER_POWER",{public28:"clear_backing"})]},
  {id:"B",label:"Dar un mensaje genérico de unidad",intentTags:["club","unity"],primaryMessage:"Apoyas al grupo y al club sin personalizar el mensaje en la continuidad del técnico.",secondaryMessage:"La ambigüedad protege opciones y puede ser interpretada como falta de respaldo real.",primaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",2)],secondaryEffects:[n("reputation.mediaHeat",1),n("professional.publicPolarization",1)],primarySeedTransitions:[tr("SEED_MANAGER_POWER",{public28:"generic_unity"})],secondarySeedTransitions:[tr("SEED_MANAGER_POWER",{public28:"generic_unity"})]},
  {id:"C",label:"Negarte a personalizar apoyo",intentTags:["club","boundary"],primaryMessage:"Te niegas a prestar tu nombre a una decisión de continuidad que corresponde a la dirección.",secondaryMessage:"Proteges tu frontera y pierdes parte de la utilidad institucional que el presidente buscaba.",primaryEffects:[n("professional.careerControl",4),n("professional.institutionalPower",-1)],secondaryEffects:[n("professional.institutionalTrust",-1),n("professional.careerControl",3)],primarySeedTransitions:[tr("SEED_MANAGER_POWER",{public28:"refuse_personal_backing"})],secondarySeedTransitions:[tr("SEED_MANAGER_POWER",{public28:"refuse_personal_backing"})]},
  {id:"D",label:"Decir al presidente en privado que tienes dudas antes de hablar",intentTags:["club","private_doubt"],primaryMessage:"Trasladas tu lectura real antes de decidir si harás una declaración pública.",secondaryMessage:"La honestidad mejora información de dirección y te convierte en actor interno de la crisis.",primaryEffects:[n("professional.institutionalPower",3),n("professional.careerControl",3)],secondaryEffects:[n("professional.environmentStability",-1),n("professional.institutionalPower",2)],primarySeedTransitions:[tr("SEED_MANAGER_POWER",{public28:"private_doubts"})],secondarySeedTransitions:[tr("SEED_MANAGER_POWER",{public28:"private_doubts"})]}
 ],gates:[{path:"facts.presidentManagerBackingRequest",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_MANAGER_POWER"],seedsWrite:["SEED_MANAGER_POWER"],
 tags:["club","coach_crisis","a6_ready_external_blocker","needs_current_club_president_request","needs_seed_public_manager_backing_catalog","t5_29"],canonStatus:"verified"
});

export const T529_STAGED_PRINCIPAL_EVENTS:EventDefinition[]=[MKT28,FORM28,STAR28,MED28,CLUB28];
