import type { EventDefinition, SeedTransition } from "../../../core/types.js";
import { ambiguousEvent, n, seedCreate } from "../18_20/helpers.js";
const tr=(seedId:string,payload:Record<string,string|number|boolean|null>):SeedTransition=>({seedId,action:"transform",payload});

const HOME26=ambiguousEvent({
 id:"EVT_26_HOME_001",ageWindow:[26,26],phase:"26_30",family:"family",title:"Valdoria propone algo que dura más que tu carrera",
 body:"UDV te ofrece financiar y dar nombre a una pequeña academia o programa de becas. El club quiere anunciarlo en un momento de máxima notoriedad tuya.",
 visible:["Conoces presupuesto, gobernanza y uso de tu nombre."],uncertain:["No sabes quién dirigirá UDV en cinco años ni si el proyecto será usado políticamente."],
 choices:[
  {id:"A",label:"Financiar y prestar tu nombre",intentTags:["home","academy"],primaryMessage:"Financias el proyecto y aceptas que tu identidad quede asociada a él.",secondaryMessage:"El legado aumenta y también tu exposición a decisiones futuras que no controlarás por completo.",primaryEffects:[n("professional.legacyCapital",5),n("professional.moneyComfort",-3),n("professional.homePull",4)],secondaryEffects:[n("professional.legacyCapital",4),n("professional.publicPolarization",2)],primarySeedTransitions:[seedCreate("SEED_HOME_INSTITUTION",72,{academy26:"fund_and_name"})],secondarySeedTransitions:[seedCreate("SEED_HOME_INSTITUTION",76,{academy26:"fund_and_name"})]},
  {id:"B",label:"Financiar sin usar tu imagen",intentTags:["home","private_support"],primaryMessage:"Apoyas el proyecto sin convertir tu nombre en marca institucional.",secondaryMessage:"El impacto material se mantiene y el valor público del anuncio disminuye.",primaryEffects:[n("professional.legacyCapital",3),n("professional.moneyComfort",-3),n("professional.careerControl",2)],secondaryEffects:[n("professional.legacyCapital",2),n("professional.homePull",2)],primarySeedTransitions:[seedCreate("SEED_HOME_INSTITUTION",66,{academy26:"fund_no_image"})],secondarySeedTransitions:[seedCreate("SEED_HOME_INSTITUTION",70,{academy26:"fund_no_image"})]},
  {id:"C",label:"Participar solo si una fundación independiente gestiona",intentTags:["home","governance"],primaryMessage:"Condicionas tu participación a una gobernanza separada del club.",secondaryMessage:"La independencia reduce control político del club y también el tuyo.",primaryEffects:[n("professional.careerControl",4),n("professional.legacyCapital",4),n("professional.moneyComfort",-2)],secondaryEffects:[n("professional.legacyCapital",3),n("professional.environmentStability",1)],primarySeedTransitions:[seedCreate("SEED_HOME_INSTITUTION",74,{academy26:"independent_foundation"})],secondarySeedTransitions:[seedCreate("SEED_HOME_INSTITUTION",78,{academy26:"independent_foundation"})]},
  {id:"D",label:"Rechazar por ahora",intentTags:["home","defer"],primaryMessage:"Mantienes el vínculo con Valdoria sin convertir una oportunidad concreta en obligación inmediata.",secondaryMessage:"Proteges liquidez y control, pero el proyecto puede avanzar sin ti.",primaryEffects:[n("professional.careerControl",3),n("professional.moneyComfort",2)],secondaryEffects:[n("professional.homePull",-1),n("professional.careerControl",2)],primarySeedTransitions:[seedCreate("SEED_HOME_INSTITUTION",54,{academy26:"defer"})],secondarySeedTransitions:[seedCreate("SEED_HOME_INSTITUTION",58,{academy26:"defer"})]}
 ],gates:[{path:"facts.homeAcademyProposal",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_HOME_SYMBOL"],seedsWrite:["SEED_HOME_INSTITUTION"],
 tags:["home","legacy","a6_ready_external_blocker","needs_home_academy_proposal_fact","t5_30"],canonStatus:"verified"
});

const CAP26=ambiguousEvent({
 id:"EVT_26_CAP_001",ageWindow:[26,26],phase:"26_30",family:"captaincy",title:"El capitán te pide que elijas lado",
 body:"El entrenador endurece multas y control interno. El capitán cree que ha cruzado una línea y quiere que los líderes amenacen con no acudir a un acto del club.",
 visible:["Conoces reglamento, sanciones y petición del capitán."],uncertain:["No sabes si dirección respalda al técnico ni si el capitán también negocia su futuro."],
 choices:[
  {id:"A",label:"Apoyar la acción colectiva",intentTags:["locker","collective_action"],primaryMessage:"Te sumas a la presión colectiva sabiendo que la decisión afecta a club y técnico.",secondaryMessage:"La acción puede cambiar reglas o romper confianza institucional.",primaryEffects:[n("professional.lockerPower",4),n("professional.institutionalTrust",-2)],secondaryEffects:[n("professional.environmentStability",-2),n("professional.lockerPower",3)],primarySeedTransitions:[tr("SEED_CAPTAINCY_STYLE",{cap26:"collective_action"})],secondarySeedTransitions:[tr("SEED_CAPTAINCY_STYLE",{cap26:"collective_action"})]},
  {id:"B",label:"Negociar con entrenador antes",intentTags:["locker","mediate"],primaryMessage:"Intentas abrir una vía directa antes de escalar la protesta.",secondaryMessage:"La mediación puede mejorar reglas o dejarte entre dos bloques.",primaryEffects:[n("professional.careerControl",3),n("professional.institutionalTrust",2)],secondaryEffects:[n("professional.environmentStability",-1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_CAPTAINCY_STYLE",{cap26:"mediate_first"})],secondarySeedTransitions:[tr("SEED_CAPTAINCY_STYLE",{cap26:"mediate_first"})]},
  {id:"C",label:"Desmarcarte",intentTags:["locker","distance"],primaryMessage:"Decides no participar en una protesta que no consideras tu responsabilidad.",secondaryMessage:"Proteges relación institucional y puedes perder peso de vestuario.",primaryEffects:[n("professional.institutionalTrust",3),n("professional.lockerPower",-2)],secondaryEffects:[n("professional.environmentStability",-2),n("professional.careerControl",1)],primarySeedTransitions:[tr("SEED_CAPTAINCY_STYLE",{cap26:"distance"})],secondarySeedTransitions:[tr("SEED_CAPTAINCY_STYLE",{cap26:"distance"})]},
  {id:"D",label:"Proponer que solo los capitanes asuman la protesta",intentTags:["locker","formal_leaders"],primaryMessage:"Limitar la protesta a cargos formales reduce exposición del resto del grupo.",secondaryMessage:"La frontera protege compañeros y concentra el coste sobre quienes tienen brazalete.",primaryEffects:[n("professional.lockerPower",3),n("professional.careerControl",2)],secondaryEffects:[n("professional.institutionalTrust",-1),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_CAPTAINCY_STYLE",{cap26:"captains_only"})],secondarySeedTransitions:[tr("SEED_CAPTAINCY_STYLE",{cap26:"captains_only"})]}
 ],gates:[{path:"facts.captainCollectiveActionRequest",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_CAPTAINCY_STYLE","SEED_PRIVATE_CHAT"],seedsWrite:["SEED_CAPTAINCY_STYLE"],
 tags:["captaincy","locker","a6_ready_external_blocker","needs_current_captain_request_fact","needs_seed_locker_endorsement_origin_alignment","t5_30"],canonStatus:"verified"
});

const MED26=ambiguousEvent({
 id:"EVT_26_MED_001",ageWindow:[26,26],phase:"26_30",family:"medical",title:"Cada tres días",
 body:"En seis semanas hay liga, copa, competición continental y selección. El staff propone descansar dos partidos menores; tu racha individual es excelente.",
 visible:["Conoces carga, rivales, descanso previsto y estado de forma."],uncertain:["No sabes cuáles serán realmente los partidos decisivos ni si descansar corta la racha."],
 choices:[
  {id:"A",label:"Aceptar ambos descansos",intentTags:["load","rest_two"],primaryMessage:"Aceptas la descarga planificada completa.",secondaryMessage:"Reduces carga sin garantía de conservar ritmo.",primaryEffects:[n("professional.recoveryMargin",5),n("professional.bodyLoad",-4)],secondaryEffects:[n("professional.roleSecurity",-1),n("professional.recoveryMargin",4)],primarySeedTransitions:[tr("SEED_LOAD_MANAGEMENT",{peak26:"rest_two"})],secondarySeedTransitions:[tr("SEED_LOAD_MANAGEMENT",{peak26:"rest_two"})]},
  {id:"B",label:"Jugar todo mientras estés bien",intentTags:["load","play_all"],primaryMessage:"Mantienes disponibilidad total mientras los controles sigan siendo compatibles.",secondaryMessage:"La continuidad puede sostener la racha y aumentar riesgo acumulado.",primaryEffects:[n("professional.roleSecurity",2),n("professional.bodyLoad",4)],secondaryEffects:[n("professional.recoveryMargin",-4),n("professional.bodyLoad",6)],primarySeedTransitions:[tr("SEED_LOAD_MANAGEMENT",{peak26:"play_all"})],secondarySeedTransitions:[tr("SEED_LOAD_MANAGEMENT",{peak26:"play_all"})]},
  {id:"C",label:"Elegir tú qué partido descansar",intentTags:["load","choose_rest"],primaryMessage:"Aceptas descansar pero quieres decidir dónde asumes el coste deportivo.",secondaryMessage:"Ganas control y puedes tensionar la planificación del técnico.",primaryEffects:[n("professional.careerControl",4),n("professional.recoveryMargin",3)],secondaryEffects:[n("professional.institutionalTrust",-1),n("professional.recoveryMargin",2)],primarySeedTransitions:[tr("SEED_LOAD_MANAGEMENT",{peak26:"player_selects"})],secondarySeedTransitions:[tr("SEED_LOAD_MANAGEMENT",{peak26:"player_selects"})]},
  {id:"D",label:"Aceptar descanso solo si el club lo comunica como plan físico",intentTags:["load","public_plan"],primaryMessage:"Aceptas la descarga y pides que se explique como planificación física.",secondaryMessage:"La comunicación protege parte del relato y puede amplificar una rotación normal.",primaryEffects:[n("professional.recoveryMargin",4),n("professional.careerControl",2)],secondaryEffects:[n("reputation.mediaHeat",1),n("professional.recoveryMargin",3)],primarySeedTransitions:[tr("SEED_LOAD_MANAGEMENT",{peak26:"rest_public_plan"})],secondarySeedTransitions:[tr("SEED_LOAD_MANAGEMENT",{peak26:"rest_public_plan"})]}
 ],gates:[{path:"facts.highCongestionRestProposal",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_LOAD_MANAGEMENT"],seedsWrite:["SEED_LOAD_MANAGEMENT"],
 tags:["medical","calendar","a6_ready_external_blocker","needs_congestion_rest_proposal","needs_seed_peak_load_origin_alignment","t5_30"],canonStatus:"verified"
});

const RIV26=ambiguousEvent({
 id:"EVT_26_RIV_001",ageWindow:[26,26],phase:"26_30",family:"sport",title:"Adrián en el otro vestuario",
 body:"Adrián Costa llega al mismo escenario de élite o a un rival directo. La prensa vende el reencuentro como «la comparación que empezó en Valdoria» aunque vuestras carreras ya sean distintas.",
 visible:["Conoces su club, forma y declaraciones públicas."],uncertain:["No sabes cuánto le importa realmente la comparación ni qué dijo en privado."],
 choices:[
  {id:"A",label:"Alimentar la rivalidad deportiva",intentTags:["rivalry","embrace"],primaryMessage:"Aceptas la comparación como parte pública del partido sin convertirla en hostilidad personal.",secondaryMessage:"La rivalidad puede aumentar foco y también cansar a ambos.",primaryEffects:[n("professional.publicMyth",3),n("professional.publicPolarization",2)],secondaryEffects:[n("reputation.mediaHeat",3),n("professional.publicPolarization",3)],primarySeedTransitions:[tr("SEED_ADRIAN_MIRROR",{elite26:"embrace_rivalry"})],secondarySeedTransitions:[tr("SEED_ADRIAN_MIRROR",{elite26:"embrace_rivalry"})]},
  {id:"B",label:"Quitar importancia",intentTags:["rivalry","downplay"],primaryMessage:"Tratas la comparación como narrativa externa y no como eje de tu carrera.",secondaryMessage:"Reduces combustible público sin impedir que el partido siga siendo comparado.",primaryEffects:[n("professional.careerControl",3),n("reputation.mediaHeat",-1)],secondaryEffects:[n("professional.publicMyth",-1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_ADRIAN_MIRROR",{elite26:"downplay"})],secondarySeedTransitions:[tr("SEED_ADRIAN_MIRROR",{elite26:"downplay"})]},
  {id:"C",label:"Contactarle en privado antes del partido",intentTags:["rivalry","private_contact"],primaryMessage:"Intentas separar relación privada y relato público antes del reencuentro.",secondaryMessage:"La conversación puede normalizar la comparación sin controlar cómo hablará cada uno después.",primaryEffects:[n("professional.environmentStability",2),n("professional.careerControl",2)],secondaryEffects:[n("professional.publicPolarization",-1),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_ADRIAN_MIRROR",{elite26:"private_contact"})],secondarySeedTransitions:[tr("SEED_ADRIAN_MIRROR",{elite26:"private_contact"})]},
  {id:"D",label:"Usar la historia para una campaña conjunta si aparece",intentTags:["rivalry","commercial"],primaryMessage:"Aceptas que la comparación tenga una dimensión comercial si ambos controláis el marco.",secondaryMessage:"La campaña puede convertir una rivalidad deportiva en activo de marca y hacerla más difícil de abandonar.",primaryEffects:[n("professional.commercialPower",4),n("professional.publicMyth",2)],secondaryEffects:[n("professional.publicPolarization",2),n("reputation.mediaHeat",2)],primarySeedTransitions:[tr("SEED_ADRIAN_MIRROR",{elite26:"joint_campaign"})],secondarySeedTransitions:[tr("SEED_ADRIAN_MIRROR",{elite26:"joint_campaign"})]}
 ],gates:[{path:"facts.adrianEliteDirectRivalContext",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_ADRIAN_MIRROR"],seedsWrite:["SEED_ADRIAN_MIRROR"],npcRefs:["NPC_PLR_15"],
 tags:["rivalry","adrian","a6_ready_external_blocker","needs_adrian_current_sport_context","needs_seed_public_rivalry_origin_alignment","t5_30"],canonStatus:"verified"
});

const NAT28=ambiguousEvent({
 id:"EVT_28_NAT_001",ageWindow:[28,28],phase:"26_30",family:"selection",title:"Un gran torneo con minutos limitados",
 body:"Llegas a un gran torneo como líder de vestuario, pero el seleccionador planea gestionar tus minutos o usar una posición distinta.",
 visible:["Conoces el plan comunicado y tu estado físico."],uncertain:["No sabes si los resultados obligarán a cambiarlo ni si será tu último torneo en pleno pico."],
 choices:[
  {id:"A",label:"Aceptar el plan",intentTags:["national","accept_plan"],primaryMessage:"Aceptas la gestión prevista sin convertirla en renuncia a competir.",secondaryMessage:"La cooperación protege carga y deja abierta la jerarquía real del torneo.",primaryEffects:[n("professional.nationalPower",2),n("professional.recoveryMargin",3)],secondaryEffects:[n("professional.nationalPower",1),n("professional.roleSecurity",-1)],primarySeedTransitions:[tr("SEED_MAJOR_TOURNAMENT",{mature28:"accept_plan"})],secondarySeedTransitions:[tr("SEED_MAJOR_TOURNAMENT",{mature28:"accept_plan"})]},
  {id:"B",label:"Pedir empezar partidos grandes y descansar otros",intentTags:["national","selective_starts"],primaryMessage:"Intentas concentrar minutos en las citas de mayor impacto.",secondaryMessage:"La propuesta puede encajar con carga y crear una jerarquía difícil de sostener si cambian resultados.",primaryEffects:[n("professional.careerControl",4),n("professional.nationalPower",2)],secondaryEffects:[n("professional.recoveryMargin",2),n("professional.environmentStability",-1)],primarySeedTransitions:[tr("SEED_MAJOR_TOURNAMENT",{mature28:"big_games"})],secondarySeedTransitions:[tr("SEED_MAJOR_TOURNAMENT",{mature28:"big_games"})]},
  {id:"C",label:"Competir por rol sin acuerdos previos",intentTags:["national","compete"],primaryMessage:"Rechazas una jerarquía cerrada y aceptas competir entrenamiento a entrenamiento.",secondaryMessage:"Mantienes ambición y elevas incertidumbre de carga y minutos.",primaryEffects:[n("professional.nationalPower",3),n("professional.recoveryMargin",-1)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.environmentStability",-1)],primarySeedTransitions:[tr("SEED_MAJOR_TOURNAMENT",{mature28:"compete_open"})],secondarySeedTransitions:[tr("SEED_MAJOR_TOURNAMENT",{mature28:"compete_open"})]},
  {id:"D",label:"Priorizar posición habitual aunque juegues menos",intentTags:["national","role_identity"],primaryMessage:"Prefieres menos minutos en tu rol principal a más minutos en una posición distinta.",secondaryMessage:"Proteges identidad deportiva y reduces flexibilidad del seleccionador.",primaryEffects:[n("professional.careerControl",3),n("professional.roleAdaptability",-1)],secondaryEffects:[n("professional.nationalPower",-1),n("professional.roleSecurity",1)],primarySeedTransitions:[tr("SEED_MAJOR_TOURNAMENT",{mature28:"usual_position"})],secondarySeedTransitions:[tr("SEED_MAJOR_TOURNAMENT",{mature28:"usual_position"})]}
 ],gates:[{path:"facts.majorTournamentManagedRolePlan",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_MAJOR_TOURNAMENT","SEED_NATIONAL_CAPTAINCY"],seedsWrite:["SEED_MAJOR_TOURNAMENT"],
 tags:["selection","tournament","a6_ready_external_blocker","needs_tournament_squad_and_role_plan","needs_seed_mature_tournament_role_catalog","t5_30"],canonStatus:"verified"
});

export const T530_STAGED_PRINCIPAL_EVENTS:EventDefinition[]=[HOME26,CAP26,MED26,RIV26,NAT28];
