import type { EventDefinition, SeedTransition } from "../../../core/types.js";
import { ambiguousEvent, n } from "../18_20/helpers.js";
const tr=(seedId:string,payload:Record<string,string|number|boolean|null>):SeedTransition=>({seedId,action:"transform",payload});

const EUR26=ambiguousEvent({
 id:"EVT_26_EUR_001",ageWindow:[26,26],phase:"26_30",family:"sport",title:"La noche en la que no empiezas",
 body:"Llega una eliminatoria o partido máximo y el entrenador elige un sistema que te deja de inicio en el banquillo pese a tu estatus. Te explica que espera que decidas la última media hora.",
 visible:["Conoces el plan táctico y la conversación privada."],uncertain:["No sabes si es una decisión aislada o señal de nueva jerarquía."],
 choices:[
  {id:"A",label:"Aceptar el plan sin discutir",intentTags:["europe","accept_bench"],primaryMessage:"Aceptas el papel de impacto posterior sin convertir una suplencia en conflicto previo.",secondaryMessage:"La decisión puede salir bien o mal y quedar como precedente de uso futuro.",primaryEffects:[n("professional.institutionalTrust",3),n("professional.environmentStability",2)],secondaryEffects:[n("professional.roleSecurity",-1),n("professional.institutionalTrust",2)],primarySeedTransitions:[tr("SEED_EURO_REGISTRATION",{bigGame26:"accept_bench"})],secondarySeedTransitions:[tr("SEED_EURO_REGISTRATION",{bigGame26:"accept_bench"})]},
  {id:"B",label:"Pedir explicación táctica detallada",intentTags:["europe","ask_plan"],primaryMessage:"Pides entender el plan antes de asumir que la suplencia expresa jerarquía.",secondaryMessage:"La conversación puede aclarar la decisión o mostrar que el cambio es más profundo.",primaryEffects:[n("professional.careerControl",3),n("professional.institutionalTrust",2)],secondaryEffects:[n("professional.careerControl",2),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_EURO_REGISTRATION",{bigGame26:"ask_detail"})],secondarySeedTransitions:[tr("SEED_EURO_REGISTRATION",{bigGame26:"ask_detail"})]},
  {id:"C",label:"Mostrar desacuerdo y exigir empezar",intentTags:["europe","demand_start"],primaryMessage:"Defiendes tu jerarquía y pides cambiar el once.",secondaryMessage:"La presión puede cambiar nada, cambiar el plan o dañar confianza antes del partido.",primaryEffects:[n("professional.careerControl",3),n("professional.institutionalTrust",-2)],secondaryEffects:[n("professional.environmentStability",-2),n("professional.publicPolarization",1)],primarySeedTransitions:[tr("SEED_EURO_REGISTRATION",{bigGame26:"demand_start"})],secondarySeedTransitions:[tr("SEED_EURO_REGISTRATION",{bigGame26:"demand_start"})]},
  {id:"D",label:"Aceptar pero pedir que no se venda públicamente como descanso",intentTags:["europe","message_control"],primaryMessage:"Aceptas la decisión deportiva y separas el relato público de una falsa explicación física.",secondaryMessage:"Proteges el significado de la decisión sin impedir que otros la interpreten.",primaryEffects:[n("professional.careerControl",4),n("reputation.mediaHeat",-1)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.careerControl",3)],primarySeedTransitions:[tr("SEED_EURO_REGISTRATION",{bigGame26:"accept_no_rest_story"})],secondarySeedTransitions:[tr("SEED_EURO_REGISTRATION",{bigGame26:"accept_no_rest_story"})]}
 ],gates:[{path:"facts.bigContinentalBenchPlan",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_EURO_REGISTRATION","SEED_CAPTAINCY_STYLE"],seedsWrite:["SEED_EURO_REGISTRATION"],
 tags:["sport","europe","a6_ready_external_blocker","needs_competition_stage_starting_status","needs_seed_big_game_bench_origin_alignment","t5_31"],canonStatus:"verified"
});

const MATCH26=ambiguousEvent({
 id:"EVT_26_MATCH_001",ageWindow:[26,26],phase:"26_30",family:"sport",title:"El penalti para un récord",
 body:"Estás a un gol de un récord personal o del club. En un partido resuelto llega un penalti y el lanzador habitual también compite por una cifra propia.",
 visible:["Conoces marcador, jerarquía de lanzadores y cifra."],uncertain:["No sabes cómo interpreta el vestuario perseguir el récord ni si habrá otra oportunidad."],
 choices:[
  {id:"A",label:"Pedir el balón",intentTags:["record","ask_penalty"],primaryMessage:"Pides lanzar por el récord sin determinar el resultado del penalti.",secondaryMessage:"La ambición queda visible y el desenlace deportivo seguirá perteneciendo al resolver autorizado.",primaryEffects:[n("professional.publicMyth",2),n("professional.lockerPower",-1)],secondaryEffects:[n("professional.publicPolarization",2),n("professional.lockerPower",-2)],primarySeedTransitions:[tr("SEED_PENALTY_HIERARCHY",{record26:"ask_ball"})],secondarySeedTransitions:[tr("SEED_PENALTY_HIERARCHY",{record26:"ask_ball"})]},
  {id:"B",label:"Respetar al lanzador",intentTags:["record","respect_taker"],primaryMessage:"Mantienes la jerarquía existente aunque el récord esté a un gol.",secondaryMessage:"La decisión protege reglas internas y no garantiza otra oportunidad.",primaryEffects:[n("professional.lockerPower",3),n("professional.environmentStability",2)],secondaryEffects:[n("professional.publicMyth",-1),n("professional.lockerPower",2)],primarySeedTransitions:[tr("SEED_PENALTY_HIERARCHY",{record26:"respect_taker"})],secondarySeedTransitions:[tr("SEED_PENALTY_HIERARCHY",{record26:"respect_taker"})]},
  {id:"C",label:"Hablarlo en el campo y decidir juntos",intentTags:["record","shared_decision"],primaryMessage:"Conviertes la decisión en conversación inmediata con el lanzador.",secondaryMessage:"El acuerdo puede reducir fricción o hacer visible una negociación en pleno partido.",primaryEffects:[n("professional.lockerPower",2),n("professional.careerControl",2)],secondaryEffects:[n("professional.environmentStability",1),n("professional.publicPolarization",1)],primarySeedTransitions:[tr("SEED_PENALTY_HIERARCHY",{record26:"decide_together"})],secondarySeedTransitions:[tr("SEED_PENALTY_HIERARCHY",{record26:"decide_together"})]},
  {id:"D",label:"Dejar que el capitán decida",intentTags:["record","captain_decides"],primaryMessage:"Remites la decisión a la autoridad de campo disponible.",secondaryMessage:"Evitas imponer tu objetivo y trasladas el coste de decisión al liderazgo formal.",primaryEffects:[n("professional.careerControl",1),n("professional.lockerPower",2)],secondaryEffects:[n("professional.environmentStability",1),n("professional.publicMyth",-1)],primarySeedTransitions:[tr("SEED_PENALTY_HIERARCHY",{record26:"captain_decides"})],secondarySeedTransitions:[tr("SEED_PENALTY_HIERARCHY",{record26:"captain_decides"})]}
 ],gates:[{path:"facts.resolvedMatchRecordPenaltyMoment",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_PENALTY_HIERARCHY"],seedsWrite:["SEED_PENALTY_HIERARCHY"],
 tags:["sport","penalty","record","a6_ready_external_blocker","needs_a4_penalty_context_and_resolver","needs_seed_record_chase_origin_alignment","t5_31"],canonStatus:"verified"
});

const TEAM26B=ambiguousEvent({
 id:"EVT_26_TEAM_002",ageWindow:[26,26],phase:"26_30",family:"team",title:"El sustituto te pregunta si debe irse",
 body:"Un compañero joven que apenas juega te pide consejo. Su agente tiene una cesión; el entrenador te ha pedido en privado que le convenzas de quedarse porque lo necesita como fondo de plantilla.",
 visible:["Conoces ambas peticiones y la situación deportiva."],uncertain:["No sabes si realmente tendrá minutos ni si la cesión es buena."],
 choices:[
  {id:"A",label:"Decirle lo que quiere el entrenador",intentTags:["mentor","club_request"],primaryMessage:"Trasladas el deseo del técnico sin prometer minutos que no controlas.",secondaryMessage:"Ayudas al club y puedes sesgar una decisión personal del joven.",primaryEffects:[n("professional.institutionalTrust",3),n("professional.environmentStability",1)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.careerControl",-1)],primarySeedTransitions:[tr("SEED_YOUNG_MENTOR",{advice26:"coach_request"})],secondarySeedTransitions:[tr("SEED_YOUNG_MENTOR",{advice26:"coach_request"})]},
  {id:"B",label:"Contarle también la petición del técnico y dejarle decidir",intentTags:["mentor","transparent"],primaryMessage:"Revelas el conflicto de intereses y dejas la decisión en manos del jugador.",secondaryMessage:"La transparencia protege autonomía y puede romper confianza privada con el técnico.",primaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",2)],secondaryEffects:[n("professional.institutionalTrust",-2),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_YOUNG_MENTOR",{advice26:"full_context"})],secondarySeedTransitions:[tr("SEED_YOUNG_MENTOR",{advice26:"full_context"})]},
  {id:"C",label:"Recomendar la cesión",intentTags:["mentor","loan"],primaryMessage:"Priorizas que el joven busque minutos fuera según la información disponible.",secondaryMessage:"La cesión puede ayudar o salir mal por factores que tu consejo no controla.",primaryEffects:[n("professional.environmentStability",1),n("professional.careerControl",2)],secondaryEffects:[n("professional.institutionalTrust",-1),n("professional.publicPolarization",1)],primarySeedTransitions:[tr("SEED_YOUNG_MENTOR",{advice26:"recommend_loan"})],secondarySeedTransitions:[tr("SEED_YOUNG_MENTOR",{advice26:"recommend_loan"})]},
  {id:"D",label:"No aconsejar sobre una decisión que afecta a su carrera",intentTags:["mentor","boundary"],primaryMessage:"Le das información factual y te niegas a decidir por él.",secondaryMessage:"Proteges su autonomía y reduces la utilidad directa que ambos lados buscaban en ti.",primaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",1)],secondaryEffects:[n("professional.lockerPower",-1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_YOUNG_MENTOR",{advice26:"no_recommendation"})],secondarySeedTransitions:[tr("SEED_YOUNG_MENTOR",{advice26:"no_recommendation"})]}
 ],gates:[{path:"facts.youngTeammateLoanAdviceConflict",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_YOUNG_MENTOR"],seedsWrite:["SEED_YOUNG_MENTOR"],
 tags:["team","mentor","a6_ready_external_blocker","needs_current_club_young_teammate_and_loan_fact","needs_seed_mentor_advice_origin_alignment","t5_31"],canonStatus:"verified"
});

const NAT26B=ambiguousEvent({
 id:"EVT_26_NAT_002",ageWindow:[26,26],phase:"26_30",family:"selection",title:"Titular con el club, suplente con la selección",
 body:"Con tu club eres referencia. En selección, el sistema favorece a otro jugador. El seleccionador te ofrece un rol de revulsivo y liderazgo fuera del once.",
 visible:["Conoces el rol comunicado y las razones tácticas."],uncertain:["No sabes si la jerarquía cambiará ni cuánto mercado o imagen perderías al asumirla."],
 choices:[
  {id:"A",label:"Aceptar y especializarte en ese rol",intentTags:["national","accept_role"],primaryMessage:"Aceptas que tu utilidad internacional pueda ser distinta a la del club.",secondaryMessage:"Puedes volverte imprescindible de otra forma y normalizar una jerarquía secundaria.",primaryEffects:[n("professional.nationalPower",3),n("professional.roleAdaptability",3)],secondaryEffects:[n("professional.nationalPower",2),n("professional.publicMyth",-1)],primarySeedTransitions:[tr("SEED_FIRST_ABSOLUTE_CALL",{matureRole26:"accept_impact"})],secondarySeedTransitions:[tr("SEED_FIRST_ABSOLUTE_CALL",{matureRole26:"accept_impact"})]},
  {id:"B",label:"Pedir competir por otra posición",intentTags:["national","alternate_position"],primaryMessage:"Intentas abrir otra vía táctica para competir por titularidad.",secondaryMessage:"La flexibilidad puede generar encaje o diluir tu rendimiento habitual.",primaryEffects:[n("professional.roleAdaptability",4),n("professional.careerControl",2)],secondaryEffects:[n("professional.nationalPower",1),n("professional.environmentStability",-1)],primarySeedTransitions:[tr("SEED_FIRST_ABSOLUTE_CALL",{matureRole26:"alternate_position"})],secondarySeedTransitions:[tr("SEED_FIRST_ABSOLUTE_CALL",{matureRole26:"alternate_position"})]},
  {id:"C",label:"Expresar que no te satisface",intentTags:["national","challenge_role"],primaryMessage:"Dejas claro que quieres competir por más sin abandonar la convocatoria.",secondaryMessage:"La honestidad puede elevar competencia o reducir confianza.",primaryEffects:[n("professional.careerControl",3),n("professional.nationalPower",1)],secondaryEffects:[n("professional.environmentStability",-2),n("professional.publicPolarization",1)],primarySeedTransitions:[tr("SEED_FIRST_ABSOLUTE_CALL",{matureRole26:"unsatisfied"})],secondarySeedTransitions:[tr("SEED_FIRST_ABSOLUTE_CALL",{matureRole26:"unsatisfied"})]},
  {id:"D",label:"Reducir compromisos de selección fuera de partidos",intentTags:["national","reduce_nonmatch"],primaryMessage:"Mantienes disponibilidad competitiva y recortas carga periférica.",secondaryMessage:"Proteges recuperación y puedes perder presencia informal en el grupo.",primaryEffects:[n("professional.recoveryMargin",3),n("professional.nationalPower",-1)],secondaryEffects:[n("professional.recoveryMargin",2),n("professional.environmentStability",-1)],primarySeedTransitions:[tr("SEED_FIRST_ABSOLUTE_CALL",{matureRole26:"reduce_nonmatch"})],secondarySeedTransitions:[tr("SEED_FIRST_ABSOLUTE_CALL",{matureRole26:"reduce_nonmatch"})]}
 ],gates:[{path:"facts.nationalImpactSubRoleOffer",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_FIRST_ABSOLUTE_CALL"],seedsWrite:["SEED_FIRST_ABSOLUTE_CALL"],
 tags:["selection","role","a6_ready_external_blocker","needs_current_national_role_fact","needs_seed_national_role_origin_alignment","t5_31"],canonStatus:"verified"
});

const FINAL26=ambiguousEvent({
 id:"EVT_26_FINAL_001",ageWindow:[26,26],phase:"26_30",family:"sport",title:"La final y el banquillo",
 body:"Tu equipo llega a una final grande. El entrenador repite el plan de la eliminatoria: empezar sin ti y usarte después. Todo el mundo sabe que quizá sea el partido más importante de tu carrera hasta ahora.",
 visible:["Conoces el once previsto, la conversación del técnico y tu estado físico."],uncertain:["No sabes si habrá momento para entrar ni si protestar cambiaría realmente el once."],
 choices:[
  {id:"A",label:"Aceptar",intentTags:["final","accept"],primaryMessage:"Aceptas el plan y preparas tu impacto desde el banquillo.",secondaryMessage:"Puedes ganar, perder o ser decisivo después; ninguna respuesta queda fijada por la elección.",primaryEffects:[n("professional.institutionalTrust",3),n("professional.environmentStability",2)],secondaryEffects:[n("professional.roleSecurity",-1),n("professional.institutionalTrust",2)],primarySeedTransitions:[tr("SEED_SHADOW_ESCAPE",{final26:"accept_bench"})],secondarySeedTransitions:[tr("SEED_SHADOW_ESCAPE",{final26:"accept_bench"})]},
  {id:"B",label:"Pedir reconsideración una sola vez",intentTags:["final","reconsider"],primaryMessage:"Defiendes tu caso una vez y aceptas que el técnico cierre la decisión.",secondaryMessage:"La conversación puede cambiar nada o ajustar el plan sin convertirse en escalada.",primaryEffects:[n("professional.careerControl",3),n("professional.institutionalTrust",1)],secondaryEffects:[n("professional.environmentStability",-1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_SHADOW_ESCAPE",{final26:"ask_once"})],secondarySeedTransitions:[tr("SEED_SHADOW_ESCAPE",{final26:"ask_once"})]},
  {id:"C",label:"Escalar al capitán o director deportivo",intentTags:["final","escalate"],primaryMessage:"Buscas una segunda autoridad para cuestionar el plan del entrenador.",secondaryMessage:"La escalada puede aumentar presión y dañar confianza aunque el once no cambie.",primaryEffects:[n("professional.careerControl",2),n("professional.institutionalTrust",-3)],secondaryEffects:[n("professional.environmentStability",-3),n("professional.publicPolarization",1)],primarySeedTransitions:[tr("SEED_SHADOW_ESCAPE",{final26:"escalate"})],secondarySeedTransitions:[tr("SEED_SHADOW_ESCAPE",{final26:"escalate"})]},
  {id:"D",label:"No discutir antes, pero decidir que revisarás tu futuro después",intentTags:["final","review_future"],primaryMessage:"Proteges la preparación inmediata y conviertes la decisión en dato para tu futuro.",secondaryMessage:"La calma previa no elimina el peso posterior de la suplencia.",primaryEffects:[n("professional.careerControl",4),n("professional.environmentStability",2)],secondaryEffects:[n("reputation.marketHeat",2),n("professional.careerControl",3)],primarySeedTransitions:[tr("SEED_SHADOW_ESCAPE",{final26:"review_after"})],secondarySeedTransitions:[tr("SEED_SHADOW_ESCAPE",{final26:"review_after"})]}
 ],gates:[{path:"facts.majorFinalBenchPlan",op:"eq",value:true}],weight:18,cooldown:99999,seedsRead:["SEED_SHADOW_ESCAPE","SEED_EURO_REGISTRATION"],seedsWrite:["SEED_SHADOW_ESCAPE"],
 tags:["sport","final","a6_ready_external_blocker","needs_a4_final_stage_and_starting_status","needs_seed_final_bench_origin_alignment","t5_31"],canonStatus:"verified"
});

export const T531_STAGED_PRINCIPAL_EVENTS:EventDefinition[]=[EUR26,MATCH26,TEAM26B,NAT26B,FINAL26];
