import type { EventDefinition, SeedTransition } from "../../../core/types.js";
import { ambiguousEvent, n } from "../18_20/helpers.js";
const tr=(seedId:string,payload:Record<string,string|number|boolean|null>):SeedTransition=>({seedId,action:"transform",payload});

const RIVAS=ambiguousEvent({
 id:"CEVT_26_RIVAS_03",ageWindow:[26,30],phase:"26_30",family:"conditional",title:"Rivas te quiere... con condiciones",
 body:"Rivas impulsa tu fichaje pero deja por escrito dudas sobre encaje o salario. Su historia contigo no elimina su deber profesional.",
 visible:["Conoces su apoyo y las condiciones que ha dejado por escrito."],uncertain:["No sabes cuánto margen real tiene dentro del proceso ni si sus dudas pesan más que su confianza personal."],
 choices:[
  {id:"A",label:"Llamar a Rivas y hablar de las condiciones",intentTags:["rivas","direct"],primaryMessage:"Usas la relación para entender sus dudas sin pedir que las retire.",secondaryMessage:"La conversación aclara matices y puede confirmar que la objeción es profesional, no personal.",primaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",1)],secondaryEffects:[n("professional.careerControl",2),n("professional.publicPolarization",1)],primarySeedTransitions:[tr("SEED_RIVAS_TRUST",{callback26:"direct_conditions_call"})],secondarySeedTransitions:[tr("SEED_RIVAS_TRUST",{callback26:"direct_conditions_call"})]},
  {id:"B",label:"Dejar que el proceso siga por vía formal",intentTags:["rivas","formal"],primaryMessage:"Separas la relación histórica de la decisión institucional.",secondaryMessage:"Proteges límites y renuncias a información informal que podría ayudarte.",primaryEffects:[n("professional.institutionalTrust",2),n("professional.careerControl",2)],secondaryEffects:[n("professional.environmentStability",1),n("professional.careerControl",1)],primarySeedTransitions:[tr("SEED_RIVAS_TRUST",{callback26:"formal_process"})],secondarySeedTransitions:[tr("SEED_RIVAS_TRUST",{callback26:"formal_process"})]},
  {id:"C",label:"Buscar otra referencia dentro del club",intentTags:["rivas","second_reference"],primaryMessage:"Contrastas la valoración con otra persona sin invalidar a Rivas.",secondaryMessage:"La segunda referencia amplía contexto y puede revelar desacuerdos internos.",primaryEffects:[n("professional.careerControl",3),n("professional.institutionalPower",1)],secondaryEffects:[n("professional.environmentStability",-1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_RIVAS_TRUST",{callback26:"second_reference"})],secondarySeedTransitions:[tr("SEED_RIVAS_TRUST",{callback26:"second_reference"})]}
 ],gates:[{path:"flags.HAS_SEED_RIVAS_TRUST",op:"eq",value:true},{path:"facts.rivasCompatibleInstitutionRole",op:"eq",value:true}],weight:10,cooldown:99999,
 seedsRead:["SEED_RIVAS_TRUST"],seedsWrite:["SEED_RIVAS_TRUST"],npcRefs:["NPC_ACA_01"],tags:["conditional","rivas","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const MENA=ambiguousEvent({
 id:"CEVT_26_MENA_03",ageWindow:[26,30],phase:"26_30",family:"conditional",title:"Mena diseña el partido contra tu nueva posición",
 body:"Mena conoce hábitos antiguos y prepara un plan pensando que no has cambiado. Su lectura puede ser obsoleta y aun ser peligrosa.",
 visible:["Conoces qué comportamientos antiguos espera explotar el rival."],uncertain:["No sabes si Mena realmente subestima tu nueva versión o si quiere empujarte a cambiar de nuevo."],
 choices:[
  {id:"A",label:"Insistir en tu nueva versión",intentTags:["mena","new_role"],primaryMessage:"Confías en que la reinvención ya cambió suficientes hábitos para romper su lectura.",secondaryMessage:"La novedad puede sorprender o hacerte previsible de otra manera.",primaryEffects:[n("professional.roleAdaptability",3),n("professional.careerControl",2)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.roleAdaptability",2)],primarySeedTransitions:[tr("SEED_MENA_EARLY_READ",{callback26:"trust_new_role"})],secondarySeedTransitions:[tr("SEED_MENA_EARLY_READ",{callback26:"trust_new_role"})]},
  {id:"B",label:"Recuperar recursos viejos solo para este partido",intentTags:["mena","old_tools"],primaryMessage:"Usas hábitos que Mena cree conocer como recurso situacional, no como vuelta permanente.",secondaryMessage:"La mezcla puede desordenar su plan o devolverte a automatismos menos eficientes.",primaryEffects:[n("professional.tacticalReading",3),n("professional.careerControl",2)],secondaryEffects:[n("professional.roleAdaptability",-1),n("professional.tacticalReading",2)],primarySeedTransitions:[tr("SEED_MENA_EARLY_READ",{callback26:"old_tools_once"})],secondarySeedTransitions:[tr("SEED_MENA_EARLY_READ",{callback26:"old_tools_once"})]},
  {id:"C",label:"Mezclar ambas versiones durante el partido",intentTags:["mena","hybrid"],primaryMessage:"Tratas la memoria de Mena como información táctica y alternas comportamientos.",secondaryMessage:"La variación eleva imprevisibilidad y exigencia cognitiva.",primaryEffects:[n("professional.tacticalReading",4),n("professional.roleAdaptability",3)],secondaryEffects:[n("professional.bodyLoad",1),n("professional.roleAdaptability",2)],primarySeedTransitions:[tr("SEED_MENA_EARLY_READ",{callback26:"hybrid_versions"})],secondarySeedTransitions:[tr("SEED_MENA_EARLY_READ",{callback26:"hybrid_versions"})]}
 ],gates:[{path:"flags.HAS_SEED_MENA_EARLY_READ",op:"eq",value:true},{path:"flags.HAS_SEED_POSITIONAL_REINVENTION",op:"eq",value:true},{path:"facts.menaCurrentOpponentPlan",op:"eq",value:true}],weight:10,cooldown:99999,
 seedsRead:["SEED_MENA_EARLY_READ","SEED_POSITIONAL_REINVENTION"],seedsWrite:["SEED_MENA_EARLY_READ"],npcRefs:["NPC_CCH_02"],tags:["conditional","mena","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const VELA=ambiguousEvent({
 id:"CEVT_26_VELA_03",ageWindow:[26,30],phase:"26_30",family:"conditional",title:"Vela dirige la casa",
 body:"Vela participa en una decisión sobre academia, inversión o regreso. Su postura mezcla historia personal y deber institucional.",
 visible:["Conoces su cargo actual y la decisión concreta en la que participa."],uncertain:["No sabes cuánto de su postura viene de vuestra historia y cuánto del interés del club."],
 choices:[
  {id:"A",label:"Hablar con Vela como directivo o técnico, no como excompañero",intentTags:["vela","institution"],primaryMessage:"Le pides que explique la posición institucional y separas la relación personal.",secondaryMessage:"La separación aporta claridad y puede enfriar una conversación que antes era informal.",primaryEffects:[n("professional.careerControl",3),n("professional.institutionalTrust",2)],secondaryEffects:[n("professional.environmentStability",1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_VELA_STANCE",{callback26:"institutional_role"})],secondarySeedTransitions:[tr("SEED_VELA_STANCE",{callback26:"institutional_role"})]},
  {id:"B",label:"Recordarle vuestra historia antes de decidir",intentTags:["vela","history"],primaryMessage:"Introduces vuestra relación como contexto sin exigir trato favorable.",secondaryMessage:"La memoria puede humanizar la decisión o hacer más incómoda su obligación profesional.",primaryEffects:[n("professional.environmentStability",2),n("professional.homePull",2)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_VELA_STANCE",{callback26:"shared_history"})],secondarySeedTransitions:[tr("SEED_VELA_STANCE",{callback26:"shared_history"})]},
  {id:"C",label:"Pedir que otra persona cierre la decisión",intentTags:["vela","recusal"],primaryMessage:"Intentas evitar que una relación antigua cargue una decisión institucional adulta.",secondaryMessage:"La recusación reduce conflicto personal y también pierde el contexto que Vela conoce.",primaryEffects:[n("professional.careerControl",4),n("professional.institutionalTrust",1)],secondaryEffects:[n("professional.institutionalPower",-1),n("professional.careerControl",3)],primarySeedTransitions:[tr("SEED_VELA_STANCE",{callback26:"ask_recusal"})],secondarySeedTransitions:[tr("SEED_VELA_STANCE",{callback26:"ask_recusal"})]}
 ],gates:[{path:"flags.HAS_SEED_VELA_STANCE",op:"eq",value:true},{path:"facts.velaCurrentUdvInstitutionRole",op:"eq",value:true}],weight:10,cooldown:99999,
 seedsRead:["SEED_VELA_STANCE"],seedsWrite:["SEED_VELA_STANCE"],npcRefs:["NPC_PLR_10"],tags:["conditional","vela","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const BRUNO=ambiguousEvent({
 id:"CEVT_26_BRUNO_04",ageWindow:[26,30],phase:"26_30",family:"conditional",title:"Bruno se retira",
 body:"Bruno anuncia su retirada. Según vuestra relación, puede pedirte participar en su despedida o pedir un contacto para empezar como agente o técnico.",
 visible:["Sabes qué te pide y qué planes profesionales ha hecho públicos."],uncertain:["No sabes si su siguiente carrera funcionará ni cuánto peso tendrá vuestra vieja deuda o favor."],
 choices:[
  {id:"A",label:"Participar en la despedida y cerrar la etapa deportiva",intentTags:["bruno","farewell"],primaryMessage:"Tratas la retirada como cierre de una relación deportiva, no como obligación profesional futura.",secondaryMessage:"El gesto honra la historia y puede reactivar expectativas de ayuda posterior.",primaryEffects:[n("professional.legacyCapital",3),n("professional.environmentStability",2)],secondaryEffects:[n("professional.publicMyth",1),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_BRUNO_FAVOR",{callback26:"farewell"})],secondarySeedTransitions:[tr("SEED_BRUNO_FAVOR",{callback26:"farewell"})]},
  {id:"B",label:"Ayudarle con un contacto profesional",intentTags:["bruno","career_contact"],primaryMessage:"Le das una introducción concreta sin garantizarle trabajo.",secondaryMessage:"El favor cambia de naturaleza: ya no afecta minutos o vestuario, sino una segunda carrera.",primaryEffects:[n("professional.legacyCapital",2),n("professional.careerControl",1)],secondaryEffects:[n("professional.environmentStability",1),n("professional.careerControl",1)],primarySeedTransitions:[tr("SEED_BRUNO_FAVOR",{callback26:"professional_contact"})],secondarySeedTransitions:[tr("SEED_BRUNO_FAVOR",{callback26:"professional_contact"})]},
  {id:"C",label:"Mantener afecto sin comprometer tu red profesional",intentTags:["bruno","boundary"],primaryMessage:"Separar amistad y contactos evita convertir una historia pasada en deuda indefinida.",secondaryMessage:"El límite es claro y puede sentirse frío en un momento importante.",primaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",1)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_BRUNO_FAVOR",{callback26:"personal_only"})],secondarySeedTransitions:[tr("SEED_BRUNO_FAVOR",{callback26:"personal_only"})]}
 ],gates:[{path:"flags.HAS_SEED_BRUNO_FAVOR",op:"eq",value:true},{path:"facts.brunoRetirementNow",op:"eq",value:true}],weight:10,cooldown:99999,
 seedsRead:["SEED_BRUNO_FAVOR"],seedsWrite:["SEED_BRUNO_FAVOR"],npcRefs:["NPC_PLR_12"],tags:["conditional","bruno","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const NANO=ambiguousEvent({
 id:"CEVT_26_NANO_03",ageWindow:[26,30],phase:"26_30",family:"conditional",title:"Nano vuelve a estar cerca",
 body:"Nano firma por un club de tu órbita o vuelve a destacar. Rechaza que su historia sea contada como «el amigo de».",
 visible:["Conoces su nuevo contexto deportivo y su postura pública."],uncertain:["No sabes si quiere recuperar cercanía privada o solo simetría pública."],
 choices:[
  {id:"A",label:"Tratarle públicamente como carrera propia",intentTags:["nano","symmetry"],primaryMessage:"Evitas usar vuestra amistad para explicar su trayectoria.",secondaryMessage:"La simetría pública puede reparar una sombra antigua sin garantizar cercanía privada.",primaryEffects:[n("professional.environmentStability",2),n("professional.legacyCapital",1)],secondaryEffects:[n("professional.publicPolarization",-1),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_NANO_SHADOW",{callback26:"career_symmetry"})],secondarySeedTransitions:[tr("SEED_NANO_SHADOW",{callback26:"career_symmetry"})]},
  {id:"B",label:"Hablar con Nano en privado antes de cualquier gesto",intentTags:["nano","private"],primaryMessage:"Buscas entender qué necesita de ti sin convertir la conversación en contenido.",secondaryMessage:"La privacidad protege la relación y deja sin resolver el relato público inmediato.",primaryEffects:[n("professional.careerControl",2),n("professional.environmentStability",2)],secondaryEffects:[n("reputation.mediaHeat",-1),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_NANO_SHADOW",{callback26:"private_first"})],secondarySeedTransitions:[tr("SEED_NANO_SHADOW",{callback26:"private_first"})]},
  {id:"C",label:"No intervenir en su narrativa",intentTags:["nano","distance"],primaryMessage:"Aceptas que Nano defina solo cómo quiere contar su carrera.",secondaryMessage:"El límite devuelve autonomía y puede mantener distancia entre ambos.",primaryEffects:[n("professional.careerControl",3),n("professional.publicMyth",-1)],secondaryEffects:[n("professional.environmentStability",-1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_NANO_SHADOW",{callback26:"no_intervention"})],secondarySeedTransitions:[tr("SEED_NANO_SHADOW",{callback26:"no_intervention"})]}
 ],gates:[{path:"flags.HAS_SEED_NANO_SHADOW",op:"eq",value:true},{path:"facts.nanoCompatibleCareerNearPlayer",op:"eq",value:true}],weight:10,cooldown:99999,
 seedsRead:["SEED_NANO_SHADOW"],seedsWrite:["SEED_NANO_SHADOW"],npcRefs:["NPC_PLR_14"],tags:["conditional","nano","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

export const T532_STAGED_CONDITIONAL_EVENTS:EventDefinition[]=[RIVAS,MENA,VELA,BRUNO,NANO];
