import type { EventDefinition, SeedTransition } from "../../../core/types.js";
import { ambiguousEvent, n } from "../18_20/helpers.js";
const tr=(seedId:string,payload:Record<string,string|number|boolean|null>):SeedTransition=>({seedId,action:"transform",payload});

const FAMILY=ambiguousEvent({
 id:"CEVT_26_FAMILY_03",ageWindow:[26,30],phase:"26_30",family:"conditional",title:"El negocio familiar despega",
 body:"La inversión familiar funciona y la familia quiere reinvertir más. Un buen resultado pasado no demuestra que aumentar riesgo vuelva a ser correcto.",
 visible:["Conoces beneficios, capital solicitado y estructura actual."],uncertain:["No sabes si el siguiente ciclo repetirá el rendimiento ni cuánto riesgo nuevo asume cada familiar."],
 choices:[
  {id:"A",label:"Aumentar exposición",intentTags:["family","reinvest"],primaryMessage:"Reinviertes más capital después de un resultado positivo.",secondaryMessage:"El éxito previo aumenta confianza y también concentración de riesgo.",primaryEffects:[n("professional.moneyComfort",-4),n("professional.environmentStability",2)],secondaryEffects:[n("professional.moneyComfort",-6),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_FAMILY_BUSINESS",{callback26:"reinvest_more"})],secondarySeedTransitions:[tr("SEED_FAMILY_BUSINESS",{callback26:"reinvest_more"})]},
  {id:"B",label:"Retirar parte de los beneficios",intentTags:["family","take_profit"],primaryMessage:"Consolidas parte del resultado y reduces exposición adicional.",secondaryMessage:"Proteges liquidez y puedes frenar una expansión que la familia considera oportuna.",primaryEffects:[n("professional.moneyComfort",4),n("professional.careerControl",2)],secondaryEffects:[n("professional.environmentStability",-1),n("professional.moneyComfort",3)],primarySeedTransitions:[tr("SEED_FAMILY_BUSINESS",{callback26:"take_profit"})],secondarySeedTransitions:[tr("SEED_FAMILY_BUSINESS",{callback26:"take_profit"})]},
  {id:"C",label:"Profesionalizar antes de reinvertir",intentTags:["family","governance"],primaryMessage:"Condicionas el siguiente paso a una estructura profesional de gestión y control.",secondaryMessage:"La gobernanza reduce ambigüedad y puede sentirse como pérdida de autonomía familiar.",primaryEffects:[n("professional.careerControl",4),n("professional.environmentStability",1)],secondaryEffects:[n("professional.environmentStability",-1),n("professional.careerControl",3)],primarySeedTransitions:[tr("SEED_FAMILY_BUSINESS",{callback26:"professionalize_first"})],secondarySeedTransitions:[tr("SEED_FAMILY_BUSINESS",{callback26:"professionalize_first"})]}
 ],gates:[{path:"flags.HAS_SEED_FAMILY_BUSINESS",op:"eq",value:true},{path:"facts.familyBusinessPositiveOutcome",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_FAMILY_BUSINESS"],seedsWrite:["SEED_FAMILY_BUSINESS"],npcRefs:["NPC_FAM_01","NPC_FAM_02"],tags:["conditional","family","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const OWNER=ambiguousEvent({
 id:"CEVT_27_OWNER_03",ageWindow:[27,30],phase:"26_30",family:"conditional",title:"Nuevo propietario, nueva promesa",
 body:"El club cambia de propiedad. La nueva dirección te declara intocable y promete fichajes mientras el entrenador queda en segundo plano.",
 visible:["Conoces el cambio de propiedad y las promesas públicas concretas."],uncertain:["No sabes si el nuevo propietario mantendrá gasto, entrenador o prioridades cuando aparezcan resultados adversos."],
 choices:[
  {id:"A",label:"Aceptar el respaldo sin pedir más promesas",intentTags:["owner","accept_support"],primaryMessage:"Aceptas el respaldo público y evitas convertirlo en una lista de garantías.",secondaryMessage:"El estatus aumenta y puede transformarte en activo de marketing si el plan deportivo cambia.",primaryEffects:[n("professional.institutionalPower",4),n("professional.publicMyth",2)],secondaryEffects:[n("professional.publicPolarization",2),n("professional.institutionalPower",3)],primarySeedTransitions:[tr("SEED_PROJECT_FACE",{owner27:"accept_support"})],secondarySeedTransitions:[tr("SEED_PROJECT_FACE",{owner27:"accept_support"})]},
  {id:"B",label:"Pedir un plan deportivo verificable",intentTags:["owner","written_plan"],primaryMessage:"Pides objetivos y estructura antes de tratar el discurso de intocable como poder real.",secondaryMessage:"La concreción mejora información y puede revelar que la promesa era más comercial que deportiva.",primaryEffects:[n("professional.careerControl",4),n("professional.institutionalTrust",2)],secondaryEffects:[n("professional.environmentStability",-1),n("professional.careerControl",3)],primarySeedTransitions:[tr("SEED_PROJECT_FACE",{owner27:"ask_plan"})],secondarySeedTransitions:[tr("SEED_PROJECT_FACE",{owner27:"ask_plan"})]},
  {id:"C",label:"Mantenerte fuera del cambio de poder",intentTags:["owner","neutral"],primaryMessage:"Evitas respaldar públicamente a una propiedad que acaba de llegar.",secondaryMessage:"Proteges distancia y renuncias a parte de la influencia temprana.",primaryEffects:[n("professional.careerControl",3),n("professional.institutionalPower",-1)],secondaryEffects:[n("professional.environmentStability",1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_PROJECT_FACE",{owner27:"stay_neutral"})],secondarySeedTransitions:[tr("SEED_PROJECT_FACE",{owner27:"stay_neutral"})]}
 ],gates:[{path:"facts.currentClubOwnershipChange",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_PROJECT_FACE"],seedsWrite:["SEED_PROJECT_FACE"],tags:["conditional","owner","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const STAR=ambiguousEvent({
 id:"CEVT_27_STAR_02",ageWindow:[27,30],phase:"26_30",family:"conditional",title:"La otra estrella quiere irse",
 body:"Tu compañero estrella considera salir y te pregunta si el proyecto sigue mereciendo la pena.",
 visible:["Conoces lo que te cuenta, su rol y la situación pública del club."],uncertain:["No sabes si ya ha decidido irse ni si tu opinión cambiará algo."],
 choices:[
  {id:"A",label:"Animarle a quedarse",intentTags:["star","retain"],primaryMessage:"Defiendes que el proyecto todavía merece continuidad aunque su permanencia reduzca tu foco individual.",secondaryMessage:"Retener una gran estrella puede ayudar a ganar y mantener competencia interna.",primaryEffects:[n("professional.environmentStability",3),n("professional.trophyCapital",1)],secondaryEffects:[n("professional.successionPressure",1),n("professional.environmentStability",2)],primarySeedTransitions:[tr("SEED_SECOND_STAR",{callback27:"encourage_stay"})],secondarySeedTransitions:[tr("SEED_SECOND_STAR",{callback27:"encourage_stay"})]},
  {id:"B",label:"Contarle tus dudas con honestidad",intentTags:["star","honest"],primaryMessage:"Compartes tu lectura real sin convertirla en recomendación de salida.",secondaryMessage:"La honestidad protege la relación y puede acelerar una decisión que perjudique al club.",primaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",1)],secondaryEffects:[n("professional.institutionalTrust",-1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_SECOND_STAR",{callback27:"share_doubts"})],secondarySeedTransitions:[tr("SEED_SECOND_STAR",{callback27:"share_doubts"})]},
  {id:"C",label:"No intentar influir en su carrera",intentTags:["star","boundary"],primaryMessage:"Le das información factual y evitas decidir por alguien que también compite contigo.",secondaryMessage:"El límite reduce conflicto de interés y puede parecer distancia.",primaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",1)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_SECOND_STAR",{callback27:"no_influence"})],secondarySeedTransitions:[tr("SEED_SECOND_STAR",{callback27:"no_influence"})]}
 ],gates:[{path:"flags.HAS_SEED_SECOND_STAR",op:"eq",value:true},{path:"facts.secondStarExitConflict",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_SECOND_STAR"],seedsWrite:["SEED_SECOND_STAR"],tags:["conditional","star","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const BODY=ambiguousEvent({
 id:"CEVT_27_BODY_03",ageWindow:[27,30],phase:"26_30",family:"conditional",title:"Lesión pese a hacerlo todo bien",
 body:"Sufres una lesión en una acción normal pese a seguir protocolos. La prevención reduce riesgo, no compra inmunidad.",
 visible:["Conoces diagnóstico, mecanismo y que el plan preventivo se había seguido."],uncertain:["No sabes si cambiar el protocolo habría evitado una acción fortuita."],
 choices:[
  {id:"A",label:"Mantener el plan y centrarte en rehabilitación",intentTags:["body","rehab"],primaryMessage:"No conviertes la lesión en prueba automática contra un protocolo que reducía riesgo, no lo eliminaba.",secondaryMessage:"La continuidad evita sobrerreacción y puede omitir mejoras reales que solo aparecen al revisar.",primaryEffects:[n("professional.environmentStability",2),n("professional.recoveryMargin",2)],secondaryEffects:[n("professional.careerControl",1),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_SELF_OPTIMIZATION",{callback27:"rehab_keep_plan"})],secondarySeedTransitions:[tr("SEED_SELF_OPTIMIZATION",{callback27:"rehab_keep_plan"})]},
  {id:"B",label:"Auditar el protocolo sin buscar culpables",intentTags:["body","audit"],primaryMessage:"Revisas carga y prevención para aprender sin asumir que alguien falló.",secondaryMessage:"La auditoría puede encontrar mejoras o confirmar que la lesión era compatible con un buen proceso.",primaryEffects:[n("professional.careerControl",3),n("professional.recoveryMargin",2)],secondaryEffects:[n("professional.environmentStability",1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_SELF_OPTIMIZATION",{callback27:"protocol_audit"})],secondarySeedTransitions:[tr("SEED_SELF_OPTIMIZATION",{callback27:"protocol_audit"})]},
  {id:"C",label:"Cambiar parte del equipo de rendimiento",intentTags:["body","change_staff"],primaryMessage:"Usas la lesión como señal para modificar responsabilidades dentro de tu estructura.",secondaryMessage:"El cambio puede mejorar el proceso o castigar a profesionales por un evento no prevenible.",primaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",-2)],secondaryEffects:[n("professional.recoveryMargin",1),n("professional.environmentStability",-3)],primarySeedTransitions:[tr("SEED_SELF_OPTIMIZATION",{callback27:"change_staff"})],secondarySeedTransitions:[tr("SEED_SELF_OPTIMIZATION",{callback27:"change_staff"})]}
 ],gates:[{path:"flags.HAS_SEED_SELF_OPTIMIZATION",op:"eq",value:true},{path:"facts.normalActionInjuryDespiteProtocol",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_SELF_OPTIMIZATION"],seedsWrite:["SEED_SELF_OPTIMIZATION"],npcRefs:["NPC_MED_01"],tags:["conditional","body","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const AWARD=ambiguousEvent({
 id:"CEVT_27_AWARD_02",ageWindow:[27,30],phase:"26_30",family:"conditional",title:"Pierdes el premio por poco",
 body:"Quedas segundo o tercero en un gran premio individual y tu equipo quiere publicar un mensaje preparado.",
 visible:["Conoces el resultado oficial y el texto propuesto."],uncertain:["No sabes cómo leerán el mensaje compañeros, ganador y afición."],
 choices:[
  {id:"A",label:"Publicar el mensaje preparado y felicitar al ganador",intentTags:["award","publish"],primaryMessage:"Reconoces el resultado y mantienes la campaña prevista sin negar la derrota.",secondaryMessage:"El mensaje protege continuidad de marca y puede parecer demasiado preparado.",primaryEffects:[n("professional.publicMyth",2),n("professional.environmentStability",1)],secondaryEffects:[n("reputation.mediaHeat",1),n("professional.publicPolarization",1)],primarySeedTransitions:[tr("SEED_RECORD_CHASE",{awardLoss27:"publish"})],secondarySeedTransitions:[tr("SEED_RECORD_CHASE",{awardLoss27:"publish"})]},
  {id:"B",label:"Publicar solo una felicitación breve",intentTags:["award","brief"],primaryMessage:"Reducir el mensaje evita convertir el segundo puesto en campaña propia.",secondaryMessage:"La brevedad baja exposición y deja más espacio a interpretaciones.",primaryEffects:[n("professional.careerControl",2),n("reputation.mediaHeat",-1)],secondaryEffects:[n("professional.publicMyth",1),n("professional.careerControl",1)],primarySeedTransitions:[tr("SEED_RECORD_CHASE",{awardLoss27:"brief"})],secondarySeedTransitions:[tr("SEED_RECORD_CHASE",{awardLoss27:"brief"})]},
  {id:"C",label:"No publicar nada esa noche",intentTags:["award","silence"],primaryMessage:"Dejas que el resultado exista sin convertirlo inmediatamente en contenido.",secondaryMessage:"El silencio puede parecer serenidad, decepción o simple ausencia de estrategia.",primaryEffects:[n("professional.careerControl",3),n("professional.publicMyth",-1)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_RECORD_CHASE",{awardLoss27:"no_post"})],secondarySeedTransitions:[tr("SEED_RECORD_CHASE",{awardLoss27:"no_post"})]}
 ],gates:[{path:"facts.globalAwardRunnerUpResult",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_RECORD_CHASE"],seedsWrite:["SEED_RECORD_CHASE"],tags:["conditional","award","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

export const T533_STAGED_CONDITIONAL_EVENTS:EventDefinition[]=[FAMILY,OWNER,STAR,BODY,AWARD];
