import type { EventDefinition, SeedTransition } from "../../../core/types.js";
import { ambiguousEvent, n } from "../18_20/helpers.js";
const tr=(seedId:string,payload:Record<string,string|number|boolean|null>):SeedTransition=>({seedId,action:"transform",payload});

const FINAL=ambiguousEvent({
 id:"CEVT_27_FINAL_02",ageWindow:[27,30],phase:"26_30",family:"conditional",title:"Campeón sin ser protagonista",
 body:"Ganas un gran título tras jugar poco en la final o eliminatoria decisiva. El palmarés y la experiencia subjetiva pueden divergir.",
 visible:["Conoces el título, tus minutos y el plan que te dejó fuera del protagonismo."],uncertain:["No sabes qué recuerdo pesará más dentro de unos años."],
 choices:[
  {id:"A",label:"Celebrar el título sin matices públicos",intentTags:["final","celebrate"],primaryMessage:"Tratas el trofeo como logro colectivo completo.",secondaryMessage:"La celebración no borra tu frustración privada ni la convierte en contradicción.",primaryEffects:[n("professional.trophyCapital",4),n("professional.environmentStability",2)],secondaryEffects:[n("professional.publicMyth",2),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_SHADOW_ESCAPE",{callback27Final:"celebrate"})],secondarySeedTransitions:[tr("SEED_SHADOW_ESCAPE",{callback27Final:"celebrate"})]},
  {id:"B",label:"Reconocer que fue especial y difícil a la vez",intentTags:["final","mixed"],primaryMessage:"Expresas orgullo por el título y honestidad sobre el rol reducido.",secondaryMessage:"El matiz puede humanizar la experiencia o reabrir el debate sobre jerarquía.",primaryEffects:[n("professional.careerControl",3),n("reputation.mediaHeat",1)],secondaryEffects:[n("professional.publicPolarization",2),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_SHADOW_ESCAPE",{callback27Final:"mixed_feeling"})],secondarySeedTransitions:[tr("SEED_SHADOW_ESCAPE",{callback27Final:"mixed_feeling"})]},
  {id:"C",label:"Dejar la revisión de tu futuro para después de la celebración",intentTags:["final","defer_future"],primaryMessage:"Separar celebración y futuro evita convertir el título en ultimátum.",secondaryMessage:"La pausa protege al grupo y mantiene abierta la decisión contractual o deportiva.",primaryEffects:[n("professional.environmentStability",3),n("professional.careerControl",3)],secondaryEffects:[n("reputation.marketHeat",1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_SHADOW_ESCAPE",{callback27Final:"review_later"})],secondarySeedTransitions:[tr("SEED_SHADOW_ESCAPE",{callback27Final:"review_later"})]}
 ],gates:[{path:"facts.finalBenchVictory",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_SHADOW_ESCAPE"],seedsWrite:["SEED_SHADOW_ESCAPE"],tags:["conditional","final","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const MEDIA=ambiguousEvent({
 id:"CEVT_28_MEDIA_02",ageWindow:[28,30],phase:"26_30",family:"conditional",title:"El estadio cambia de opinión",
 body:"Después de meses tensos, una gran actuación o gesto reduce silbidos. La reconciliación pública puede ser temporal.",
 visible:["Percibes una reacción del estadio claramente distinta a la etapa de tensión."],uncertain:["No sabes si el cambio es duradero ni si responde a una sola actuación."],
 choices:[
  {id:"A",label:"Abrazar el gesto sin declarar cerrada la crisis",intentTags:["fans","reconcile"],primaryMessage:"Reconoces la mejora sin convertirla en perdón total.",secondaryMessage:"La cautela permite que la relación evolucione sin exigir una narrativa definitiva.",primaryEffects:[n("professional.publicMyth",2),n("professional.publicPolarization",-2)],secondaryEffects:[n("reputation.mediaHeat",1),n("professional.publicPolarization",-1)],primarySeedTransitions:[tr("SEED_GLOBAL_IMAGE",{fan28:"cautious_reconcile"})],secondarySeedTransitions:[tr("SEED_GLOBAL_IMAGE",{fan28:"cautious_reconcile"})]},
  {id:"B",label:"No convertirlo en tema",intentTags:["fans","quiet"],primaryMessage:"Dejas que el cambio ocurra en el estadio sin campaña de reconciliación.",secondaryMessage:"Reducir relato puede consolidar normalidad o perder una oportunidad de reparar vínculo.",primaryEffects:[n("professional.careerControl",3),n("reputation.mediaHeat",-1)],secondaryEffects:[n("professional.environmentStability",1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_GLOBAL_IMAGE",{fan28:"no_story"})],secondarySeedTransitions:[tr("SEED_GLOBAL_IMAGE",{fan28:"no_story"})]},
  {id:"C",label:"Agradecer públicamente el cambio",intentTags:["fans","thanks"],primaryMessage:"Agradeces el apoyo sin afirmar que la afición se equivocó antes.",secondaryMessage:"El gesto refuerza reconciliación y puede volver a centrar la historia en la fractura previa.",primaryEffects:[n("professional.publicMyth",3),n("professional.environmentStability",2)],secondaryEffects:[n("reputation.mediaHeat",2),n("professional.publicPolarization",1)],primarySeedTransitions:[tr("SEED_GLOBAL_IMAGE",{fan28:"public_thanks"})],secondarySeedTransitions:[tr("SEED_GLOBAL_IMAGE",{fan28:"public_thanks"})]}
 ],gates:[{path:"facts.fanReconciliationMoment",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_GLOBAL_IMAGE"],seedsWrite:["SEED_GLOBAL_IMAGE"],tags:["conditional","fans","a6_ready_external_blocker","needs_seed_fan_fracture_origin","t5_conditional"],canonStatus:"verified"
});

const TRANSFER=ambiguousEvent({
 id:"CEVT_28_TRANSFER_02",ageWindow:[28,30],phase:"26_30",family:"conditional",title:"El reconocimiento médico frena el fichaje",
 body:"El comprador pide renegociar estructura o se retira por riesgo percibido, aunque tú puedas jugar. La percepción médica de mercado no equivale a tu estado real.",
 visible:["Conoces el hallazgo, la postura del comprador y los cambios de términos solicitados."],uncertain:["No sabes si otro club valorará igual el riesgo ni si la condición cambiará."],
 choices:[
  {id:"A",label:"Aceptar renegociar la estructura",intentTags:["transfer","renegotiate"],primaryMessage:"Mantienes viva la operación y aceptas discutir términos por la nueva valoración de riesgo.",secondaryMessage:"La flexibilidad puede cerrar el fichaje o convertir una duda médica en descuento permanente.",primaryEffects:[n("professional.careerControl",2),n("professional.contractPower",-2)],secondaryEffects:[n("professional.environmentStability",-1),n("professional.careerControl",1)],primarySeedTransitions:[tr("SEED_CHRONIC_BODY",{transfer28:"renegotiate"})],secondarySeedTransitions:[tr("SEED_CHRONIC_BODY",{transfer28:"renegotiate"})]},
  {id:"B",label:"Pedir una revisión médica independiente",intentTags:["transfer","medical_review"],primaryMessage:"Buscas una segunda evaluación sin asumir que invalide la del comprador.",secondaryMessage:"La revisión puede aclarar el riesgo o confirmar la discrepancia sin obligar al club a cambiar términos.",primaryEffects:[n("professional.careerControl",4),n("professional.institutionalTrust",1)],secondaryEffects:[n("professional.environmentStability",-1),n("professional.careerControl",3)],primarySeedTransitions:[tr("SEED_CHRONIC_BODY",{transfer28:"independent_review"})],secondarySeedTransitions:[tr("SEED_CHRONIC_BODY",{transfer28:"independent_review"})]},
  {id:"C",label:"Retirarte de la operación",intentTags:["transfer","walk_away"],primaryMessage:"Rechazas convertir una percepción médica en condiciones que ya no aceptas.",secondaryMessage:"Proteges límites contractuales y pierdes una operación que quizá no reaparezca.",primaryEffects:[n("professional.careerControl",5),n("reputation.marketHeat",-2)],secondaryEffects:[n("professional.contractPower",-1),n("professional.careerControl",4)],primarySeedTransitions:[tr("SEED_CHRONIC_BODY",{transfer28:"walk_away"})],secondarySeedTransitions:[tr("SEED_CHRONIC_BODY",{transfer28:"walk_away"})]}
 ],gates:[{path:"flags.HAS_SEED_CHRONIC_BODY",op:"eq",value:true},{path:"facts.medicalTransferRenegotiation",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_CHRONIC_BODY"],seedsWrite:["SEED_CHRONIC_BODY"],npcRefs:["NPC_MED_01"],tags:["conditional","transfer","medical","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const DDL=ambiguousEvent({
 id:"CEVT_28_DDL_02",ageWindow:[28,30],phase:"26_30",family:"conditional",title:"La operación cae por tiempo",
 body:"Documentos, una aprobación o una venta encadenada no llegan a tiempo. No hay un villano necesario.",
 visible:["Conoces qué paso no llegó antes del cierre."],uncertain:["No sabes si el mismo acuerdo podrá reconstruirse en la siguiente ventana."],
 choices:[
  {id:"A",label:"Aceptar que la operación terminó",intentTags:["deadline","accept"],primaryMessage:"Cierras la ventana sin fabricar un culpable donde la evidencia no lo sostiene.",secondaryMessage:"La claridad protege foco y no recupera la oportunidad perdida.",primaryEffects:[n("professional.environmentStability",2),n("professional.careerControl",2)],secondaryEffects:[n("reputation.marketHeat",-1),n("professional.careerControl",1)],primarySeedTransitions:[tr("SEED_DIRECT_RECRUIT",{deadline28:"accept_failure"})],secondarySeedTransitions:[tr("SEED_DIRECT_RECRUIT",{deadline28:"accept_failure"})]},
  {id:"B",label:"Pedir un informe del fallo de proceso",intentTags:["deadline","postmortem"],primaryMessage:"Buscas entender logística y responsabilidades sin convertir análisis en acusación.",secondaryMessage:"El postmortem puede prevenir repeticiones o confirmar que la cadena era demasiado frágil.",primaryEffects:[n("professional.careerControl",4),n("professional.institutionalTrust",1)],secondaryEffects:[n("professional.environmentStability",-1),n("professional.careerControl",3)],primarySeedTransitions:[tr("SEED_DIRECT_RECRUIT",{deadline28:"process_review"})],secondarySeedTransitions:[tr("SEED_DIRECT_RECRUIT",{deadline28:"process_review"})]},
  {id:"C",label:"Mantener abierto el canal para la siguiente ventana",intentTags:["deadline","keep_channel"],primaryMessage:"Separar el fracaso logístico del interés deportivo conserva una posibilidad futura.",secondaryMessage:"El canal sobrevive y el contexto de mercado puede dejar de existir.",primaryEffects:[n("reputation.marketHeat",2),n("professional.careerControl",3)],secondaryEffects:[n("professional.environmentStability",1),n("reputation.marketHeat",1)],primarySeedTransitions:[tr("SEED_DIRECT_RECRUIT",{deadline28:"keep_channel"})],secondarySeedTransitions:[tr("SEED_DIRECT_RECRUIT",{deadline28:"keep_channel"})]}
 ],gates:[{path:"facts.deadlineOperationExpired",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_DIRECT_RECRUIT"],seedsWrite:["SEED_DIRECT_RECRUIT"],tags:["conditional","deadline","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const MANAGER=ambiguousEvent({
 id:"CEVT_28_MANAGER_02",ageWindow:[28,30],phase:"26_30",family:"conditional",title:"Respaldaste al técnico y lo despiden",
 body:"Tu declaración de respaldo queda circulando horas o días antes del cese. Apoyar no te hace ingenuo si la información cambió o nunca fue tu decisión.",
 visible:["Conoces tu declaración previa y el anuncio oficial del despido."],uncertain:["No sabes cuándo decidió la dirección el cese ni qué información tenía cuando te pidió apoyo."],
 choices:[
  {id:"A",label:"Mantener que el respaldo era sincero entonces",intentTags:["manager","stand_by"],primaryMessage:"Distingues una opinión honesta en su contexto de la decisión posterior del club.",secondaryMessage:"La coherencia protege tu versión y no evita que se use el archivo para acusarte de error.",primaryEffects:[n("professional.careerControl",3),n("professional.institutionalTrust",1)],secondaryEffects:[n("reputation.mediaHeat",2),n("professional.publicPolarization",1)],primarySeedTransitions:[tr("SEED_MANAGER_POWER",{manager28:"stand_by_context"})],secondarySeedTransitions:[tr("SEED_MANAGER_POWER",{manager28:"stand_by_context"})]},
  {id:"B",label:"Explicar que la situación cambió",intentTags:["manager","context_changed"],primaryMessage:"Separas el mensaje anterior de hechos posteriores sin fingir que conocías la decisión futura.",secondaryMessage:"La explicación puede cerrar contexto o prolongar el ciclo mediático.",primaryEffects:[n("professional.careerControl",3),n("reputation.mediaHeat",1)],secondaryEffects:[n("reputation.mediaHeat",3),n("professional.publicPolarization",2)],primarySeedTransitions:[tr("SEED_MANAGER_POWER",{manager28:"situation_changed"})],secondarySeedTransitions:[tr("SEED_MANAGER_POWER",{manager28:"situation_changed"})]},
  {id:"C",label:"No comentar el despido",intentTags:["manager","no_comment"],primaryMessage:"No añades una segunda declaración a una decisión institucional que no controlabas.",secondaryMessage:"El silencio limita nuevas frases y deja el archivo anterior intacto.",primaryEffects:[n("professional.careerControl",2),n("reputation.mediaHeat",-1)],secondaryEffects:[n("professional.environmentStability",1),n("professional.careerControl",1)],primarySeedTransitions:[tr("SEED_MANAGER_POWER",{manager28:"no_comment"})],secondarySeedTransitions:[tr("SEED_MANAGER_POWER",{manager28:"no_comment"})]}
 ],gates:[{path:"facts.managerSackedAfterPlayerBacking",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_MANAGER_POWER"],seedsWrite:["SEED_MANAGER_POWER"],tags:["conditional","manager","a6_ready_external_blocker","needs_seed_public_manager_backing_catalog","t5_conditional"],canonStatus:"verified"
});

export const T534_STAGED_CONDITIONAL_EVENTS:EventDefinition[]=[FINAL,MEDIA,TRANSFER,DDL,MANAGER];
