import type { EventDefinition, SeedTransition } from "../../../core/types.js";
import { ambiguousEvent, n } from "../18_20/helpers.js";
const tr=(seedId:string,payload:Record<string,string|number|boolean|null>):SeedTransition=>({seedId,action:"transform",payload});

const MANAGER=ambiguousEvent({
 id:"CEVT_28_MANAGER_03",ageWindow:[28,30],phase:"26_30",family:"conditional",title:"No lo apoyaste y sobrevive",
 body:"El entrenador continúa y conoce, correctamente o por rumor, que evitaste respaldarlo.",
 visible:["Conoces que sigue en el cargo y que vuestra relación incorpora la crisis anterior."],uncertain:["No sabes exactamente qué versión de tu postura ha recibido."],
 choices:[
  {id:"A",label:"Hablar con él en privado",intentTags:["manager","private_reset"],primaryMessage:"Intentas separar la relación de trabajo de la crisis institucional anterior.",secondaryMessage:"La conversación puede resetear confianza o confirmar que la herida sigue abierta.",primaryEffects:[n("professional.environmentStability",2),n("professional.institutionalTrust",2)],secondaryEffects:[n("professional.environmentStability",-1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_MANAGER_POWER",{manager28Survives:"private_reset"})],secondarySeedTransitions:[tr("SEED_MANAGER_POWER",{manager28Survives:"private_reset"})]},
  {id:"B",label:"Mantener relación estrictamente profesional",intentTags:["manager","professional"],primaryMessage:"Evitas reabrir una decisión pasada y trabajas con la jerarquía actual.",secondaryMessage:"La normalidad puede cerrar el episodio o mantener una distancia estable.",primaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",1)],secondaryEffects:[n("professional.institutionalTrust",-1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_MANAGER_POWER",{manager28Survives:"professional_only"})],secondarySeedTransitions:[tr("SEED_MANAGER_POWER",{manager28Survives:"professional_only"})]},
  {id:"C",label:"Aclarar qué dijiste y qué no dijiste",intentTags:["manager","clarify"],primaryMessage:"Corriges rumores concretos sin fingir que tuviste una posición distinta.",secondaryMessage:"La precisión protege tu versión y puede hacer más explícita una tensión antes difusa.",primaryEffects:[n("professional.careerControl",4),n("professional.institutionalTrust",1)],secondaryEffects:[n("reputation.mediaHeat",1),n("professional.environmentStability",-1)],primarySeedTransitions:[tr("SEED_MANAGER_POWER",{manager28Survives:"clarify_record"})],secondarySeedTransitions:[tr("SEED_MANAGER_POWER",{manager28Survives:"clarify_record"})]}
 ],gates:[{path:"flags.HAS_SEED_MANAGER_POWER",op:"eq",value:true},{path:"facts.managerStayedAfterCrisis",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_MANAGER_POWER"],seedsWrite:["SEED_MANAGER_POWER"],tags:["conditional","manager","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const YOUTH=ambiguousEvent({
 id:"CEVT_29_YOUTH_02",ageWindow:[29,30],phase:"26_30",family:"conditional",title:"El joven te atribuye parte de su éxito",
 body:"En una entrevista, el joven te da crédito por parte de su éxito. El reconocimiento mejora legado y puede reforzar la idea de sucesión.",
 visible:["Conoces sus palabras completas y su rendimiento reciente."],uncertain:["No sabes si la prensa convertirá gratitud en relato de relevo generacional."],
 choices:[
  {id:"A",label:"Abrazar la narrativa de mentoría",intentTags:["youth","mentor"],primaryMessage:"Aceptas públicamente que tu relación influyó en su desarrollo.",secondaryMessage:"El gesto aumenta legado y puede acelerar una narrativa de sucesión.",primaryEffects:[n("professional.legacyCapital",4),n("professional.successionPressure",2)],secondaryEffects:[n("professional.publicMyth",2),n("professional.successionPressure",3)],primarySeedTransitions:[tr("SEED_MENTOR_ADVICE",{callback29:"embrace_credit"})],secondarySeedTransitions:[tr("SEED_MENTOR_ADVICE",{callback29:"embrace_credit"})]},
  {id:"B",label:"Reducir tu papel y devolverle el mérito",intentTags:["youth","reduce_credit"],primaryMessage:"Subrayas que su carrera depende de su propio trabajo.",secondaryMessage:"La respuesta protege simetría y pierde parte del capital de mentoría.",primaryEffects:[n("professional.environmentStability",2),n("professional.legacyCapital",1)],secondaryEffects:[n("professional.publicMyth",-1),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_MENTOR_ADVICE",{callback29:"return_credit"})],secondarySeedTransitions:[tr("SEED_MENTOR_ADVICE",{callback29:"return_credit"})]},
  {id:"C",label:"Recordar que ahora también compite contigo",intentTags:["youth","competition"],primaryMessage:"Reconoces la relación y también la competencia deportiva actual.",secondaryMessage:"El matiz evita una despedida prematura y puede alimentar comparación pública.",primaryEffects:[n("professional.careerControl",3),n("professional.successionPressure",1)],secondaryEffects:[n("professional.publicPolarization",2),n("professional.successionPressure",2)],primarySeedTransitions:[tr("SEED_MENTOR_ADVICE",{callback29:"mentor_and_competitor"})],secondarySeedTransitions:[tr("SEED_MENTOR_ADVICE",{callback29:"mentor_and_competitor"})]}
 ],gates:[{path:"flags.HAS_SEED_MENTOR_ADVICE",op:"eq",value:true},{path:"facts.successorBreakoutCreditsPlayer",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_MENTOR_ADVICE"],seedsWrite:["SEED_MENTOR_ADVICE"],tags:["conditional","successor","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const NAT=ambiguousEvent({
 id:"CEVT_29_NAT_02",ageWindow:[29,30],phase:"26_30",family:"conditional",title:"Cambia el seleccionador",
 body:"Un nuevo técnico reevalúa jerarquías y puede valorar tu nueva posición de forma distinta. La reputación internacional no se transfiere uno a uno entre entrenadores.",
 visible:["Conoces al nuevo seleccionador, su primer mensaje y el rol que quiere evaluar."],uncertain:["No sabes cuánto peso dará a tu historial frente a su propio sistema."],
 choices:[
  {id:"A",label:"Aceptar la reevaluación desde cero",intentTags:["national","reset"],primaryMessage:"Tratas el cambio de técnico como una nueva jerarquía real.",secondaryMessage:"La actitud reduce fricción y no protege tu rol previo.",primaryEffects:[n("professional.nationalPower",1),n("professional.environmentStability",2)],secondaryEffects:[n("professional.roleSecurity",-1),n("professional.environmentStability",1)]},
  {id:"B",label:"Mostrar cómo encaja tu nueva posición",intentTags:["national","reinvention"],primaryMessage:"Usas tu evolución táctica como argumento deportivo, no tu reputación pasada.",secondaryMessage:"La reinvención puede abrir un rol distinto o no encajar con el nuevo sistema.",primaryEffects:[n("professional.roleAdaptability",3),n("professional.careerControl",2)],secondaryEffects:[n("professional.nationalPower",1),n("professional.roleAdaptability",2)]},
  {id:"C",label:"Pedir claridad sobre expectativas",intentTags:["national","clarity"],primaryMessage:"Pides saber qué necesita el nuevo técnico antes de tomar decisiones de disponibilidad.",secondaryMessage:"La claridad ayuda a planificar y no garantiza una jerarquía favorable.",primaryEffects:[n("professional.careerControl",3),n("professional.nationalPower",1)],secondaryEffects:[n("professional.environmentStability",1),n("professional.careerControl",2)]}
 ],gates:[{path:"facts.newNationalCoachReevaluation",op:"eq",value:true}],weight:10,cooldown:99999,tags:["conditional","selection","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const HOME=ambiguousEvent({
 id:"CEVT_29_HOME_03",ageWindow:[29,30],phase:"26_30",family:"conditional",title:"UDV vive su mejor temporada",
 body:"El club de origen asciende, llega a una final o logra un hito. Te invitan a participar sin saber si tu presencia ayuda o roba foco.",
 visible:["Conoces el hito y el tipo de invitación."],uncertain:["No sabes cuánto de la atención se desplazaría hacia ti."],
 choices:[
  {id:"A",label:"Aceptar la invitación y estar presente",intentTags:["home","attend"],primaryMessage:"Participas como parte de la historia del club sin atribuirte el logro actual.",secondaryMessage:"Tu presencia suma simbolismo y puede desplazar foco mediático.",primaryEffects:[n("professional.homePull",4),n("professional.legacyCapital",2)],secondaryEffects:[n("reputation.mediaHeat",2),n("professional.publicMyth",1)],primarySeedTransitions:[tr("SEED_HOME_SYMBOL",{callback29:"attend_udv_historic_day"})],secondarySeedTransitions:[tr("SEED_HOME_SYMBOL",{callback29:"attend_udv_historic_day"})]},
  {id:"B",label:"Enviar apoyo y no acudir",intentTags:["home","support_distance"],primaryMessage:"Reconoces el hito sin ocupar espacio físico en la celebración.",secondaryMessage:"El gesto protege el foco del equipo actual y reduce tu presencia simbólica.",primaryEffects:[n("professional.homePull",2),n("professional.environmentStability",1)],secondaryEffects:[n("professional.publicMyth",-1),n("professional.homePull",1)],primarySeedTransitions:[tr("SEED_HOME_SYMBOL",{callback29:"support_from_distance"})],secondarySeedTransitions:[tr("SEED_HOME_SYMBOL",{callback29:"support_from_distance"})]},
  {id:"C",label:"Pedir participar solo en un acto secundario",intentTags:["home","low_profile"],primaryMessage:"Buscas estar presente sin convertirte en imagen principal del hito.",secondaryMessage:"El equilibrio reduce foco y puede parecer demasiado calculado.",primaryEffects:[n("professional.homePull",3),n("professional.careerControl",2)],secondaryEffects:[n("reputation.mediaHeat",1),n("professional.careerControl",1)],primarySeedTransitions:[tr("SEED_HOME_SYMBOL",{callback29:"secondary_event"})],secondarySeedTransitions:[tr("SEED_HOME_SYMBOL",{callback29:"secondary_event"})]}
 ],gates:[{path:"flags.HAS_SEED_HOME_SYMBOL",op:"eq",value:true},{path:"facts.udvHistoricPositiveSeason",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_HOME_SYMBOL"],seedsWrite:["SEED_HOME_SYMBOL"],npcRefs:["NPC_DIR_02"],tags:["conditional","home","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const BODY=ambiguousEvent({
 id:"CEVT_29_BODY_04",ageWindow:[29,30],phase:"26_30",family:"conditional",title:"Recuperas mejor de lo esperado",
 body:"Una recuperación supera plazos centrales y abre una cita que creías perdida. La buena fortuna médica tampoco es un premio moral.",
 visible:["Conoces el nuevo estado clínico y la cita que vuelve a ser posible."],uncertain:["No sabes si estar disponible antes significa estar listo para máxima exigencia."],
 choices:[
  {id:"A",label:"Intentar volver para la cita reabierta",intentTags:["body","return_early"],primaryMessage:"Usas la mejoría como oportunidad y mantienes controles médicos antes de competir.",secondaryMessage:"El regreso puede ser viable y elevar carga antes de lo previsto.",primaryEffects:[n("professional.roleSecurity",2),n("professional.recoveryMargin",-1)],secondaryEffects:[n("professional.bodyLoad",3),n("professional.recoveryMargin",-2)],primarySeedTransitions:[tr("SEED_CHRONIC_BODY",{callback29:"target_reopened_match"})],secondarySeedTransitions:[tr("SEED_CHRONIC_BODY",{callback29:"target_reopened_match"})]},
  {id:"B",label:"Mantener el calendario conservador",intentTags:["body","conservative"],primaryMessage:"No conviertes una recuperación favorable en obligación de acelerar.",secondaryMessage:"Proteges margen y renuncias a una cita que ahora parecía posible.",primaryEffects:[n("professional.recoveryMargin",4),n("professional.careerControl",2)],secondaryEffects:[n("professional.roleSecurity",-1),n("professional.recoveryMargin",3)],primarySeedTransitions:[tr("SEED_CHRONIC_BODY",{callback29:"keep_original_timeline"})],secondarySeedTransitions:[tr("SEED_CHRONIC_BODY",{callback29:"keep_original_timeline"})]},
  {id:"C",label:"Reevaluar con el staff antes de fijar objetivo",intentTags:["body","reevaluate"],primaryMessage:"Usas la mejoría como nueva información, no como decisión automática.",secondaryMessage:"La reevaluación puede abrir la cita o confirmar que el margen sigue siendo insuficiente.",primaryEffects:[n("professional.careerControl",3),n("professional.recoveryMargin",2)],secondaryEffects:[n("professional.environmentStability",1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_CHRONIC_BODY",{callback29:"medical_reevaluation"})],secondarySeedTransitions:[tr("SEED_CHRONIC_BODY",{callback29:"medical_reevaluation"})]}
 ],gates:[{path:"flags.HAS_SEED_CHRONIC_BODY",op:"eq",value:true},{path:"facts.recoveryAheadOfExpectedRange",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_CHRONIC_BODY"],seedsWrite:["SEED_CHRONIC_BODY"],npcRefs:["NPC_MED_01"],tags:["conditional","body","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

export const T535_STAGED_CONDITIONAL_EVENTS:EventDefinition[]=[MANAGER,YOUTH,NAT,HOME,BODY];
