import type { EventDefinition, SeedTransition } from "../../../core/types.js";
import { ambiguousEvent, n } from "../18_20/helpers.js";
const tr=(seedId:string,payload:Record<string,string|number|boolean|null>):SeedTransition=>({seedId,action:"transform",payload});

const CLARA=ambiguousEvent({
 id:"CEVT_26_CLARA_04",ageWindow:[26,30],phase:"26_30",family:"conditional",title:"La noticia que puede tirar una operación",
 body:"Clara conoce una cláusula, desacuerdo o condición médica de una operación grande y te avisa de que publicará si la confirma con una segunda fuente.",
 visible:["Sabes qué parte cree conocer y que todavía exige segunda confirmación."],uncertain:["No sabes si la segunda fuente aparecerá ni qué efecto tendría la publicación sobre la operación."],
 choices:[
  {id:"A",label:"Dar contexto sin pedirle que no publique",intentTags:["clara","context"],primaryMessage:"Aportas contexto verificable y respetas que la decisión editorial no te pertenece.",secondaryMessage:"La precisión puede evitar errores y también facilitar que la noticia quede mejor confirmada.",primaryEffects:[n("professional.careerControl",3),n("reputation.mediaHeat",1)],secondaryEffects:[n("reputation.mediaHeat",2),n("professional.publicPolarization",1)],primarySeedTransitions:[tr("SEED_CLARA_CHANNEL",{callback26Transfer:"give_context"})],secondarySeedTransitions:[tr("SEED_CLARA_CHANNEL",{callback26Transfer:"give_context"})]},
  {id:"B",label:"Avisar a las partes de que la información puede salir",intentTags:["clara","warn_parties"],primaryMessage:"Preparas a club, agencia o comprador sin atribuirle a Clara información que no te autorizó a revelar.",secondaryMessage:"La prevención puede estabilizar la operación o acelerar movimientos defensivos.",primaryEffects:[n("professional.careerControl",4),n("professional.environmentStability",1)],secondaryEffects:[n("professional.institutionalTrust",-1),n("professional.careerControl",3)],primarySeedTransitions:[tr("SEED_CLARA_CHANNEL",{callback26Transfer:"warn_parties"})],secondarySeedTransitions:[tr("SEED_CLARA_CHANNEL",{callback26Transfer:"warn_parties"})]},
  {id:"C",label:"No intervenir y preparar respuesta si publica",intentTags:["clara","prepare_response"],primaryMessage:"No intentas influir en su proceso y preparas una respuesta factual por si la noticia se confirma.",secondaryMessage:"Proteges el canal y aceptas que el timing de la noticia quede fuera de tu control.",primaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",1)],secondaryEffects:[n("reputation.mediaHeat",1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_CLARA_CHANNEL",{callback26Transfer:"prepare_response"})],secondarySeedTransitions:[tr("SEED_CLARA_CHANNEL",{callback26Transfer:"prepare_response"})]}
 ],gates:[{path:"flags.HAS_SEED_CLARA_CHANNEL",op:"eq",value:true},{path:"facts.claraMegaTransferSensitiveInfo",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_CLARA_CHANNEL"],seedsWrite:["SEED_CLARA_CHANNEL"],npcRefs:["NPC_PRS_01"],tags:["conditional","clara","transfer","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const AGENT=ambiguousEvent({
 id:"CEVT_26_AGENT_05",ageWindow:[26,30],phase:"26_30",family:"conditional",title:"Tu primer agente representa al sucesor",
 body:"El agente que te llevó al inicio firma al joven que compite contigo. Puede ser coincidencia comercial o estrategia; ninguna lectura queda demostrada por la relación pasada.",
 visible:["Conoces que el contrato de representación existe y quién es el sucesor."],uncertain:["No sabes si el agente busca construir una narrativa de relevo ni qué conversaciones privadas mantiene con el joven."],
 choices:[
  {id:"A",label:"Hablar con tu primer agente sobre el conflicto potencial",intentTags:["agent","conflict_check"],primaryMessage:"Pides claridad sobre límites de información y conflicto de intereses sin acusar una estrategia inexistente.",secondaryMessage:"La conversación puede aclarar fronteras o revelar que vuestras carreras profesionales ya están separadas.",primaryEffects:[n("professional.careerControl",4),n("professional.environmentStability",1)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.careerControl",3)],primarySeedTransitions:[tr("SEED_FIRST_AGENT",{callback26Successor:"conflict_check"})],secondarySeedTransitions:[tr("SEED_FIRST_AGENT",{callback26Successor:"conflict_check"})]},
  {id:"B",label:"Tratarlo como una relación comercial independiente",intentTags:["agent","separate_clients"],primaryMessage:"Aceptas que representar al sucesor no equivale automáticamente a trabajar contra ti.",secondaryMessage:"La separación reduce drama y exige más cuidado con información compartida.",primaryEffects:[n("professional.environmentStability",2),n("professional.careerControl",2)],secondaryEffects:[n("professional.environmentStability",1),n("professional.careerControl",1)],primarySeedTransitions:[tr("SEED_FIRST_AGENT",{callback26Successor:"separate_clients"})],secondarySeedTransitions:[tr("SEED_FIRST_AGENT",{callback26Successor:"separate_clients"})]},
  {id:"C",label:"Reforzar límites de información con tu entorno actual",intentTags:["agent","information_boundary"],primaryMessage:"Proteges tus negociaciones y planes sin convertir la representación del joven en acusación.",secondaryMessage:"El control de información reduce exposición y puede enfriar relaciones antiguas.",primaryEffects:[n("professional.careerControl",4),n("professional.agentControl",2)],secondaryEffects:[n("professional.environmentStability",-1),n("professional.careerControl",3)],primarySeedTransitions:[tr("SEED_FIRST_AGENT",{callback26Successor:"tighten_boundaries"})],secondarySeedTransitions:[tr("SEED_FIRST_AGENT",{callback26Successor:"tighten_boundaries"})]}
 ],gates:[{path:"flags.HAS_SEED_FIRST_AGENT",op:"eq",value:true},{path:"flags.HAS_SEED_YOUNG_SUCCESSOR",op:"eq",value:true},{path:"facts.firstAgentRepresentsSuccessor",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_FIRST_AGENT","SEED_YOUNG_SUCCESSOR"],seedsWrite:["SEED_FIRST_AGENT"],tags:["conditional","agent","successor","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const RECORD=ambiguousEvent({
 id:"CEVT_29_RECORD_02",ageWindow:[29,30],phase:"26_30",family:"conditional",title:"Adrián o el sucesor rompe tu récord",
 body:"Un récord que perseguías dura poco. La prensa pide reacción. El legado no es propiedad permanente y la rivalidad puede seguir sin hostilidad.",
 visible:["Conoces el nuevo récord, quién lo ha superado y el contexto deportivo."],uncertain:["No sabes cuánto durará el nuevo registro ni qué lectura hará la prensa de tu respuesta."],
 choices:[
  {id:"A",label:"Felicitarle y reconocer el nuevo récord",intentTags:["record","congratulate"],primaryMessage:"Reconoces el logro sin borrar lo que significó tu propio récord.",secondaryMessage:"La respuesta reduce hostilidad y puede reforzar una narrativa de relevo.",primaryEffects:[n("professional.legacyCapital",2),n("professional.publicPolarization",-1)],secondaryEffects:[n("professional.publicMyth",1),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_RECORD_CHASE",{callback29Broken:"congratulate"})],secondarySeedTransitions:[tr("SEED_RECORD_CHASE",{callback29Broken:"congratulate"})]},
  {id:"B",label:"Restar importancia al récord",intentTags:["record","downplay"],primaryMessage:"Tratas el registro como una parte menor de una carrera más amplia.",secondaryMessage:"La distancia protege foco y puede parecer una respuesta defensiva.",primaryEffects:[n("professional.careerControl",3),n("reputation.mediaHeat",-1)],secondaryEffects:[n("professional.publicPolarization",2),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_RECORD_CHASE",{callback29Broken:"downplay"})],secondarySeedTransitions:[tr("SEED_RECORD_CHASE",{callback29Broken:"downplay"})]},
  {id:"C",label:"Usarlo como motivación para el siguiente objetivo",intentTags:["record","next_goal"],primaryMessage:"Aceptas que el récord cambió de dueño y conviertes la comparación en estímulo futuro.",secondaryMessage:"La ambición mantiene foco competitivo y puede prolongar una carrera de comparaciones.",primaryEffects:[n("professional.motivationReserve",3),n("professional.careerControl",2)],secondaryEffects:[n("reputation.mediaHeat",1),n("professional.publicPolarization",1)],primarySeedTransitions:[tr("SEED_RECORD_CHASE",{callback29Broken:"next_goal"})],secondarySeedTransitions:[tr("SEED_RECORD_CHASE",{callback29Broken:"next_goal"})]}
 ],gates:[{path:"flags.HAS_SEED_RECORD_CHASE",op:"eq",value:true},{path:"facts.rivalOrSuccessorBrokePlayerRecord",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_RECORD_CHASE","SEED_PUBLIC_RIVALRY"],seedsWrite:["SEED_RECORD_CHASE"],tags:["conditional","record","rivalry","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const PROJECT=ambiguousEvent({
 id:"CEVT_29_PROJECT_02",ageWindow:[29,30],phase:"26_30",family:"conditional",title:"El proyecto gira hacia otro",
 body:"El club que te vendió como centro cambia estrategia y construye alrededor de otro jugador. Una promesa de proyecto puede dejar de ser mentira y aun dejar de ser verdad.",
 visible:["Conoces el cambio de propietario o entrenador y las decisiones deportivas que muestran el nuevo centro."],uncertain:["No sabes si el giro es temporal ni si todavía existe un rol importante para ti."],
 choices:[
  {id:"A",label:"Pedir el nuevo plan y decidir con información actual",intentTags:["project","clarity"],primaryMessage:"Tratas la promesa original como contexto histórico y exiges entender la estructura presente.",secondaryMessage:"La claridad puede abrir una adaptación útil o confirmar que el proyecto ya no gira a tu alrededor.",primaryEffects:[n("professional.careerControl",4),n("professional.institutionalTrust",1)],secondaryEffects:[n("professional.environmentStability",-1),n("professional.careerControl",3)],primarySeedTransitions:[tr("SEED_PROJECT_FACE",{callback29Shift:"ask_new_plan"})],secondarySeedTransitions:[tr("SEED_PROJECT_FACE",{callback29Shift:"ask_new_plan"})]},
  {id:"B",label:"Adaptarte al nuevo reparto de poder",intentTags:["project","adapt"],primaryMessage:"Aceptas que el proyecto cambió y buscas valor dentro de la nueva estructura.",secondaryMessage:"La adaptación conserva continuidad y reduce parte del poder nominal con el que llegaste.",primaryEffects:[n("professional.roleAdaptability",3),n("professional.environmentStability",2)],secondaryEffects:[n("professional.institutionalPower",-2),n("professional.roleAdaptability",2)],primarySeedTransitions:[tr("SEED_PROJECT_FACE",{callback29Shift:"adapt_new_center"})],secondarySeedTransitions:[tr("SEED_PROJECT_FACE",{callback29Shift:"adapt_new_center"})]},
  {id:"C",label:"Explorar mercado sin declarar ruptura",intentTags:["project","market"],primaryMessage:"Usas el cambio como razón para recuperar opciones externas.",secondaryMessage:"El mercado devuelve palanca y puede convertir una reestructuración interna en salida.",primaryEffects:[n("professional.careerControl",5),n("reputation.marketHeat",3)],secondaryEffects:[n("professional.environmentStability",-2),n("reputation.mediaHeat",1)],primarySeedTransitions:[tr("SEED_PROJECT_FACE",{callback29Shift:"explore_market"})],secondarySeedTransitions:[tr("SEED_PROJECT_FACE",{callback29Shift:"explore_market"})]}
 ],gates:[{path:"flags.HAS_SEED_PROJECT_FACE",op:"eq",value:true},{path:"facts.projectShiftedToAnotherPlayer",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_PROJECT_FACE"],seedsWrite:["SEED_PROJECT_FACE"],tags:["conditional","project","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

export const T536_STAGED_CONDITIONAL_EVENTS:EventDefinition[]=[CLARA,AGENT,RECORD,PROJECT];
