import fs from 'fs';import path from 'path';
import { EVENTS_26_30 } from '../dist/content/events/26_30/index.js';import { MICROFEEDS_26_30 } from '../dist/content/microfeeds/26_30.js';
const dir=process.argv[2]??'qa/v06-shards';const files=fs.readdirSync(dir).filter(x=>x.endsWith('.json')).sort();
const sumObj=(dst,src)=>{for(const [k,v] of Object.entries(src))dst[k]=(dst[k]??0)+v};
let runs=0,elapsedMs=0,age30Reached=0,principal=0,conditional=0,feeds=0;const eventFrequency={},feedFrequency={},state30Frequency={},primaryState30Frequency={},comboFrequency={};const seq=new Set();
for(const file of files){const x=JSON.parse(fs.readFileSync(path.join(dir,file),'utf8'));runs+=x.runs;elapsedMs+=x.elapsedMs;age30Reached+=x.age30Reached;principal+=x.principal;conditional+=x.conditional;feeds+=x.feeds;sumObj(eventFrequency,x.eventFrequency);sumObj(feedFrequency,x.feedFrequency);sumObj(state30Frequency,x.state30Frequency);sumObj(primaryState30Frequency,x.primaryState30Frequency);sumObj(comboFrequency,x.comboFrequency);for(const h of x.sequenceHashes)seq.add(h)}
const principals=EVENTS_26_30.filter(e=>e.family!=='conditional').map(e=>e.id), conditionals=EVENTS_26_30.filter(e=>e.family==='conditional').map(e=>e.id), feedsExpected=MICROFEEDS_26_30.map(f=>f.id);
const statesExpected=['STATE30_WORLD_ICON','STATE30_GLOBAL_STAR','STATE30_ELITE_CAPTAIN','STATE30_ELITE_ROTATION_LUXURY','STATE30_PROJECT_FACE','STATE30_TOP_LEAGUE_STAR','STATE30_ONE_CLUB_LEGEND','STATE30_NATIONAL_ICON','STATE30_REINVENTED_VETERAN','STATE30_BODY_MANAGED_STAR','STATE30_EARLY_DECLINE_RISK','STATE30_BIG_CONTRACT_TRAP','STATE30_CONTRACT_KINGMAKER','STATE30_LATE_PEAK','STATE30_MEDIA_POLARIZED','STATE30_WEALTHY_EXIT','STATE30_EARLY_HOME_RETURN'];
const missingPrincipal=principals.filter(id=>!eventFrequency[id]), missingConditional=conditionals.filter(id=>!eventFrequency[id]), missingFeeds=feedsExpected.filter(id=>!feedFrequency[id]), missingStates=statesExpected.filter(id=>!state30Frequency[id]);
const report={runs,daysPerRun:4383,elapsedMsAggregate:elapsedMs,age30Reached,uniqueSequences:seq.size,avgPrincipal26_30:principal/runs,avgConditional26_30:conditional/runs,avgMicrofeeds26_30:feeds/runs,principalCoverage:[principals.length-missingPrincipal.length,principals.length],conditionalCoverage:[conditionals.length-missingConditional.length,conditionals.length],microfeedCoverage:[feedsExpected.length-missingFeeds.length,feedsExpected.length],state30Coverage:[statesExpected.length-missingStates.length,statesExpected.length],uniqueState30Combinations:Object.keys(comboFrequency).length,missingPrincipal,missingConditional,missingFeeds,missingStates,eventFrequency,feedFrequency,state30Frequency,primaryState30Frequency};
const counts=Object.values(primaryState30Frequency);const totalPrimary=counts.reduce((a,b)=>a+b,0);const entropy=totalPrimary? -counts.reduce((sum,c)=>{const p=c/totalPrimary;return c?sum+p*Math.log2(p):sum},0):0;
report.primaryState30EntropyBits=Math.round(entropy*1000)/1000;
report.finalNarrativeFrequency=Object.fromEntries(Object.entries(eventFrequency).filter(([k])=>k.includes('FINAL')));
const acceptance={passed:runs===1000&&age30Reached===1000&&seq.size===1000&&missingPrincipal.length===0&&missingConditional.length===0&&missingFeeds.length===0&&missingStates.length===0&&(principal/runs)>=15&&(principal/runs)<=23&&(conditional/runs)>=6&&(conditional/runs)<=10,runs,age30Reached,uniqueSequences:seq.size,principalCoverage:report.principalCoverage,conditionalCoverage:report.conditionalCoverage,microfeedCoverage:report.microfeedCoverage,state30Coverage:report.state30Coverage,uniqueState30Combinations:report.uniqueState30Combinations,avgPrincipal26_30:report.avgPrincipal26_30,avgConditional26_30:report.avgConditional26_30,avgMicrofeeds26_30:report.avgMicrofeeds26_30,primaryState30EntropyBits:report.primaryState30EntropyBits,missingPrincipal,missingConditional,missingStates,finalNarrativeFrequency:report.finalNarrativeFrequency};
fs.writeFileSync('qa/batch-1000-v06.json',JSON.stringify(report,null,2));fs.writeFileSync('qa/acceptance-v06.json',JSON.stringify(acceptance,null,2));console.log(JSON.stringify(report,null,2));
