import type { EventDefinition, SeedTransition } from "../../../core/types.js";
import { ambiguousEvent, n } from "../18_20/helpers.js";
const tr=(seedId:string,payload:Record<string,string|number|boolean|null>):SeedTransition=>({seedId,action:"transform",payload});

const RIVAS=ambiguousEvent({
 id:"CEVT_23_RIVAS_02",ageWindow:[23,26],phase:"23_26",family:"conditional",title:"Rivas firma la recomendación",
 body:"Rivas debe emitir un informe sobre ti. Puede ser positivo y aun advertir riesgos de carácter o rol.",
 visible:["Conoces que Rivas participa institucionalmente en la operación."],uncertain:["No sabes qué advertencias incluirá ni cuánto peso tendrá su informe."],
 choices:[
  {id:"A",label:"Contactarle antes del informe",intentTags:["rivas","contact"],primaryMessage:"Hablas con tu antiguo mentor sin pedir un favor automático.",secondaryMessage:"La conversación puede aclarar su lectura y también hacer más incómodo su deber profesional.",primaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",1)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_RIVAS_TRUST",{callback23:"contact_before_report"})],secondarySeedTransitions:[tr("SEED_RIVAS_TRUST",{callback23:"contact_before_report"})]},
  {id:"B",label:"Dejar que el proceso sea formal",intentTags:["rivas","formal"],primaryMessage:"Separas la historia personal del informe que debe firmar.",secondaryMessage:"Proteges límites y renuncias a contexto informal.",primaryEffects:[n("professional.institutionalTrust",2),n("professional.careerControl",2)],secondaryEffects:[n("professional.environmentStability",1),n("professional.careerControl",1)],primarySeedTransitions:[tr("SEED_RIVAS_TRUST",{callback23:"formal_process"})],secondarySeedTransitions:[tr("SEED_RIVAS_TRUST",{callback23:"formal_process"})]}
 ],gates:[{path:"flags.HAS_SEED_RIVAS_TRUST",op:"eq",value:true},{path:"facts.rivasReportOperationCompatible",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_RIVAS_TRUST"],seedsWrite:["SEED_RIVAS_TRUST"],npcRefs:["NPC_ACA_01"],tags:["conditional","rivas","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const MENA=ambiguousEvent({
 id:"CEVT_23_MENA_02",ageWindow:[23,26],phase:"23_26",family:"conditional",title:"Mena enfrente",
 body:"El equipo de Mena prepara una trampa táctica basada en hábitos que te conoce desde los 18.",
 visible:["Conoces señales del plan rival y qué hábitos antiguos intenta explotar."],uncertain:["No sabes si el plan es una lectura real o una invitación a sobrerreaccionar."],
 choices:[
  {id:"A",label:"Cambiar tu juego para romper la lectura",intentTags:["mena","change"],primaryMessage:"Alteras patrones conocidos para reducir la utilidad de su memoria táctica.",secondaryMessage:"La variación puede sorprender y alejarte de tus fortalezas.",primaryEffects:[n("professional.roleAdaptability",3),n("professional.careerControl",2)],secondaryEffects:[n("professional.roleSecurity",-1),n("professional.roleAdaptability",2)],primarySeedTransitions:[tr("SEED_MENA_EARLY_READ",{callback23:"change_patterns"})],secondarySeedTransitions:[tr("SEED_MENA_EARLY_READ",{callback23:"change_patterns"})]},
  {id:"B",label:"Mantener tus fortalezas",intentTags:["mena","keep_strengths"],primaryMessage:"Aceptas que conocer un hábito no equivale a poder detenerlo.",secondaryMessage:"La continuidad protege automatismos y hace más relevante la calidad del plan rival.",primaryEffects:[n("professional.careerControl",2),n("professional.environmentStability",1)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.careerControl",1)],primarySeedTransitions:[tr("SEED_MENA_EARLY_READ",{callback23:"keep_strengths"})],secondarySeedTransitions:[tr("SEED_MENA_EARLY_READ",{callback23:"keep_strengths"})]},
  {id:"C",label:"Usar su expectativa en contra",intentTags:["mena","counter_read"],primaryMessage:"Mantienes señales antiguas y cambias el comportamiento cuando la trampa se activa.",secondaryMessage:"La contra-lectura puede funcionar o dejarte reaccionando demasiado al rival.",primaryEffects:[n("professional.tacticalReading",4),n("professional.careerControl",2)],secondaryEffects:[n("professional.roleAdaptability",2),n("professional.environmentStability",-1)],primarySeedTransitions:[tr("SEED_MENA_EARLY_READ",{callback23:"counter_expectation"})],secondarySeedTransitions:[tr("SEED_MENA_EARLY_READ",{callback23:"counter_expectation"})]}
 ],gates:[{path:"flags.HAS_SEED_MENA_EARLY_READ",op:"eq",value:true},{path:"facts.menaRivalCoachTacticalTrap",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_MENA_EARLY_READ"],seedsWrite:["SEED_MENA_EARLY_READ"],npcRefs:["NPC_CCH_02"],tags:["conditional","mena","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const VELA=ambiguousEvent({
 id:"CEVT_23_VELA_02",ageWindow:[23,26],phase:"23_26",family:"conditional",title:"El curso de Vela",
 body:"Vela participa en una sesión con jóvenes o, si la relación fue mala, evita invitarte pese al interés del club.",
 visible:["Conoces su cargo actual y la existencia de la sesión."],uncertain:["No sabes cuánto pesa vuestra historia en su decisión."],
 choices:[
  {id:"A",label:"Participar si Vela te invita",intentTags:["vela","participate"],primaryMessage:"Aceptas colaborar en el marco institucional actual.",secondaryMessage:"La sesión puede reparar o normalizar la relación sin premio material.",primaryEffects:[n("professional.legacyCapital",2),n("professional.environmentStability",2)],secondaryEffects:[n("professional.publicMyth",1),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_VELA_STANCE",{callback23:"participate_session"})],secondarySeedTransitions:[tr("SEED_VELA_STANCE",{callback23:"participate_session"})]},
  {id:"B",label:"Ofrecerte por otra vía si no te invita",intentTags:["vela","alternate_channel"],primaryMessage:"Separas el interés por los jóvenes de la relación concreta con Vela.",secondaryMessage:"La iniciativa puede ser útil o sentirse como una forma de saltarte su decisión.",primaryEffects:[n("professional.careerControl",3),n("professional.legacyCapital",1)],secondaryEffects:[n("professional.environmentStability",-1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_VELA_STANCE",{callback23:"alternate_route"})],secondarySeedTransitions:[tr("SEED_VELA_STANCE",{callback23:"alternate_route"})]},
  {id:"C",label:"No intervenir",intentTags:["vela","no_intervention"],primaryMessage:"Aceptas que la sesión no necesita convertirse en un capítulo de vuestra relación.",secondaryMessage:"Proteges límites y dejas pasar una oportunidad de vínculo con la cantera.",primaryEffects:[n("professional.careerControl",2),n("professional.environmentStability",1)],secondaryEffects:[n("professional.legacyCapital",-1),n("professional.careerControl",1)],primarySeedTransitions:[tr("SEED_VELA_STANCE",{callback23:"no_intervention"})],secondarySeedTransitions:[tr("SEED_VELA_STANCE",{callback23:"no_intervention"})]}
 ],gates:[{path:"flags.HAS_SEED_VELA_STANCE",op:"eq",value:true},{path:"facts.velaYouthSessionInstitutionRole",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_VELA_STANCE"],seedsWrite:["SEED_VELA_STANCE"],npcRefs:["NPC_PLR_10"],tags:["conditional","vela","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const BRUNO=ambiguousEvent({
 id:"CEVT_23_BRUNO_03",ageWindow:[23,26],phase:"23_26",family:"conditional",title:"Bruno necesita club",
 body:"Bruno pregunta si tu agente puede moverle en un momento de declive. Recomendarlo puede gastar capital y negarte puede ser razonable si no encaja.",
 visible:["Conoces su situación y qué tipo de ayuda pide."],uncertain:["No sabes si tu agente tiene un destino real ni si una recomendación mejorará sus opciones."],
 choices:[
  {id:"A",label:"Recomendarlo a tu agente",intentTags:["bruno","recommend"],primaryMessage:"Gastas capital relacional para abrir una conversación, no para garantizarle club.",secondaryMessage:"La ayuda puede servir o quemar credibilidad si no existe encaje.",primaryEffects:[n("professional.environmentStability",2),n("professional.agentControl",-1)],secondaryEffects:[n("professional.careerControl",-1),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_BRUNO_FAVOR",{callback23:"recommend_to_agent"})],secondarySeedTransitions:[tr("SEED_BRUNO_FAVOR",{callback23:"recommend_to_agent"})]},
  {id:"B",label:"Pedir primero a tu agente si existe encaje real",intentTags:["bruno","check_fit"],primaryMessage:"Compruebas mercado antes de prestar tu nombre.",secondaryMessage:"La prudencia protege capital y puede sentirse como falta de apoyo.",primaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",1)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_BRUNO_FAVOR",{callback23:"check_fit_first"})],secondarySeedTransitions:[tr("SEED_BRUNO_FAVOR",{callback23:"check_fit_first"})]},
  {id:"C",label:"Negarte a recomendarlo si no ves encaje",intentTags:["bruno","decline"],primaryMessage:"Separas afecto y recomendación profesional.",secondaryMessage:"El límite puede ser razonable y doloroso al mismo tiempo.",primaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",-1)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_BRUNO_FAVOR",{callback23:"decline_recommendation"})],secondarySeedTransitions:[tr("SEED_BRUNO_FAVOR",{callback23:"decline_recommendation"})]}
 ],gates:[{path:"flags.HAS_SEED_BRUNO_FAVOR",op:"eq",value:true},{path:"facts.brunoDeclineAsksAgentHelp",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_BRUNO_FAVOR"],seedsWrite:["SEED_BRUNO_FAVOR"],npcRefs:["NPC_PLR_12"],tags:["conditional","bruno","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const ADR=ambiguousEvent({
 id:"CEVT_23_ADR_03",ageWindow:[23,26],phase:"23_26",family:"conditional",title:"Los dos en la absoluta",
 body:"Una concentración os vuelve a poner juntos y una entrevista busca enfrentaros. La rivalidad espejo no obliga enemistad.",
 visible:["Conoces la convocatoria real y las preguntas previstas."],uncertain:["No sabes cómo Adrián quiere gestionar el relato ni qué rol deportivo tendrá cada uno."],
 choices:[
  {id:"A",label:"Coordinar una respuesta con Adrián",intentTags:["adrian","coordinate"],primaryMessage:"Intentáis evitar que una entrevista fabrique un conflicto que ninguno quiere.",secondaryMessage:"La coordinación reduce hostilidad y puede parecer demasiado calculada.",primaryEffects:[n("professional.environmentStability",2),n("professional.publicPolarization",-1)],secondaryEffects:[n("reputation.mediaHeat",1),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_ADRIAN_MIRROR",{callback23:"coordinate_response"})],secondarySeedTransitions:[tr("SEED_ADRIAN_MIRROR",{callback23:"coordinate_response"})]},
  {id:"B",label:"Competir por foco sin atacar",intentTags:["adrian","compete"],primaryMessage:"Aceptas la comparación como competencia pública y mantienes límites personales.",secondaryMessage:"La rivalidad gana energía y puede invadir el vestuario de selección.",primaryEffects:[n("professional.publicMyth",2),n("professional.publicPolarization",2)],secondaryEffects:[n("reputation.mediaHeat",2),n("professional.publicPolarization",3)],primarySeedTransitions:[tr("SEED_ADRIAN_MIRROR",{callback23:"compete_for_focus"})],secondarySeedTransitions:[tr("SEED_ADRIAN_MIRROR",{callback23:"compete_for_focus"})]},
  {id:"C",label:"Ignorar el relato",intentTags:["adrian","ignore"],primaryMessage:"Tratas la concentración como selección y no como capítulo de una comparación antigua.",secondaryMessage:"Reducir combustible no impide que los medios mantengan el marco.",primaryEffects:[n("professional.careerControl",3),n("reputation.mediaHeat",-1)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_ADRIAN_MIRROR",{callback23:"ignore_story"})],secondarySeedTransitions:[tr("SEED_ADRIAN_MIRROR",{callback23:"ignore_story"})]}
 ],gates:[{path:"flags.HAS_SEED_ADRIAN_MIRROR",op:"eq",value:true},{path:"facts.adrianAndPlayerSameNationalCamp",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_ADRIAN_MIRROR"],seedsWrite:["SEED_ADRIAN_MIRROR"],npcRefs:["NPC_PLR_15"],tags:["conditional","adrian","selection","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

export const T537_STAGED_CONDITIONAL_EVENTS:EventDefinition[]=[RIVAS,MENA,VELA,BRUNO,ADR];
