import type { EventDefinition, SeedTransition } from "../../../core/types.js";
import { ambiguousEvent, n } from "../18_20/helpers.js";
const tr=(seedId:string,payload:Record<string,string|number|boolean|null>):SeedTransition=>({seedId,action:"transform",payload});

const NANO=ambiguousEvent({
 id:"CEVT_23_NANO_02",ageWindow:[23,26],phase:"23_26",family:"conditional",title:"Nano te pide que no llames",
 body:"Te enteras de que Nano está sin jugar. Cuando contactas, te dice que no quiere que «le arregles» la carrera.",
 visible:["Conoces que está en una etapa deportiva difícil y que ha marcado un límite explícito."],uncertain:["No sabes si rechaza toda ayuda o solo una ayuda que le quite agencia."],
 choices:[
  {id:"A",label:"Respetar y no intervenir",intentTags:["nano","respect"],primaryMessage:"Aceptas su límite aunque tengas recursos para ayudar.",secondaryMessage:"La autonomía queda protegida y la distancia puede mantenerse.",primaryEffects:[n("professional.environmentStability",1),n("professional.careerControl",2)],secondaryEffects:[n("professional.environmentStability",-1),n("professional.careerControl",1)],primarySeedTransitions:[tr("SEED_NANO_SHADOW",{callback23Crisis:"respect_boundary"})],secondarySeedTransitions:[tr("SEED_NANO_SHADOW",{callback23Crisis:"respect_boundary"})]},
  {id:"B",label:"Ofrecer una ayuda concreta y dejar que decida",intentTags:["nano","specific_help"],primaryMessage:"Ofreces una puerta concreta sin mover contactos por detrás.",secondaryMessage:"La ayuda preserva elección y puede seguir sintiéndose como tutela.",primaryEffects:[n("professional.environmentStability",2),n("professional.careerControl",2)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_NANO_SHADOW",{callback23Crisis:"specific_offer"})],secondarySeedTransitions:[tr("SEED_NANO_SHADOW",{callback23Crisis:"specific_offer"})]},
  {id:"C",label:"Hablar con un tercero sin comprometer a Nano",intentTags:["nano","third_party"],primaryMessage:"Buscas información general sin prometer nada en su nombre.",secondaryMessage:"El paso puede aportar contexto o vulnerar el espíritu de su límite.",primaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",-1)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_NANO_SHADOW",{callback23Crisis:"third_party_context"})],secondarySeedTransitions:[tr("SEED_NANO_SHADOW",{callback23Crisis:"third_party_context"})]}
 ],gates:[{path:"flags.HAS_SEED_NANO_SHADOW",op:"eq",value:true},{path:"facts.nanoCurrentCareerCrisis",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_NANO_SHADOW"],seedsWrite:["SEED_NANO_SHADOW"],npcRefs:["NPC_PLR_14"],tags:["conditional","nano","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const CLARA=ambiguousEvent({
 id:"CEVT_23_CLARA_03",ageWindow:[23,26],phase:"23_26",family:"conditional",title:"La exclusiva antes de la lista",
 body:"Clara conoce una decisión relevante antes de hacerse oficial y ofrece contártela si no la atribuyes.",
 visible:["Sabes qué tipo de decisión conoce y las condiciones de atribución."],uncertain:["No sabes si la información cambiará antes del anuncio ni qué otras fuentes tiene."],
 choices:[
  {id:"A",label:"Escuchar bajo esas condiciones",intentTags:["clara","listen"],primaryMessage:"Aceptas recibir la información sin convertirla en fuente pública propia.",secondaryMessage:"El acceso mejora preparación y aumenta responsabilidad sobre qué haces con lo sabido.",primaryEffects:[n("professional.careerControl",3),n("reputation.mediaHeat",1)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_CLARA_CHANNEL",{callback23Exclusive:"listen"})],secondarySeedTransitions:[tr("SEED_CLARA_CHANNEL",{callback23Exclusive:"listen"})]},
  {id:"B",label:"Rechazar la exclusiva",intentTags:["clara","decline"],primaryMessage:"Prefieres esperar a la comunicación oficial.",secondaryMessage:"Proteges límites y pierdes una ventaja informativa real.",primaryEffects:[n("professional.careerControl",2),n("professional.environmentStability",1)],secondaryEffects:[n("reputation.mediaHeat",-1),n("professional.careerControl",1)],primarySeedTransitions:[tr("SEED_CLARA_CHANNEL",{callback23Exclusive:"decline"})],secondarySeedTransitions:[tr("SEED_CLARA_CHANNEL",{callback23Exclusive:"decline"})]},
  {id:"C",label:"Intercambiar información no sensible",intentTags:["clara","reciprocity"],primaryMessage:"Mantienes el canal como relación de doble dirección sin filtrar material protegido.",secondaryMessage:"La reciprocidad fortalece confianza y crea nuevas expectativas de intercambio.",primaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",2)],secondaryEffects:[n("reputation.mediaHeat",1),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_CLARA_CHANNEL",{callback23Exclusive:"non_sensitive_exchange"})],secondarySeedTransitions:[tr("SEED_CLARA_CHANNEL",{callback23Exclusive:"non_sensitive_exchange"})]}
 ],gates:[{path:"flags.HAS_SEED_CLARA_CHANNEL",op:"eq",value:true},{path:"facts.claraPreOfficialRelevantDecision",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_CLARA_CHANNEL"],seedsWrite:["SEED_CLARA_CHANNEL"],npcRefs:["NPC_PRS_01"],tags:["conditional","clara","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const MED=ambiguousEvent({
 id:"CEVT_23_MED_02",ageWindow:[23,26],phase:"23_26",family:"conditional",title:"Paula pide todos los informes",
 body:"Paula, desde Valdoria o una consulta autorizada, ve patrones que tu club actual interpreta de otro modo.",
 visible:["Conoces su lectura y la diferencia con el staff actual."],uncertain:["No sabes cuál de las dos interpretaciones anticipará mejor tu evolución."],
 choices:[
  {id:"A",label:"Compartir su opinión con el club",intentTags:["medical","share"],primaryMessage:"Introduces una segunda lectura en la cadena médica actual.",secondaryMessage:"La información puede enriquecer el plan o generar choque entre staffs.",primaryEffects:[n("professional.careerControl",3),n("professional.recoveryMargin",1)],secondaryEffects:[n("professional.environmentStability",-1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_PHYSIO_CONFIDENCE",{callback23Medical:"share_with_club"})],secondarySeedTransitions:[tr("SEED_PHYSIO_CONFIDENCE",{callback23Medical:"share_with_club"})]},
  {id:"B",label:"Pedir una segunda opinión delimitada",intentTags:["medical","second_opinion"],primaryMessage:"Usas a Paula como contraste puntual sin crear dos cadenas paralelas de autoridad.",secondaryMessage:"El enfoque reduce solapamiento y puede no resolver la discrepancia.",primaryEffects:[n("professional.careerControl",3),n("professional.environmentStability",1)],secondaryEffects:[n("professional.recoveryMargin",1),n("professional.careerControl",2)],primarySeedTransitions:[tr("SEED_PHYSIO_CONFIDENCE",{callback23Medical:"bounded_second_opinion"})],secondarySeedTransitions:[tr("SEED_PHYSIO_CONFIDENCE",{callback23Medical:"bounded_second_opinion"})]},
  {id:"C",label:"No mezclar equipos médicos",intentTags:["medical","single_chain"],primaryMessage:"Mantienes una sola cadena de decisión con el club actual.",secondaryMessage:"La coordinación mejora y renuncias a una lectura que podría ser útil.",primaryEffects:[n("professional.institutionalTrust",2),n("professional.environmentStability",2)],secondaryEffects:[n("professional.careerControl",-1),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_PHYSIO_CONFIDENCE",{callback23Medical:"do_not_mix"})],secondarySeedTransitions:[tr("SEED_PHYSIO_CONFIDENCE",{callback23Medical:"do_not_mix"})]}
 ],gates:[{path:"flags.HAS_SEED_PHYSIO_CONFIDENCE",op:"eq",value:true},{path:"facts.paulaAuthorizedContrastingMedicalRead",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_PHYSIO_CONFIDENCE","SEED_CHRONIC_BODY","SEED_MEDICAL_DISCLOSURE"],seedsWrite:["SEED_PHYSIO_CONFIDENCE"],npcRefs:["NPC_MED_01"],tags:["conditional","medical","paula","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const UDV=ambiguousEvent({
 id:"CEVT_23_UDV_02",ageWindow:[23,26],phase:"23_26",family:"conditional",title:"UDV elimina a un grande",
 body:"Tu antiguo club vive una noche histórica y te pide aparecer por videollamada o vestuario. Tu equipo actual podría ser rival o estar en plena concentración.",
 visible:["Conoces el hito, la invitación y tu calendario actual."],uncertain:["No sabes si tu presencia suma al momento o desplaza foco hacia tu propia historia."],
 choices:[
  {id:"A",label:"Aparecer en la celebración",intentTags:["home","appear"],primaryMessage:"Participas como parte del pasado del club sin reclamar el logro actual.",secondaryMessage:"El vínculo se refuerza y tu presencia puede dominar parte de la atención.",primaryEffects:[n("professional.homePull",4),n("professional.legacyCapital",2)],secondaryEffects:[n("reputation.mediaHeat",2),n("professional.publicMyth",1)],primarySeedTransitions:[tr("SEED_HOME_DISTANCE",{callback23Udv:"appear"})],secondarySeedTransitions:[tr("SEED_HOME_DISTANCE",{callback23Udv:"appear"})]},
  {id:"B",label:"Enviar un mensaje y no entrar en directo",intentTags:["home","message"],primaryMessage:"Reconoces el hito y mantienes el foco sobre quienes lo consiguieron.",secondaryMessage:"La distancia protege obligaciones actuales y reduce presencia simbólica.",primaryEffects:[n("professional.homePull",2),n("professional.environmentStability",1)],secondaryEffects:[n("professional.publicMyth",-1),n("professional.homePull",1)],primarySeedTransitions:[tr("SEED_HOME_DISTANCE",{callback23Udv:"message_only"})],secondarySeedTransitions:[tr("SEED_HOME_DISTANCE",{callback23Udv:"message_only"})]},
  {id:"C",label:"Priorizar a tu equipo actual",intentTags:["home","current_team"],primaryMessage:"No participas porque el calendario actual tiene prioridad real.",secondaryMessage:"Proteges concentración y aceptas que el origen viva su historia sin ti.",primaryEffects:[n("professional.institutionalTrust",2),n("professional.careerControl",2)],secondaryEffects:[n("professional.homePull",-1),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_HOME_DISTANCE",{callback23Udv:"current_team_first"})],secondarySeedTransitions:[tr("SEED_HOME_DISTANCE",{callback23Udv:"current_team_first"})]}
 ],gates:[{path:"flags.HAS_SEED_HOME_DISTANCE",op:"eq",value:true},{path:"facts.udvHistoricCupOrFriendlyUpset",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_HOME_DISTANCE"],seedsWrite:["SEED_HOME_DISTANCE"],npcRefs:["NPC_DIR_02"],tags:["conditional","home","udv","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

const TOURN=ambiguousEvent({
 id:"CEVT_24_TOURN_01",ageWindow:[24,26],phase:"23_26",family:"conditional",title:"Entraste por una lesión",
 body:"Llegas a la lista final como reemplazo tardío por la lesión de un tercero conocido. La oportunidad deportiva nace de una mala noticia ajena.",
 visible:["Conoces la convocatoria, la baja real y el rol inicial que te ofrece la selección."],uncertain:["No sabes si tendrás minutos ni si seguirás en la lista cuando el lesionado vuelva."],
 choices:[
  {id:"A",label:"Aceptar la llamada sin presentarla como triunfo personal",intentTags:["selection","late_call"],primaryMessage:"Entras al torneo y separas tu oportunidad de la lesión del otro jugador.",secondaryMessage:"La prudencia protege el contexto y no reduce la precariedad de tu rol.",primaryEffects:[n("professional.nationalPower",2),n("professional.environmentStability",1)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.nationalPower",1)],primarySeedTransitions:[tr("SEED_MAJOR_TOURNAMENT",{callback24:"injury_replacement"})],secondarySeedTransitions:[tr("SEED_MAJOR_TOURNAMENT",{callback24:"injury_replacement"})]},
  {id:"B",label:"Contactar al jugador lesionado antes de incorporarte",intentTags:["selection","respect_injured"],primaryMessage:"Reconoces la situación humana sin convertir el contacto en permiso para aceptar.",secondaryMessage:"El gesto puede cuidar la relación y añadir carga emocional innecesaria.",primaryEffects:[n("professional.environmentStability",2),n("professional.nationalPower",1)],secondaryEffects:[n("professional.publicPolarization",1),n("professional.environmentStability",1)],primarySeedTransitions:[tr("SEED_MAJOR_TOURNAMENT",{callback24:"contact_injured_player"})],secondarySeedTransitions:[tr("SEED_MAJOR_TOURNAMENT",{callback24:"contact_injured_player"})]},
  {id:"C",label:"Incorporarte y centrarte en el rol precario",intentTags:["selection","role_focus"],primaryMessage:"Tratas la convocatoria como oportunidad real pero reversible.",secondaryMessage:"La concentración en el rol reduce relato y no garantiza continuidad.",primaryEffects:[n("professional.careerControl",2),n("professional.nationalPower",2)],secondaryEffects:[n("professional.roleSecurity",-1),n("professional.careerControl",1)],primarySeedTransitions:[tr("SEED_MAJOR_TOURNAMENT",{callback24:"focus_role"})],secondarySeedTransitions:[tr("SEED_MAJOR_TOURNAMENT",{callback24:"focus_role"})]}
 ],gates:[{path:"facts.lateTournamentReplacementCall",op:"eq",value:true}],weight:10,cooldown:99999,seedsRead:["SEED_MAJOR_TOURNAMENT"],seedsWrite:["SEED_MAJOR_TOURNAMENT"],tags:["conditional","selection","tournament","a6_ready_external_blocker","t5_conditional"],canonStatus:"verified"
});

export const T538_STAGED_CONDITIONAL_EVENTS:EventDefinition[]=[NANO,CLARA,MED,UDV,TOURN];
