import { createIndexedSaveStore } from './indexed-save-store.js';
// UI reads PlayerView only. All career mutations go through GameSession commands.
export function mountGame({root, GameSession, assets, css, storageKey='historia-jugador.preview.session.v1', events}) {
  const KEY=storageKey;
  let session=null, busy=false, paused=false, view='home', cinematic=false, message='', replacement=null, lastArt='stadium_bg';
  let savedRaw=null;
  const sessionOptions=events?{events}:{};
  const store=createIndexedSaveStore({storage:localStorage,indexedDB:globalThis.indexedDB,key:KEY,validate:raw=>GameSession.fromSave(raw,sessionOptions)});
  const doc=root.ownerDocument, win=doc.defaultView||globalThis, el=(tag,text,cls)=>{const n=doc.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
  const style=el('style');style.textContent=css;root.append(style);
  const shell=el('div',undefined,'mh');root.append(shell);
  const date=s=>new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(s+'T00:00:00Z'));
  const decisionCount=n=>`${n} ${n===1?'decisión':'decisiones'}`;
  const hasBackup=()=>store.hasPrevious();
  const money=n=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
  const clubName=name=>name==='UDV'?'U. D. Valdoria':name==='BIG_CLUB'?'Gran club':name.startsWith('Foreign_')?'Club extranjero':name.startsWith('Loan_')?'Club de cesión':name;
  const club=v=>clubName(v.club);
  const position=v=>({winger:'Extremo',midfielder:'Centrocampista',striker:'Delantero',defender:'Defensa',goalkeeper:'Portero'})[v.position]||'Futbolista';
  const svgPaths={home:'M3 10 12 3l9 7v11h-6v-7H9v7H3z',career:'M5 3h14v18H5z M8 8h8M8 12h8M8 16h5',world:'M3 12h18M12 3c-5 5-5 13 0 18 5-5 5-13 0-18 M12 3a9 9 0 1 0 0 18 9 9 0 1 0 0-18',relations:'M2 21c0-9 13-9 13 0M15 14c4-1 7 2 7 6 M8.5 3a4 4 0 1 0 0 8 4 4 0 1 0 0-8 M17 5a3 3 0 0 1 0 6',profile:'M4 21c0-10 16-10 16 0 M12 3a4 4 0 1 0 0 8 4 4 0 1 0 0-8',save:'M4 3h14l3 3v15H3V3h1 M7 3v7h10V3M7 21v-7h10v7',arrow:'M4 12h15M14 6l6 6-6 6'};
  function icon(name){const s=doc.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('viewBox','0 0 24 24');s.setAttribute('aria-hidden','true');const p=doc.createElementNS(s.namespaceURI,'path');p.setAttribute('d',svgPaths[name]||svgPaths.arrow);s.append(p);return s;}
  function button(text,fn,cls='secondary',options={}){const b=el('button',undefined,cls);b.type='button';b.append(el('span',text));b.disabled=busy||(paused&&options.blockedWhenPaused===true);if(options.ariaLabel)b.setAttribute('aria-label',options.ariaLabel);if(options.pressed!==undefined)b.setAttribute('aria-pressed',String(options.pressed));b.addEventListener('click',fn);return b;}
  function photo(name,cls='photo'){const img=el('img',undefined,cls);img.src=assets[name]||assets.stadium_bg;img.alt='';img.draggable=false;return img;}
  function panel(title){const p=el('article',undefined,'panel');p.append(el('h2',title));return p;}
  const validViews=new Set(['home','career','world','relations','profile','save']);
  let historyReady=false;
  function routeState(){return {mhOwner:true,mhView:view,mhCinematic:cinematic};}
  function replaceRouteState(){if(win.history?.replaceState)win.history.replaceState(routeState(),'');}
  function prepareHistory(){if(historyReady||!win.history?.replaceState)return;const initialCinematic=cinematic;win.history.replaceState({...routeState(),mhCinematic:false},'');historyReady=true;if(initialCinematic)win.history.pushState(routeState(),'');}
  function navigate(name){view=validViews.has(name)?name:'home';cinematic=false;message='';if(historyReady)win.history.pushState(routeState(),'');else prepareHistory();render(true);}
  function openCinematic(){if(!session)return;cinematic=true;if(historyReady)win.history.pushState(routeState(),'');else prepareHistory();render(true);}
  function closeCinematic(){if(historyReady&&win.history.state?.mhOwner&&win.history.state.mhCinematic){win.history.back();return;}cinematic=false;view='home';replaceRouteState();render(true);}
  function goBack(){if(cinematic){closeCinematic();return;}if(historyReady&&win.history.state?.mhOwner&&view!=='home'){win.history.back();return;}if(view!=='home'){view='home';replaceRouteState();render(true);}}
  function pauseToggle(){if(!session||busy)return;paused=!paused;render();}
  async function commit(next,previous){
    if(previous){const current=savedRaw&&JSON.parse(savedRaw);if(!current||current.sessionId!==previous.sessionId||current.revision!==previous.revision)throw Error('Recupera la partida guardada antes de continuar.');}
    await store.write(next,previous?savedRaw:replacement);
    savedRaw=JSON.stringify(next);
  }
  async function load(){
    if(busy)return;busy=true;message='';render();
    try{const raw=await store.read();savedRaw=raw;if(raw){session=await GameSession.fromSave(raw,{...sessionOptions,commit});cinematic=['decision','result','offer'].includes(session.getView().screen);}else{replacement=null;session=await GameSession.create(424242,{...sessionOptions,commit});}prepareHistory(); if(await store.legacyChanged())message='Otra pestaña ha cambiado la copia antigua. Puedes descargarla en Tu partida para revisarla antes de importar.'; }
    catch(e){session=null;message='No se pudo abrir la partida. '+e.message+' La copia guardada se conserva.';view='save';}
    finally{busy=false;render();}
  }
  async function run(type,extra={}){
    if(busy||paused||!session)return;
    const command={type,commandId:crypto.randomUUID(),expectedRevision:session.getView().revision,...extra};
    busy=true;message='';render();
    try{const wasCinematic=cinematic;await session.dispatch(command);cinematic=['decision','result','offer'].includes(session.getView().screen);view='home';if(cinematic&&!wasCinematic){if(historyReady)win.history.pushState(routeState(),'');else prepareHistory();}else if(!cinematic)replaceRouteState();}
    catch(e){message=e.message+' Recupera la partida guardada antes de reintentar.';}
    finally{busy=false;render(true);}
  }
  function mainAction(v){
    if(v.screen==='offer')return button('Revisar oferta',openCinematic,'primary',{blockedWhenPaused:true});
    if(v.screen==='decision')return button('Una decisión te espera',openCinematic,'primary',{blockedWhenPaused:true});
    if(v.screen==='result')return button('Volver a tu decisión',openCinematic,'primary',{blockedWhenPaused:true});
    if(v.screen==='epilogue')return button('Ver mi carrera',()=>navigate('career'),'primary');
    return button('Simular semana',()=>run('continue',{maxDays:7}),'primary',{blockedWhenPaused:true});
  }
  function hero(v){const h=el('article',undefined,'hero');h.append(photo('hero_player'));const c=el('div',undefined,'hero-copy');c.append(el('span','TU HISTORIA, POR ESCRIBIR','eyebrow'),el('h1','Una vida.\nMil decisiones.'),el('p',position(v)+' · '+v.age+' años'),el('p',club(v),'muted'));h.append(c);return h;}
  function stats(v){const p=panel('Tu momento');for(const [label,value]of[['Forma',v.form],['Estado físico',v.fitness],['Fatiga',v.fatigue]]){const row=el('div',undefined,'meter');row.append(el('span',label),el('strong',Math.round(value)+' / 100'));const meter=el('progress');meter.max=100;meter.value=value;meter.setAttribute('aria-label',label);row.append(meter);p.append(row);}p.append(el('p',v.appearances+' partidos disputados','muted'));return p;}
  function home(v,main){const grid=el('div',undefined,'home-grid');grid.append(hero(v));const next=panel(v.screen==='epilogue'?'El final de un capítulo':'Lo que viene ahora');next.classList.add('next');next.append(photo('stadium_bg','card-bg'));const content=el('div',undefined,'next-content');content.append(el('span',date(v.date),'eyebrow'),el('h2',v.offer?.reason||v.decision?.title||v.result?.title||(v.screen==='epilogue'?'Una carrera para recordar':'El siguiente paso.')),
      el('p',v.offer?'Hay una propuesta de contrato que necesita tu respuesta.':v.decision?'Hay un momento que necesita tu respuesta.':v.result?'Tu decisión ya forma parte de esta historia.':v.screen==='epilogue'?'Mira atrás y recorre los momentos que te han traído hasta aquí.':'Entrenamientos, partidos y conversaciones. Avanza hasta que la vida te pida decidir.','muted'),mainAction(v));next.append(content);grid.append(next,stats(v));
    const recent=panel('El último capítulo');recent.classList.add('recent');recent.append(photo('hero_player','news-thumb'));const row=v.journal.at(-1);recent.append(el('h3',row?.title||'Todo empieza en Valdoria'),el('p',row?.messages[0]||'Una oportunidad de acercarte al primer equipo. Todavía queda todo por decidir.','muted'),button('Recorrer mi historia',()=>navigate('career')));grid.append(recent);
    const tutorial=panel('Cómo se juega');tutorial.classList.add('tutorial');tutorial.append(el('p','Simula una semana para avanzar. Cuando aparezca un momento, lee lo que sabes, revisa lo que no está claro y elige una respuesta. Después podrás ver el resultado y continuar.','muted'));grid.append(tutorial);
    const people=panel('Tu entorno');const contacts=v.contacts.filter(c=>['NPC_CCH_01','NPC_MED_01','NPC_FAM_01'].includes(c.id));for(const c of contacts){const r=el('div',undefined,'contact-row');r.append(photo(portrait(c.id),'avatar'));const info=el('div');info.append(el('strong',c.name),el('p',c.role,'muted'));r.append(info);people.append(r);}people.append(button('Ver relaciones',()=>navigate('relations')));grid.append(people);
    const chapter=panel('Tu carrera');chapter.append(el('span',v.season.replace('-',' / 20'),'eyebrow'),el('div',String(v.decisionsMade),'big-number'),el('p',v.decisionsMade===1?'decisión que cuenta':'decisiones que cuentan','muted'),el('p','Tu recorrido se construye con lo que eliges.'),button('Ver recorrido',()=>navigate('career')));grid.append(chapter);main.append(grid);if(v.offerHistory.length){const h=v.offerHistory.at(-1),p=panel('Tu última respuesta de contrato');p.append(el('p',h.explanation));main.append(p);}}
  function portrait(id){return ({NPC_CCH_01:'portrait_coach',NPC_MED_01:'portrait_doctor',NPC_FAM_01:'portrait_mother',NPC_FAM_02:'portrait_father',NPC_AGT_01:'portrait_agent',NPC_AGT_02:'portrait_agent'})[id]||null;}
  function renderDecision(v,main){if(v.screen==='offer'){renderOffer(v,main);return;}const d=v.decision, result=v.screen==='result';if(d)lastArt=['preseason','sport','team','captaincy','tactical'].includes(d.family)?'prematch_scene':'stadium_bg';
    main.classList.add('cinema');main.append(photo(lastArt,'cinema-bg'));const top=el('div',undefined,'cinema-top');top.append(button('Volver a Inicio',closeCinematic,'glass'),el('span',date(v.date)+' · '+club(v),'eyebrow'));main.append(top);
    const sheet=el('section',undefined,'decision-sheet');sheet.append(el('span',result?'DESPUÉS DE TU DECISIÓN':'UN MOMENTO QUE CUENTA','eyebrow'),el('h1',result?v.result.title:d.title));
    if(result){sheet.append(el('p',v.result.choiceLabel,'chosen'));v.result.messages.forEach(m=>sheet.append(el('p',m,'story-text')));if(v.resultCategory==='match'){const summary=el('section',undefined,'match-summary');summary.append(el('h2','Resumen del partido'),el('p','Tu decisión queda registrada en el recorrido.','muted'));const rows=[['Fecha',date(v.date)],['Partidos disputados',String(v.appearances)],['Forma',`${Math.round(v.form)} / 100`],['Estado físico',`${Math.round(v.fitness)} / 100`]];for(const [label,value]of rows){const row=el('div',undefined,'data-row');row.append(el('span',label),el('strong',value));summary.append(row);}sheet.append(summary);}sheet.append(button('Continuar',()=>run('acknowledge'),'primary',{blockedWhenPaused:true}));}
    else{sheet.append(el('p',d.body,'story-text'));const intel=el('details',undefined,'intel');intel.open=true;intel.append(el('summary','Lo que sabes · lo que queda por descubrir'));for(const [title,lines]of[['Lo que sabes',d.visible],['Lo que no está claro',d.uncertain]]){if(lines.length){intel.append(el('h3',title));lines.forEach(t=>intel.append(el('p',t)));}}sheet.append(intel);const choices=el('div',undefined,'choices');d.choices.forEach((c,i)=>{const b=button('',()=>run('choose',{pendingInstanceId:d.instanceId,choiceId:c.id}),'choice',{blockedWhenPaused:true});b.replaceChildren(el('span',String.fromCharCode(65+i),'choice-key'),el('span',c.label));choices.append(b);});sheet.append(choices);}
    main.append(sheet);}
  function renderOffer(v,main){
    const o=v.offer,p=panel(o.reason);p.append(el('p','Una propuesta para tu carrera. Revisa las condiciones antes de decidir.','story-text'));
    for(const [label,before,after] of [['Club',clubName(o.before.club),clubName(o.terms.club)],['Club propietario',clubName(o.before.ownerClub),clubName(o.terms.ownerClub)],['Categoría',o.before.leagueTier,o.terms.leagueTier],['Salario mensual',money(o.before.salary),money(o.terms.salary)],['Duración',o.before.months+' meses',o.terms.months+' meses'],['Cláusula',o.before.releaseClause===null?'Sin cláusula':money(o.before.releaseClause),o.terms.releaseClause===null?'Sin cláusula':money(o.terms.releaseClause)]]){
      const row=el('div',undefined,'data-row');row.append(el('span',label),el('strong',before+' → '+after));p.append(row);
    }
    p.append(el('p',o.terms.loan?'La propuesta es una cesión.':'La propuesta no es una cesión.','muted'));
    p.append(el('p','Si delegas esta oferta, tu representante solo aceptará si no baja el salario ni la categoría y asegura al menos 12 meses. La delegación termina con esta respuesta.','story-text'));
    const choices=el('div',undefined,'choices');for(const [action,label]of [['accept','Aceptar oferta'],['reject','Rechazar oferta'],['delegate','Delegar esta oferta']])choices.append(button(label,()=>run('offer',{offerId:o.id,action}),'choice',{blockedWhenPaused:true}));
    p.append(choices,button('Volver a Inicio',closeCinematic));main.append(p);
  }
  function offerHistory(v,main){for(const h of [...v.offerHistory].reverse()){const p=panel(h.offer.reason);p.append(el('time',date(h.offer.date),'eyebrow'),el('p',h.explanation),el('p',clubName(h.offer.terms.club)+' · '+money(h.offer.terms.salary)+' al mes · '+h.offer.terms.months+' meses','muted'));main.append(p);}}
  function career(v,main){offerHistory(v,main);main.append(el('span','CADA DECISIÓN DEJA HUELLA','eyebrow'),el('h1','Tu carrera. Tu historia.'));if(v.ageMilestones.length){const milestones=panel('Hitos de edad');for(const m of v.ageMilestones)milestones.append(el('p',`${m.age} años · ${date(m.date)} · ${clubName(m.club)} · ${m.signature}`,'muted'));main.append(milestones);}const list=el('div',undefined,'timeline');if(!v.journal.length)list.append(el('p','El primer capítulo está a punto de empezar.','muted'));for(const row of [...v.journal].reverse()){const item=panel(row.title);item.prepend(el('time',date(row.date),'eyebrow'));item.append(el('p',row.choiceLabel,'chosen'));row.messages.forEach(m=>item.append(el('p',m,'muted')));list.append(item);}main.append(list);}
  function world(v,main){main.append(el('span','MÁS ALLÁ DEL TERRENO DE JUEGO','eyebrow'),el('h1','El mundo sigue.'));const banner=el('article',undefined,'world-banner');banner.append(photo('stadium_bg'));banner.append(el('h2','El fútbol nunca se detiene.'));main.append(banner);const news=el('div',undefined,'news-grid');if(!v.news.length)news.append(el('p','Todavía no han llegado noticias a tu carrera. Las novedades aparecerán mientras avanzas.','muted'));for(const n of [...v.news].reverse().slice(0,30)){const p=panel(date(n.date));p.append(el('p',n.text));news.append(p);}main.append(news);}
  function relations(v,main){main.append(el('span','NADIE LLEGA SOLO','eyebrow'),el('h1','Las personas de tu historia.'),el('p','Entrenadores, compañeros, familia. Lo que ocurra entre vosotros se recordará en tu recorrido.','muted'));const grid=el('div',undefined,'people-grid');for(const c of v.contacts){const p=panel(c.name);p.prepend(portrait(c.id)?photo(portrait(c.id),'person-portrait'):el('div',c.name.split(' ').map(x=>x[0]).slice(0,2).join(''),'initials'));p.append(el('p',c.role,'muted'));grid.append(p);}main.append(grid);}
  function profile(v,main){main.append(el('span','EL PROTAGONISTA ERES TÚ','eyebrow'),el('h1','Tu perfil.'));const grid=el('div',undefined,'profile-grid');grid.append(hero(v));const p=panel('En este momento');for(const [label,value]of[['Edad',v.age+' años'],['Posición',position(v)],['Club',club(v)],['Partidos',v.appearances],['Salario mensual',money(v.salaryMonthly)],['Contrato restante',v.contractMonths+' meses']]){const r=el('div',undefined,'data-row');r.append(el('span',label),el('strong',String(value)));p.append(r);}p.append(stats(v));grid.append(p);main.append(grid);}
  async function download(){try{const raw=await store.readRaw();if(!raw)throw Error('No hay una partida guardada.');downloadText(raw,'multihistoria-partida.json');}catch(e){message=e.message;render();}}
  function downloadText(raw,filename){if(win.AndroidBridge?.saveTextFile){win.AndroidBridge.saveTextFile(filename,raw);return;}const url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));const a=el('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
  async function importFile(file){if(!file||busy)return;busy=true;message='';render();try{if(file.size>8*1024*1024)throw Error('La copia supera 8 MiB.');const raw=await file.text();const candidate=await GameSession.fromSave(raw,{...sessionOptions,commit});const previous=await store.readRaw();busy=false;render();confirmReplace('Recuperar esta copia',`Partida del ${date(candidate.getView().date)}, con ${decisionCount(candidate.getView().decisionsMade)}. Se conservará una copia de la partida actual.`,async()=>{
      await store.write(candidate.exportSnapshot(),previous);savedRaw=JSON.stringify(candidate.exportSnapshot());session=candidate;view='home';cinematic=false;replaceRouteState();
    });}catch(e){message='No se pudo importar. '+e.message;busy=false;render();}}
  function confirmReplace(title,body,accept){const dialog=el('dialog',undefined,'dialog');dialog.append(el('h2',title),el('p',body));const actions=el('div',undefined,'dialog-actions');actions.append(button('Cancelar',()=>dialog.close()),button('Confirmar',async()=>{dialog.close();busy=true;message='';render();try{await accept();}catch(e){message=e.message;}finally{busy=false;render();}},'primary'));dialog.append(actions);shell.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();}
  function saves(v,main){main.append(el('span','CONTINÚA DONDE LO DEJASTE','eyebrow'),el('h1','Tu partida.'));const p=panel('Guardada en este navegador');p.append(el('p',v?`${date(v.date)} · ${decisionCount(v.decisionsMade)}`:'Partida sin abrir','muted'),el('p','La partida local y PlayCanvas se guardan por separado. Descarga una copia aquí e impórtala en el otro navegador para continuar allí.'));const a=el('div',undefined,'save-actions');a.append(button('Descargar copia',download,'primary'),button('Recuperar partida guardada',load));const input=el('input');input.type='file';input.accept='.json,application/json';input.id='mh-import';input.setAttribute('aria-label','Importar copia de partida');input.addEventListener('change',()=>importFile(input.files[0]));const label=el('label','Importar copia de partida','file-label');label.append(input);a.append(label);p.append(a);p.append(el('p','Guardado transaccional · IndexedDB','muted'));a.append(button('Descargar copia antigua',()=>{try{const raw=store.legacyRaw();if(!raw)throw Error('No hay copia antigua.');downloadText(raw,'multihistoria-copia-antigua.json');}catch(e){message=e.message;render();}}));main.append(p);if(hasBackup()){const b=panel('Copia anterior');b.append(el('p','Último estado válido conservado antes de guardar un cambio.'),button('Recuperar copia anterior',async()=>{try{const raw=await store.previous();if(!raw)throw Error('No hay copia anterior.');await importFile(new File([raw],'anterior.json',{type:'application/json'}));}catch(e){message=e.message;render();}}));main.append(b);}const n=panel('Otra historia');n.append(el('p','Empieza de nuevo con otra semilla. Conservaremos una copia de tu carrera actual.','muted'));const seed=el('input');seed.type='number';seed.min='0';seed.max='4294967295';seed.value='424242';seed.setAttribute('aria-label','Semilla de la nueva carrera');n.append(seed,button('Empezar otra carrera',async()=>{const selected=Number(seed.value);if(!Number.isSafeInteger(selected)||selected<0||selected>4294967295){message='Introduce una semilla entre 0 y 4294967295.';render();return;}let old;try{old=await store.readRaw();}catch(e){message=e.message;render();return;}confirmReplace('Empezar otra carrera','La partida actual pasará a la copia anterior.',async()=>{replacement=old;session=await GameSession.create(selected,{...sessionOptions,commit});view='home';cinematic=false;replaceRouteState();});}));main.append(n);}
  function render(focus=false){const v=session?.getView();shell.replaceChildren();shell.classList.toggle('immersive',cinematic&&!!v);const header=el('header',undefined,'topbar');const brand=el('div',undefined,'brand');brand.append(el('span','M','brand-mark'));const name=el('div');name.append(el('strong','Multihistoria'),el('small','Carrera de futbolista'));brand.append(name);const pause=v?button(paused?'Reanudar':'Pausar',pauseToggle,'secondary',{ariaLabel:paused?'Reanudar la partida':'Pausar la partida',pressed:paused}):null;if(pause)pause.classList.add('pause-button');header.append(brand,el('span',v?'Temporada '+v.season.replace('-',' / 20'):'Una vida. Mil decisiones.','chapter'),pause,button(v?date(v.date):'Tu partida',()=>navigate('save'),'date-button'));shell.append(header);
    const nav=el('nav',undefined,'navigation');nav.setAttribute('aria-label','Navegación principal');for(const [key,label]of[['home','Inicio'],['career','Carrera'],['world','Mundo'],['relations','Relaciones'],['profile','Perfil'],['save','Tu partida']]){const b=button(label,()=>navigate(key),'nav-button');b.prepend(icon(key));if(key===view){b.classList.add('active');b.setAttribute('aria-current','page');}nav.append(b);}const foot=el('div',undefined,'nav-foot');foot.append(el('span','Cada elección cuenta.'),el('small','Una carrera de principio a fin.'));nav.append(foot);shell.append(nav);
    const main=el('main');main.tabIndex=-1;main.setAttribute('aria-busy',String(busy));shell.append(main);
    if(v){if(cinematic&&['decision','result','offer'].includes(v.screen))renderDecision(v,main);else({home,career,world,relations,profile,save:saves})[view](v,main);}else if(view==='save')saves(null,main);else main.append(el('h1','Tu historia está a punto de empezar.'));
    if(message){const alert=el('div',undefined,'alert');alert.setAttribute('role','alert');alert.append(el('p',message),button('Abrir guardados',()=>navigate('save')));shell.append(alert);}
    if(busy){const status=el('div','Guardando tu historia…','busy-status');status.setAttribute('role','status');shell.append(status);}else if(paused){const status=el('div','Juego en pausa · pulsa Reanudar para continuar.','pause-status');status.setAttribute('role','status');status.setAttribute('aria-live','polite');shell.append(status);}else{const status=el('div',session?'Guardado automático · '+decisionCount(v?.decisionsMade||0):'','save-status');shell.append(status);}
    if(focus){main.focus({preventScroll:true});main.scrollTop=0;}
  }
  function keyboard(e){if(e.key==='Escape'&&!shell.querySelector('dialog[open]')){e.preventDefault();goBack();}if(['ArrowDown','ArrowRight','ArrowUp','ArrowLeft'].includes(e.key)&&e.target.closest('.choices,.navigation')){const group=e.target.closest('.choices,.navigation'),buttons=[...group.querySelectorAll('button:not(:disabled)')],index=buttons.indexOf(e.target.closest('button'));e.preventDefault();buttons[(index+(['ArrowDown','ArrowRight'].includes(e.key)?1:buttons.length-1))%buttons.length]?.focus();}}
  function popstate(e){const s=e.state;if(!s?.mhOwner){view='home';cinematic=false;message='';render(true);return;}view=validViews.has(s.mhView)?s.mhView:'home';cinematic=Boolean(s.mhCinematic)&&Boolean(session&&['decision','result','offer'].includes(session.getView().screen));message='';render(true);}
  root.addEventListener('keydown',keyboard);win.addEventListener?.('popstate',popstate);load();
  return ()=>{store.close().catch(()=>{});root.removeEventListener('keydown',keyboard);win.removeEventListener?.('popstate',popstate);shell.remove();style.remove();};
}
